### ISSUE TITLE
#else after #else in stb_voxel_render.h

### ISSUE THREAD

**Issue by Arbeiterunfallversicherungsgesetz** [nothings/stb#100]
In `stb_voxel_render.h`  line 1167 should be `#elif defined(STBVOX_ICONFIG_VERTEX_8)` instead of `#else defined(STBVOX_ICONFIG_VERTEX_8)`

(GCC correctly complains with `error: #else after #else`)

```C
#else defined(STBVOX_ICONFIG_VERTEX_8)
typedef stbvox_uint8 stbvox_mesh_vertex;
#define stbvox_vertex_encode(x,y,z,ao,texlerp) \
((stbvox_uint8) ((z)+((ao)<<6))
#else
#error "internal error, no vertex type"
#endif
```

**Comment by nothings** [comment]
fixed and committed.
