### ISSUE TITLE
stb_image only reads 4 bytes

### ISSUE THREAD

**Issue by hututudor** [nothings/stb#1004]
Hello,

I am using stb_image and I try to load one 64x64 RGB file. However, the stbi_load function only returns the 4 bytes of the image. 
I tried with BMP, PNG and JPG and all produced the same output. The file I am trying to load is fine, because I can open it in Windows Photo App.

Why is that?
I will attach the screenshot with the debugger.
![image](https://user-images.githubusercontent.com/45239828/88454262-ef089000-ce76-11ea-806a-8c76f4c6a5bc.png)

This is the picture I am trying to load. 
![1](https://user-images.githubusercontent.com/45239828/88454267-fc257f00-ce76-11ea-9f43-61be249f84e5.jpg)

**Comment by nothings** [comment]
sizeof(data) is just the size of the pointer, which is 4 bytes
