### ISSUE TITLE
stb_sprintf: compilation error

### ISSUE THREAD

**Issue by stefano-zanotti-88** [nothings/stb#1010]
[Line 157 of stb_sprintf.h version 1.09](https://github.com/nothings/stb/blob/master/stb_sprintf.h#L157) raises an error for some GCC versions:
`#if __SANITIZE_ADDRESS__`

because `__SANITIZE_ADDRESS__` is not defined (and, depending on the compiler options, it might not be assumed that undefined symbols are treated as a literal 0)

Changing the line to this solves the problem:
`#if defined(__SANITIZE_ADDRESS__) && __SANITIZE_ADDRESS__`

**Comment by rygorous** [comment]
Fix is merged in the dev branch, will be in the next release.
