### ISSUE TITLE
Don't deprecate 'arraddn', allow it to work for 'n == 0'

### ISSUE THREAD

**Issue by luauser32167** [nothings/stb#1015]
I think loops like these in which the length of the array is known are not rare, and using arraddn instead of arrput is an optimization, but it crashes when n == 0:
```
int n = ...;
Foo* foos = nilptr;
arraddn(foos, n); // crashes when n == 0, needs to be guarded with  if (n != 0) { arraddn(foos, n); }
for (int i = 0; i < n; ++n) {
    foos[i] = ...;
}
```

**Comment by nothings** [comment]
Yes, that's a bug. Does it have anything to do with the deprecation or has it always been true?

**Comment by nothings** [comment]
From my look at the history, it's always been broken? Anyway, the fix is to change "stbds_header(a)->length-(n)" to "stbds_arrlen(a)-(n)" in a couple places.

**Comment by rygorous** [comment]
This is now fixed on the dev branch and will be in the next release.
