### ISSUE TITLE
stb_load can't find the path for the image I am using

### ISSUE THREAD

**Issue by nikhilAnayak** [nothings/stb#1017]
I'm using OpenGL(GLFW/GLAD) and am using stb_load to load images. I've tried using a relative path, absolute path, backslashes instead of slashes(I'm on Windows), and a few other things.

No matter what I do, the same error: `cannot fopen` is still there.
From my understanding, that means stb_load can't find the file but it's right there so I'm not sure what to do.

Any help would be appreciated.
Thanks!

**Comment by nothings** [comment]
Can you fopen the file from your own code? If not, then it's not an stb_image problem.

**Comment by rygorous** [comment]
FWIW inside C strings you need to escape backslashes as \\, which might be
your problem.
