### ISSUE TITLE
stbi_write_bmp_to_func wrong image layout

### ISSUE THREAD

**Issue by teamclouday** [nothings/stb#1023]
Hi, I tried to load JPEG byte array and store data into another BMP byte array.  
But the final output BMP was wrong. I tried to search for ```stbi_write_bmp_to_func``` examples, but found nothing.  
Here's my code:  
```cpp
void convertJpeg2Bmp(std::vector<unsigned char>& bmp, const unsigned char* image, int max)
{
	int width, height, channels;
	stbi_uc* ptr = stbi_load_from_memory((stbi_uc*)image, max, &width, &height, &channels, STBI_rgb);
	stbi_write_bmp_to_func(
		[](void* context, void* data, int size)
		{
			std::vector<unsigned char>* bmp = (std::vector<unsigned char>*)context;
			bmp->insert(bmp->end(), (unsigned char*)data, (unsigned char*)data + size);
		},
		&bmp, width, height, channels, ptr
	);
	stbi_image_free(ptr);
}
```
The output BMP looks like this:  
![image](https://user-images.githubusercontent.com/22620163/91707432-cc405a00-eb4d-11ea-894f-e4da46e62a08.png)

I think the issue is with ```stbi_write_bmp_to_func```  
This works, by the way:  
```cpp
stbi_write_bmp("sample.bmp", width, height, channels, ptr);
```

Anyone knows how to solve it?

**Comment by RufUsul** [comment]
Hi, wrote some code using `stbi_write_bmp_to_func` last week and works nicely for me.
But do not see an issue with your code either... sorry

**Comment by teamclouday** [comment]
This might be unique for my case. The JPEG byte array was sent from android phone via TCP socket, so probably some data loss caused this error.  
I posted this issue just in case there were some problem discovered on stb side.  
I will close this issue for now.
