### ISSUE TITLE
How to extract only width and height of an image

### ISSUE THREAD

**Issue by blackandwhite34521** [nothings/stb#1026]
I hope it's okay to ask questions here. I was wondering how to extract width and height of an image without extracting the actual pixel data. Can't find anything in the documentation.

**Comment by nothings** [comment]
`stbi_info()` and related functions

**Comment by nothings** [comment]
Actually I'm gonna leave this issue open as a reminder that it should probably be documented better.

**Comment by AndreiDespinoiu** [comment]
I recently needed to do this. My "solution" was to use a container like ``std::unsorted_map`` and insert it for every image I load, making it easily retrievable later on.

```cpp
// Load image
int width, height, channels;
unsigned char *data = stbi_load(path.c_str(), &width, &height, &channels, 0);
...
// Store the resolution
static std::unordered_map<std::string, ImVec2> thumbnailSizesLookupMap;
thumbnailSizesLookupMap[path] = { static_cast<float>(width), static_cast<float>(height) };
```

**Comment by rygorous** [comment]
Fix is in dev branch.
