### ISSUE TITLE
stbi_load, high memory consumption.

### ISSUE THREAD

**Issue by DEFAULTSAAS** [nothings/stb#1028]
When using stbi_load to load an image to be used as a texture, the memory consumption jumps up to 1GB. This is compared to 70MB, without using stbi_load and no textures. I have tried disabling other aspects of my texture loading code, but it makes no difference; just commenting out stbi_load results in normal memory consumption.

I have used to stbi_failure_reason to try and deduce the problem, to no avail. I get errors about corrupted JPEG's, but this happens when the image is a .png file as well. The images I am using are small in size, only 37 MB in total. It turned out that at one point, the image path was incorrect, but I have fixed that and still the same result.

The images do eventually load, and after a period of time, the memory consumption drops by half, but not fully.  

Here is the code:
``` CPP

int Width, Height, NRChannels;
std::string FinalTexturePath = AltPath;
unsigned char* Data;

std::string TempString = CurrSubStr;
TempString = TempString.substr(TempString.find("."));
std::transform(TempString.begin(), TempString.end(), TempString.begin(), ::tolower);

if (TempString == ".png" || TempString == ".tga")
{
	Data = stbi_load(FinalTexturePath.c_str(), &Width, &Height, &NRChannels, STBI_rgb_alpha);
}
else
{
	Data = stbi_load(FinalTexturePath.c_str(), &Width, &Height, &NRChannels, STBI_rgb);
}

// Further down...
stbi_image_free(Data);
```
If you need any more info, just let me know.
Thanks.

**Comment by nothings** [comment]
images on disk are compressed, so saying the image is "only 37 MB in total" doesn't really mean anything. stbi_load may use about 2x the total memory of the image, so you're probably loading images that are ~500 MB. An 8K x 8K RGBA image is about 256 MB. So 8 4K x 4K images would do something like this.

**Comment by DEFAULTSAAS** [comment]
Indeed, I am uploading the textures to the GPU. I never realised that compressed images on the disk, uncompressed, could take up so much memory. I think I have some quite large resolution images, which would explain the memory consumption. Thank you for responding, I will definitely take this into account in the future!
