### ISSUE TITLE
components per pixel with stb_image.h

### ISSUE THREAD

**Issue by kylophone** [nothings/stb#103]
Forcing the number of components per pixel doesn't seem to be working with stb_image.h. Calling stbi_load() with any number between 0 .. 4 always results in 3. See code below. I'm loading a .jpg.

```c
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#define STB_IMAGE_IMPLEMENTATION
#include "stb_image.h"

int main(int argc, char **argv) {
	const char *inputFile = argv[1];
	int x,y,n;
	unsigned char *data = stbi_load(inputFile, &x, &y, &n, 1); //This should force just one (gray) component per pixel. 

	if (!data) {
		fprintf(stderr, "Couldn't load image.\n"); 
		return (-1);
	}

	printf("%d\n", n); //This prints `3`, should print 1.

	stbi_image_free(data);
	return 0;
}
```

**Comment by rygorous** [comment]
This is the intended behavior. Quoting from the header file:

If req_comp is non-zero, *comp has the number of components that _would_
have been output otherwise. E.g. if you set req_comp to 4, you will always
get RGBA output, but you can check *comp to easily see if it's opaque.

-Fabian
