### ISSUE TITLE
stb_truetype.h lowercase starts at top

### ISSUE THREAD

**Issue by LORDTEK** [nothings/stb#1046]
First of all, thank you for the great job of stb_truetype.h
Well, I used it on opengl project. I saw that it starts position of lowercase chars from top rather then bottom line.

[https://ibb.co/YDtQ3c8](https://ibb.co/YDtQ3c8)

Edit: I use JetBrains' font

**Comment by nothings** [comment]
In proper text layout, text coordinates start at the bottom of the non-descender characters, called the "baseline". Search for that word in the file.
