### ISSUE TITLE
Assertion failure (area <= 1.01f) in stb_truetype rasterizer (v2)

### ISSUE THREAD

**Issue by tom7** [nothings/stb#1057]
Hi Sean, thanks for stb_truetype, I love it!

I get the following assertion failure:
```
Assertion failed: fabs(area) <= 1.01f, file stb_truetype.h, line 3170
```

for some specific subpixel/scale values on some fonts. These fonts seem to be fine. Small jitter in the floating point values causes the issue to go away, rasterizer v1 works, and the values are in reasonable range.

Here's an example call for "Exedore Laser Italic" (free for noncommercial use in http://iconian.com/fonts/exedore.zip via http://iconian.com/e.html):

```c
  stbtt_fontinfo font;
  fread(ttf_buffer, 1, 1<<25, fopen("exedoreli.ttf", "rb"));
  stbtt_InitFont(&font, ttf_buffer, 0);

  int width, height, xoff, yoff;
  (void)stbtt_GetCodepointBitmapSubpixel(&font,
					 0.4972374737262726,
					 0.4986416995525360,
					 0.2391788959503174,
					 0.1752119064331055,
					 'd',
					 &width, &height,
					 &xoff, &yoff);
```

In d38339775128c4a43b075b11eba4fd1ae66d9e6c I have a standalone test case with the 48 edges that reproduces the problem, so you don't need to load the font. I tried to debug further but I don't really understand the guts of the rasterizer. Lemme know if I can provide more info or make the bug report in a more useful way (I'm a github noob).

**Comment by nothings** [comment]
thanks Tom! I'll try to take a look at it.

**Comment by nothings** [comment]
Fixed in next release.

(If a near-vertical edge's x-endpoint landed exactly on an integer, a very small value and a very large value could fail to cancel properly when multiplied. Possibly it didn't have to land exactly on an integer, but that was the specific case the above hit. I put in a more general fix.)
