### ISSUE TITLE
Any interest in enabling sponsorship?

### ISSUE THREAD

**Issue by nmr8acme** [nothings/stb#1060]
ACME has a small amount of recurring sponsorship money to spend. We've gotten a lot of mileage out of stb libs, and I would choose to send a small sponsorship to you if you enabled it. (It's somewhere in the repo settings.) Not sure if that's something you're into, but I didn't see an issue already discussing it, so here we are.

**Comment by rygorous** [comment]
Sean and I both have full-time jobs and not enough energy to spend on stb libs to begin with; any sponsorship is not going to change that and will only well us even more guilty than we already do.
