### ISSUE TITLE
[stb_truetype] Getting codepoints for each glyph

### ISSUE THREAD

**Issue by tinotanovr** [nothings/stb#1062]
I don't know if already exist something to do this but I haven't found it.
I want to get the array of glyphs in the font and get the codepoint for each one. Like in the image below. The image is from a Font viewer website.
How can I do this?

![rthtrhtrhrth](https://user-images.githubusercontent.com/69604835/102325495-7f10b880-3f83-11eb-94e0-7b4ae6d6f9d5.png)**

**Comment by nothings** [comment]
iterate over all the codepoints you might care about and query stbtt_FindGlyphIndex and see if it's 0 or not

**Comment by tinotanovr** [comment]
But I need to iterate from 0 to 65533 for each font, this will take some time. There isn't other way?

**Comment by nothings** [comment]
computers are fast

**Comment by tinotanovr** [comment]
> 
> 
> computers are fast

I know XD But should exist any way to do it without needed to iterate over all the codepoints. Anyway I'll iterate for now.
