### ISSUE TITLE
Shifting 32-bit value by 32 bits is undefined behaviour. See condition at line 2054.

### ISSUE THREAD

**Issue by Derteanoo** [nothings/stb#1065]
Hi, std Authors,

I'm using stb_image.h and using checking tools (such as cppcheck) for code quality ensurement.

I noticed in stb_image.h there is a cast,.

`k = stbi_lrot(j->code_buffer, n);`

And my checking rule report complains that:

> Shifting 32-bit value by 32 bits is undefined behaviour.

DO you know how to solve it ?

**Comment by rygorous** [comment]
Yeah, I think we'll need to tweak the definition of stbi_lrot for n=0.

**Comment by rygorous** [comment]
This is now fixed in the dev branch and will be in the next release.
