### ISSUE TITLE
stbi_load in multi threaded context

### ISSUE THREAD

**Issue by whitwhoa** [nothings/stb#1071]
I'm working on a little hobby game engine and recently split asset loading into a separate thread. This allows scenes to load while the main render loop is still updating. Everything is working however there's a stutter while the background thread is running. After some debugging I've traced this down to my texture loading code, but the only thing I can see that might cause this would be if I'm possibly using stbi_load incorrectly from a multi threaded perspective. 

Is there any possible reason that anyone can think of as to why calling stbi_load on a separate thread from main could cause the main thread to block until it was complete?

**Comment by nothings** [comment]
no, there is no reason stb_image would cause thread blocking.
