### ISSUE TITLE
DLL libary

### ISSUE THREAD

**Issue by fellowchap-samuel** [nothings/stb#1072]
Hello Everyone!

Is there a way to pack stb_image.h to a dll?

Thank you very much, 
Samuel

**Comment by rygorous** [comment]
It's an explicit non-goal, but nothing stops you from writing your own
3-line wrapper funcs and putting those in a DLL if you want it.

**Comment by fellowchap-samuel** [comment]
Thanks for your reply!

Uhm, actually that was my original Idea, but sadly I haven't got that knowledge to put together a dll. Would you help me out with some guidance to begin it? (I wanna use MSVC 2019)
(my purpose: Use this dll for with a wrapper in another languages (ruby, python......).

**Comment by fellowchap-samuel** [comment]
Hi! Good news!

I got the solution 😁😁😊😊! If somebody need it I will comit it to the git repo! (Though only works with windows 64-bit)
