### ISSUE TITLE
stb_vorbis #defines BUFFER_SIZE which may conflict with other code

### ISSUE THREAD

**Issue by sagamusix** [nothings/stb#1076]
In two locations, stb_vorbis #defines a macro called `BUFFER_SIZE`. This is a very generic name that may conflict with other surrounding code. Can this macro be renamed to `STB_BUFFER_SIZE`, and maybe also be `#undef`d afterwards?

**Comment by rygorous** [comment]
We will probably merge this, but note that stb_vorbis (unlike most other stb libs) is not a header-file library and is meant to be compiled as its own translation unit; #including it into other code is not an intended use case to begin with.

**Comment by rygorous** [comment]
Fix is merged into dev branch, will be in the next release.
