### ISSUE TITLE
stb_image_write (png) corrupt data on M1 mac mini

### ISSUE THREAD

**Issue by mrqwak** [nothings/stb#1079]
I'm creating a buffer, memsetting it to 0, using stbi_write_png, and it's coming out corrupted. There's no multi-threading going on. Any idea's what could be causing this?

int BufferSize = s_DestWidth * s_DestHeight * s_DestPitch;
char* p = new char[BufferSize];
memset(p,0,BufferSize);
stbi_write_png(psFile,s_DestWidth,s_DestHeight,DEST_BITMAP_COMPONENTS,p,s_DestPitch);

![fonts_@2x](https://user-images.githubusercontent.com/76137201/105608333-4abac400-5d9b-11eb-878a-134f470341c7.png)

**Comment by nothings** [comment]
Your BufferSize calculation is incorrect. Please check with a debugger before submitting bug reports, it is not my job to debug your code.
