### ISSUE TITLE
stbtt_isFont type issue

### ISSUE THREAD

**Issue by stanley0614** [nothings/stb#1090]
Just look at this function blew!
see the line 3 and line 6.
we can see if font =='1' 0 0 0 we get the font is truetype,  if font == 0 1 0 0 we get the font is OpenType 1.0
but in windows for the font file "C:/Windows/Fonts/Arial.ttf".  I get the buffer is 0 1 0 0. It mean the font is OpenType 1.0, not Truetype 1. 
so I think this is wrong.  because I am sure the font is truetype.
Is there any issue here?
Thank you!

Stanley Shan
2021-2-4

1. static int stbtt__isfont(stbtt_uint8 *font)
2. {
   // check the version number
3.   if (stbtt_tag4(font, '1',0,0,0))  return 1; // TrueType 1
4.   if (stbtt_tag(font, "typ1"))   return 1; // TrueType with type 1 font -- we don't support this!
5.   if (stbtt_tag(font, "OTTO"))   return 1; // OpenType with CFF
6.  if (stbtt_tag4(font, 0,1,0,0)) return 1; // OpenType 1.0
7.   if (stbtt_tag(font, "true"))   return 1; // Apple specification for TrueType fonts
   return 0;
}

**Comment by nothings** [comment]
what is your complaint about stb_truetype here. that the comment is wrong?

**Comment by stanley0614** [comment]
@nothings  Yes I think the comment is incorrect. For stbtt_tag4(font, 0,1,0,0 ). I think the comment should be truetype font. but I  don't know what (stbtt_tag4(font, '1',0,0,0) represent!

**Comment by rygorous** [comment]
I don't understand the complaint.

For one, both paths return the exact same value (namely 1).

Separately, arial.ttf on Windows 10 (which I'm assuming you're using) uses OpenType features (as the built-in Windows font viewer explicitly mentions) and is definitely OpenType 1.0 format.
