### ISSUE TITLE
stb_image abstract stdlib functions other than malloc/realloc/free

### ISSUE THREAD

**Issue by muratmat** [nothings/stb#1091]
At the current stage malloc/realloc/free are the only functions that can be redefined/abstracted.
It would be nice to have the option to redefine/abstract all other standard library functions.
For example:

```
#ifndef STBI_MEMSET
#define STBI_MEMSET(_dest, _c, _count) memset(_dest, _c, _count)
#endif
#ifndef STBI_MEMCPY
#define STBI_MEMCPY(_dest, _src, _count) memcpy(_dest, _src, _count)
#endif
```

and of course change, for example, all memset(...) calls with STBI_MEMSET(...)

Many thanks!

**Comment by rygorous** [comment]
This is very unlikely to happen; the instances where we allow replacing libc functions right now are already an ongoing maintenance headache. If you want to avoid basic libc functionality that badly, stb_image probably isn't for you.
