### ISSUE TITLE
Unresolved external errors for stbi__bmp_load

### ISSUE THREAD

**Issue by gomidas** [nothings/stb#1092]
I use this lib with standalone GNU_EFI. I use vs2019. I added it via project properties->C/C++->general->Additional Include Directories
```
/*EFI HEADERS BEFORE */

#define STB_IMAGE_IMPLEMENTATION
#define STBI_NO_PSD
#define STBI_NO_TGA
#define STBI_NO_PNM
#define STBI_NO_STDIO 
#define STB_IMAGE_STATIC 
#include "stb_image.h"


BOOLEAN stbiImageTest( /*FileBuffer Filesize Args*/ ) {
    stbi__context s;
    stbi__result_info ri;

    s.read_from_callbacks = 0;
    s.img_buffer = s.img_buffer_original = FileBuffer;
    s.img_buffer_end = s.img_buffer_original_end = FileBuffer + FileSize;

    int* x;
    int* y;
    int* comp;
    int req_comp;

    ri.bits_per_channel = 8;
    stbi__bmp_load(&s, &x, &y, &comp, 0, &ri);
}
```

What am I missing here ?

**Comment by nothings** [comment]
does it work if you omit the STBI_NO_* defines?

**Comment by gomidas** [comment]
> does it work if you omit the STBI_NO_* defines?

I get more errors.

**Comment by nothings** [comment]
I don't know what EFI is, but if it doesn't provide standard library functions like malloc, you'll need to define them yourself.

**Comment by gomidas** [comment]
> I don't know what EFI is.
That means I am using UEFI headers and I have no stdlib, stdio and no standard C functions.

**Comment by nothings** [comment]
stb libraries require the C standard library.
