### ISSUE TITLE
stb_truetype.h: consider thread-safe code in stbtt__buf

### ISSUE THREAD

**Issue by iryont** [nothings/stb#1093]
Hello

It looks that the code is thread-unsafe due to ``stbtt__buf`` seeking. Not sure if anything else is affected, but I only had crashes in incorrectly fetched values due to multiple threads seeking the buffer from ``stbtt_GetGlyphSDF`` and its call to ``stbtt_GetGlyphBitmapBoxSubpixel``.

Multi threading ability is quite useful as functions such as ``stbtt_GetGlyphSDF`` are quite heavy and they can be dispatched among multiple workers which actually significantly speeds things up.

**Comment by nothings** [comment]
The main truetype code doesn't use stbtt__buf as far as I know. That code was added by a contributor for support of CFF and Type 2 fonts: https://github.com/nothings/stb/commit/0181b37188698d0921d6df2d3a4cce5228f2fb13, which I never touched.

You can always work around it by creating a separate stbtt_fontinfo* for each thread. This structure is relatively small (compared to the font) so that shouldn't be too bad.

**Comment by iryont** [comment]
> You can always work around it by creating a separate stbtt_fontinfo* for each thread. This structure is relatively small (compared to the font) so that shouldn't be too bad.

That is the first thing I tried, but since I dispatch each glyph separately to worker threads it becomes quite expensive workload.

Anyway, I don't understand the part with "The main truetype code". What do you mean by main code?

**Comment by nothings** [comment]
> > You can always work around it by creating a separate stbtt_fontinfo* for each thread. This structure is relatively small (compared to the font) so that shouldn't be too bad.
> 
> That is the first thing I tried, but since I dispatch each glyph separately to worker threads it becomes quite expensive workload.

If you have 16 worker threads you need 16 stbtt_fontinfos, one per font. Not one per glyph.

> Anyway, I don't understand the part with "The main truetype code". What do you mean by main code?

TrueType is an old font format, and the type of font stored in the font file.

OpenType is a newer font format which is closely related, which can store both TrueType fonts, and Postscript Level 1 and Postscript Level 2 fonts.

stb_truetype supports both TrueType font files and some OpenType font files. It supports TrueType fonts and Postscript Level 1 and Level 2 fonts. The Postscript fonts is code I didn't write and uses stbtt_buf. TrueType fonts do not use stbtt_buf as far as I know.

**Comment by iryont** [comment]
I do appreciate your answers, thank you.

Anyway, I did manage to actually work around this by simply copying the structure itself, without buffers, leaving pointers as they are (so it's a simple copy assign to another struct). That way each thread has its own structure and the buffer pointer without data races. It is efficient enough as we are just copying bunch of bytes, without actual buffers.
