### ISSUE TITLE
stb_image.h: BMP support for BI_ALPHABITFIELDS

### ISSUE THREAD

**Issue by bplu4t2f** [nothings/stb#1104]
Current DIB support includes BI_RGB (without explicit color masks) and BI_BITFIELDS (which is the "compress == 3" line here):

https://github.com/nothings/stb/blob/master/stb_image.h#L5327

```
            if (compress == 0) {
               if (info->bpp == 32) {
                  info->mr = 0xffu << 16;
                  info->mg = 0xffu <<  8;
                  info->mb = 0xffu <<  0;
                  info->ma = 0xffu << 24;
                  info->all_a = 0; // if all_a is 0 at end, then we loaded alpha channel but it was all 0
               } else {
                  info->mr = 31u << 10;
                  info->mg = 31u <<  5;
                  info->mb = 31u <<  0;
               }
            } else if (compress == 3) {
               info->mr = stbi__get32le(s);
               info->mg = stbi__get32le(s);
               info->mb = stbi__get32le(s);
               info->extra_read += 12;
               // not documented, but generated by photoshop and handled by mspaint
               if (info->mr == info->mg && info->mg == info->mb) {
                  // ?!?!?
                  return stbi__errpuc("bad BMP", "bad BMP");
               }
            }
```

Although not widely supported, BITMAPINFOHEADER compression can also be 6 (BI_ALPHABITFIELDS), in which case there is one additional color mask containing the alpha channel mask (so the total extra_read would be +16). I don't really have any expectations that this will be implemented (although it's quite a low hanging fruit), but I'm throwing it here anyway in the hopes that SEO picks up on the terms BI_BITFIELDS and BI_ALPHABITFIELDS, clarifying stb_image support.

**Comment by rygorous** [comment]
`BI_ALPHABITFIELDS` is, as far as I can tell, a Windows CE extension that requires both Windows CE 5.0 *and* .NET 4.0 and is not supported anywhere else. It does not show up in the either the documentation or header files in the most recent Win10 SDK I have installed on this machine (10.0.19041.0), which has this list:

```
/* constants for the biCompression field */
#define BI_RGB        0L
#define BI_RLE8       1L
#define BI_RLE4       2L
#define BI_BITFIELDS  3L
#define BI_JPEG       4L
#define BI_PNG        5L
```

I don't think it makes sense for stb_image to support format variants obscure enough that it takes me a while to even find where they're coming from.
