### ISSUE TITLE
is stb_dxt.h thread safe?

### ISSUE THREAD

**Issue by TylerGlaiel** [nothings/stb#1117]
I'm not 100% sure that stb_dxt is thread safe, mostly because of this block in stb_compress_dxt_block():
`   
   static int init=1;
   if (init) {
      stb__InitDXT();
      init=0;
   }`

(I think the optimizer could potentially move init=0 in front of stb__InitDXT but I havent exactly tested this extensively, I just don't trust it)

I get I could probably avoid this by throwing a dummy block at stb_compress_dxt_block on the main thread before doing any compression, but that feels a little bit clunky

**Comment by rygorous** [comment]
You're correct in that it's not and in that encoding a single block on the main thread is sufficient to make subsequent uses thread-safe.

**Comment by nothings** [comment]
Yes, nowadays I generally require an explicit init function, but I don't want to break existing users by adding it as a requirement.

**Comment by TylerGlaiel** [comment]
yeah I get that, might be a good idea just to add a simple optional one in, I'm doing this currently

```
void stb_dxt_warmup(){
        unsigned char block[64];
        unsigned char dst[16];
        stb_compress_dxt_block(dst, block, true, 0);
    }
```

**Comment by nothings** [comment]
Oh, I guess I can make it optional, yeah. Now I just need to ever have time to fix bugs myself instead of only infrequently processing pull requests.

**Comment by TylerGlaiel** [comment]
ok ok I get it https://github.com/nothings/stb/pull/1121

**Comment by nothings** [comment]
That WASN'T actually what I meant or I'd have told you how I wanted it done, sorry!
