### ISSUE TITLE
stb_image decode at a user-specified memory location

### ISSUE THREAD

**Issue by Eichenherz** [nothings/stb#1119]
Hello ! I'm having an issue in my workflow:
compressed_data ---stb_image---> some_malloc-ed_memory----memcpy--->where_i_actually_need_to_place_the_data
I basically want remove the memcpy step.
Is this possible to work so with the current state of stb_image ?
If not I'd like to make a feature request/suggestion .
Thanks and Cheers !

**Comment by nothings** [comment]
Duplicate of #58
