### ISSUE TITLE
Add non-AA rendering to stb_truetype

### ISSUE THREAD

**Issue by gnarz** [nothings/stb#112]
I know this might sound like a weird idea, but especially for games this is very useful. Currently I have to resort to freetype for this, which is more than a little on the heavy side...

**Comment by nothings** [comment]
If you want unhinted, you can just threshhold the AA output to black-and-white.

Hinting support is a huge can of worms that I'm not going to do (though somebody else claims to be investigating).

**Comment by gnarz** [comment]
I've tried unhinted, but it is not very convincing. I understand the part about hinting, though...
