### ISSUE TITLE
stb_image: ability to extract palette from images

### ISSUE THREAD

**Issue by LunarLambda** [nothings/stb#1124]
> Paletted PNG, BMP, GIF, and PIC images are automatically depalettized.

While I understand this is useful for 99% of cases, my use case actually mainly uses paletted images, and it would be useful to extract palettes from images

Is there a similar library with this capability, or perhaps a callback I can use to achieve this? Was really hoping to be able to use stb_image for this purpose.

**Comment by nothings** [comment]
There is no way to do this with stb_image. I'm sure there are other libraries to do it, but I don't actually know.
