### ISSUE TITLE
How to load a 8bit gif properly?

### ISSUE THREAD

**Issue by Meldryt** [nothings/stb#1131]
I try to load a 8bit gif (not animated) with stbi_load but i'm not sure if its possible because result is blank. 
In docs it says "comp always reports as 4-channel".
Anyone tried to create texture from gif with opengl? should i use GL_R3_G3_B2 and GL_UNSIGNED_BYTE_3_3_2 ?

**Comment by nothings** [comment]
like everything in stb_image, gifs are loaded as 24- or 32-bit, with one byte for each of R, G, B.
