### ISSUE TITLE
Will `stbi_write_jpg_to_mem` and `stbi_write_bmp_to_mem` be implemented?

### ISSUE THREAD

**Issue by zchrissirhcz** [nothings/stb#1132]
Hi, stb authors

I'm using stb_image_write.h for saving images via network. I would like to save image to memory buffer, then write the whole buffer together to file. Actually, the stdio file io functions and via network functions are with similar names:
- fopen,  my_fopen_network
- fclose, my_fclose_network
- fread, my_fread_network
- fwrite, my_fwrite_network

By calling `stbi_write_jpg_to_mem( )`, the speed is fast; and calling `stbi_write_bmp_core` or `stbi_write_jpg_core` is slow, with the "my_*_network" functions used.

I'd like to know, if there's plan for implementing this two functions:
- `stbi_write_jpg_to_mem()`
- `stbi_write_bmp_to_mem()`

Thanks anyway.

**Comment by rambip** [comment]
This is exactly what I was looking for !
But How can I malloc the right size for the buffer with the different parameters ?

**Comment by samuelabreu** [comment]
I was using the size of a loaded jpg and extra bytes to avoid overflow, and on context.last_pos you should have the exact length.

**Comment by nothings** [comment]
JPG and PNG are compressed file formats, so it's impossible to know how large the results will be before you compress the file. So generally you must realloc(). (Or you can run the whole thing twice, once to figure out the size and the second to store it, but I don't recommend this). BMP you can guess how big the output will be.

**Comment by LightYears88** [comment]
> I was using the size of a loaded jpg and extra bytes to avoid overflow, and on context.last_pos you should have the exact length.

i malloc a big size to avoid overflow,but when run stbi_write_jpg_to_func,the buffer size is 4,then i write the buffer to file,fclose coredump, bellow is my code:
         int w, h, n, com;
	unsigned char* data = stbi_load("1__1.jpg", &w, &h, &n, 0);
	int len = strlen((char*)data);
	unsigned char* redata = new unsigned char[len + 10000];
	memset(redata, '\0', len + 10000);
	custom_stbi_mem_context context;
	context.last_pos = 0;
	context.context = (void*)redata;
	int result = stbi_write_jpg_to_func(custom_stbi_write_mem, &context, w, h, n, data, 20);

	//stbi_write_jpg("out.jpg", w, h, n, redata, 100);

	string filename = "out.jpg";

	int size = strlen((char*)redata);
	FILE* pFile = fopen(filename.c_str(), "wb");
	fwrite(redata, size, 1, pFile);
	fclose(pFile);

**Comment by nothings** [comment]
if you need help debugging your code, please do it elsewhere. this is not an issue with stb_image.
