### ISSUE TITLE
[stb_image] Invert green channel of normal maps?

### ISSUE THREAD

**Issue by AndreiDespinoiu** [nothings/stb#1138]
I have a bunch of normal maps with inverted green channels (DirectX instead of OpenGL).

I know there's ``stbi_set_flip_vertically_on_load(true)``, but that flips the entire texture.

Is there a way to load them with the green channel inverted? Or maybe iterate through the data once it was loaded and invert them that way?

**Comment by rygorous** [comment]
You get a pointer to the pixel data back. You can just loop over the resulting array and do it yourself.

```
// load as 4-channel RGBA
int w, h;
stbi_uc *pixels = stbi_load(filename, &w, &h, NULL, 4);
if (!pixels) { /* error handling */ }

// invert green channel
for (int i = 0; i < w * h; ++i)
  pixels[i*4 + 1] = 255 - pixels[i*4 + 1];
```
