### ISSUE TITLE
Cannot force the default alpha channel in RGB images

### ISSUE THREAD

**Issue by ichlubna** [nothings/stb#1146]
Hi,
I request 4 channels in the load function but still only get three. According to #582 it should be working with the default 255 alpha.
Example:
```
stbi_uc* pixels = stbi_load(path.c_str(), &image->width, &image->height, &image->channels, STBI_rgb_alpha);
std::cerr << image->channels;
```
The printed result is always 3. The format of the input file is:
`PNG 1920x1080 1920x1080+0+0 8-bit sRGB`

Thanks and have a nice day

**Comment by nothings** [comment]
No problem, this is the top thing that confuses people about stb_image, the API is too confusing but can't really change it now.
