### ISSUE TITLE
stb_textedit has problems when the baseline is in the usual position

### ISSUE THREAD

**Issue by danielkeller** [nothings/stb#115]
In several places in stb_textedit, such as `stb_textedit_find_charpos` and `stb_text_locate_coord`, it assumes that the baseline is at the top of the characters. This is mildly inconvenient when integrating with stb_truetype, which assumes the usual baseline position.

It should be quite simple to fix this in a way that doesn't break existing code.

**Comment by nothings** [comment]
Can you be more specific about how you imagine this being fixed?

**Comment by danielkeller** [comment]
The fix was actually pretty simple. in `stb_text_locate_coord` I removed the lines

    if (y < 0)
      return 0;

and added in the while loop, after the empty line check,

	  if (i == 0 && y < base_y + r.ymin)
	     return 0;

I haven't tested extensively, but this appears to be the only needed change. For users that put the baseline at the top of the text, ymin should be 0 and this shouldn't break anything.

**Comment by nothings** [comment]
Sounds good.

**Comment by nothings** [comment]
Fixed in next version.
