### ISSUE TITLE
Invalid macro short name and documentation of arraddnindex/stbds_arraddnindex

### ISSUE THREAD

**Issue by gimpycpu** [nothings/stb#1151]
Short name **arraddnindex** refers to an non existing macro **stbds_arraddnindex**.
The documentation of the dynamic array also refer to **arraddnindex** which again do not exist.

arraddnindex:
        size_t arraddnindex(T* a, int n)
          Appends n uninitialized items onto array at the end.
          Returns the index of the first uninitialized item added.

**Comment by rygorous** [comment]
This is now fixed in the dev branch and will be in the next release.
