### ISSUE TITLE
stb_vorbis: Clang -O2 and -O3 produces broken results in `imdct_step3_inner_s_loop_ld654`'s while loop

### ISSUE THREAD

**Issue by kcgen** [nothings/stb#1152]
The latest versions of Clang produce broken results on x86-64 when optimizing the while loop inside `imdct_step3_inner_s_loop_ld654`.

This effectively means stb_vorbis is broken on all macOS release builds. 

It can be mitigated by: disabling optimizations for the function, disrupting the optimizer by moving a portion of the while loop out (https://github.com/dosbox-staging/dosbox-staging/commit/cd3b9569f7c27d932ff979c698db4dc6c12e4c58), or compiling with O1 or Ofast. 

Perhaps refactoring the while loop's step-wise array rotation using a temporary array (or some other mechanism) might make this code easier for the compiler to handle.

**Comment by rygorous** [comment]
Yeah, bug was filed with LLVM over 2 months ago, sadly nothings seems to have happened with it so far.

https://bugs.llvm.org/show_bug.cgi?id=50015

**Comment by kcgen** [comment]
Thanks for the heads up, @rygorous. 

This is no doubt the fault of `stb_vorbis`, but given the impact, it seems like we should try for a work-around in the meantime. 

Has anyone take a crack at refactoring this strange negatively-indexed z[] array loop into something a bit more humane?

**Comment by rygorous** [comment]
Avoiding the negative indices doesn't appear to do anything. (Or rather, it does seem to help in the minimal repro in the LLVM bug report, but not in the actual stb_vorbis code.)

**Comment by rygorous** [comment]
Avoiding the reverse subtracts, and resulting more irregular dataflow, appears to be sufficient to make the SLP vectorizer happy and get correct code out of Clang 12 here. I took the opportunity to introduce a few more locals to also simplify alias analysis while I was at it.

Fix is in dev branch, will be in the next release, or feel free to just cherry-pick it for DOSBox if you want it before then.
