### ISSUE TITLE
error: expected primary-expression before ‘>’ token

### ISSUE THREAD

**Issue by bmahlbrand** [nothings/stb#1154]
https://github.com/nothings/stb/blob/80c8f6af0304588b9d780a41015472013b705194/stb_image.h#L5533

stb_image.h:5533:38: error: expected primary-expression before ‘>’ token
 L5533|         for (j = 0; j<(int)s->img_y> > 1; ++j) {

**Comment by rsachetto** [comment]
It seem to be an error in your version. The version in the repo there is no space between the two ">".

for (j=0; j < (int) s->img_y>>1; ++j) <- original code.
