### ISSUE TITLE
stb_image_write: Support writing BMPs with alpha

### ISSUE THREAD

**Issue by rygorous** [nothings/stb#1159]
Should use a V4 bitmap header and set the alpha bit mask.

**Comment by rygorous** [comment]
Pushed to dev.

**Comment by zchrissirhcz** [comment]
@rygorous @nothings  Hi, this merged PR works for BMPs with alpha, but the support for BMPs with single channels is broken.

Consider the following reproduce code:
```c++
#define STB_IMAGE_IMPLEMENTATION
#include "stb_image.h"

#define STB_IMAGE_WRITE_IMPLEMENTATION
#include "stb_image_write.h"

int main()
{
    const int width = 256;
    const int height = 256;
    const int channels = 1;
    uint8_t* buffer = (uint8_t*)malloc(sizeof(uint8_t) * width * height * channels);
    for (int i = 0; i < height; i++)
    {
        for (int j = 0; j < width; j++)
        {
            buffer[i * width + j] = (i + j) / 2;
        }
    }

    static const auto write_func = [](void* context, void* data, int size) {
        if (size == 0) return;
        FILE* fp = reinterpret_cast<FILE*>(context);
        int ret = fwrite(data, size, 1, fp);
        assert(ret == 1);
    };

    const char* path = "result.bmp";
    FILE* fp = fopen(path, "wb");
    int ret = stbi_write_bmp_to_func(write_func, fp, width, height, channels, buffer);
    printf("%d\n", ret);

    return 0;
}
```

With stb_image_write.h v1.15, `file result.bmp` shows:
```
result.bmp: PC bitmap, Windows 3.x format, 256 x 256 x 8, 256 important colors, cbSize 66614, bits offset 1078
```
(note: `8` means single channel)

But with stb_image_write.h v1.16, `file result.bmp` shows:
```
result.bmp: PC bitmap, Windows 3.x format, 256 x 256 x 24, cbSize 196662, bits offset 54
```
i.e. `24` means 3 channels, means the gray image is stored as an "BGR" image, which is not expected.

**Comment by nothings** [comment]
is the image output by v1.15 actually valid, i.e. if you load it in another program is it correct?

**Comment by zchrissirhcz** [comment]
> is the image output by v1.15 actually valid, i.e. if you load it in another program is it correct?

Hi, thanks for the reply. I use v1.15, then load it via `Gwenview` software (I'm on KDE Plasma), it show correctly:

![图片](https://user-images.githubusercontent.com/3831847/190113328-369a3524-e820-45e5-9cc9-7932d8c369a7.png)

Also tried `KolourPaint` software, shows correctly:
![图片](https://user-images.githubusercontent.com/3831847/190113829-91ac75f3-aa34-4934-9ae2-a5bfa4172a3a.png)

**Comment by nothings** [comment]
The weird thing is that the documentation says it converts 1-channel bmp to 3-channel bmp, so I didn't realize there was anything wrong with it. But if it used to work correctly, it should probably be fixed.
