### ISSUE TITLE
stb_vorbis.c fails to compile because of __forceinline (windows cross-compile)

### ISSUE THREAD

**Issue by leiradel** [nothings/stb#116]
I'm compiling my application in a Debian x64 box, using an [Windows cross-compilation toolchain](http://sourceforge.net/projects/mingw-w64/files/).

The error message is:

    In file included from ../retroluxury/src/rl_sound.c:25:0:
    ../retroluxury/src/stb_vorbis.c:941:1: error: multiple storage classes in declaration specifiers
     static __forceinline uint32 crc32_update(uint32 crc, uint8 byte)
     ^

followed by four more identical errors at lines 1558, 2042, and 2599.

`__forceinline` default definition has `extern` in it, as the error message shows when I add `#define __forceinline` to `std_vorbis.c`:

    In file included from ../retroluxury/src/rl_sound.c:25:0:
    ../retroluxury/src/stb_vorbis.c:565:0: warning: "__forceinline" redefined [enabled by default]
     #define __forceinline
     ^
    In file included from /opt/mingw64/x86_64-w64-mingw32/include/crtdefs.h:10:0,
                     from /opt/mingw64/x86_64-w64-mingw32/include/stdint.h:28,
                     from /opt/mingw64/lib/gcc/x86_64-w64-mingw32/4.9.0/include/stdint.h:9,
                     from ../retroluxury/src/rl_sound.h:6,
                     from ../retroluxury/src/rl_sound.c:1:
    /opt/mingw64/x86_64-w64-mingw32/include/_mingw.h:263:0: note: this is the location of the previous definition
     #define __forceinline extern __inline__ __attribute__((__always_inline__,__gnu_inline__))
     ^

and it clashes with the functions declarations which are `static`.

I'm not sure how to fix this without redefining `__forceinline` in `std_vorbis.c`.

**Comment by nothings** [comment]
This appears to be a mingw bug? Are you using a current version of mingw?

http://sourceforge.net/p/mingw-w64/mailman/message/32882927/

**Comment by leiradel** [comment]
Sorry, I was using version 4.9.0, version 4.9.1 corrected the problem.

**Comment by bioglaze** [comment]
I still have this issue on Windows with Nuwen MinGW distro 13.0 that uses GCC 5.1.0.

**Comment by nothings** [comment]
Go to: http://sourceforge.net/p/mingw-w64/code/HEAD/tree/trunk/mingw-w64-headers/crt/_mingw.h.in

This line of code is still there:

`#define __forceinline extern __inline__ __attribute__((__always_inline__,__gnu_inline__))`

As noted in the thread linked above, the "extern" is invalid. I don't know why the code hasn't been fixed as described in the thread, but I'd say it's still a bug in mingw and so not my problem.

**Comment by leiradel** [comment]
I was wrong when I said that version 4.9.1 corrected the problem, but like nothings said the bug is in MinGW. I moved on by editing `stb_vorbis.c` and removing all references to `__forceinline`.

**Comment by nothings** [comment]
If that's the case then we should probably just wrap it in an MINGW #ifndef.

**Comment by leiradel** [comment]
I'm pretty new to git so I don't know if I did it right:

    $ git request-pull origin/master myfork
    The following changes since commit 947bdcd02716b6bb9f365710b23493ae1564f990:

      update version numbers & docs (2015-04-19 04:19:55 -0700)

    are available in the git repository at:

      https://github.com/leiradel/stb.git

    for you to fetch changes up to 8c3f562d239ceda8f9491ac166a95768128cca12:

      redefine __forceinline under MinGW to work around a MinGW bug (2015-05-10 21:48:29 -0300)

    ----------------------------------------------------------------
    Andre Leiradella (1):
          redefine __forceinline under MinGW to work around a MinGW bug

     stb_vorbis.c | 3 +++
     1 file changed, 3 insertions(+)
    warn: No branch of https://github.com/leiradel/stb.git is at:
    warn:   8c3f562: redefine __forceinline under MinGW to work around a MinGW bug
    warn: Are you sure you pushed 'HEAD' there?

This change redefines `__forceinline` only when compiling with MinGW.

**Comment by r-lyeh** [comment]
@leiradel, You have to fork the repo by clicking on the fork icon in the landing project page, then clone your repo, apply the changes, and push them to github. Then go to your fork page and click on the Pull Request button.

**Comment by nothings** [comment]
reopening due to new report

**Comment by Murii** [comment]
My suggestion would be to remove "__forceinline" or if it's really needed add some #ifdef and see what happens

**Comment by EZSPECIAL** [comment]
Including the vorbis file into even the simplest of programs in C++ doesn't work for me, using VS2015 compiler. Tried with naming it .c .h and .cpp. Don't know if its related to the __forceinline issue though

**Comment by rygorous** [comment]
You'll need to be more specific than "doesn't work for me". What doesn't work? What's the error message?

**Comment by EZSPECIAL** [comment]
The file is perfectly fine, I'm so sorry, I haven't used C++ in a year and forgot to close my class with ";" and that was destroying the rest of the code, nothing to do with the actual file

**Comment by denisdemais** [comment]
try use extern "C" { ... }

**Comment by nothings** [comment]
Reading through the thread I linked above, it ends with somebody reverting the fix because it broke something else. So I've added a workaround, it will be in next release.
