### ISSUE TITLE
stb_truetype: small suggested changes to silence static analyzer

### ISSUE THREAD

**Issue by ocornut** [nothings/stb#1162]
Based on `dev` branch as of today.

PVS Studio:

(1)
`imstb_truetype.h:1877 	High 	V595 	The 'vertices' pointer was utilized before it was verified against nullptr. Check lines: 1877, 1879.`
```
if (num_vertices > 0) STBTT_memcpy(tmp, vertices, num_vertices*sizeof(stbtt_vertex));
↑ V595 The 'vertices' pointer was utilized before it was verified against nullptr. Check lines: 1877, 1879.
```
Other nearby use of `vertices` are testing for NULL. Probably a false positive since I'd assume `num_vertices > 0` guarantee it is not null, but wouldn't hurt adding the extra test there as other analyzers are likely to do the same.

(2)
`imstb_truetype.h:2245 	Medium 	V560 	A part of conditional expression is always false: b0 > 254.`
```
      default:
         if (b0 != 255 && b0 != 28 && (b0 < 32 || b0 > 254))
↑ V560 A part of conditional expression is always false: b0 > 254.
```
Because even though b0 is `int` the analyzer sees that b0 came from `stbtt__buf_get8()`.

(3)
`imstb_truetype.h:4409 	Medium 	V519 	The 'orig[1]' variable is assigned values twice successively. Perhaps this is a mistake. Check lines: 4401, 4409.`
```
   orig[1] = y;
↑ V519 The 'orig[1]' variable is assigned values twice successively. Perhaps this is a mistake. Check lines: 4401, 4409.
```
I think the first `orig[1] = y` can be removed, maybe both assignments moved down for consistency.

----

(ran a bunch of basic CI with aggressive warning settigs: https://github.com/ocornut/imgui/runs/3028562836?check_suite_focus=true nothing else to report)

**Comment by rygorous** [comment]
Fixed on dev branch, will be in the next release.
