### ISSUE TITLE
stb_truetype does not compile on dev: _FindSVGDoc decl requires STB_TRUETYPE_IMPLEMENTATION

### ISSUE THREAD

**Issue by leafi** [nothings/stb#1163]
Based on the current `dev` branch, as of this commit:

https://github.com/nothings/stb/commit/315e979f34a1f8479bfc82481fb60fd22965fd1d

... stb_truetype does not compile, when imported as a header, without STB_TRUETYPE_IMPLEMENTATION set.

```
STBTT_DEF stbtt_uint8 *stbtt_FindSVGDoc(const stbtt_fontinfo *info, int gl)
```

1. Missing ';' semicolon at end of declaration
2. stbtt_uint8 is not defined unless STB_TRUETYPE_IMPLEMENTATION is defined (or at all import points stbtt_uint8 is manually defined). Other declarations avoid using `stbtt_*int*` types.

**Comment by nothings** [comment]
Fixed in dev branch.
