### ISSUE TITLE
lodepng is one of them single file image libs

### ISSUE THREAD

**Issue by baxissimo** [nothings/stb#118]
You said you would list other single-file no-deps image libs in the FAQ if people send you their names.
Here's one:
http://lodev.org/lodepng/

**Comment by nothings** [comment]
It's two files!

**Comment by baxissimo** [comment]
That's no file.  It's a header.

But this one is really one file:  http://lodev.org/lodepng/picopng.cpp

**Comment by DanielGibson** [comment]
others:
* miniz.c - zlib-clone + zip file support + png writing (https://github.com/richgel999/miniz)
* nanosvg.h SVG parser (https://github.com/memononen/nanosvg)
* DG_misc.h function to get binary path cross-platform + a bunch of string functions missing on some platforms (https://github.com/DanielGibson/Snippets/)
