### ISSUE TITLE
Error with a JPG file

### ISSUE THREAD

**Issue by photopea** [nothings/stb#1182]
I was not able to parse this JPG file correctly with your JPEG decoder. Could you fix it?

![JD500013](https://user-images.githubusercontent.com/15955558/127323193-cb48851a-d7c7-437d-94be-0c75f3b34f8e.JPG)

**Comment by nothings** [comment]
The file contains unknown data after the image data; stb_image sees this as corruption (it's more conservative about accepting such images than other loaders). Looks like to be the same issue as this: https://github.com/jpeg-js/jpeg-js/issues/81

**Comment by nothings** [comment]
Since the Internet does not seem to have any documented explanation for JPEG marker 0, I'm going to consider this a broken image and not fix it.

**Comment by bgyarfas** [comment]
@nothings It's also a problem with all JPEGs generated by DJI drones. See the linked issue. Are there any flags or alternate methods in STB to ignore "bad data" like this?

**Comment by photopea** [comment]
Could you share an image with us, which you can not open in Photopea?

**Comment by photopea** [comment]
@nothings could you maybe add 2 lines of code to deal with this bug in JPG files? There are hundreds of thousands of such images out there, and since most of programs can open them, it would be nice if your library could handle them (as people are expecting it).

**Comment by photopea** [comment]
@nothings also, my first image contains just one marker 0xFFD9, and that is the last two bytes of a binary file. What do you mean by "unknown data after the image data"?  Also, I can not see any marker 0 in the file.

**Comment by bgyarfas** [comment]
@photopea I haven't tried photopea, I ran into the error using [instant-ngp](https://github.com/NVlabs/instant-ngp). Here's an example image that won't load with stb. 
![DJI_0396](https://github.com/nothings/stb/assets/6708431/e93ffdfa-83f1-46e4-8df0-dbb9c27590f2)
