### ISSUE TITLE
How can I load from pixel map?

### ISSUE THREAD

**Issue by HackHarry** [nothings/stb#1190]

**Comment by HackHarry** [comment]
I need to resize the picture from `adb exec-out screencap`. The data which `screencap` get is pixelmap, I don't know how to load it.

**Comment by thedmd** [comment]
You can use `-p` switch to make screencap save it as a PNG and then you can load it with stb_image. When using raw output please see [this stackoverflow answer](https://stackoverflow.com/a/32733228/15194693) to learn about output format. You can load it to memory and feed stb_image_resize.

Also, this question isn't really related to stb itself, so I think you will not get more hints here.

**Comment by HackHarry** [comment]
Thank you for your reply. 
Actually, `-p` command will cause to more cpu usage, that 's why I want to get the picture from `adb exec-out screencap`.
I just want to know if stb can load from pixel data, and now I get answer.

**Comment by thedmd** [comment]
No. You already are getting pixel data and you can load it almost directly. stb_image also return pixel data in same format, so it does not provide any benefit for this use case.
Format of the data is described in the stackoverflow answer above, you can easily do loading function.
