### ISSUE TITLE
Not recognized by pkgconfig

### ISSUE THREAD

**Issue by manen** [nothings/stb#1191]
I'm not sure how pkgconfig works, especially not for library developers, but right now I have to copy and paste `stb_image.h` manually into my project folder to get it to work, which is very not ideal.

Could `stb` have pkgconfig support in the future sometime?

**Comment by nothings** [comment]
Copying stb_image.h into your project is the intended method of using it.

**Comment by manen** [comment]
well uhm thanks anyway
