### ISSUE TITLE
stb_image Cannot convert 'size_t' t 'void'

### ISSUE THREAD

**Issue by Anrik21** [nothings/stb#1201]
Not sure if I'm missing something obvious but after setting my #define & #include to:

```
#define STB_IMAGE_IMPLEMENTATION
#define STBI_ASSERT(x)
#define STBI_MALLOC
#define STBI_REALLOC
 #define STBI_FREE

 #include "stb_image.h"
[...]
```

the following code generates a compiler error (C2440	'return': cannot convert from 'size_t' to 'void *'	)

```
static void *stbi__malloc(size_t size)
{
    return STBI_MALLOC(size);
}
```

Can't find anything here or otherwise about this, using microsoft visual c++ 2019.

**Comment by nothings** [comment]
what are you trying to accomplish by defining STBI_MALLOC, STBI_REALLOC, and STBI_FREE to empty values?

**Comment by nothings** [comment]
Ah, I see, the instructions there are not clear. It should say:

"define STBI_MALLOC etc. to your own functions to avoid calling malloc/realloc/free"

**Comment by Anrik21** [comment]
Thanks for the quick reply, my 2h of troubleshooting are now resolved!
