### ISSUE TITLE
glyph not rasterized correctly when using stbtt_MakeCodepointBitmap

### ISSUE THREAD

**Issue by lordadamson** [nothings/stb#1202]
Hi :D

So glyphs are rasterized perfectly when I use `stbtt_GetCodepointBitmap` but when I use `stbtt_MakeCodepointBitmap` with identical input the glyph is not rasterized.

Here's a small program that reproduces the bug:

```c
#define STB_TRUETYPE_IMPLEMENTATION
#include "stb_truetype.h"

#define STB_IMAGE_WRITE_IMPLEMENTATION
#include "stb_image_write.h"

char buffer[24<<20];

int main(int arg, char **argv)
{
   stbtt_fontinfo font;
   int i,j,ascent,baseline,ch=0;
   float scale, xpos=2;
   char letter = 'y';

   fread(buffer, 1, 1000000, fopen("/Users/adam/Downloads/Roboto/Roboto-Regular.ttf", "rb"));
   stbtt_InitFont(&font, buffer, 0);

   scale = stbtt_ScaleForPixelHeight(&font, 300);
   stbtt_GetFontVMetrics(&font, &ascent,0,0);
   baseline = (int) (ascent*scale);

  int advance,lsb,x0,y0,x1,y1;
  float x_shift = xpos - (float) floor(xpos);
  stbtt_GetCodepointHMetrics(&font, letter, &advance, &lsb);
  stbtt_GetCodepointBitmapBoxSubpixel(&font, letter, scale, scale, x_shift, 0, &x0, &y0, &x1, &y1);

  int w = x1-x0, h = y1-y0;

  uint8_t* bitmap = (uint8_t*)malloc(w*h);
  memset(bitmap, 0, w*h);

  stbtt_MakeCodepointBitmap(&font, bitmap, w, h, 0, scale, scale, letter);
  stbi_write_png("/Users/adam/makecodepoint.png", w, h, 1, bitmap, 0);

  memset(bitmap, 0, w*h);

  bitmap = stbtt_GetCodepointBitmap(&font, scale, scale, letter, &w, &h, 0, 0);
  stbi_write_png("/Users/adam/getcodepoint.png", w, h, 1, bitmap, 0);

   return 0;
}
```

When I use `stbtt_GetCodepointBitmap` the glyph is rasterized perfectly and I get this output:
![getcodepoint](https://user-images.githubusercontent.com/43860544/131857327-2bdb4bbf-1d49-456c-a7be-85c07c408575.png)

However when I use `stbtt_MakeCodepointBitmap` I get this output:
![makecodepoint](https://user-images.githubusercontent.com/43860544/131857206-e9052bea-ffdb-43cb-a818-62c0ddf2d419.png)

If you look closely at the output of `stbtt_MakeCodepointBitmap` you'll find a tiny white spot at the upper left corner.

**Comment by nothings** [comment]
you have a bug in your code. it is not my job to debug and fix your bugs!

but there's not much point in me not telling you the answer: you're passing in 0 for stride, so the offset from one row to the next is 0 bytes, so it's rendering every row of the character into the first row, so the white spot is the bottom row of the character
