### ISSUE TITLE
stb_image: usage with SDL_RWops?

### ISSUE THREAD

**Issue by VinnyVicious** [nothings/stb#1203]
I'm converting some old SDL_Image code to stb_image and I was wondering if it is possible to use SDL_RWops with it. Here's an example of what I'm doing:

    SDL_RWops *rw = myZipFile->rwops();

    if (rw) {
        const char *ext = strrchr(myFileName, '.');
        if (ext) ++ext;
        s = IMG_LoadTyped_RW(rw, 0, ext);
        SDL_FreeRW(rw);
    }

    delete myZipFile;

**Comment by nothings** [comment]
i don't know anything about SDL_RWops
