### ISSUE TITLE
stbi_write_png (stb_image_write.h) segfaults on OpenBSD with -O3

### ISSUE THREAD

**Issue by justinmeiners** [nothings/stb#1212]
**Describe the bug**

`stbi_write_png` does not appear to work on OpenBSD when compiled with the gcc included in the base system with the `-O3` flag. Based on stack traces, it appears to be caused by the stretchy array allocation code `stbiw__sbpush` (see screenshot). This is the code that hides allocation information in two integers before the returned buffer.

I suspect that the optimization is causing something to be evaluated in an unexpected order or some other undefined behavior.

I understand OpenBSD has quite an old version of `gcc` they maintain, so it's certainly possible their compiler has a bug, or it's old enough not to matter. I understand if you do not consider this an important issue. However, I wanted to log this bug for completeness sake. Perhaps the allocation code can be quickly improved by someone familiar.

**To Reproduce**
1. Attempt to compile and run the test `image_write_test.c`:

        gcc -DIWT_TEST image_write_test.c
        ./a.out

2. This should work find. However, if you add the `-O3` flag it will fail:

        gcc -DIWT_TEST -O3 image_write_test.c
        ./a.out

        Segmentation fault (core dumped)

Note that this issue is not limited to this specific test.
Any attempt to use a variation of `stbi_write_png` will segfault.

**Expected behavior**
Test should pass without segfault.

**Screenshots**

Here is a related stack trace (from a different program, not the `image_write_test.c` but same problem).

![image](https://user-images.githubusercontent.com/3220045/134452464-039a759e-dddd-4c1e-9582-aea0e91f5a1e.png)

**Additional info:**
- Architecture: `amd64`
- Compiler: `gcc version 4.2.1 2007019`
- OS version: `OpenBSD 6.9`

**Comment by nothings** [comment]
does it still happen with -O3 -fno-strict-aliasing?

what version of gcc is it?

**Comment by justinmeiners** [comment]
With those options, the segfault does not occur. So that fixes it.

**Comment by nothings** [comment]
It is in current versions, I don't know about that version. Or it may be an interaction with other optimizations that -O3 enables.

**Comment by justinmeiners** [comment]
I myself probably don't follow strict aliasing so that's a fine fix for me. Is it worth adding a comment to the `stb_image_write` to inform others that it may be necessary?

**Comment by nothings** [comment]
Already has one.

     Will probably not work correctly with strict-aliasing optimizations.
