### ISSUE TITLE
[stb_truetype] Read access violation When initialize font

### ISSUE THREAD

**Issue by Jony01** [nothings/stb#1214]
**Describe the bug**
Some font, when load from binary data on windows cause 'Read access violation' 

**To Reproduce**
1. Use windows native font selector
![Screenshot 2021-09-24 133018](https://user-images.githubusercontent.com/15888762/134667491-6731bd57-39ee-4d1b-83de-f3e4a2d28fc6.png)
2. Select: @Microsoft JhengHei UI
3. confirm by [ok]
OUTPUT:  `selected font is @Microsoft JhengHei UI`
3. Use HFONT descriptor to get font data
![Screenshot 2021-09-24 132845](https://user-images.githubusercontent.com/15888762/134667320-fb867812-59c7-4636-9f54-d9e9b6eb9bbd.png)

**Expected behavior**
I expect that when it is not possible to load I get zero from `stbtt_InitFont` function or bad offset from `stbtt_GetFontOffsetForIndex` .

**Minimal example**
```
#define STB_TRUETYPE_IMPLEMENTATION // force following include to generate implementation
#include "imgui/imstb_truetype.h" // stbtt_fontinfo

#include <windows.h>
#include <wingdi.h>
#include <windef.h>
#include <WinUser.h>
#include <commdlg.h>

TEST_CASE("font test")
{
    HWND hwnd = (HWND) GetFocus(); // owner window
    HDC  hdc  = ::CreateCompatibleDC(NULL); // display device context of owner window
    if (hdc == NULL) {
        std::cerr << "Can't create HDC by CreateCompatibleDC(NULL).";
        return;
    }

    CHOOSEFONT     cf;         // common dialog box structure
    static LOGFONT lf;         // logical font structure
    static DWORD   rgbCurrent; // current text color

    // Initialize CHOOSEFONT
    ZeroMemory(&cf, sizeof(cf));
    cf.lStructSize = sizeof(cf);
    cf.hwndOwner   = hwnd;
    cf.lpLogFont   = &lf;
    cf.rgbColors   = rgbCurrent;
    cf.Flags       = CF_SCREENFONTS | CF_EFFECTS;

    if (ChooseFont(&cf) != TRUE) {
        std::cout << "Not selected font.";
        return;
    }
    std::wcout << "selected font is "
                << (std::wstring) cf.lpLogFont->lfFaceName << std::endl;
    HFONT hfont = CreateFontIndirect(&lf);
    ::SelectObject(hdc, hfont);
    size_t size = ::GetFontData(hdc, 0, 0, NULL, 0);
    if (size == 0) {
        std::cerr << "HFONT doesn't have size.";
        ::DeleteDC(hdc);
        return;
    }

    std::vector<unsigned char> buffer(size);
    size_t loaded_size = ::GetFontData(hdc, 0, 0, buffer.data(), size);
    ::DeleteDC(hdc);

    if (size != loaded_size) {
        std::cerr << "Different loaded(from HFONT) data size.";
        return;
    }

    int index = 0;
    int offset = stbtt_GetFontOffsetForIndex(buffer.data(), index);
    if (offset < 0) {
        std::cerr << "No offset exists.";
        return;
    }
    stbtt_fontinfo font_info;
    int result = stbtt_InitFont(&font_info, buffer.data(), offset);//  THIS throw Read access violation.
    if (result ==0) { 
        std::cerr << "Can't initialize font.";
        return;
    }
}
```

**Version**
I use Imgui version of libs --> [[link to file](https://github.com/ocornut/imgui/blob/master/imstb_truetype.h)] --> version 1.20 (2019-02-07)

**Comment by nothings** [comment]
Can you use a current version of the library?

Does this happen with all fonts, or only with this specific font?

If it only happens with that font, I do not have that font installed so I cannot test what is happening. If the font is not actually a truetype font, read access violation is a plausible outcome (because InitFont does not receive a lengh for the font, there is no way to test for and prevent out-of-bounds reads).

**Comment by Jony01** [comment]
I use the latest version and it is same.

No, it happens only with some font.

Originaly i use wxFontDialog where i fitrate to use only scalable font. But when i use only data pointer not font file. I am not sure that it is TrueType. 

I know length of data, when i copy it from HFont. Will it be possible to add test bounds as optional?

**Comment by Jony01** [comment]
I stored the binary data of font into file by this code:
![image](https://user-images.githubusercontent.com/15888762/135254893-dd9b4453-af23-4a28-93a0-04a331c8bfa0.png)

You could download it from [link](https://easyupload.io/eg87ye) (link will be active for 30days)
It is possible way to test it on your side.

**Comment by nothings** [comment]
> I know length of data, when i copy it from HFont. Will it be possible to add test bounds as optional?

Unlikely to change anytime soon. It's a breaking change to the API, and it requires changing pretty much ALL code that accesses the font data.

>You could download it from link (link will be active for 30days)
>It is possible way to test it on your side.

Thank you, downloaded.

**Comment by paulwratt** [comment]
thats a "wide" font as far as I know, like most CJK/JIS fonts

**Comment by nothings** [comment]
I've looked at it, and I'm not 100% sure, but I believe the font is a TrueType Collection, which contains multiple fonts which share some data. In this case, apparently GetFontData() does not return a valid TrueType font, because it's missing the shared data and/or the offsets in the TrueType font are relative to the beginning of the ttc file (the latter is the part I can see going wrong in the debugger).

In the documentation for GetFontData, it appears you can query for 'ttcf' to maybe get the whole collection file; then you can stb_truetype for any of the fonts in the collection.

Reopen if this doesn't solve it for you.
