### ISSUE TITLE
Cannot load gifs produced by Go image library

### ISSUE THREAD

**Issue by mntn-xyz** [nothings/stb#1222]
Using the Go image library to produce a gif results in an image that will display properly in Chrome and a few other programs I tested, but not in the Lagrange Gemini client (which uses stb). Lagrange does nothing special with the image so I'm pretty sure this is both an stb issue and a Go issue. (Stb should probably try to handle these weird images, and Go should produce images that are more correct.)

The produced images have invalid information in the Logical Screen Descriptor's packed byte; the color resolution and global color table size are zeroed out. (No local color table is defined.) I assume this is the cause of the problem. An example image is below:

![PIXNIO-2545657-5760x3840](https://user-images.githubusercontent.com/85877297/136432619-3036882e-5f53-4196-b54f-08c1718046d8.gif)

The image can be fixed with GraphicsMagick: `gm convert broken.gif -colors 8 fixed.gif`. This adds some bytes to the image, sets the color resolution bits to 111 (8 bit color), and sets the global color table size to 010 (8 colors). I'm not sure what the additional bytes are or where they are placed, I haven't looked that deep into it yet.

This page was used as a reference in figuring out the GIF header issues: https://www.matthewflickinger.com/lab/whatsinagif/bits_and_bytes.asp

**To Reproduce**
1. Generate gif with Go image library
2. Attempt to load image
3. stb_image reports "no clear code" (per https://github.com/skyjake/lagrange/issues/353)

**Expected behavior**
The image should load.

Related discussion: https://github.com/makeworld-the-better-one/didder/issues/7

**Comment by rygorous** [comment]
Looks like this was recognized as a bug in the Go image/gif writing library and resolved in Oct 2021, closing.
