### ISSUE TITLE
stb_voxel_renderer compilation error when #define STBVOX_CONFIG_OPTIMIZED_VHEIGHT

### ISSUE THREAD

**Issue by friesencr** [nothings/stb#123]
I  #define STBVOX_CONFIG_OPTIMIZED_VHEIGHT and get compilation errors

ln 3216: 'stbvox_reverse_face' : undeclared identifier
ln 3216  'stbvox_make_mesh_for_face' : function does not take 8 arguments

**Comment by nothings** [comment]
Just uploaded a fix. Didn't actually try running it, but I did try running it back before the original release, so odds are it works.

You almost certainly don't want to use it, as lighting doesn't look right (as specified).

**Comment by friesencr** [comment]
Have gotten some of it working in Urho3d.  Looking forward to getting some different sloped blocks done.  Thanks for the lib :D
![screenshot_thu_may_28_18_45_02_2015](https://cloud.githubusercontent.com/assets/105460/7876855/c4dff226-0597-11e5-9772-d272630d247f.png)
