### ISSUE TITLE
Can't include in two places (C++)

### ISSUE THREAD

**Issue by Ploppz** [nothings/stb#125]
Hi. I'm trying to use `stb_image_write.h`. I included it in `main.cpp`, as well as in another `.cpp` file. However, I get [these linker errors](https://bpaste.net/show/a5b5b50466b2).

In `main.cpp`, I have this:
```
#define STB_IMAGE_IMPLEMENTATION
#include "stb_image.h"
#define STB_IMAGE_WRITE_IMPLEMENTATION
#include "stb_image_write.h"
```
and in the other cpp file, I have this.
```
#define STB_IMAGE_WRITE_IMPLEMENTATION
#include "stb_image_write.h"
```
It works fine when I only do it in main.cpp.

Thanks.

**Comment by nothings** [comment]
Only put STB_IMAGE_WRITE_IMPLEMENTATION in one cpp file. It creates the implementation in that file.

**Comment by Ploppz** [comment]
Ah. Thanks.
