### ISSUE TITLE
stb_ds.h: Proper out-of-memory handling

### ISSUE THREAD

**Issue by Itay2805** [nothings/stb#1259]
**Describe the bug**
Currently on situations where `realloc` returns a `NULL` (for example when trying to allocate too much), the code will simply crash as there are no `NULL` checks on the return from `realloc`.

And more than that, it would be the best to not have it assert on such a case, but somehow fail and have the application handle the error.

**To Reproduce**
Easiest way is to make `realloc` always return `NULL`, but trying to allocate any size that takes more memory than `realloc` can allocate will work as well.

**Expected behavior**
Return some kind of indicative error when `realloc` returns `NULL`. For example setting the pointer to a special invalid value on error like `mmap` does (given `NULL` is already taken).

**Comment by nothings** [comment]
There is no way to address this reasonably given the API. Do not use stb_ds.h if you need robust out-of-memory handling.
