### ISSUE TITLE
Test files depend on removed stb_perlin.h

### ISSUE THREAD

**Issue by salty-horse** [nothings/stb#1260]
`stb_perlin.h` was removed on August 13, 2021, commit 59e7dec3e8bb0a8d4050d03c2dc32cf71ffa87c6

The test file and the references in the build files were not removed, so builds fail.

**Comment by musicinmybrain** [comment]
https://github.com/nothings/stb/pull/1204

**Comment by salty-horse** [comment]
Sorry, I searched issues but not PRs.

**Comment by musicinmybrain** [comment]
It’s good to have this recorded as an issue. I didn’t do that when I filed the PR. I just wanted to point out an available fix.

**Comment by nothings** [comment]
No worries saltyhorse, but no, there's no need for both an issue and a PR for the same issue. Anyway, the patent expires in less than a month, at which point the library can be restored, so it's not worth stripping all this other stuff out.
