### ISSUE TITLE
stb_image.h fails on CMYK jpeg

### ISSUE THREAD

**Issue by pjreddie** [nothings/stb#128]
When i try to load a jpg with CMYK colorspace stb_image fails. I understand that stb_image isn't supposed to be robust to every image format so this may not be an issue, is this just something you don't plan on supporting? Here's an example, thanks!

![bad](https://cloud.githubusercontent.com/assets/302108/8072398/47dd99cc-0eca-11e5-8b1c-479b68093fcf.jpg)

**Comment by nothings** [comment]
This does not seem to be an official standard, instead it is a variant someone (Adobe?) just started doing on their own. I have no plan to support it.

**Comment by pjreddie** [comment]
Makes sense, thanks for responding! ImageNet, a popular image dataset, has like 1 or 2 images in this format so i may try to cook something up so i don't have to use OpenCV. If I do, I'll let you know. Thanks again.
