### ISSUE TITLE
Specific versions of files are hard to find due to lack of tags

### ISSUE THREAD

**Issue by melbyruarus** [nothings/stb#129]
Finding a particular version of a specific file is not terribly easy as the repository has no version tags.

While adding tags for each version of a file will introduce a large number of tags (77 as of writing) it would make the repository more accessible both to humans and tools which do not play nice with commit hashes (I'm specifically thinking of CocoaPods).

I have created a quick and dirty python script which retrospectively adds tags for every commit it can find which changes a version number. It does this based off the first line of each .h file which starts with stb_.

Some examples of the tags it creates are as follows:
- stb_image_resize/0.50
- stb_truetype/0.8b
- stb_image/2.00

The source for the script is here: https://gist.github.com/melbyruarus/ffd577b97ed9e6c4f31b

**Comment by nothings** [comment]
What is the use-case/workflow for needing this functionality?

Like, I have my doubts whether you can even use most dependency management tools, since all of the files are stored in a single repo. If you need different versions of different stb libs, you would need to get only those files from the repo, not the whole repo.

Anyway, certainly the intent of the stb design is to sidestep it entirely by having people simply copy the files into their project, rather than leaving an explicit dependency on github.

**Comment by melbyruarus** [comment]
The two use-cases I have encountered thus far are:

1. Finding a specific version of a file. For example I have a project using stb_image 1.44, documenting this using a commit hash or relying on people to be able to find the commit for this is less than ideal. Elsewhere I could just refer to a named tag or branch.

2. As mentioned before, CocoaPods/other dependancy management tools. While this may not be the case for other dependancy management tools, CocoaPods can refer to a single file in a repository—if the commit the file exists in is tagged. Ideally I would wish to be able to create a CocoaPod specification for every stb file without having to fork and maintain a separate repo which mirrors this one—but with tags.

If you would rather not add tags I can likely work around this second point.

**Comment by ocornut** [comment]
I think what Sean is saying is that if your project use stb_image 1.44 then just copy that file into your project. Neither people or a tool will have to "find" the correct version.

**Comment by melbyruarus** [comment]
While this is not ideal for us I will have to do something of the sort.

Thanks for your time.
