### ISSUE TITLE
Many codepoints cannot be retrieved for Awesome Font 5 TTF

### ISSUE THREAD

**Issue by amesgames** [nothings/stb#1314]
**Describe the bug**
I am unable to use many of the glyphs in the awesome font TTF file because looking up their codepoints yields no glyph.

**To Reproduce**
1. Go grab an Awesome Font TTF: https://github.com/FortAwesome/Font-Awesome/blob/5.x/webfonts/fa-regular-400.ttf
2. Build the test_truetype.c test program under tests/. Make sure TT_TEST is defined. I also had to #if 0 the stbtt_GetCodepointSDF block of code because it does not find the codepoint.
3. Run the test program using these command-line args: 61461 13 fa-regular-400.ttf. The codepoint (61461) is for the home icon and is defined in the header file as ICON_FA_HOME over here https://github.com/juliettef/IconFontCppHeaders/blob/main/IconsFontAwesome5.h.
4. Observe that stbtt_GetCodepointBitmap returns NULL for that codepoint.
5. Also, using ImGui with that font yields many holes in the atlas.

**Expected behavior**
I expect to be able to load bitmaps for the font glyphs. Perhaps there is a misconception I have.

**Screenshots**
ImGui holes
![image](https://user-images.githubusercontent.com/16503839/159525901-426acb69-69b2-4f9d-81f8-6ec3a6b66c3b.png)
font-manager without holes
![image](https://user-images.githubusercontent.com/16503839/159526036-31f1ae76-f2ad-413e-831c-45c82e06f1e2.png)

**Comment by nothings** [comment]
you linked to a font that is 33 KB and contains 154 glyphs, and according to stb_image and the data tab on fontdrop.info does not include a mapping for 61461. fontdrop.info says:

```
glyphIndexMap: {"61444":3,"61445":4,"61447":5,"61463":6,"61474":7,"61476":8,"61486":9,"61502":10,"61508":11,"61527":12,"61528":13,"61529":14,"61550":15,"61552":16,"61555":17,"61557":18,"61563":1
..etc...
```

Note these are sorted, and there is no entry for 61461. I don't know what font manager is, but it's seems like it's looking at a different font.

**Comment by amesgames** [comment]
That is exactly what happened. Excuse the noise.
