### ISSUE TITLE
Assertion failed while loading 32bit BMP

### ISSUE THREAD

**Issue by cyanskies** [nothings/stb#1325]
The following gets written to the console after calling stbi_load:
Assertion failed: info.offset == s->callback_already_read + (int) (s->img_buffer - s->img_buffer_original)
stb_image.h, line 5397

Here is the BMP that triggers the error [example_bmp.zip](https://github.com/nothings/stb/files/8639336/example_bmp.zip).

**Comment by sharmadhiraj86** [comment]
I want to contribute to solve this issue. So if you could suggest me with some resources for this issue, it would be very helpful. Please assign me this issue as I want to work on it.

**Comment by sharmadhiraj86** [comment]
@cyanskies

**Comment by cyanskies** [comment]
Hi I've created a repo with the file and some code to load it. I mimic the same behaviour as SFML as that is where I experienced the original assertion error.

https://github.com/cyanskies/stb_recreate

The graphic was downloaded from a free game art repository(I don't remember which), it seems the original source for the image was 8bit, so it must have been converted along the way.

Using the latest stb in my repo above, stbi_load_from_callbacks() no longer asserts and the file is reported as having a bad offset.

Opening and saving the file with paint.net(forcing it to keep it as 32bit) doesn't seem to repair the file(it previews fine in windows and other image editors, but is still unloadable with stb).

I'm satisfied with the returned error, so I'll close this issue unless you want to try and make stb tolerate this file?

**Comment by sharmadhiraj86** [comment]
@cyanskies okay then you can close this issue but if you have any other issue of beginner level in C++ in any open source project, then please share that. Thank you

**Comment by nothings** [comment]
it opens correctly in mspaint and photoshop and FreeImage, so it's probably worth fixing it. it appears to have extra data in the header, and instead of skipping that data, stb_image throws an error.

**Comment by sharmadhiraj86** [comment]
I would like to contribute to solve this issue. So if possible, can you please assign this issue to me and help me with some resources for the issue? @nothings @cyanskies @rygorous @sgraham @jorgenpt @cap @RobLoach @krig @vincentisambart @akx @kinetiknz @jlnr @vfig @kritzikratzi @friesencr @Try @debiatan @enginmanap @GrayHatter @serge-rgb @blackpawn @1ace @MarcoLizza @mosra @aras-p @phprus @zanshi @zturtleman @mastensg

**Comment by nothings** [comment]
dude, why are you tagging a bunch of people? that's spam.

i don't use github assignment to outsider contributors, if you want to work on it, work on it.

**Comment by nothings** [comment]
@sharmadhiraj86

Let me be clearer. The thing you did with the list of random contributors is _spam_ and it is _not cool_ and it is the kind of thing that will get you banned from this repository. You get one strike, if you do something like that again you're out.

Feel free to continue participating normally, or if that makes you uncomfortable feel free to stop, whatever, but I have better things to do than police the repository issue comments.

**Comment by sharmadhiraj86** [comment]
> @sharmadhiraj86
> 
> Let me be clearer. The thing you did with the list of random contributors is _spam_ and it is _not cool_ and it is the kind of thing that will get you banned from this repository. You get one strike, if you do something like that again you're out.
> 
> Feel free to continue participating normally, or if that makes you uncomfortable feel free to stop, whatever, but I have better things to do than police the repository issue comments.
Sorry for that but I did not know whom to tag who will assign me the issue.

**Comment by akx** [comment]
@sharmadhiraj86 As Sean said, you don't need to be assigned. You're free to work on the issue, and open a PR that fixes things.

**Comment by rygorous** [comment]
A fix for this was just added on the dev branch. Will be in the next release.

**Comment by rygorous** [comment]
Fixed in 2.28.
