### ISSUE TITLE
stbir_resize_uint8_srgb() does not handle alpha correctly

### ISSUE THREAD

**Issue by theagentd** [nothings/stb#1338]
Hello!

I have been unsuccesful in making stb_resize handle my alpha channel correctly when generating mipmaps for my textures. I am unable to make stb_resize treat the alpha channel as linear.

Running the following code:
```
stbir_resize_uint8_srgb(
	inputData, 2, 2, 0, 
	outputData, 1, 1, 0, 
	4, 3, STBIR_FLAG_ALPHA_PREMULTIPLIED
);
```
where the input image is 
    (255, 255, 255, 255), (255, 255, 255, 255)
    (0, 0, 0, 0), (0, 0, 0, 0)
I expect the output to be
    (188, 188, 188, 128)
but I get the output
    (188, 188, 188, 188)
instead. In other words, it's treating the alpha as being sRGB-encoded even though the docs explicitly say that it by default will be treated as linear.

Looking at the documentation, it seems like the STBIR_FLAG_ALPHA_USES_COLORSPACE flag should be controlling if the sRGB conversion is applied to the alpha channel too, but I get (188, 188, 188, 188) regardless of if the flag is present or not.

In fact, the two alpha flags are behaving incorrectly when used on their own.

- No flags: (255, 255, 255, 128), correct given that it premultiplies, scales and unpremultiplies.
- STBIR_FLAG_ALPHA_PREMULTIPLIED: (188, 188, 188, 188). As described above, alpha channel is incorrect. I expect (188, 188, 188, 128).
- STBIR_FLAG_ALPHA_USES_COLORSPACE: (188, 188, 188, 188). Why is the color premultiplied here? I expect (255, 255, 255, 188).
- STBIR_FLAG_ALPHA_PREMULTIPLIED | STBIR_FLAG_ALPHA_USES_COLORSPACE: (188, 188, 188, 188). Correct.

Thanks.

**Comment by karrih** [comment]
Hmm, I gave it a quick try but couldn't repro. Ran this code:
```
uint8_t inputData[16] = {
    255, 255, 255, 255,
    255, 255, 255, 255,
    0, 0, 0, 0,
    0, 0, 0, 0,
};
uint8_t outputData[4];

stbir_resize_uint8_srgb(
    inputData, 2, 2, 0, 
    outputData, 1, 1, 0, 
    4, 3, STBIR_FLAG_ALPHA_PREMULTIPLIED
);

for (int i = 0; i < 4; ++i)
    printf("%d ", outputData[i]);
printf("\n");
```
Output: `188 188 188 128`

**Comment by rygorous** [comment]
Can't reproduce this either. Can you give a runnable test program that reproduces the issue with the current version of stb_image_resize and mention what compiler you're using?

**Comment by theagentd** [comment]
I am using the Java binding of stb_image_resize in LWJGL. I threw together a quick repro of the issue. For completeness I decided to print out the flags I was passing in.

```
Flags:  (0)
    255, 255, 255, 128

Flags: STBIR_FLAG_ALPHA_PREMULTIPLIED (-1)
    188, 188, 188, 188

Flags: STBIR_FLAG_ALPHA_USES_COLORSPACE (-1)
    188, 188, 188, 188

Flags: STBIR_FLAG_ALPHA_PREMULTIPLIED | STBIR_FLAG_ALPHA_USES_COLORSPACE (-1)
    188, 188, 188, 188
```

"... Why are they all -1?"

```
    /**
     * Set this flag if your texture has premultiplied alpha. Otherwise, stbir will use alpha-weighted resampling (effectively premultiplying, resampling,
     * then unpremultiplying).
     */
    public static final int STBIR_FLAG_ALPHA_PREMULTIPLIED = -1;

    /** The specified alpha channel should be handled as gamma-corrected value even when doing sRGB operations. */
    public static final int STBIR_FLAG_ALPHA_USES_COLORSPACE = -1;
```

So yeah, it's just a bug in the LWJGL binding. Sorry about that! I'll open an issue there instead!
