### ISSUE TITLE
stb_image fails on (seemingly) proper gif file

### ISSUE THREAD

**Issue by Mojofreem** [nothings/stb#135]
I've found some gif images fail to load with an "illegal code in raster" message. The gif file in question was generated by Photoshop, and seems to load properly in other programs/utilities. Note that this same execution path worked for previous edits of this gif file. The workaround I'm using at the moment is to save the file as interlaced.

Here is the specific image that's breaking:
https://www.dropbox.com/s/2z56lwl6ycglue9/this-breaks-stbi.gif?dl=0

**Comment by nothings** [comment]
That file loads for me.

Check one of these to make sure I tested the correct file.

sha-1: d0f26cb711f99c097c3d1e29f70390c6ba52d988
md5: 98dfdc8735e1272eb7b76c8b78afb5cc
sha-256: 1ae924021b7bf24b33eafa4636f338e979cbda0cf8d2e097741773277e3e5774
crc32: e27725b5

**Comment by Mojofreem** [comment]
Turns out I was using revision 2.03 of stb_image. I pulled the latest, and it does work.

**Comment by nothings** [comment]
Weird, since the changelog doesn't mention any changes to GIF. But alrighty!
