### ISSUE TITLE
stb_truetype: RGB Rasterization

### ISSUE THREAD

**Issue by Brotcrunsher** [nothings/stb#1351]
The rasterizer for stb_truetype currently has a single channel. This however is not how characters are typically rasterized. As an example, when zooming in on a "S" within the CMD, it looks as in the following picture:

![image](https://user-images.githubusercontent.com/19430475/180660460-1801d23a-8a68-477f-bd18-9522f849608c.png)

This RGB rasterization makes small characters look much better. Is it maybe already possible to do this and I overlooked something?

**Comment by nothings** [comment]
If you want to do this, you nee to do it yourself. The starting point is generating characters that are scaled 3x horizontally--which you can do with this library--and then applying various filters and mapping the text pixels to RGB or BGR. Doing this in the library is outside its scope, as there are many non-trivial issues that have to be solved. Search for "subpixel font rendering" on google.
