### ISSUE TITLE
PackFontRanges() creates a sigsegv crash

### ISSUE THREAD

**Issue by heysokam** [nothings/stb#1376]
**Describe the bug**
On file: `stb_truetype.h`
Before execution of line #4118, access to `spc->pixels` works normally
After execution of the loop, the address stops being accesible, and code that needs to access the pixel buffer just segfaults the application.
```c
STBTT_DEF int stbtt_PackFontRanges(stbtt_pack_context *spc, const unsigned char *fontdata, int font_index, stbtt_pack_range *ranges, int num_ranges)
{
   stbtt_fontinfo info;
   int i,j,n, return_value = 1;
   //stbrp_context *context = (stbrp_context *) spc->pack_info;
   stbrp_rect    *rects;

// <---- spc->pixels memory is readable correctly, and zeroed as expected
   // flag all characters as NOT packed
   for (i=0; i < num_ranges; ++i)
      for (j=0; j < ranges[i].num_chars; ++j)
         ranges[i].chardata_for_range[j].x0 =
         ranges[i].chardata_for_range[j].y0 =
         ranges[i].chardata_for_range[j].x1 =
         ranges[i].chardata_for_range[j].y1 = 0;
// <---- spc->pixels memory is not accessible anymore
   n = 0;
```
The line that crashes with SIGSEGV is at #3192
```c
result->pixels[j*result->stride + i] = (unsigned char) m;
```
Code in between this line, and the previously mentioned for loop, works correctly without crashing.

**To Reproduce**
- Follow the Font Packing documentation in stb_truetype
- Try to pack font `LiberationMono-Bold.ttf`, with charset range `0x20 to 0x7F`
- Compile on linux, with `gcc -ggdb`
- Execution will end with a Segmentation Fault, during the call to `stbtt_PackFontRange`

**Expected behavior**
If the spc->pixels buffer is accessible correctly right before the loop to flag all characters as not packed, code that doesn't modify that pixel buffer shouldn't break access to the buffer either.

**Screenshots**
![image](https://user-images.githubusercontent.com/7308253/190914306-b966417a-cb8d-4940-a99e-795a7f167fa3.png)

**Comment by nothings** [comment]
The loop in question only processes `ranges`. `ranges` is a user-supplied array of structs. It sounds like you haven't initialized `ranges` correctly in your code.

**Comment by heysokam** [comment]
As mentioned, I'm using `stbtt_PackFontRange`, not `stbtt_PackFontRanges` _(note the missing S)_ which generates such `ranges` struct from the function inputs `int first_unicode_codepoint_in_range` and `int num_chars_in_range`

As said, the value for first is `0x20` and the value for num is `0x7F - 0x20`, which resolves to `95`. This covers all ascii printable characters, starting from space and ending in tilde.
I checked with the debugger, and the integer values supplied to PackRange are correct

Are these incorrect integers to pass to the function?

**Comment by heysokam** [comment]
I gathered a bit more data.  
The loop breaks the `spc->pixels` address right before line #4120, when the value of `j` becomes `3`. So assuming this happens during the value assignment of the previous iteration, when `j=2`
Stepping through the loop, I noticed that the contents of `spc->nodes` are also being updated. I don't know if this is expected behavior, but noting it just in case.

**Comment by nothings** [comment]
I can only guess because you're not actually showing YOUR code which is where the bug lies.

You pass in `chardata_for_range` to `stbtt_PackFontRange`. Because you're asking for 95 characters, `chardata_for_range` needs to be an array of 95 elements. But probably you only have one, and the loop in question is overwriting random memory on the stack. Probably the spc->pxiels pointer is different after the loop than it was before the loop, because it got overwritten.
