### ISSUE TITLE
DWORD compilation error in stb.h

### ISSUE THREAD

**Issue by vinjn** [nothings/stb#138]
https://github.com/nothings/stb/blob/b53c08a14808ba911a0ffa81a26a00615026a702/stb.h#L1403-L1407

```C
   #if _MSC_VER > 1700
   DWORD i;
   _BitScanReverse(&i, n);
   return i != 0 ? i : -1;
   #else
```

I suggest replacing DWORD with unsigned long.

**Comment by zao** [comment]
For someone that is not on your machine, which Visual Studio version is this, and what is the actual error message?

**Comment by rwhitworth** [comment]
I experienced this issue with Visual Studio 2015 Community edition.

1>c:\fullpath\stb.h(1404): error C2065: 'DWORD': undeclared identifier

**Comment by nothings** [comment]
Fixed in new version by pull request as noted above.
