### ISSUE TITLE
Missing stb.h,  this header file is not in the library, so you can't build .

### ISSUE THREAD

**Issue by rcsteiner** [nothings/stb#1403]
File stb.h is missing or is referenced incorrectly in caveview.h

#ifndef INCLUDE_CAVEVIEW_H
#define INCLUDE_CAVEVIEW_H

#include "stb.h"

#include "stb_voxel_render.h"

**Comment by thedmd** [comment]
`stb.h` was moved to `deprecated/stb.h`

**Comment by rcsteiner** [comment]
Thanks.
