### ISSUE TITLE
JPG image decoded incorrectly

### ISSUE THREAD

**Issue by photopea** [nothings/stb#1409]
Your JPG decoder works great on thousands of JPG files, except of this one, do you know why?
![20221116221724_001](https://user-images.githubusercontent.com/15955558/202714533-24a33ff8-0bfe-4494-b4c9-b5a80726ffc5.jpg)

**Comment by nothings** [comment]
The image file contains bad data in the JPEG stream after the end of the regular image data. stb_image sees the bad data and abandons the image (even though it has already successfully decoded it). Other decoders must ignore the bad data.

**Comment by rygorous** [comment]
Fix for this is now in the dev branch, will be in the next release.

**Comment by rygorous** [comment]
Fixed in 2.28.
