### ISSUE TITLE
stb_voxel_render geometry not rendering the same as block_geometry

### ISSUE THREAD

**Issue by friesencr** [nothings/stb#143]
Naturally I could easily be doing this wrong or don't understand how the geometry works exactly.

For all of this I am using blocktype and setting the color of the blocktype's color = to the index of the blocktype.  When I am setting the blocktype I am using the height of the current voxel.  The effect is stripped colored height.

All of these are rendered using the 3d indexed lighting much like you have done in your open block game.

The first image is using blocktype and not geometry.
![screenshot_fri_jul_03_17_09_47_2015](https://cloud.githubusercontent.com/assets/105460/8505342/c2956848-21a8-11e5-906c-b7763992d7c7.png)

This image is using geometry: blocktype > 0 ? 2 : 0 -- so solid where there is a blocktype.  There is a big chunk of voxels not getting to drawn.  The large white thing is my 'water'.
![screenshot_fri_jul_03_17_11_34_2015](https://cloud.githubusercontent.com/assets/105460/8505389/8f50320a-21a9-11e5-8419-77a268b7650b.png)

The problem is also occurring in some odd areas other than my 'water height'
Here is block_geometry:
![screenshot_fri_jul_03_17_09_38_2015](https://cloud.githubusercontent.com/assets/105460/8505372/3ea63778-21a9-11e5-866b-3f65b417fdfc.png)

Here is geometry:
![screenshot_fri_jul_03_17_11_43_2015](https://cloud.githubusercontent.com/assets/105460/8505373/4792a5ec-21a9-11e5-83f6-f8c7af595fc2.png)

There is a case at the edge where it is being drawn correctly:
![screenshot_fri_jul_03_17_11_57_2015](https://cloud.githubusercontent.com/assets/105460/8505377/55e62d8a-21a9-11e5-913e-4ee43f15b399.png)

Thank you in advance,
Chris

**Comment by nothings** [comment]
Block geometry and geometry SHOULD work exactly the same, as you imagine... except:

Possibility #1: You still need block type to be 0 or non-0 depending on whether the block is empty or not. If input.geometry[] is EMPTY when block type is non-zero, or input,geometry[] is non-empty when block type is 0, it will break. This is documented, but perhaps not clearly enough.

Possibility #2: Somehow the geometries aren't coming out the same in the two cases. Not sure how this could happen; could be your bug, could be a bug in something I'm not thinking of. The geometries are loaded in these two sections:
    https://github.com/nothings/stb/blob/master/stb_voxel_render.h#L2891
    https://github.com/nothings/stb/blob/master/stb_voxel_render.h#L2911
so you could narrow your build call down just to a region that is inconsistent, and then breakpoint in there and see what geo & ngeo[6] are computing as ("ngeo" = "neighbor geometry").

**Comment by friesencr** [comment]
Adding up and down checks here:
https://github.com/nothings/stb/blob/master/stb_voxel_render.h#L3295
Fixed my problem.  I don't know why it wasn't implimented though.

```
         if (bt[z] && ( !bt[z+ns_off] || !STBVOX_GET_GEO(geo[z+ns_off]) || !bt[z-ns_off] || !STBVOX_GET_GEO(geo[z-ns_off])
                      || !bt[z+ew_off] || !STBVOX_GET_GEO(geo[z+ew_off]) || !bt[z-ew_off] || !STBVOX_GET_GEO(geo[z-ew_off])
                      || !bt[z-1] || !STBVOX_GET_GEO(geo[z-1]) || !bt[z+1] || !STBVOX_GET_GEO(geo[z+1])))
```

**Comment by nothings** [comment]
Haha whoops! Dunno why it was A TODO either.
