### ISSUE TITLE
how about give a explict end conditaton check for function  "stbi__hdr_test_core" for loop

### ISSUE THREAD

**Issue by longjiang321** [nothings/stb#1434]
the original  is below:
static int stbi__hdr_test_core(stbi__context *s, const char *signature)
{
   int i;
   **### for (i=0; signature[i]; ++i)**
      if (stbi__get8(s) != signature[i])
          return 0;
   stbi__rewind(s);
   return 1;
}

the for loop don`t have a explict end condition check,  it is easy to  understand as below in my opinion  

static int stbi__hdr_test_core(stbi__context *s, const char *signature)
{
   int i;
   for (i=0; i <= strlen(signature); ++i)
      if (stbi__get8(s) != signature[i])
          return 0;
   stbi__rewind(s);
   return 1;
}

**Comment by N-R-K** [comment]
`strlen` inside loop condition is a bad idea, if the compiler fails to optimize it then you'll end up with a quadratic loop.

Besides, conditions like that are very common in C. Weather someone wants to use `str[i]`, `str[i] != 0` or `str[i] != '\0'` is just a matter of style.
