### ISSUE TITLE
Defining single letters and not undoing that again is a recipe for trouble

### ISSUE THREAD

**Issue by ell1e** [nothings/stb#1463]
**Describe the bug**
`stb_vorbis.c` is meant to be included in larger surrounding files. It defines `L`, `C`, and `R`. Now any user code that follows will blow up if it uses single letter variables. I would suggest defining single letters *and leaving them defined* is bad practice.

**To Reproduce**
1. `#include <stb/stb_vorbis.c>`
2. Use something like `int L` in your own code afterward

**Expected behavior**
The include won't break use of single letter variables following later. However, it does.

**Screenshots**

**Comment by nothings** [comment]
stb_vorbis.c is not a header file, it is not meant to be included in larger surrounding files
