### ISSUE TITLE
stb_textedit.h bug with STB_TEXTEDIT_K_LINEEND in a multi-line context?

### ISSUE THREAD

**Issue by ocornut** [nothings/stb#148]
Following this bug report:
https://github.com/ocornut/imgui/issues/275

The STB_TEXTEDIT_K_LINEEND event is calling stb_textedit_find_charpos() which relies on STB_TEXTEDIT_LAYOUTROW. If STB_TEXTEDIT_LAYOUTROW count the \n at the end of a line as part of 'num_chars' then effectively the cursor position will be set after the '\n' aka on the next-line instead of being set at the of the current line.

It is a little unclear from the specs of STB_TEXTEDIT_LAYOUTROW() if the trailing \n at the end of line could be counted in the 'num_chars' output but looking and running at the code suggest that it has to and I'm not sure how it could ever work without counting it. 

Which suggest that there is a bug in the two case statements for STB_TEXTEDIT_K_LINEEND (shifted and non-shifted) putting the cursor position 1 too far. We can't just remove -1 as we need to consider a) single_line mode and b) multi-line buffer without a trailing \n on the last line.

Adding those 2 lines after the state->cursor assignment in STB_TEXTEDIT_K_LINEEND
```cpp
if (find.length > 0 && STB_TEXTEDIT_GETCHAR(str, state->cursor-1) == STB_TEXTEDIT_NEWLINE)
   state->cursor--;
```
And in STB_TEXTEDIT_K_LINEEND | STB_TEXTEDIT_K_SHIFT:
```cpp
if (find.length > 0 && STB_TEXTEDIT_GETCHAR(str, state->cursor-1) == STB_TEXTEDIT_NEWLINE)
   state->cursor = state->select_end = state->cursor - 1;
```
Appears to fix it, but I'm not sure if that's a correct fix.
*EDIT* minor edit: removed the unnecessary `!state->single_line &&` in the if statements.

**Comment by nothings** [comment]
Makes sense, I'll investigate.

**Comment by DanielGibson** [comment]
One detail, not sure if ignoring it breaks the code: what if the line ending is not "\n", but "\r\n" - do we have to go back two chars then?

**Comment by nothings** [comment]
These fixes sound right to me, and they're in the next version, but I haven't actually extensively tested them.

@DanielGibson Belatedly... stb_textedit doesn't handle \r\n type line endings; it just has a STB_TEXTEDIT_NEWLINE macro that can only be a single character.
