### ISSUE TITLE
texture random flipped orientation

### ISSUE THREAD

**Issue by git-xiaocao** [nothings/stb#1489]
```c++
	bool LoadTextureFromMemory(unsigned char* buffer, unsigned int buffer_size, ID3D11ShaderResourceView** out_srv, int* out_width, int* out_height)
	{
		// Load from memory into a raw RGBA buffer
		int image_width = 0;
		int image_height = 0;
		unsigned char* image_data = stbi_load_from_memory(buffer, buffer_size, &image_width, &image_height, NULL, 4);
		if (image_data == NULL)
			return false;


		// Create texture
		D3D11_TEXTURE2D_DESC desc;
		ZeroMemory(&desc, sizeof(desc));
		desc.Width = image_width;
		desc.Height = image_height;
		desc.MipLevels = 1;
		desc.ArraySize = 1;
		desc.Format = DXGI_FORMAT_R8G8B8A8_UNORM;
		desc.SampleDesc.Count = 1;
		desc.Usage = D3D11_USAGE_DEFAULT;
		desc.BindFlags = D3D11_BIND_SHADER_RESOURCE;
		desc.CPUAccessFlags = 0;

		ID3D11Texture2D* pTexture = NULL;
		D3D11_SUBRESOURCE_DATA subResource;
		subResource.pSysMem = image_data;
		subResource.SysMemPitch = desc.Width * 4;
		subResource.SysMemSlicePitch = 0;
		if (device->CreateTexture2D(&desc, &subResource, &pTexture) != S_OK)
		{
			*out_width = 0;
			*out_height = 0;
			stbi_image_free(image_data);

			return false;
		}

		// Create texture view
		D3D11_SHADER_RESOURCE_VIEW_DESC srvDesc;
		ZeroMemory(&srvDesc, sizeof(srvDesc));
		srvDesc.Format = DXGI_FORMAT_R8G8B8A8_UNORM;
		srvDesc.ViewDimension = D3D11_SRV_DIMENSION_TEXTURE2D;
		srvDesc.Texture2D.MipLevels = desc.MipLevels;
		srvDesc.Texture2D.MostDetailedMip = 0;
		device->CreateShaderResourceView(pTexture, &srvDesc, out_srv);
		pTexture->Release();

		*out_width = image_width;
		*out_height = image_height;
		stbi_image_free(image_data);

		return true;
	}
```

The texture orientation that this code loads from memory is random, restarting the program multiple times will see the texture facing a different orientation (flipped)

https://github.com/ocornut/imgui/issues/6530

**Comment by nothings** [comment]
The above function as written will never cause the image to be flipped unless (a) you're manipulating `stbi_set_flip_vertically_on_load` or (b) you have a memory write error and are randomly writing into the variable set by `stbi_set_flip_vertically_on_load`. Without knowing more info, it's impossible to know if this is a bug in stb_image or a bug in your code.

**Comment by git-xiaocao** [comment]
I found that using `stbi_set_flip_vertically_on_load(0)` and `stbi_set_flip_vertically_on_load_thread(0)` before `stbi_load_from_memory` will not randomly flip the texture.

```c++
#define STB_IMAGE_IMPLEMENTATION
#define STBI_NO_STDIO
#define STBI_ONLY_JPEG
#define STBI_ONLY_PNG
#include "stb_image.h"

...
stbi_set_flip_vertically_on_load(0);
stbi_set_flip_vertically_on_load_thread(0);
unsigned char* image_data = stbi_load_from_memory(buffer, buffer_size, &image_width, &image_height, NULL, 4);

```

But if I don't add these codes, the texture is randomly flipped.

**Comment by nothings** [comment]
Both of those default to 0. So most likely you're either using another library that is using stb_image and setting that value, or you're randomly trashing memory.

**Comment by zao** [comment]
I pointed the user over here from the Dear ImGui issue where they first reported the problem.
There I suggested this as a further avenue of investigation:
> If it's varying per-run, a wild guess is that the code might be expecting thread-local variables to be zero-initialized but your platform's thread-local variables might not give that guarantee, or it might differ based on whether your STB_IMAGE_IMPLEMENTATION inclusion is in a C or C++ source file.

It would be interesting if @git-xiaocao could tell more about what platform and compiler this is and which implementation of `STBI_THREAD_LOCAL` is used there. While the workarounds are likely sufficient to mask the problem, there's definitely an underlying problem at hand, may it be overwritten variables or insufficient platform guarantees.

It might also be worthwhile to inspect it in a debugger to see what values the three implementation variables have in runs without the workarounds - that would help to tell if they seem to be legitimately set or have indeterminate or overwritten values.

**Comment by git-xiaocao** [comment]
I used `stb_image` like this before.
```c++
#include "imgui/imgui.h"
#include "imgui/imgui_impl_win32.h"
#include "imgui/imgui_impl_dx11.h"

#define STB_IMAGE_IMPLEMENTATION
#include "stb_image.h"
```

```c++
bool LoadTextureFromMemory(unsigned char* buffer, unsigned int buffer_size, ID3D11ShaderResourceView** out_srv, int* out_width, int* out_height)
{
	// Load from memory into a raw RGBA buffer
	int image_width = 0;
	int image_height = 0;
	unsigned char* image_data = stbi_load_from_memory(buffer, buffer_size, &image_width, &image_height, NULL, 4);
	if (image_data == NULL)
		return false;


	// Create texture
	D3D11_TEXTURE2D_DESC desc;
	ZeroMemory(&desc, sizeof(desc));
	desc.Width = image_width;
	desc.Height = image_height;
	desc.MipLevels = 1;
	desc.ArraySize = 1;
	desc.Format = DXGI_FORMAT_R8G8B8A8_UNORM;
	desc.SampleDesc.Count = 1;
	desc.Usage = D3D11_USAGE_DEFAULT;
	desc.BindFlags = D3D11_BIND_SHADER_RESOURCE;
	desc.CPUAccessFlags = 0;

	ID3D11Texture2D* pTexture = NULL;
	D3D11_SUBRESOURCE_DATA subResource;
	subResource.pSysMem = image_data;
	subResource.SysMemPitch = desc.Width * 4;
	subResource.SysMemSlicePitch = 0;
	if (device->CreateTexture2D(&desc, &subResource, &pTexture) != S_OK)
	{
		*out_width = 0;
		*out_height = 0;
		stbi_image_free(image_data);

		return false;
	}

	// Create texture view
	D3D11_SHADER_RESOURCE_VIEW_DESC srvDesc;
	ZeroMemory(&srvDesc, sizeof(srvDesc));
	srvDesc.Format = DXGI_FORMAT_R8G8B8A8_UNORM;
	srvDesc.ViewDimension = D3D11_SRV_DIMENSION_TEXTURE2D;
	srvDesc.Texture2D.MipLevels = desc.MipLevels;
	srvDesc.Texture2D.MostDetailedMip = 0;
	device->CreateShaderResourceView(pTexture, &srvDesc, out_srv);
	pTexture->Release();

	*out_width = image_width;
	*out_height = image_height;
	stbi_image_free(image_data);

	return true;
}
```

Dear ImGui Platform see include header file.

Development Platform is `Visual Studio 2022` `MSVC` `C++17` `Windows 11 SDK 10.0.22621.0`

**Comment by KyuuChiaki** [comment]
---

I hit the same thing. VS2022, C++20, Win32, DLL injected into a game. Debug always fine, Release randomly flips.

Root cause is `stb_image.h` L1124:

```c
static STBI_THREAD_LOCAL int stbi__vertically_flip_on_load_local, stbi__vertically_flip_on_load_set;
```

No `= 0`. Doesn't matter for a normal exe — TLS gets zeroed. But with DLL injection, threads that existed before the DLL loaded don't get their TLS zero-initialized. Windows + `LoadLibrary` thing, been like this forever.

So `_set` is whatever garbage happened to be in that slot. In Release it's often non-zero. The macro:

```c
_set ? _local : _global
```

picks `_local`, which is also garbage → random flip.

Why it's not "random every time" but depends on timing: main thread during DLL init gets fresh TLS → works. Host's render thread later gets stale TLS → flips. Consistent pattern across runs.

Fix is adding `= 0`:

```c
static STBI_THREAD_LOCAL int stbi__vertically_flip_on_load_local = 0, stbi__vertically_flip_on_load_set = 0;
```

Same for the unpremultiply / de-iphone ones at L5010.

---

一样的症状，VS2022 / C++20 / Win32，DLL 注入到游戏进程。Debug 永远正常，Release 随机翻转。

根因在 `stb_image.h` 第 1124 行，两个 `thread_local` 变量没写 `= 0`。普通 exe 里 TLS 自动清零无所谓，但 DLL 注入时，加载前就在跑的线程不会被清零。`LoadLibrary` 的老毛病。

所以 `_set` 是垃圾值，Release 下大概率非零，宏走 `_local` 分支，也是垃圾 → 随机翻。

不是"次次翻"是因为看哪个线程调的：主线程加载时有新鲜 TLS → 正常，宿主渲染线程后加载是旧 TLS → 翻车。

修法就一行补 `= 0`。5010 行那两组同理。
