### ISSUE TITLE
The Jpeg image is decoded incorrectly.

### ISSUE THREAD

**Issue by evilrace** [nothings/stb#1503]
**Describe the bug**
I load a image using stb_image.h library.
but the values of image are different with values loaded by other libraries(opencv, window paint app)
In detail, the value at position (47,27,2 h,w,c) of image is 128, but stb image read this as 130.
the difference points are displayed as below. this shows difference between original image loaded by opencv and stb image scaled up by 255 times 
![image](https://github.com/nothings/stb/assets/34363323/f15ceb64-ecb1-48be-8d33-0e5449f7f819)

**To Reproduce**
1. read the image below
2. compare the values this with a image loaded by other image library
![dog_416x416](https://github.com/nothings/stb/assets/34363323/cb7923c7-5829-4a9f-9bf1-7ffc5df8f662)

**Expected behavior**

loaded values are different.

**Screenshots**

**Comment by nothings** [comment]
This is not a bug.

JPEG images are a lossy format which do not exactly reproduce the original compressed image. The exact nature of that inexact reproduction is not defined by the JPEG specification; there is no standard correct way to decode a given JPEG. Every decoder is potentially different, and producing different values from other decoders is the execpted behavior.
