### ISSUE TITLE
Segmentation fault when load an corruption pictures in stbi_load_from_memory

### ISSUE THREAD

**Issue by Nuctori** [nothings/stb#1583]
**Describe the bug**
I tried to open the image using stbi_load_from_memory after downloading it on the web, but because I downloaded a data corrupted image, the stb reads it in with a segmentation fault

**To Reproduce**
1. load any data corrupted image. You can use any non-image file to simulate
2. see error, and some time will segmentation fault 

**Expected behavior**
return a error in some way when the image is data corrupted

**Comment by nothings** [comment]
stb_image detects many kinds of corruption and does report them. 

it is also possible there is a bug and it will segmentation fault. there are a number of open issues and PRs that deal with this (some of which have been fixed and not released yet).

Without an example that we can reproduce, there's nothing we can do with your report.

**Comment by Nuctori** [comment]
> stb_image detects many kinds of corruption and does report them.
> 
> it is also possible there is a bug and it will segmentation fault. there are a number of open issues and PRs that deal with this (some of which have been fixed and not released yet).
> 
> Without an example that we can reproduce, there's nothing we can do with your report.

Sorry, is my fault..I'm free a Null symbol make this.
![image](https://github.com/nothings/stb/assets/23477613/1c347afc-51fa-44f6-862d-c20e19bc9c92)
