### ISSUE TITLE
stb_image incorrectly sees png as 16bit.

### ISSUE THREAD

**Issue by marauder2k7** [nothings/stb#1585]
**Describe the bug**
When loading a PNG file stb incorrectly sees it as a 16bit image, when it is an 8bit SRGB file

**To Reproduce**

using this call with an 8bit SRGB file exported from substance designer
`if (stbi_is_16_bit(path.getFullPath().c_str()))`

it returns true, yet renderDoc and a few other programs we have checked it with report it as 8bit format.

am i using this incorrectly?

**Comment by nothings** [comment]
works for me on my PNGs. you'll have to provide an image that it doesn't work on.

**Comment by marauder2k7** [comment]
![sandy_d](https://github.com/nothings/stb/assets/5903429/51be27ce-a101-4c83-9ba8-ce5c2c2a7efc)

this is one of the images it does it on.

**Comment by nothings** [comment]
exiftool reports this as "Bit Depth: 16" and ffprobe reports "Video: png, rgba64be(pc)" (64 = 4 channels * 16 bits). It's a 16-bit image.

**Comment by marauder2k7** [comment]
![image](https://github.com/nothings/stb/assets/5903429/44ce5bee-d94f-4b28-9076-629aade66daf)
render doc

**Comment by nothings** [comment]
please don't report renderdoc bugs to me, i don't make renderdoc
