### ISSUE TITLE
problem loading bmp & jpg 

### ISSUE THREAD

**Issue by codz01** [nothings/stb#161]
Hi
i've a simple 24bits bmp file (150x120) , when using SDL_LoadBMP it displayed correctly but when using stb_image it displayed wrong .
![wrong](https://cloud.githubusercontent.com/assets/10813427/9192511/a7fa6744-4003-11e5-8ffc-3a4d5ecc98b2.jpg)

there is no problem if the same image converted to png :
![correct](https://cloud.githubusercontent.com/assets/10813427/9192526/ce005020-4003-11e5-9dc4-6f5b5b835fc0.jpg)

btw , if i i change the size of the bmp from 150x120 to 152x120 , it then displayed correctly 

the function i use to load image is :
SDL_Surface *load_image(const char * filename)
{
    int x, y, comp;
    unsigned char *data;
    unsigned int rmask, gmask, bmask, amask;
    SDL_Surface *rv;

    FILE *file = fopen(filename, "rb");
    if (!file)
        return 0;

    data = stbi_load_from_file(file, &x, &y, &comp, 0);
    fclose(file);

#if SDL_BYTEORDER == SDL_BIG_ENDIAN
    rmask = 0xff000000;
    gmask = 0x00ff0000;
    bmask = 0x0000ff00;
    amask = 0x000000ff;
#else
    rmask = 0x000000ff;
    gmask = 0x0000ff00;
    bmask = 0x00ff0000;
    amask = 0xff000000;
#endif

    if (comp == 4) {
        rv = SDL_CreateRGBSurface(0, x, y, 32, rmask, gmask, bmask, amask);
    } else if (comp == 3) {
        rv = SDL_CreateRGBSurface(0, x, y, 24, rmask, gmask, bmask, 0);
    } else {
        stbi_image_free(data);
        return 0;
    }

    memcpy(rv->pixels, data, comp * x * y);
    stbi_image_free(data);

    return rv;
}

and this is the image

![cb](https://cloud.githubusercontent.com/assets/10813427/9192637/ae9b4734-4004-11e5-80b0-21dbdca5e6c1.jpg)

**Comment by yzt** [comment]
It sounds like a row alignment issue. IIRC, bmp rows are supposed to be
padded to multiples of 4 bytes, and in your image, they might not be (I say
this because 150*3 is not divisible by 4, but 152*3 is.)

I have not looked at the source of neither STB nor SDL, but if STB expects
that multiple-of-four padding and SDL does not, then the reported behavior
*might* happen.
​
-yzt

**Comment by nothings** [comment]
stb_image does not pad, so it implicitly uses a stride (pitch) of comp*x. 

The relevant field is SDL_surface is rv->pitch. Add an assertion that "x * comp == rv->pitch". If that assertion fails, then this is a problem with your use of SDL, not an stb_image problem.

**Comment by codz01** [comment]
yes you are right , i thought stb_image do the padding automatically . ok i've to malloc another array with appropriate size , then copying line by line .

thanks

**Comment by nothings** [comment]
IIRC, you don't need to malloc another array, SDL is already allocating one of the correct size. You just need to replace the memcpy() in the above code with copying line-by-line.
