### ISSUE TITLE
stb_image: Add support for gainmaps (`libultrahdr`) support to image loader

### ISSUE THREAD

**Issue by cmahnke** [nothings/stb#1637]
**Is your feature request related to a problem? Please describe.**
This is a feature request, see https://github.com/Tom94/tev/issues/226, which uses `sbt_image` internally.

**Describe the solution you'd like**
Loading HDR images, in the form of JPEG files with gainmap should be supported. The format is implemented by [`libultrahdr`](https://github.com/google/libultrahdr), a technical description is linked in the further ressources section.

**Describe alternatives you've considered**
None yet, since this is upstream library.

**Additional context**
Further Resources:
* [Description of the format](https://developer.android.com/media/platform/hdr-image-format?hl=de)
* [Using `libultrahdr` with Python](https://www.reddit.com/r/Python/comments/1ac8ooy/playing_around_with_ultra_hdr/)
* [Greg Benz on HDR](https://gregbenzphotography.com/hdr/)

CC @gregbenz

**Comment by nothings** [comment]
We're not adding any new image formats to stb_image.

**Comment by cmahnke** [comment]
It's not a completely new format, it's just a SDR JPEG with an additional data stream, containing the gainmap.
