### ISSUE TITLE
Characterizing crashes with respect to file size

### ISSUE THREAD

**Issue by Samg381** [nothings/stb#1639]
Hello,

I have been using `stb_image.h` in a personal C++ project for a few years now. The project uses GLFW / OpenGL and ImGui to load a very large satellite map image. Over time, my requirements for the size of this map have increased.

I now seem to have bumped into the image size limit of `stb_image.h`. Here are the identify outputs of two images I am using for testing:

**Image 1 (Loads perfectly)**
map_topo.jpg PNG 15360x15360 15360x15360+0+0 8-bit sRGB 260.76MiB 0.000u 0:00.000

**Image 2 (Immediately crashes program)**
map_topo_new.jpg JPEG 65024x65024 65024x65024+0+0 8-bit sRGB 467.523MiB 0.000u 0:00.000

I presume this is simply me exceeding the size of some internal data structure, which would make sense, but I want to check that I am not doing anything wrong. I read in issue #672 that the maximum file size is ~256 MB, but Image 1 is 260 MB and loads fine.

I am using the latest ([ae721c5](https://github.com/nothings/stb/commit/ae721c50eaf761660b4f90cc590453cdb0c2acd0)) version of `stb_image.h` as of this writing, and am using the below snippets to load the image.

Any clarity, insight, or workarounds would be much appreciated! Thank you.

```
bool LoadTextureFromFile(const char* filename, GLuint* out_texture, int* out_width, int* out_height)
{

    // Load from file
    int image_width = 0;
    int image_height = 0;
    unsigned char* image_data = stbi_load(filename, &image_width, &image_height, NULL, 4);
    
    if (image_data == NULL) {
        printf("Error with stb_image.h - unable to open file.\n");
        return false;
    }

    // Create a OpenGL texture identifier
    GLuint image_texture;
    glGenTextures(1, &image_texture);
    glBindTexture(GL_TEXTURE_2D, image_texture);

    // Setup filtering parameters for display
    glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MIN_FILTER, GL_LINEAR);
    glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MAG_FILTER, GL_LINEAR);
    glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_WRAP_S, GL_CLAMP_TO_EDGE); // This is required on WebGL for non power-of-two textures
    glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_WRAP_T, GL_CLAMP_TO_EDGE); // Same

    // Upload pixels into texture
#if defined(GL_UNPACK_ROW_LENGTH) && !defined(__EMSCRIPTEN__)
    glPixelStorei(GL_UNPACK_ROW_LENGTH, 0);
#endif
    glTexImage2D(GL_TEXTURE_2D, 0, GL_RGBA, image_width, image_height, 0, GL_RGBA, GL_UNSIGNED_BYTE, image_data);
    stbi_image_free(image_data);

    *out_texture = image_texture;
    *out_width = image_width;
    *out_height = image_height;

    return true;
}
```

```
        bool ret = LoadTextureFromFile("maps/map_topo.jpg", &map_image, &map_width, &map_height);

        if (!ret) {
            printf("[ERROR] Map loading failed.");
            exit(0);
        }

        IM_ASSERT(ret);
```

**Comment by nothings** [comment]
The size limit mentioned at your link is the size limit of the *decoded* image size. stb_image uses 32-bit arithmetic and cannot easily be made 64-bit. 32-bit is limited to addressing 2^32 bytes, often only 2^31 or 2^30 bytes addressable in a 32-bit image.

An image of 65536 x 65536 is an image of 2^16 x 2^16 pixels, or 2^32 pixels. Each pixel would take 3 bytes, so you're talking about something like 3*2^32. Relative to the (say) 2^30 bytes available in user space, that's 12*2^30, or 12 times larger than avaliable memory in a 32-bit program.

If you must load such images and you're in a 64-bit program, you will need to use a different image library. However, you may find that OpenGL/your hardware does not support such larger textures either.
