### ISSUE TITLE
[stb_image] `stbi__do_png` doesn't set number of components correctly after changing using `req_comp`

### ISSUE THREAD

**Issue by marctenbosch** [nothings/stb#1662]
**Describe the bug**
`stbi__do_png` doesn't set the number of components correctly after changing them using req_comp. 
Seems like at some point the line 
`      if (n) *n = p->s->img_out_n;`
was changed to 
`      if (n) *n = p->s->img_n;`
which is not the new number of components after conversion but the old one. I'm not sure why that line was changed but the reported number of components is now incorrect.

**To Reproduce**
1. Load a 3 component png image
2. call `stbi_load_from_file` with `req_comp==1` (which calls `stbi__do_png`)
3. n is still set to 3

**Expected behavior**
n should be set to 1

**Comment by nothings** [comment]
This is the correct, documented behavior--that always confuses everyone.

Originally there was no stbi_info function, so the only way to get the number of channels in the file without loading it twice was through this variable.
