### ISSUE TITLE
STBIR-NO-UNROLL_LOOP_STAR breaks mingw gcc compilation

### ISSUE THREAD

**Issue by TianZerL** [nothings/stb#1663]
**Describe the bug**
#1655 adds `STBIR-NO-UNROLL_LOOP_STAR` to `stb_image_resize2.h`, whitch breaks mingw gcc compilation.

```shell
/stb_image_resize2.h: In function 'void stbir_simd_memcpy(void*, const void*, size_t)':
/stb_image_resize2.h:2588:12: error: missing loop condition in loop with 'GCC unroll' pragma before ';' token
 2588 |       for(;;)
      |   
```

**To Reproduce**
Use MinGW-W64 (14.1.0 for me) to build stb_image_resize2.h will get this error.

**Comment by yangfl** [comment]
Also on GCC 13/14.

Sample: https://godbolt.org/z/d9jvrxKfK

**Comment by jeffrbig2** [comment]
This was tested on GCC at compiler explorer, but I only have mingw my computer in another state.  Maybe @TianZerL can check it?

**Comment by TianZerL** [comment]
@jeffrbig2 
I can confirm that @1671 has fixed this for mingw gcc.
But I think there is still issue for clang: https://godbolt.org/z/dv6Tjadrf. Both mingw clang and x86 clang have the same issue.

**Comment by jeffrbig2** [comment]
Clang uses completely different pragmas?

**Comment by TianZerL** [comment]
@jeffrbig2
No, it should be compatible with gcc, but not completely compatible.
According to https://github.com/llvm/llvm-project/issues/88624, it should have fixed in some versions, but not for Clang 18 in godbolt.
Maybe make `_Pragma("GCC unroll 0")` for gcc only?

**Comment by jeffrbig2** [comment]
Dude, what are you talking about?  stb_image_resize2 has a separate clang codepath - it doesn't use the gcc pragmas at all?

> Maybe make _Pragma("GCC unroll 0") for gcc only?

It is only for GCC!

**Comment by jeffrbig2** [comment]
Look at line 1206-1235...

**Comment by TianZerL** [comment]
@jeffrbig2
oops, my bad.

> Clang uses completely different pragmas?

I thought this was a question 😂.

**Comment by jeffrbig2** [comment]
Haha, ok, cool!!

**Comment by nothings** [comment]
Fix committed.
