### ISSUE TITLE
stb_truetype.h shadowed variables warning with VS2015

### ISSUE THREAD

**Issue by ocornut** [nothings/stb#167]
FYI apparently this warning has been promoted in VS2015

"declaration of 'xx' hides previous local declaration"
http://blogs.msdn.com/b/vcblog/archive/2014/11/12/improvements-to-warnings-in-the-c-compiler.aspx

I don't know at which warning level it is enabled (default? or higher?), I don't have VS2015 myself,  I may investigate if you want. 

It happens in stb_truetype.h at least

```
// rename variables to clear pairs
float y0 = y_top;
float x1 = (float) (x);
float x2 = (float) (x+1);
float x3 = xb;
float y3 = y_bottom;
float y1,y2;```
```

```
1>e:\krg\code\system\render\imgui\stb_truetype.h(2004): error C2220: warning treated as error - no 'object' file generated
1>e:\krg\code\system\render\imgui\stb_truetype.h(2004): warning C4456: declaration of 'y0' hides previous local declaration
1>  e:\krg\code\system\render\imgui\stb_truetype.h(2004): note: to simplify migration, consider the temporary use of /Wv:18 flag with the version of the compiler with which you used to build without warnings
1>  e:\krg\code\system\render\imgui\stb_truetype.h(1910): note: see declaration of 'y0'
1>e:\krg\code\system\render\imgui\stb_truetype.h(2009): warning C4456: declaration of 'y1' hides previous local declaration
1>  e:\krg\code\system\render\imgui\stb_truetype.h(2009): note: to simplify migration, consider the temporary use of /Wv:18 flag with the version of the compiler with which you used to build without warnings
1>  e:\krg\code\system\render\imgui\stb_truetype.h(1910): note: see declaration of 'y1'
```

I don't know what is your policy with that sort of stuff. You can possiibly surround the code with VS specific pragma if you want to keep the shadowing.

```
#pragma warning( push )
#pragma warning( disable : 4456 )
..
#pragma warning( pop )
```

Similar stuff in stb_image_write.h according to https://github.com/memononen/nanosvg/issues/41#issuecomment-111478485 (haven't tried myself)

**Comment by nothings** [comment]
My policy is to fix things like that. I will.

**Comment by nothings** [comment]
Fixed the ones in stb_image_write

**Comment by nothings** [comment]
Fixed the stb_truetype ones.

**Comment by DJLink** [comment]
I found some more (using VS2015 Update 3 with Level 4(/w4) 
on stb_image.h lines 3638 and 3681, both referring to variable k shadowing previous declaration.

Want me to send the updated one or is it something it's easier for you to fix directly?

**Comment by nothings** [comment]
I'll just fix it.
