### ISSUE TITLE
Compiler warnings

### ISSUE THREAD

**Issue by JBoschma** [nothings/stb#1687]
Not sure if this is a known issue, just letting you know: in my C++ project I got several warnings using 
```
gcc 13.2.0
-Wall -Wextra -O3
C++20
```
about missing initializer values for members of `stbi__write_context` when using `stb_image_write.h`. So I replaced:
`stbi__write_context s = { 0 };`
with
`stbi__write_context s = { nullptr, nullptr, {}, 0 };`

which eliminates these warnings.

**Comment by N-R-K** [comment]
Duplicate of https://github.com/nothings/stb/issues/1099

Summary is that missing field initializer warning behaves differently between:

- c and c++
- gcc and clang
- different versions of gcc/clang

And so we haven't gotten any satisfactory way to address it all. I recommend silencing that warning (either globally or for stb header specifically via pragma) for now.

**Comment by JBoschma** [comment]
Thanks for pointing out the earlier issue, I should have searched better.
