### ISSUE TITLE
Using stbi_load_gif_from_memory results in incorrect image data for each frame of the GIF

### ISSUE THREAD

**Issue by pudding186** [nothings/stb#1688]
After rendering each frame of the GIF, I noticed that some images are not correct.
![horse-1237_256](https://github.com/user-attachments/assets/d2cc49b0-a48d-4982-8121-2c96fd6a8ca8)
![frame](https://github.com/user-attachments/assets/9413023d-af46-4bd4-a68f-4629f4f5495d)

**Comment by pudding186** [comment]
@cocoa-xu thanks for your help, I applied your patch, but it seems that the issue still persists. You can try it with my horse GIF.

**Comment by pudding186** [comment]
@cocoa-xu Thank you so much. The problem is solved. I hope the author @nothings can merge your pull request soon.

**Comment by cocoa-xu** [comment]
> @cocoa-xu Thank you again for your help.

Not a problem!

>  In my program, I merge each frame's texture into a large texture, and then use UV coordinates based on the delay time read from the GIF to display the animation. I found that the following code seems to be necessary for correct display:
> 
> if (dispose == 3) {
> // background is what out is after the undoing of the previous frame;
> memcpy(g->background, g->out, 4 * g->w * g->h); 
> } 
> Please try this

Ah I wasn't really sure about this, but I did get the same results when using `if (dispose == 3) {`.

I wonder if you happen to have any example file(s) that you can share for this case, which gives wrong data if we use `if (dispose == 2 || dispose == 3) {` while returning the correct data when we do `if (dispose == 3) {`.

**Comment by pudding186** [comment]
![horse-1237_512](https://github.com/user-attachments/assets/502a385a-eb86-45ad-928b-7773ce8708df)
Yes, you can try this GIF file. In my program, I found that there are still incorrect frames when it is equal to 2 or equal to 3.

**Comment by pudding186** [comment]
> > @cocoa-xu Thank you again for your help.
> 
> Not a problem!
> 
> > In my program, I merge each frame's texture into a large texture, and then use UV coordinates based on the delay time read from the GIF to display the animation. I found that the following code seems to be necessary for correct display:
> > if (dispose == 3) {
> > // background is what out is after the undoing of the previous frame;
> > memcpy(g->background, g->out, 4 * g->w * g->h);
> > }
> > Please try this
> 
> Ah I wasn't really sure about this, but I did get the same results when using `if (dispose == 3) {`.
> 
> I wonder if you happen to have any example file(s) that you can share for this case, which gives wrong data if we use `if (dispose == 2 || dispose == 3) {` while returning the correct data when we do `if (dispose == 3) {`.

![horse-1237_512](https://github.com/user-attachments/assets/5e9eba06-c0db-4a42-8c4b-fae1358baa93)
Yes, you can try this GIF file. In my program, I found that there are still incorrect frames when it is equal to 2 or equal to 3.

**Comment by cocoa-xu** [comment]
Okay gotcha, I've updated the PR! Thanks for sending the test file! ;)
