### ISSUE TITLE
rect_pack crashes using truetype (new API) with padding=0 

### ISSUE THREAD

**Issue by 0x1100** [nothings/stb#169]
I used `std_truetype.h` with its new API, without `stb_rect_pack.h`, using no padding within the bitmap and didn't experience any problem (I tried several fonts, each rasterized using several sizes). Yet, a `NULL` pointer gets dereferenced when including `stb_rect_pack.h`. The problem disappears when adding some padding.

```C
stbtt_PackBegin( &spc, bitmap, w, h, 0, 0 /* no padding */, NULL );
```

The crashes occurs in `stb_rect_pack.h` when dereferencing `node->next` to access the `x` member in the following assert (currently at line 281).

```C
   #if 0
   // skip in case we're past the node
   while (node->next->x <= x0)
      ++node;
   #else
   STBRP_ASSERT(node->next->x > x0); // we ended up handling this in the caller for efficiency
   #endif
```

The crash even occurs when you pack a single character. You can use this program to reproduce the bug. I used the embed font from issue #149 (https://fuwa.se/onql0q.c) for convenience only, it happened with every font I tried so far.

```C
#define STB_RECT_PACK_IMPLEMENTATION
#include "stb_rect_pack.h"
#define STB_TRUETYPE_IMPLEMENTATION
#include "stb_truetype.h"

extern unsigned char DroidSansMono_ttf[];

int main()
{
    unsigned char bitmap[ 128 * 128 ];
    const int first_char = 32;
    const int num_chars = 1;
    stbtt_packedchar cdata[1];
    stbtt_pack_context spc;
    
    stbtt_pack_range range;
    range.font_size = 16.f;
    range.first_unicode_codepoint_in_range = first_char;
    range.array_of_unicode_codepoints = NULL;
    range.num_chars = num_chars;
    range.chardata_for_range = cdata;
    
    if (stbtt_PackBegin( &spc, bitmap, 128, 128, 0, 0/*padding*/, NULL )) {
        stbtt_PackFontRanges( &spc, DroidSansMono_ttf, 0, &range, 1 );
        stbtt_PackEnd( &spc );
    }
    
    return 0;
}
```

**Comment by 0x1100** [comment]
I just looked a bit what happens and could narrow the problem.
I'll write something more detailled later, hopefully in a few hours.

**Comment by nothings** [comment]
At first it seems a little wrong to do this since x=y=0 may still have non-empty data. But I guess that's the point, with padding=1 and w=0,h=0 you get an empty 1x1 rect intentionally, so if padding=0, you're not asking for a valid empty texel, so you might as well do your thing.

**Comment by 0x1100** [comment]
We may put x=y=1 instead of x=y=1 just in case.
The default algorithm beeing BL skykine, the top right texel is unlikely to hold data.

**Comment by 0x1100** [comment]
Your commit (83d36fd28a2f25bbcbf887832d896203957f8b92) doesn't fix the crash. The point was to avoid calling `stbrp__skyline_pack_rectangle` when width is equal to zero. You have to move the call inside the `else` block.

**Comment by nothings** [comment]
Whoops, I meant to but forgot.

**Comment by nothings** [comment]
(I couldn't use your fix as written because it requires C++ / C99, so I had to rewrite it, and screwed it up.)

**Comment by 0x1100** [comment]
Yeah, that's what I though. I'll remember that next time.

**Comment by nothings** [comment]
My bad for not actually testing it though.

I pushed a new version.

I still didn't test it though.

**Comment by 0x1100** [comment]
It works for me now.
