### ISSUE TITLE
stb_image doesn't support 16bpc png.

### ISSUE THREAD

**Issue by vinjn** [nothings/stb#171]
Will that be implemented?

**Comment by nothings** [comment]
There are no plans to implement it.

**Comment by vinjn** [comment]
Thanks for the reply.
I would like to give it a try.
How difficult it is to implement based on current 1/2/4/8 support.
Could you give some instructions?

**Comment by rygorous** [comment]
There's no good way to do it since the public interface contract is that
pixels are 8 bits per channel.

**Comment by nothings** [comment]
It can be treated as an HDR format: if you use the 8-bit interface you only get 8 bits, but if you use the float interface you'll get full precision.

I'll have to look at the code and the spec in detail to have any idea of how hard it would be to add.

**Comment by socks-the-fox** [comment]
I've just finished a rudimentary implementation that'll read a 16-bit PNG and downsample it to 8-bit. I haven't yet looked at the float interface, and have only done preliminary testing so far, but it shouldn't be too much more work. Once I'm done fighting Visual Studio's insistence on it's own code format standard I could toss you a pull request, if you'd like.

**Comment by socks-the-fox** [comment]
After reviewing the code, I've come across a bit of a limitation. Due to the super-cheaty way I handle decoding and downsampling, and with the fact that handling the `tRNS` chunk is a separate step and not inline with the decoding, I can't think of a way to handle it in a spec-valid way for 16-bit PNGs. Beyond that, however, it looks to be working with the various test and real-world PNGs I throw at it.

**Comment by socks-the-fox** [comment]
Just figured I'd stop by and say I've gotten a more proper 16-bit PNG implementation put together in PR #212. Not 100% I've done everything properly documentation-wise (I added myself to the credits and bumped the PNG libraty's version number) but I am willing to fix anything that gets pointed out.

**Comment by nothings** [comment]
Yep, I saw it, I just was on Xmas break and then I was sick for a couple weeks. I'll get to it eventually.

**Comment by socks-the-fox** [comment]
I saw something on twitter about squashing commits for pulls which reminded me of this (which also gave me a moment to fix a doofy thing I did) so it's no rush :3

**Comment by nothings** [comment]
Superseded by pull request discussion: https://github.com/nothings/stb/pull/225
