### ISSUE TITLE
stb_image jpeg decode tearing

### ISSUE THREAD

**Issue by DickyQi** [nothings/stb#1717]
**Describe the bug**
stbi_load a jpeg file and rendering out using OpenGL / vulkan / save to PNG, image is tearing

**To Reproduce**
1. using stbi_load to open jpeg file ![tearing](https://github.com/user-attachments/assets/edbf677a-d200-4946-bb09-922b7bdb17ea)
2. rendering with OpenGL API
3. display image is tearing as 
<img width="294" alt="error" src="https://github.com/user-attachments/assets/599e0d59-3673-4a5c-82b8-413f9d4af20e">

already checked input image isn't has any stride on pixel lines

**Comment by nothings** [comment]
Read provided image as jpg, write it out as PNG/BMP:

![384290972-edbf677a-d200-4946-bb09-922b7bdb17ea](https://github.com/user-attachments/assets/918b5e7c-972a-41b4-b54d-9864535b4121)

Image is correct in memory after loading. Not an stb_image decode bug. Problem with your OpenGL code in some form.
