### ISSUE TITLE
stb_image_write.h unused variable.

### ISSUE THREAD

**Issue by jaroslov** [nothings/stb#180]
On line 798 of stb_image_write.h, the variable 'k' is unused. This causes a -Werror fails when using sufficient warnings.

       {
          // compute adler32 on input
          unsigned int k=0, s1=1, s2=0; // error: k is set, but unused.
          int blocklen = (int) (data_len % 5552);

The compiler would stop complaining with:

       {
          // compute adler32 on input
          unsigned int s1=1, s2=0;     // k is removed.
          int blocklen = (int) (data_len % 5552);

**Comment by rwhitworth** [comment]
Note: PR #182

**Comment by nothings** [comment]
Closing this one since we don't need both a pull request and issue for the same thing.
