### ISSUE TITLE
Problem with gif transparency

### ISSUE THREAD

**Issue by CelticMinstrel** [nothings/stb#183]
There seems to be a problem with transparency in GIF images which I discovered [via SFML](https://github.com/SFML/SFML/issues/978#issuecomment-143908652). A non-working GIF can be found [here](https://raw.githubusercontent.com/calref/cboe/ff7f3cca4720da7fd4ebceb3b2fd2bcd3b86079c/rsrc/cursors/boot.gif). Affected GIFs show up with a white or black background instead of transparency (or, I suppose it could be any colour, but in my experience it's generally either white or black). This happens on Windows with MSVC (no idea if it happens with eg MinGW), but it doesn't happen on the Mac.

**Comment by nothings** [comment]
Notes: It looks like SFML 2.2 uses stb_image 1.33 (2011), and SFML 2.3 uses stb_image 2.02 (2015).

**Comment by urraka** [comment]
This was fixed along with #157, already merged in the latest version. Did a quick test with the sample gif and seems to work fine.

**Comment by nothings** [comment]
Thanks @urraka, I'm closing this then.

@CelticMinstrel, reopen if we've misunderstood.
