### ISSUE TITLE
std_image PNG loader on iOS hardware reverses red and blue channels.

### ISSUE THREAD

**Issue by petedenial** [nothings/stb#184]
When a PNG file is included in an application for use with native code, Xcode changes the PNG file.  There is a codepath within stb_image.h for this (deiphone).  When loading PNGs on iOS simulator the image loaded by stb_image is correct, but when running on actual iOS hardware, the red and blue channels are reversed  This was tested on iPad2 and iPad2 Air.

**Comment by nothings** [comment]
Are you saying they are backwards with de-iphone enabled, or without de-iphone enabled?

**Comment by nothings** [comment]
Also, are you sure that this is an issue with stb_image and not an issue with your display code?

In other words, if you make an all-red image, and print out the RGB value after stb_image loads it, is it actually different on the simulator and the hardware? (It seems very unlikely.) stb_image should always load data as RGB, regardless of what your platform's display format is.

**Comment by petedenial** [comment]
Hi Sean,
First--you rock; I love the single header file implementation.  I had my own TGA loader, BMP loader, and was compiling/linking libpng and libjpeg before I discovered you.  I deleted my stuff, burned the extra libraries and immediately started using stb_image.h instead.  Thanks for the great code :)
And now onto the problem: I have an several PNGs (with transparency) and I add these to my Xcode project.  I open these files at run-time using native code and load them into OpenGL textures.  When I run on Windows, Linux, Android and the iOS emulator everything is correct.  When I run on iOS hardware (iPad2 or iPad2 Air) the resulting image has the red & blue channels swapped.  I did confirm that I entered the deiphone path on the hardware (but I don't recall if I did the same test on the simulator).  I will debug again when I'm back at the office; I submitted the bug mostly because I thought maybe this was something you were already aware of but had not yet released a fix for.  For completeness, I attached the images that I am using.  When I get to debug again, I will dig deeper and if I find something I will let you know.
Thanks,
Pete!

**Comment by nothings** [comment]
It is very unlikely that this is a code bug in stb_image, because it doesn't really have any endianness issues (which wouldn't actually swap R/B anyway) or any way to swap R/B other than when you explicitly ask for it with de-iphone. So it seems highly likely it's an issue with how you're loading the image into OpenGL.

I could be wrong, but I don't know how it could happen.

If you can't easily print the colors, another easy way to test this is immediately after calling stbi_load, iterate over the pixels and set them all to {r=255,g=0,b=0,a=255}. If everything shows as red in both iphone and simulator, then there's a problem with stb_image. If it shows as red in simulator and blue in iphone, it's an issue with your display code.

**Comment by nothings** [comment]
Keep in mind that the whole point of de-iphone is to undo the hacky R/B swap that apple does on images prepared for the iphone. I don't program iOS so I don't know *why* they do that R/B swap, but obviously there is some reason for it, and maybe you're going through the path that expects them to be swapped.

**Comment by r-lyeh** [comment]
@petedenial this is mostly an opengl issue. try to load same image on both devices, and dump raw rgba buffers to diskdisk and then diff both files. they should be both the same :)

**Comment by petedenial** [comment]
Hi Sean,
I did some more investigating.  I turned my image into a solid red square (attached).  On the emulator I see different bytes than on the hardware--specifically the red and blue bytes are swapped.
When I look at memory returned by stbi_load_from_memory on hardware its:

00 00 FF FF 00 00 FF FF 00 00 FF FF 00 00 FF FF 00 00 FF FF 00 00 FF FF 00 00 FF FF 00 00 FF FF 00 00 FF FF 00 00 FF FF 00 00 FF FF 00 00 FF FF 00 00 FF FF 00 00 FF FF 00 00 FF FF 00 00 FF FF 00 00 FF FF 00 00 FF FF 00 00 FF FF 00 00 FF FF 00 00 FF FF 00 00 FF FF 00 00 FF FF 00 00 FF FF ...

on ipad simulator its:

FF 00 00 FF FF 00 00 FF FF 00 00 FF FF 00 00 FF FF 00 00 FF FF 00 00 FF FF 00 00 FF FF 00 00 FF FF 00 00 FF FF 00 00 FF FF 00 00 FF FF 00 00 FF FF 00 00 FF FF 00 00 FF FF 00 00 FF FF 00 00 FF FF 00 00 FF FF 00 00 FF FF 00 00 FF FF 00 00 FF FF 00 00 FF FF 00 00 FF FF 00 00 FF FF 00 00 FF FF 00 00 FF FF 00 00 FF FF 00 00 FF FF 00 00 FF FF 00 00 FF FF 00 00 FF FF 00 00 FF FF 00 00 FF FF 00 00 FF FF 00 00 FF FF 00 00 FF FF 00 00 FF FF 00 00 FF  ...

The hardware is:a A1460: iPad 4th Gen (Wi-Fi/Verizon & Sprint/GPS)
Thanks again for creating this library.
Pete!

**Comment by nothings** [comment]
And it's the exact same code on both? You don't have any code doing 'if on simulator, do X, otherwise do Y'? I literally have no idea how this could happen.

**Comment by dghost** [comment]
Xcode only applies image "optimization" when building for devices. If you are applying the de-iphone code path in the simulator it's going to wind up swapping channels needlessly.

Relevant (if dated) links:
[iPhone Optimized PNGs](http://iphonedevelopment.blogspot.com/2008/10/iphone-optimized-pngs.html)
[Xcode's built-in (de)optimization](https://imageoptim.com/xcode.html)

**Comment by petedenial** [comment]
Arg, I am clown shoes.  I was not calling the stbi_convert_iphone_png_to_rgb(1) function!  Once I added that just before my call to stbi_load_from_memory everything works as expected.  Sorry for wasting your time guys.  I owe you Snickers bars.
