### ISSUE TITLE
stb_c_lexer.h overwrites buffer when parsing 0x

### ISSUE THREAD

**Issue by quartersdg** [nothings/stb#185]
line ~637
  lexer->int_number = strtol((char \*) p, (char \*\*) q, 16);
should be 
  lexer->int_number = strtol((char \*) p, (char \*\*) &q, 16);
Otherwise strtol overwrites the input buffer with the endpointer making bad things happen to the parser

**Comment by nothings** [comment]
Fixed in next version. (I fixed this ages ago and forgot to upload it.)
