### ISSUE TITLE
"stbrp_init_target" symobol is defined multiple times.

### ISSUE THREAD

**Issue by ongamex** [nothings/stb#189]
"stbrp_init_target" symbol is defined multiple times:

stb_truetype.h : 
static 
void stbrp_init_target(stbrp_context *con,       int pw,     int ph,      stbrp_node *nodes, int num_nodes)
stb_rectpack.h
STBRP_DEF 
void stbrp_init_target(stbrp_context *context, int width, int height, stbrp_node *nodes, int num_nodes)

I found this while compiling the "imgui" library ignoring the embedded stb headers, with the latest version of STB. 

For some reason the liking works fine, and at runtime the wrong "stbrp_init_target" gets called. I'm not quite sure why does this happen, the use case is pretty straight forward, I will continue to investigate.

But I think that one of the "stbrp_init_target" must be renamed.

**Comment by nothings** [comment]
If you use both stb_rect_pack and stb_truetype, the former must be included first. It's expected to get an error if you include them in the other order.

**Comment by ongamex** [comment]
I'm not having an compile time error, at runtime the wrong function gets called.
I will try to make a minimal example in the near future.
