### ISSUE TITLE
stb_vorbis uses malloc, realloc etc. when STB_VORBIS_NO_CRT is defined

### ISSUE THREAD

**Issue by michal-z** [nothings/stb#192]

**Comment by nothings** [comment]
"fixed" for next version (I haven't tested that it actually works, just that it compiles, since to use it you have to pass in all the memory, and I don't have a test bed for that)

**Comment by nothings** [comment]
I'm no longer sure that this is a legit issue. If you specify STB_VORBIS_NO_CRT, the burden is on you to provide replacements for all the stdlib functionality in stb_vorbis. There are already mechanisms to replace at least some of the allocation functions, I just need to check if there's actually some bare ones or what (which would be a separate bug).

**Comment by nothings** [comment]
Ok, yeah, I forgot that because this is a .C file not a .H file, it's much messier to replace things. Just putting in dummy definitions is probably reasonable.

**Comment by nothings** [comment]
Fixed for next version.
