### ISSUE TITLE
stb_truetype.h compile errors with non-trivial STBTT_assert override.

### ISSUE THREAD

**Issue by n-v** [nothings/stb#193]
Encountered in v1.08 under Mac OS X 10.9.5 with XCode 6.2.

The "unbraced" if/else chain in `stbtt__handle_clipped_edge()` fails to compile with our assert implementation, and likely others' as well.

Proposed patch:
```
1876c1876
<    if (x0 == x)
---
>    if (x0 == x) {
1878c1878,1879
<    else if (x0 == x+1)
---
>    }
>    else if (x0 == x+1) {
1880c1881,1882
<    else if (x0 <= x)
---
>    }
>    else if (x0 <= x) {
1882c1884,1885
<    else if (x0 >= x+1)
---
>    }
>    else if (x0 >= x+1) {
1884c1887,1888
<    else
---
>    }
>    else {
1885a1890
>    }
```

**Comment by nothings** [comment]
That sounds like a broken assert implementation where the assert doesn't properly behave like a statement.

**Comment by n-v** [comment]
After preprocessing and viewing the section in question, I see you are right! But that if/else chain remains arguably a bit dodgy style-wise. 

With our assert implementation, the code essentially looks like:
```c
if (!(condition)) {
   // complicated stuff
}; // <- that semi-colon breaks the if/else chain
```
Wrapping our assert code inside a `do { } while(false)` fixes the problem.

With that, I think that braces make the code more accommodating given the open invitation to inject foreign code into that block. I'm planning on fixing our assert code *and* keeping the braces  in that part of stb_truetype.h. Thanks for the quick response.

**Comment by rygorous** [comment]
The issue tracker is not the place for brace placement discussions (or other coding style discussions, for that matter - it's just a waste of everybody's time).

Since the bug seems to have been in your assert macro, I'm closing the issue.
