### ISSUE TITLE
Crash in stb_vorbis

### ISSUE THREAD

**Issue by sagamusix** [nothings/stb#199]
Here's a rather old OGG Vorbis file that first triggers an assertion failure, then actually crashes stb_vorbis: http://sagagames.de/stuff/stb_vorbis_crash.ogg
It might be one of those old unsupported files, but nevertheless the decoder should handle this situation gracefully and not simply crash.

**Comment by nothings** [comment]
Fixed in next version. (Doesn't crash, probably doesn't decode correctly though, I didn't even bother looking at the output.)

**Comment by sagamusix** [comment]
By the way, since there has not been an updated release yet, I just added some early return in the function that used to crash; that way, it doesn't crash and even decodes correctly. So if you fixed it the same way as I did, that old file should even decode properly.
