### ISSUE TITLE
stb.h: document regex / matching library

### ISSUE THREAD

**Issue by aras-p** [nothings/stb#202]
A simple matching / regex library sounds very useful for people who don't want full on C++11 or Boost or whatever. Looks like stb.h already has _something_, just a bit hard to tell what exactly. Documentation would be very welcome!

**Comment by nothings** [comment]
See also https://github.com/nothings/stb/issues/119#issuecomment-105247307

**Comment by rygorous** [comment]
stb.h is itself deprecated at this point, Ye Olde issue #119 is still around and we might get to it someday, but stb.h itself has numerous issues especially on 64-bit targets and doesn't really make sense to fix up in its current form, closing this.
