### ISSUE TITLE
stbi_info() fails for TGAs, but stbi_load() doesn't

### ISSUE THREAD

**Issue by DanielGibson** [nothings/stb#205]
Same for `stbi_info_from_callbacks()`, but **not** `stbi_info_from_memory()` which succeeds.
It fails with "unknown image type" - sounds like #159 (which should be fixed)?

`stbi_load()` succeeds.

**Comment by DanielGibson** [comment]
Oh, forgot to check the pull requests: #204 is supposed to fix this - and it seems like it actually does, at least for me :-)

**Comment by DanielGibson** [comment]
BTW, as a workaround one can disable HDR image support with `#define STBI_NO_HDR`
(If, like me, one cares more about TGA than HDR)

**Comment by nothings** [comment]
Fixed by PR #204 as noted.
