### ISSUE TITLE
stb.h: #ifndef WIN32 for STB_THREADS ?

### ISSUE THREAD

**Issue by rotoglup** [nothings/stb#214]
Shouldn't it be `_WIN32` ? Right now I have to define `WIN32` along with `STB_DEFINE_THREADS`, is it intended ?

https://github.com/nothings/stb/blob/master/stb.h#L11160

Thanks !

**Comment by rotoglup** [comment]
Or am I supposed to include `windows.h` before `stb.h` - it defines `WIN32` ?

In this case, the related `#error` could be improved to mention this :)

**Comment by nothings** [comment]
Yeah, it should be _WIN32 I think.

**Comment by nothings** [comment]
fixed in next release
