### ISSUE TITLE
stb_vorbis compile error

### ISSUE THREAD

**Issue by timbeaudet** [nothings/stb#215]
static __forceinline uint32 crc32_update(uint32 crc, uint8 byte)
gives an error: error:  multiple storage classes in declaration specifiers

Probably because static and extern (defined in __forceinline according to: [this](http://sourceforge.net/p/mingw-w64/mailman/message/28851647/) ) don't play well together.

**Comment by Murii** [comment]
I get the same error ! What can we do about it?

**Comment by nothings** [comment]
This is a bug in MinGW which inexplicably still hasn't gotten fixed.

https://github.com/nothings/stb/issues/116

As can be seen in that thread, somebody was supposed to submit a patch to work around it, but I don't know whatever happened to it or why the thread got closed without it being fixed. Please post in that thread any further replies.
