### ISSUE TITLE
Junk data in PNG?

### ISSUE THREAD

**Issue by rcdailey** [nothings/stb#218]
I'm seeing `0x81818100` repeated a few hundred times in my output PNG data. The image I'm using for testing [can be obtained here](https://cloud.githubusercontent.com/assets/1768054/12119968/48ccedf0-b394-11e5-96d9-b66b5d82f3d2.png). Here is my application code:

```
int w, h, comp;
auto buffer = stbi_load("test.png", &w, &h, &comp, STBI_rgb_alpha);
```

This line of code in `stb_image.h` is where this data makes its first appearance, based on my debugging:

```
z->expanded = (stbi_uc *) stbi_zlib_decode_malloc_guesssize_headerflag((char *) z->idata, ioff, raw_len, (int *) &raw_len, !is_iphone);
```

`z->expanded` here will contain this pattern of data, which gets copied over to `z->out` at some point via this switch statement later in function `stbi__create_png_image_raw`:

```
      // handle first byte explicitly
      for (k=0; k < filter_bytes; ++k) {
         switch (filter) {
            case STBI__F_none       : cur[k] = raw[k]; break;
            case STBI__F_sub        : cur[k] = raw[k]; break;
            case STBI__F_up         : cur[k] = STBI__BYTECAST(raw[k] + prior[k]); break;
            case STBI__F_avg        : cur[k] = STBI__BYTECAST(raw[k] + (prior[k]>>1)); break;
            case STBI__F_paeth      : cur[k] = STBI__BYTECAST(raw[k] + stbi__paeth(0,prior[k],0)); break;
            case STBI__F_avg_first  : cur[k] = raw[k]; break;
            case STBI__F_paeth_first: cur[k] = raw[k]; break;
         }
      }
```

`filter` in this case is `STBI__F_none`, for the first iteration. This just copies the `0x81818100` value out to the buffer returned. Eventually I do get to the 32-bit color data of the image, but this weird value is repeated in front of it first. What I'm expecting is nothing but pixel data back in the buffer.

Can you explain this behavior? Is this by design? What is the data in front of the pixel data?

**Comment by socks-the-fox** [comment]
I don't think it's a bug in the code. If you open the PNG in a program like Photoshop or GIMP and zoom in ~400% (you may need to put in a solid color background layer) you'll see it actually has a 1-pixel wide border of 0-alpha pixels. The `818181` part of the value is almost certainly from the program that created the PNG (which the metadata claims was MS Office). The color data on these pixels can be anything and it won't affect the result (due to the fact that there's 0 alpha).

**Comment by nothings** [comment]
It appears to be as @socks-the-fox says above, so I'm not going to spend my time checking this from the code unless there's comfirmation that it's not 778 copies of it (777 for the first scanline, then 1 more for the leftmost column).

**Comment by nothings** [comment]
I'm closing this since we haven't heard back from the reporter, who is welcome to reopen the bug if it's a real issue.

**Comment by rcdailey** [comment]
Sorry for taking so long to respond. What @socks-the-fox is saying makes sense, although it's weird that there is that line at the top of the image. I haven't had a chance to verify this again, but when I can get back to this I will reopen if it turns out to be something else.

Thanks a ton guys!!!

**Comment by nothings** [comment]
The line isn't just at the top, there's a 1-pixel outline around the whole image.
