### ISSUE TITLE
Scripting language interpreters for other_libs.md

### ISSUE THREAD

**Issue by dbohdan** [nothings/stb#231]
On several occasions I thought it would be nice to have an interactive scripting language interpreter packaged as a drop-in pair of .c/.h files. Here are several interpreters I have looked at (ordered by how practically usable they are IMO):

* [Wren](https://github.com/darius/wren) (edit: not to be confused with [Wren](https://github.com/munificent/wren))
* [Picol](https://tcl.wiki/17893)
* [LIL](http://runtimelegend.com/rep/lil/index)

There is also [Duktape](http://duktape.org/), a very capable JavaScript interpreter. However, much like SQLite its .c/.h distribution is an amalgamation of rather a lot of files totaling about 80 kLoC.

If this is something you'd be interested in including in other_libs.md I can create a pull request adding any or all of the above.

**Comment by nothings** [comment]
Wren doesn't seem to actually be a library, just a standalone program.

The other two are probably ok (but TCL?!?!? -- just let it die!), if you submit a PR for either or both I'll merge it.

**Comment by nothings** [comment]
Actually, it looks like Picol also isn't embeddable, it's just a standalone program? But LIL is definitely embeddable.

**Comment by dbohdan** [comment]
>it looks like Picol also isn't embeddable, it's just a standalone program

To embed Picol you need to strip off the main() function from picol.c and include both picol.h and picol.c in your application. Now that I think of it, Picol would definitely benefit from merging the header and the implementation into a single file with stb-style preprocessor conditionals. I'll submit it once I've done that.

Wren is much the same, though unlike Picol it introduces global variables. I am not up to working on it myself but I can ping the author about refactoring it.

>TCL?!?!? -- just let it die!

As someone who has used Tcl [rather](https://github.com/dbohdan/sqawk) [a](https://github.com/dbohdan/jimhttp) [lot](https://github.com/tclssg/tclssg) recently, I respectfully disagree. :-)

P.S.: I have also found, but haven't tried, [tiny-js](https://github.com/MarcoLizza/tiny-js). Tell me if I should include it in the PR.

**Comment by nothings** [comment]
tiny-js is too many files (at least if you want the std lib, which everyone would)

**Comment by dbohdan** [comment]
>which everyone would

Fair enough.

**Comment by dbohdan** [comment]
(PR #234)
