### ISSUE TITLE
PSD - all transparent pixel RGB values are pre-blended with white

### ISSUE THREAD

**Issue by armadillu** [nothings/stb#239]
It seems all PSD semi-transparent pixels come pre-blended with white. This is what I get when loading the same exact pixels from a PNG or a PSD:

![untitled](https://cloud.githubusercontent.com/assets/167057/12649576/2b4c2928-c5ad-11e5-9d15-cbeea7d0bdd3.png)

This is not an STB issue per se, as following through stb_image source reveals that this is just how the pixels come out of the PSD file... But I figured removing the white halos might be useful to some.

I managed to correct the issue with this post - pass. The code relies on OpenFramworks but it should be pretty self-explanatory.

https://github.com/armadillu/ofxPsdLoad/blob/master/src/ofxPsdLoad.cpp#L50-L68

**Comment by nothings** [comment]
Verified this is true. I suspect maybe stb_image *should* fix this, as it seems wrong to have the psd loaded be (a) different from the png, and (b) different from how it looks in photoshop.

**Comment by armadillu** [comment]
Yep it's unclear, but I would lean towards yes it should fix this. FreeImage does what stb_image currently does (white halos). Preview.app on OS X removes the white halo.

**Comment by nothings** [comment]
Fixed in next release.

**Comment by armadillu** [comment]
It seems the current version would crash on 3 channel (RGB) PSD images when accessing pixel[3] here:

https://github.com/nothings/stb/blob/master/stb_image.h#L5456

This fix should only be applied on RGBA pixels:
```if (channelCount ==4) {```

**Comment by nothings** [comment]
Yep, I typo'd that and I guess I don't have any non-4-channels in my test suite. Fixed now.
