### ISSUE TITLE
Mipmap library

### ISSUE THREAD

**Issue by thebeast33** [nothings/stb#241]
I want to start writing some single purpose header files in C, and I'm especially looking for problems that other libraries in the table haven't addressed yet. I just uploaded my first one, which creates mipmaps for 32-bit color images and floating point images (like depth textures). It is located here: https://github.com/thebeast33/cro_lib

Single file, no dependencies, compiles with cl and clang, tested on Windows 10 and OSX.

I was hoping to get included in the table. If it does not meet the qualifications, I would like some feedback so I can get it there. Thanks.

**Comment by nothings** [comment]
added
