### ISSUE TITLE
stb_image in a PNG *comp is always req_comp

### ISSUE THREAD

**Issue by Clocktown** [nothings/stb#244]
I just found out that when loading a png, *comp is always set to req_comp, contrary to how it's supposed to behave. This error seems limited to png, at least with jpegs it works as it's supposed to.
The error is in: stbi__do_png
`if (req_comp && req_comp != p->s->img_out_n){ // if channels in the img != req_comp
         result = stbi__convert_format(result, p->s->img_out_n, req_comp, p->s->img_x, p->s->img_y);
         p->s->img_out_n = req_comp; // this sets channel information to req_comp
         if (result == NULL) return result;
      }
      *x = p->s->img_x;
      *y = p->s->img_y;
      if (n) *n = p->s->img_out_n; // thus n(or comp) will always be req_comp`

I just signed up for this, I hope I'm using this system the right way, i have no idea why the code is losing it's format :S

**Comment by nothings** [comment]
Makes sense, I'll take a look at it.

**Comment by nothings** [comment]
fixed in next release
