### ISSUE TITLE
other_libs.md addition

### ISSUE THREAD

**Issue by r-lyeh** [nothings/stb#249]
https://github.com/mackron/dr_libs

**Comment by mackron** [comment]
Just keep in mind a lot of those libraries are still very work in progress. dr_wav and dr_flac are probably the only worthwhile ones at the moment.

**Comment by nothings** [comment]
You mentioned dr_flac in another issue so I added it, should I add dr_wav too?

**Comment by mackron** [comment]
Yeah dr_wav should be mostly stable. None of the others are worth adding right now, though.

**Comment by starwing** [comment]
@nothings HI, I'm making a new single-file library here: https://github.com/starwing/amoeba

this is a layout constraint algorithm, used by Apple. written in pure C, and use Lua license, with a Lua binding.

btw, a single-file library with a Lua binding is still a single-file library? (I have another several library has this format)
