### ISSUE TITLE
stretchy_buffer.h won't compile for C++

### ISSUE THREAD

**Issue by TimothyWrightSoftware** [nothings/stb#250]
Windows 10, VS 2015.

```
struct Object {
    int x;
};
Object* objects = nullptr;

// in function
Object obj;
obj.x = 42;
sb_push(objects, obj);
```

source.cpp(157): error C2440: '=': cannot convert from 'void _' to 'Object *'
source.cpp(157): note: Conversion from 'void_' to pointer to non-'void' requires an explicit cast

casting the objects pointer to a (void*) doesn't work either.  Not sure what I'm doing wrong.

**Comment by BSVino** [comment]
Stretchy buffers relies on C's lack of type safety to do its thing. It's one of those few C programs that won't compile in C++. I'm not sure it's feasible to use in a C-with-classes sort of setup, since using the C++ compiler enforces a bunch of type safety that breaks stretchy buffers.

**Comment by rygorous** [comment]
Yep. If you want a stretchy buffer equivalent in C++, you can keep the
interface, but you're probably gonna need a few templates to replace
stretchy_buffer.h's use of C implicit type conversions.

**Comment by TimothyWrightSoftware** [comment]
Just because the update notes in the docs said "1.02 -  compiles as C++, but untested" I thought I'd comment on it.

**Comment by cocoademon** [comment]
I know this is closed, but there's a fairly cheap workaround for this.
The only place where this lib relies on implicit type conversions (to & from void *) is in the stb__sbgrowf function, so you can do the following:

1. Rename `stb__sbgrowf` to `stb__raw_sbgrowf`
2. Add the following immediately afterwards - for c++ it just adds a template function which does the casting and wraps stb__raw_growf.

```c++
#ifdef __cplusplus
template<class T>
static T * stb__sbgrowf(T * arr, int increment, int itemsize) {
	return (T*)stb__raw_sbgrowf((void *)arr, increment, itemsize);
}
#else
#define stb__sbgrowf stb__raw_sbgrowf
#endif
```

This is minimally tested but seems to work ok. Usage code doesn't change as the template argument is automatically deduced. `sb_push`, `sb_count` etc all work fine and stay as macros.

**Comment by nothings** [comment]
Makes sense.

**Comment by DanielGibson** [comment]
yeah, it's a good solution.

while you're at it, stb__sbneedgrow() should be like `#define stb__sbneedgrow(a,n)  ((a)==0 || stb__sbn(a)+(n) > stb__sbm(a))` (i.e. `>`, not `>=`, else it grows even though there's still space for one more element)

**Comment by xelatihy** [comment]
For C++ users, there should be a note in the implementation that the C++ data type has to be a POD, maybe after the comment on malloc/free semantic. For example reminding them that constructions/destructors will not be called by the library.

In case you care, there is a way to test for this in C++11 at compile time with `std::is_pod`, but I would not do it myself for several reasons.

**Comment by DanielGibson** [comment]
`std::is_pod` is pretty useless IMHO.  
```c++
struct vec3 {
    float x,y,z;
    vec3(float x_, y_, z_) : x(x_), y(y_), z(z_) {}
    vec3() : x(0.0f), y(0.0f), z(0.0f) {};
}; 
```
is not POD according to std::is_pod, because it has constructors - even though they don't do any magic (like having side-effects outside the struct or even allocating memory).

Putting that in a stretchy buffer is totally safe.

So yeah, a short note should probably be added, but people should figure out themselves what's safe and what is not.  
Also I think, if you're writing actual C++ code you should use `std::vector` or something - making this work with C++ is mainly useful for C-code that you want to be able to compile as C++ as well (like in header-only libs).

**Comment by DanielGibson** [comment]
FWIW, std::pod is not great for this, but https://en.cppreference.com/w/cpp/types/is_trivially_copyable could work ok, could be put in a static_assert

**Comment by rygorous** [comment]
Tentatively closing this since `stb_ds.h` replaces the old stretchy buffer code and does work in C++.
