### ISSUE TITLE
stbtt_GetGlyphBitmapSubpixel leaks memory if scale_x is 0

### ISSUE THREAD

**Issue by hymerman** [nothings/stb#251]
Found with Coverity Scan: if `scale_x` is 0, `stbtt_GetGlyphBitmapSubpixel` leaks `vertices`. The fix is simple; call `STBTT_free(vertices, info->userdata);` before the `return NULL`.

https://github.com/nothings/stb/blob/master/stb_truetype.h#L2433

    STBTT_DEF unsigned char *stbtt_GetGlyphBitmapSubpixel(const stbtt_fontinfo *info, float scale_x, float scale_y, float shift_x, float shift_y, int glyph, int *width, int *height, int *xoff, int *yoff)
    {
       int ix0,iy0,ix1,iy1;
       stbtt__bitmap gbm;
       stbtt_vertex *vertices;   
       int num_verts = stbtt_GetGlyphShape(info, glyph, &vertices);
    
       if (scale_x == 0) scale_x = scale_y;
       if (scale_y == 0) {
          if (scale_x == 0) return NULL; // <-- HERE'S THE LEAK
          scale_y = scale_x;
       }
       ...

**Comment by nothings** [comment]
Yep. (Of course people are highly unlikely to render text with scale=0, so this bug might never get hit, but of course I will fix it.)

**Comment by hymerman** [comment]
Brilliant, thanks :) It's unlikely I know, you never know what people are going to do though... maybe someone will have text scale on a slider that goes down to 0? Stranger things happen!

**Comment by nothings** [comment]
fixed in next release
