### ISSUE TITLE
stbi__zbuild_huffman() overflow/dead code

### ISSUE THREAD

**Issue by technosaurus** [nothings/stb#254]
What is  `++sizes[sizelist[i]];` supposed to do?
```
static int stbi__zbuild_huffman(stbi__zhuffman *z, stbi_uc *sizelist, int num){
   int i,k=0;
   int code, next_code[16], sizes[17];
   memset(sizes, 0, sizeof(sizes));
   memset(z->fast, 0, sizeof(z->fast));
   for (i=0; i < num; ++i)
      ++sizes[sizelist[i]];
   sizes[0] = 0;
   for (i=1; i < 16; ++i)
      if (sizes[i] > (1 << i))
         return stbi__err("bad sizes", "Corrupt PNG");
//...
```

**Comment by rygorous** [comment]
It's a quick sanity check to make sure the code lengths can possibly form a
correct prefix code. If there's more than 2^n code words with length n
bits, the code lengths array is obviously nonsensical.

A more precise check would be to verify that the code lengths obey Kraft's
inequality.

**Comment by technosaurus** [comment]
I see it now, I was seeing `(++sizes)[sizelist[i]];` instead of `(sizes[sizelist[i]])+=1;`
