### ISSUE TITLE
[stb_truetype] sero size glyphs with some fonts

### ISSUE THREAD

**Issue by theGiallo** [nothings/stb#256]
I'm using the pack API, and I get some glyphs with x0=x1 and y0==y1 in the relative stbtt_packedchar loading the [Hack v 2.20-DEV02172016](https://github.com/chrissimpkins/Hack/tree/development/build/test_builds/DEV02172016).
The current release, [Hack v 2.019-ttf](https://github.com/chrissimpkins/Hack/releases/download/v2.019/Hack-v2_019-ttf.zip), loads all the ASCII glyphs like that.

*off* are 0 and xadvance is nan.

With another font, like [Dosis](http://www.impallari.com/dosis), it works.
Can someone reproduce this or it's my fault?

**Comment by theGiallo** [comment]
I tested on some of these, and all of them gave the *0=*1, 0/nan result. https://sourceforge.net/projects/dejavu/files/dejavu/2.35/dejavu-fonts-ttf-2.35.tar.bz2/download

**Comment by theGiallo** [comment]
I have opened DejaVuSansMono.ttf in FontForge and `File/Create Font...`, all default and `yes, go on`. 

The new font works perfectly with stbtt. They are the same exact size, but they are different.

![Screenshot of FontForge](https://dl.dropboxusercontent.com/u/27823819/stbtt/FontForge_DejaVuSansMono_create_font_2016-03-11_02%3A43%3A19.png)
[Original font](https://dl.dropboxusercontent.com/u/27823819/stbtt/DejaVuSansMono.ttf)
[Re-Saved font](https://dl.dropboxusercontent.com/u/27823819/stbtt/DejaVuSansMono_resaved.ttf)

**Comment by nothings** [comment]
I tried both DejaVuSansMono and HackRegular from your links, and looked at the output of packedchar and at GetCodepointHMetrics, and they all looked reasonable. I looked at around 10 characters of DVSM (including 'a' and 'A'), but only a couple from Hack. Can you give a very definite case: "font X, call these functions, look at this character, it's wrong"?

I know you have a workaround for it, but unless you think you're doing something wrong I'd still like to figure out what's going on here.

**Comment by theGiallo** [comment]
Oh crap. I've read this only now! I'm sorry! Too much stuff in my github notifications...
I've created a branch for the bug, with a commit that recap a little the stbtt calling.
https://bitbucket.org/theGiallo/hot_code_reloading_test/commits/32b9f94e6ff92eac150395e20e0cae8406fd331a

**Comment by nothings** [comment]
I left this for too long and can no longer reproduce it, so I'm closing it. Feel free to open it with a repro.
