### ISSUE TITLE
stb_vorbis uses alloca which is not available in standard C

### ISSUE THREAD

**Issue by manxorist** [nothings/stb#262]
stb_vorbis uses `alloca()` by default, but `alloca()` is neither in the C standard nor provided by gcc when compiling in standard-compliant mode with `-std=c99`:
```
manx@methusalix:~/tmp/stb$ cat test.c 
#include "stb_vorbis.c"
int main() {
 return 0;
}
manx@methusalix:~/tmp/stb$ gcc test.c -lm
manx@methusalix:~/tmp/stb$ gcc -std=c99 test.c -lm
In file included from test.c:1:0:
stb_vorbis.c: In function ‘decode_residue’:
stb_vorbis.c:2128:4: warning: implicit declaration of function ‘alloca’ [-Wimplicit-function-declaration]
    uint8 ***part_classdata = (uint8 ***) temp_block_array(f,f->channels, part_read * sizeof(**part_classdata));
    ^
In file included from test.c:1:0:
stb_vorbis.c:876:92: warning: pointer/integer type mismatch in conditional expression
 #define temp_alloc(f,size)              (f->alloc.alloc_buffer ? setup_temp_malloc(f,size) : alloca(size))
                                                                                            ^
stb_vorbis.c:885:58: note: in expansion of macro ‘temp_alloc’
 #define temp_block_array(f,count,size)  make_block_array(temp_alloc(f,array_size_required(count,size)), count, size)
                                                          ^
stb_vorbis.c:2128:42: note: in expansion of macro ‘temp_block_array’
    uint8 ***part_classdata = (uint8 ***) temp_block_array(f,f->channels, part_read * sizeof(**part_classdata));
                                          ^
stb_vorbis.c: In function ‘inverse_mdct’:
stb_vorbis.c:876:92: warning: pointer/integer type mismatch in conditional expression
 #define temp_alloc(f,size)              (f->alloc.alloc_buffer ? setup_temp_malloc(f,size) : alloca(size))
                                                                                            ^
stb_vorbis.c:2681:28: note: in expansion of macro ‘temp_alloc’
    float *buf2 = (float *) temp_alloc(f, n2 * sizeof(*buf2));
                            ^
/tmp/ccehySOR.o: In function `decode_residue':
test.c:(.text+0x30c7): undefined reference to `alloca'
/tmp/ccehySOR.o: In function `inverse_mdct':
test.c:(.text+0x4ac4): undefined reference to `alloca'
collect2: error: ld returned 1 exit status
manx@methusalix:~/tmp/stb$ gcc -dumpversion
4.9.2
```
Note that the availability of `alloca()` is required even if it does not get used when the user provides a custom `alloc_buffer`.

Possible solutions:
 1. Not use `alloca()` at all and just use arrays of pre-determined size (i.e. the maximum possible size) on the stack. In case `alloc_buffer` allocation should still be supported, this requires either a new macro to switch between the 2 or at least some modifications to the interface of the `temp_alloc()` macro.
 2. Not use `alloca()` at all and allocate all temporary structures of sufficient size when allocating `struct stb_vorbis` (for performance reasons), which would require some refactoring.
 3. Optionally (either enabled by default or disabled by default via some macro) implement `temp_alloc()` and `temp_free()` in terms of `malloc()` and `free()`. This of course has the performance cost of heap allocations in the fast path.
 4. Documentation of `alloca()` (on Linux) suggests `#include <alloca.h>` which will always provide `alloca()` even in standard compliant mode. I'm not sure whether all other platforms also provide `<alloca.h>`, thus I'm not sure if this is a viable solution.
 5. Document `-std=c99` as unsupported. Probably not viable as stb libraries are meant to be easy to integrate (at least to my understanding).
 6. Not use `alloca()` at all and replace the use with C99 variable length arrays (VLAs). Almost certainly not viable because it will break on older pre-C99 compilers as well as newer C11 compilers (as VLAs have been degraded to an optional feature in C11).

**Comment by BSVino** [comment]
Microsoft compilers don't support VLAs and probably never will.

**Comment by dghost** [comment]
Also worth pointing out that this isn't so much an issue with GCC as it is with glibc. glibc doesn't include alloca.h since __USE_MISC doesn't get defined in strict modes, whereas Apple's libc includes it by default unless you turn on strict POSIX compliance. As a result it works correctly with GCC + OS X, but not GCC + glibc.

Changing lines 548-561 from:

```
#ifndef STB_VORBIS_NO_CRT
#include <stdlib.h>
#include <string.h>
#include <assert.h>
#include <math.h>
#if !(defined(__APPLE__) || defined(MACOSX) || defined(macintosh) || defined(Macintosh))
#include <malloc.h>
#endif
#else // STB_VORBIS_NO_CRT
#define NULL 0
#define malloc(s)   0
#define free(s)     ((void) 0)
#define realloc(s)  0
#endif // STB_VORBIS_NO_CRT
```

to:

```
#ifndef STB_VORBIS_NO_CRT
#include <stdlib.h>
#include <string.h>
#include <assert.h>
#include <math.h>
#if !(defined(__APPLE__) || defined(MACOSX) || defined(macintosh) || defined(Macintosh))
#include <malloc.h>
#include <alloca.h>
#endif
#else // STB_VORBIS_NO_CRT
#define NULL 0
#define malloc(s)   0
#define alloca(s)   0
#define free(s)     ((void) 0)
#define realloc(s)  0
#endif // STB_VORBIS_NO_CRT
```

Should fix the issue. I'm not actually at a Linux machine right now so I can't actually test that, though.

**Comment by nothings** [comment]
One *proper* fix for this is to convert stb_vorbis.c to a header-file library, because then you can pass in overrides to e.g. disable alloca() entirely w/o having to change the source code.

But I don't expect to do that anytime soon. It would be good to know if the fix dghost offered in the previous comment fixes @manxorist's issue.

**Comment by manxorist** [comment]
Adding `#include <alloca.h>` like @dghost suggested and I hab described in solution suggestion (4.) works.
What @dghost suggested breaks other platforms/compilers (i.e. VS2010 or MinGW64 GCC cross-compiling from Linux to Windows) though, where no `<alloca.h>` is available.
Guarding `#include <alloca.h>` with `#ifdef __GNUC__` therefore also wont work.

Guarding `#include <alloca.h>` with `#if defined(__linux__) || defined(__linux)` works in all situations I tested:
```
#ifndef STB_VORBIS_NO_CRT
#include <stdlib.h>
#include <string.h>
#include <assert.h>
#include <math.h>
#if !(defined(__APPLE__) || defined(MACOSX) || defined(macintosh) || defined(Macintosh))
#include <malloc.h>
#if defined(__linux__) || defined(__linux)
#include <alloca.h>
#endif
#endif
#else // STB_VORBIS_NO_CRT
#define NULL 0
#define malloc(s)   0
#define alloca(s)   0
#define free(s)     ((void) 0)
#define realloc(s)  0
#endif // STB_VORBIS_NO_CRT
```

**Comment by nothings** [comment]
Thanks, I will do that, and we will see if anyone out there complains.

**Comment by manxorist** [comment]
Just tested emscripten, which also needs `#include <alloca.h>`, thus:
`#if defined(__linux__) || defined(__linux) || defined(__EMSCRIPTEN__)`

**Comment by nothings** [comment]
closing for the release, reopen if there's an issue.
