### ISSUE TITLE
stb_image enable SSE2 for x64 targets

### ISSUE THREAD

**Issue by zalbard** [nothings/stb#264]
SSE2 is currently only enabled for x86 targets.

It can be enabled for x64 targets by replacing [line 675](https://github.com/nothings/stb/blob/master/stb_image.h#L675) with the following:
`#if !defined(STBI_NO_SIMD) && (defined(STBI__X86_TARGET) || defined(STBI__X64_TARGET))`

**Comment by nothings** [comment]
in next version
