### ISSUE TITLE
stb_vorbis: Memory leak in start_decoder()

### ISSUE THREAD

**Issue by manxorist** [nothings/stb#265]
stb_vorbis leaks allocation `mults = (uint16 *) setup_temp_malloc(f, sizeof(mults[0]) * c->lookup_values);` at [stb_vorbis.c:3847](https://github.com/nothings/stb/blob/master/stb_vorbis.c#L3847) when taking `if (c->sorted_entries == 0) goto skip;` branch at [stb_vorbis.c:3861](https://github.com/nothings/stb/blob/master/stb_vorbis.c#L3861) in `start_decoder()`.

**Comment by nothings** [comment]
Fixed by #266
