### ISSUE TITLE
stb_image: 3 channel BMP image load error with 4 channels

### ISSUE THREAD

**Issue by mulplus** [nothings/stb#267]
when use stb_image to load a 3 channel BMP images, it give the comp/channels to be 4.
I debug into it, and find that in the function "stbi__bmp_load", the structure variable
"stbi__bmp_data info" does not make initialization. 
The problem is fixed if put the following line 
              memset(&info, 0, 1*sizeof(stbi__bmp_data));
before the line "info.all_a = 255;".

**Comment by nothings** [comment]
fixed in next version
