### ISSUE TITLE
Suggestions for other_libs.md

### ISSUE THREAD

**Issue by jibsen** [nothings/stb#270]
A few suggestions for your list of other small libraries:

  - [greatest](https://github.com/silentbicycle/greatest) - C testing library in 1 file (ISC, 1 file)
  - [µnit](https://github.com/nemequ/munit) - small unit testing framework for C (MIT, 2 files)
  - [parg](https://github.com/jibsen/parg) - parser for argv that works similarly to getopt (CC0, 2 files)

**Comment by nothings** [comment]
added all
