### ISSUE TITLE
Commit b03133000a7f7d49aa3ce57bb5fa1975dd41db21 which was supposed to fix issue #259 breaks with most valid Vorbis files

### ISSUE THREAD

**Issue by manxorist** [nothings/stb#274]
Commit b03133000a7f7d49aa3ce57bb5fa1975dd41db21 which was supposed to fix issue #259 breaks with most valid Vorbis files.

(I'm new to stb_vorbis code, so I may well be lacking context or understanding of the code)

See issue #259 for context.

`is_whole_packet_present()` is called in `start_decoder()` when `IS_PUSH_MODE(f)` with `end_page==TRUE` here. The call in question is right after starting (`start_packet()`) all 3 Vorbis header packets. The check in question enforces the following part of the Vorbis specification (https://www.xiph.org/vorbis/doc/Vorbis_I_spec.html) Section A.2. Encapsulation:
> The first audio packet of the logical stream begins a fresh Ogg page.

In other words: the last of the header packets terminates a page.

`resopad.ogg` violates this requirement:
```
manx@idefix ~/tmp $ ogginfo resopad.ogg 
Processing file "resopad.ogg"...

New logical stream (#1, serial: 00007364): type vorbis
WARNING: Vorbis stream 1 does not have headers correctly framed. Terminal header page contains additional packets or has non-zero granulepos
Vorbis headers parsed for stream 1, information follows...
Version: 0
Vendor: Xiph.Org libVorbis I 20020717 (1.0)
Channels: 2
Rate: 44100

Nominal bitrate: 499.821000 kb/s
Upper bitrate not set
Lower bitrate not set
Vorbis stream 1:
	Total data length: 21608347 bytes
	Playback length: 6m:30.188s
	Average bitrate: 443.034444 kb/s
Logical stream 1 ended
```

This fix commited in https://github.com/nothings/stb/commit/b03133000a7f7d49aa3ce57bb5fa1975dd41db21 breaks *MOST* valid Vorbis files as it forces stb_vorbis to expect further segments after the last header packet (if the header packet terminates within the page it starts in). If the last header packet ends on another page, a second check in the for loop below (in `for (; s == -1;) {`) at `if (s < n-1) return error(f, VORBIS_invalid_stream);` does the checking, which had not been changed in the commit in question.

Commit b03133000a7f7d49aa3ce57bb5fa1975dd41db21 (well, the part relevant to the bug in question) should be reverted.

Normally, there should not be any need for a demuxer/decoder to enforce this particular specification requirement unless it wants to rigorously enforce the standard. I'm not able to judge whether other parts of stb_vorbis rely on this requirement (seeking logic may be a canditate here). If not, I think both checks could be removed alltogether, allowing slightly invalid files to be parsed successfully, without breaking anything.

**Comment by nothings** [comment]
Whoops, I must have forgotten to actually test this with another file. Thanks for the analysis, I will revert.
