### ISSUE TITLE
stb_image can't decode this png file

### ISSUE THREAD

**Issue by angelystor** [nothings/stb#276]
I encountered an error decoding the attached png file with stb_image. Using commit: 4c51910

It errors out in stbi__create_png_image_raw, 
   if (s->img_x == x && s->img_y == y) {
      if (raw_len != img_len) return stbi__err("not enough pixels","Corrupt PNG"); <---

On further investigation, it looks like in stbi__parse_png_file, during the IEND case, the initial raw_len calculated is the same as img_len, but stbi_zlib_decode_malloc_guesssize_headerflag modified raw_len to a different value, hence it was failing the check in stbi__create_png_image_raw

However all other photo editing tools can load this png and tweakpng verifies that this png is valid.

![logo_1-o](https://cloud.githubusercontent.com/assets/524826/14307973/821b43fe-fc05-11e5-8779-f1bbc144a1b6.png)

**Comment by rygorous** [comment]
Fixed in stb_image 2.16.
