### ISSUE TITLE
Request: add JPEG saving to stb_image

### ISSUE THREAD

**Issue by a-teammate** [nothings/stb#279]
I'd love to see jpeg compression in stb_image (so we can save screenshots in jpg).
Would be pretty cool.

Maybe https://code.google.com/archive/p/jpeg-compressor/ could be of help, but i see its C++ rather than plain good old C.

**Comment by jpcy** [comment]
There's also [jo_jpeg](http://www.jonolick.com/code.html).

**Comment by serge-rgb** [comment]
A bit of a shameless plug, but tiny_jpeg.h is stb-style, well tested and has some happy users.
https://github.com/serge-rgb/TinyJPEG/blob/master/tiny_jpeg.h

**Comment by nothings** [comment]
Multiple solutions at https://github.com/nothings/single_file_libs#images, and I think it's definitely out of scope for stb_image_write.
