### ISSUE TITLE
stb_truetype: Weird kerning

### ISSUE THREAD

**Issue by AlexAltea** [nothings/stb#281]
I'm getting weird kernings on _stb_truetype_ in any recent version up to the latest, v1.11. And I'm unsure if this is an issue with my code, the fonts I'm using or _stb_truetype_. This has happened to me so far with _Segoe UI Light_ (5.53) and _Source Sans Pro Light_ (2.020).

The problem is, `stbtt_GetCodepointKernAdvance` is returning almost always 0 (sometimes uppercase followed by lowercase is non-zero). This is how my text renderer works:

``` cpp
// The text in my application never changes so the whole string is rendered to txBuffer
// after precomputing its dimensions: txWidth and txHeight.
txBuffer.clear();
txBuffer.resize(txWidth * txHeight);
for (size_t i = 0; i < text.length(); i++) {
    int dx, dy = (ascent - descent) + lineGap;
    int kern = stbtt_GetCodepointKernAdvance(fontInfo, text[i], text[i+1]);
    stbtt_GetCodepointHMetrics(fontInfo, text[i], &dx, 0);
    int x1, y1, x2, y2;
    stbtt_GetCodepointBitmapBox(fontInfo, text[i], scale, scale, &x1, &y1, &x2, &y2);
    size_t offset = x + ((y + ascent + y1) * txWidth);
    stbtt_MakeCodepointBitmap(fontInfo, &txBuffer[offset], x2 - x1, y2 - y1, txWidth, scale, scale, text[i]);
    x += (dx + kern) * scale;
 }
```

This is the output with _Segoe UI Light_:
![](https://i.gyazo.com/569e10b13a1d224f4a43b4f70a69bdbd.png)
Expected result:
![](https://www.microsoft.com/typography/fonts/images/Segoe-UI-Light.png)

Sorry about the diffent font size, the second image comes from Microsoft. Looking for support on the internet about this, I've also seen [other people noticing this kerning issue](https://www.reddit.com/r/gamedev/comments/2e8q5o/2d_game_c_gui_framework_with_manually/cjyg0v6).

**Comment by nothings** [comment]
- It is normal that it almost always returns 0; most character pairs are unkerned.
- The issue with Segoe UI Light sure looks like a bug. (What's it look like if you don't kern?)
- The "other people noticing the kerning issue" looks more like people not using subpixel positioning; small font sizes w/o subpixel, kerning is irrelevant. So not related to your problem.

I didn't write the kerning code and I've never used it. I don't know when I'll get a chance to look at it.

**Comment by nothings** [comment]
(Also, btw, note that your code won't actually work correctly if a pair of characters *does* get kerned together tightly, as the later character will erase the earlier character if their bounding boxes overlap (which often happens with kerning). The sample code at the top of stb_truetype explains how this is a bug.)

**Comment by AlexAltea** [comment]
I see, thanks a lot for your answer!

> It is normal that it almost always returns 0

Oh, my bad. Feel free to rename the issue to whatever you think it suits best. I'll remain subscribed until someone figures out what's wrong with this font. :-)

> What's it look like if you don't kern?

It looks quite similar:
![](https://i.gyazo.com/6a8ac3d15499d9f67823307fd9d335d1.png)
Comparing without (black) and with (grey) kerning:
![](https://i.gyazo.com/12cd4f8f169252a19974d4e269837133.png)
(Sorry about crappy Photoshop skills). As you see only "W-a" and "r-s" got non-zero kerning.

**Comment by nothings** [comment]
That looks pretty wrong without kerning too.

Ok, I guess the big question is whether the reference image you say 'came from microsoft' was actually directly rendered, or whether someone hand-kerned it. If the former, then clearly there's info in the font to fix it; if the latter, it may not be a bug at all.

**Comment by nothings** [comment]
You might try taking the second value from GetHMetrics ("left side bearing" or "lsb") and using that as an extra horizontal offset for each character (not applied as an advance, just to offset the x position). I don't know if this is necessary, I don't do it anywhere so I thought it wasn't, but maybe it is.

**Comment by AlexAltea** [comment]
Perfect! Adding the (scaled) left side bearing to the offset solves the issue:
![](https://i.gyazo.com/0f2284270463f5a7d8617a5e86ec2ded.png)
Thanks for your help. I leave the corrected code below, in case someone else blindly copies some sample code and comes accross the same problem. :-)

```cpp
// The text in my application never changes so the whole string is rendered to txBuffer
// after precomputing its dimensions: txWidth and txHeight.
txBuffer.clear();
txBuffer.resize(txWidth * txHeight);
for (size_t i = 0; i < text.length(); i++) {
    int lsb, dx, dy = (ascent - descent) + lineGap;
    int kern = stbtt_GetCodepointKernAdvance(fontInfo, text[i], text[i+1]);
    stbtt_GetCodepointHMetrics(fontInfo, text[i], &dx, &lsb);
    int x1, y1, x2, y2;
    stbtt_GetCodepointBitmapBox(fontInfo, text[i], scale, scale, &x1, &y1, &x2, &y2);
    size_t offset = x + (lsb * scale) + ((y + ascent + y1) * txWidth);
    stbtt_MakeCodepointBitmap(fontInfo, &txBuffer[offset], x2 - x1, y2 - y1, txWidth, scale, scale, text[i]);
    x += (dx + kern) * scale;
 }
```

**Comment by nothings** [comment]
I'm leaving this open since I need to fix the samples.

**Comment by nothings** [comment]
Actually I suspect this isn't a bug and the issue isn't that you should use lsb, but rather that you're not using x1 (which may or may not have the same functionality, but is the approved way to do it).
