### ISSUE TITLE
stb_vorbis compile problem due defines.

### ISSUE THREAD

**Issue by kundelstein** [nothings/stb#282]
Including stb_vorbis into a project (as a single file) gets conflicts with some already existing libraries.

Concrete example:

`#include <stb_vorbis.c>`     // Yes, this is in "include directories path", not directly in "project files", this is the reason I didn't separate it into h and cpp.

Line like:
`#define C  (PLAYBACK_LEFT  | PLAYBACK_RIGHT | PLAYBACK_MONO)`
makes problems because it leaves **C** defined which is used somewhere in **glm**.

The obvious workaround is dividing the file into header and source file. Other choice would be using special unique naming or removing macros by #undef.

Just had a look at this lib today so there is a lot I don't know about it, If I overlooked something I apologize.

**Comment by nothings** [comment]
It's not meant to be #included. Don't #include it, just compile & link it.

See #25
