### ISSUE TITLE
there is a bug in stretchy_buffer.h?

### ISSUE THREAD

**Issue by fycyes** [nothings/stb#283]
if (p) {
      if (!arr)
         p[1] = 0;
      p[0] = m;
      return p+2;
   }
why do not like this :
if (p) {
      p[1] = min_needed;
      p[0] = m;
      return p+2;
   }

**Comment by nothings** [comment]
p[1] is the length of the array, p[0] is the length of the buffer. the function in question resizes the buffer without changing the array. thus p[1] remains the same as it was before. min_needed is a temporary value used while deciding how big the buffer should but is neither the length of the array nor the length of the buffer.

**Comment by fycyes** [comment]
oh, thanks a lot.
