### ISSUE TITLE
1/2/4-bit monochrome PNGs loading incorrectly

### ISSUE THREAD

**Issue by nothings** [nothings/stb#284]
I'm not sure what the status of the old ones that supposedly loaded correctly are, but my current test ones (generated using pngout /c0 /d1) are failing. However, RGB ones (pngout /c2 /d1) worked correctly. (I believe the original code was @ocornut and me.)

Probably need to make some much smaller (8x8?) bitmaps with a known format so can see what is going wrong.

Below is a broken file (sorry for spamming the thread visually, but it's only 8KB).

![map_03](https://cloud.githubusercontent.com/assets/7525026/14582777/34c73426-03c3-11e6-8d23-1a4a86c576be.png)

**Comment by nothings** [comment]
The original PR and discussion was #45

**Comment by PazerOP** [comment]
Here's an example of a 1-bit 8x8 PNG where the background color ends up as a weird brownish tinge instead of transparent: https://puu.sh/vUKk0/57c81b459e.png

Decodes to:
![](https://puu.sh/vUKmr/d68a63feb8.png)

**Comment by rygorous** [comment]
@PazerOP That image decodes correctly. That background color is what color #0 is set to in the palette (check that contents of the PLTE chunk in the file starting at offset 0x29) and then the tRNS chunk says that the corresponding alpha value is 0. stb_image decodes the transparent pixels to r=0x6a, g=0x62, b=0x4f, a=0x00, which is exactly what the PNG palette says they should decode to (as per the spec).

**Comment by rygorous** [comment]
@nothings Your image decodes correctly (as in, looks the same way it does in the browser) for me with stb_image 2.15. Can you check whether you can still reproduce the problem on your end and close the issue if not?

**Comment by nothings** [comment]
Works for me!
