### ISSUE TITLE
Please pick a license

### ISSUE THREAD

**Issue by sol50** [nothings/stb#287]
I am not allowed to use your library (U.S copyright law makes using PD impossibly nasty) and I'm told the dual-license clause is invalid when combined with PD (because it is not a license)

Please consider a permissive license instead. You rationale for "more people will use it" is simply not true, it's quite the opposite.

**Comment by sol50** [comment]
>  I'm told

This is our legal dept btw

**Comment by nothings** [comment]
I cannot make every company and every legal department happy. The old license was not a dual license, it was just PD, but somebody else's legal department convinced me to make it a dual license.

**Comment by nothings** [comment]
See #240. Also, if you want someone to take your issue seriously, try using a more descriptive issue subject line, instead of giving orders.

**Comment by jarikomppa** [comment]
I'm half tempted to just fork the whole depo under zlib/libpng license, but
that would take effort.

**Comment by sol50** [comment]
@jarikomppa Please do, I know a few people who will help :)

**Comment by sol50** [comment]
@nothings Giving orders? "Please consider a permissive license instead" is the opposite of giving orders.

**Comment by sol50** [comment]
>  but somebody else's legal department convinced me to make it a dual license.

Unfortunately, that makes no sense.

**Comment by nothings** [comment]
>Giving orders?

"pick a license"

>Unfortunately, that makes no sense

It makes perfect sense. Not all lawyers agree with each other, thus they disagree, thus I am told contradictory things to do.

**Comment by sol50** [comment]
> Not all lawyers agree with each other, thus they disagree, thus I am told contradictory things to do.

Pick a proper license, and the problem goes away. PD is idiotic.

**Comment by jarikomppa** [comment]
> Pick a proper license, and the problem goes away. PD is idiotic.

Now you're just being rude. That isn't helping.

**Comment by sol50** [comment]
Couldn't care less.

**Comment by nothings** [comment]
Please go tell sqlite to pick a license; when you've succeeded at that, I'll change stb.

**Comment by nothings** [comment]
Locked. Do not create new issues/PRs about this; I will delete them immediately since they're a waste of everyone's time.
