### ISSUE TITLE
stb_perlin - interest in fractal brownian noise and/or SIMD enhancement?

### ISSUE THREAD

**Issue by jackmott** [nothings/stb#292]
There are some common fractal brownian noise functions that I could add, such as ridge/turbulence/fbm. They are all rather small, simple implementations.

I could also create SIMD versions of perlin noise, which is a bigger project and adds a great deal of complexity for around a ~2-3x speedup on depending on which SIMD instruction sets are available (your implementation of perlin is different than mine, so could be better, or worse).

Let me know if there is interest and I'll do a PR

**Comment by nothings** [comment]
Sure, as long as you're willing to put the code in the public domain I'll be happy to include it.

**Comment by jackmott** [comment]
Great. I've got the fractal noise in a PR. Let me know if you have any issues with the style or anything and I'll address it.  SIMD will be a bigger project but I'll start looking into it.

**Comment by nothings** [comment]
corresponding PR was merged ages ago
