### ISSUE TITLE
stb_truetype seems to incorrectly calculate quad positions for lowercase letters

### ISSUE THREAD

**Issue by darthdeus** [nothings/stb#295]
I've tried using the simple stb_truetype example to get some text rendering and I stubmled upon the following issue. When I generate a texture from a font file using `stbtt_BakeFontBitmap` it looks correct (though the lowercase letters are top-aligned, but I guess that's not necessarily the cause of the problem).

![](http://i.imgur.com/qU1pjmS.png)

The problem is when I render the quads for each character as the example shows 			using `stbtt_GetBakedQuad(cdata, 512, 512, *text - 32, &x, &y, &q, 1);`, the lower case letters are "top aligned"

![image](https://cloud.githubusercontent.com/assets/123374/15022613/cb7127e8-122c-11e6-906b-41f94988745f.png)

This is what the quads without the texture look like, which makes me think it's either my projection matrix that is wrong, or `stbtt_GetBakedQuad` is wrong?

![](http://i.imgur.com/Oze6gcP.png)

This was done using the stock arial.ttf from Windows 10, but the same problem happens when I use ProggyClean.ttf.

**Comment by gingerBill** [comment]
What is your orthographic projection? stbtt_GetBakedQuad works with (0,0) at the top left corner and +ve y is downwards.

These quads look correct but the texture coordinates are upside down and the the quads are rendering upside down too!

**Comment by darthdeus** [comment]
The projection I'm using is `glm::ortho(0.0f, WIDTH, 0.0f, HEIGHT, -1.f, 1.f);`, which should put the origin in the bottom left corner. I also tried flipping it to be `glm::ortho(0.0f, WIDTH, HEIGHT, 0.0f, -1.f, 1.f)` to put the origin in the top left corner, but that flips the whole text.

![image](https://cloud.githubusercontent.com/assets/123374/15049711/1c9b54ae-12f0-11e6-870b-9ae5a55392c9.png)

As for the texture coordinates, are you sure those are upside down (my original example), and not just the quads? Or do you mean that if the quads were flipped, the texture coords would need to be flipped as well so the text doesn't end up upside down?

**Comment by nothings** [comment]
He means the latter. In your original projection, you need to negate the Y values and flip the texture coords. in the final example, you need to flip the texture coords.

**Comment by darthdeus** [comment]
Thanks!
