### ISSUE TITLE
stb_image_write.h: Implement flipping (e.g. stbiw_set_flip_vertically_on_write)

### ISSUE THREAD

**Issue by haikarainen** [nothings/stb#302]
Just a feature request I have, title should be pretty self-explanatory.

**If it isn't:** Implement a function (e.g `stbiw_set_flip_vertically_on_write`) to automatically and vertically flip the pixel-rows when writing a file. i.e. a `stb_image_write.h`-version of `stb_image.h`'s `stbi_set_flip_vertically_on_load()`.

I might look into creating a pull request myself, as it shouldn't be too difficult to implement.

**Comment by haikarainen** [comment]
Added a pull request, copying my note from there so it is clear here as well:

Please review this code. I have **NOT** written tests or properly tested all changes as I'm not accustomed to your unit testing methods. I have, however, manually tested it in my project and there it works just fine. The code that is doing the magic is copy-pasted from stb_image.h.

Please be gentle, it has been a while since I worked on a C-project, and I'm still getting used to creating pull requests.

**Comment by haikarainen** [comment]
No idea how you usually do pull requests and contributions, but will this ever get pulled? Could I do anything to make things easier?

Sorry to nag, I just would like to get a headsup so I know how I should plan my future code.

Regards,

**Comment by nothings** [comment]
Yeah, it will get pulled eventually; processing pull requests tends to eat a lot of a weekend, so I only do it every so often (there's only four weekends a month, so even just processing once a month kinda sucks).

**Comment by haikarainen** [comment]
@nothings Thanks for the quick response, I appreciate it!

:+1:

**Comment by nothings** [comment]
fixed in next version. sorry for the non-quick outcome!

**Comment by haikarainen** [comment]
@nothings Hey, you have nothing to feel sorry for! I very much appreciate your hard work and dedication to this project, and I'm sure a ton of other people do too! 💯 🥇 

I'm sorry myself for not pulling my thumb out and creating a proper, mergable fix for this myself!
