### ISSUE TITLE
stb_image_write monochrome bmp support

### ISSUE THREAD

**Issue by Pagghiu** [nothings/stb#305]
when writing monochrome BMP from a 1 byte \* w \* h buffer, result is an unreadable file.
Digging deeper, the expand_mono flag in stbiw__write_pixel is ignored for comp==1.

From a quick test the following modification generates a correctly encoded bmp.

``` c
   switch (comp) {
      case 1:
         if (expand_mono)
            stbiw__write3(s, d[0], d[0], d[0]); // monochrome bmp
         else
            s->func(s->context,d,1);
         break;
```

**Comment by haikarainen** [comment]
You should write tests for it and create a pull request!

**Comment by nothings** [comment]
Not necessary, I will make the change the next time I update stb libs.

**Comment by Pagghiu** [comment]
I have not been sending a pull request because this was pretty simple 1 line and I wasn't sure about all the coding/test rules for it to be accepted ;)

**Comment by nothings** [comment]
appears to have been added at an unknown time in the past
