### ISSUE TITLE
stb_vorbis defines

### ISSUE THREAD

**Issue by RandyGaul** [nothings/stb#322]
stb_vorbis.c has some defines around line 4992, especially L, C and R. These defines should probably be undef'd within stb_vorbis.c since these symbols are commonly used by user code, and are used within Windows.h. I've had to do a little workaraound:

`#include "stb_vorbis.c"`
`#undef L`
`#undef C`
`#undef R`

**Comment by nothings** [comment]
stb_vorbis.c is meant to be separately compiled. it should never interact with "user code".

**Comment by RandyGaul** [comment]
Oh I see. I thought it was intended to be used like the other stb_***.h libraries (and thought the .c was just an old artifact). Thanks for the comment :)
