### ISSUE TITLE
stb_textedit.h: override is_word_boundary

### ISSUE THREAD

**Issue by chrisws** [nothings/stb#326]
My application (SmallBASIC) needs a slightly different version of is_word_boundary().  Could you please make this over-ridable, like STB_TEXTEDIT_memmove etc. Thanks for stb_textedit, it's awesome!

**Comment by ocornut** [comment]
Possibly answering your request: I have submitted a (unmerged) PR https://github.com/nothings/stb/pull/273 which essentially lets you override the next/previous word functions.

**Comment by nothings** [comment]
merged this PR ages ago
