### ISSUE TITLE
stb_image: Incorrect number of components for PNG with tRNS chunk

### ISSUE THREAD

**Issue by kstuedem** [nothings/stb#329]
Since 201af99d9fd26bae939ad7f2395920476f78d7f1 the number of components is reported incorrectly for files with a tRNS chunk. Because the value of img_n only accounts for proper alpha channels but not for transparency from a tRNS chunk.

**Comment by Tormund** [comment]
Same problem with img.png(attachment).
stbi__do_png return's 3 number of components, but actually png has 4 components.
Revert https://github.com/nothings/stb/commit/201af99d9fd26bae939ad7f2395920476f78d7f1 fix this problem 
[img.zip](https://github.com/nothings/stb/files/424925/img.zip)

**Comment by Flix01** [comment]
I'm not sure if this png has a  tRNS chunk inside or not (maybe https://github.com/nothings/stb/issues/276 was more appropriate for it). Anyway, this image was a RGBA image resaved using [lodePng](https://github.com/lvandeve/lodepng). stb_image detects it as a RGB image (3 channels), but it's a valid 4 channels png.
![rgba_but_stb_image_thinks_its_rgb](https://cloud.githubusercontent.com/assets/9608982/26833910/0f2efc90-4ad4-11e7-926d-f28b3c9bb17c.png)

P.S. This post is probably redundant... I just wanted to add another test image.
