### ISSUE TITLE
starwing's libs

### ISSUE THREAD

**Issue by nothings** [nothings/stb#333]
Original post:

I have made several single-header libraries:

- znet: one header cross-platform proactive network library (only znet.h needed, others are standalone utils), with Lua binding.
https://github.com/starwing/znet
- amoeba: one header Cassowary constraint solver, with Lua binding.
https://github.com/starwing/amoeba
- loki: one header multi-thread message framework (not yet complete, however loki.h itself is a one-header library and usable now)
https://github.com/starwing/loki
- nui: generic node-based hierarchical structure, virtual DOM framework.
https://github.com/starwing/nui

All my libraries are Lua License, same as MIT license.

**Comment by starwing** [comment]
Thanks for single issues :)

**Comment by nothings** [comment]
I'm leaving loki.h off for now because w/o docs it doesn't seem very usable (can't even tell what it does). Added the others.
