### ISSUE TITLE
stb_image can't load these png files (but they view OK in any other app)

### ISSUE THREAD

**Issue by theodore-h-smith** [nothings/stb#335]
I saved some png files on OSX. Via the screen capture, but also via resaving the file in Apple's Preview.app. And now the files don't load properly in stb_image.

![stb_fail1](https://cloud.githubusercontent.com/assets/5270662/17080580/26dc46fa-512d-11e6-94b3-220ffc10498e.png)
![stb_fail2](https://cloud.githubusercontent.com/assets/5270662/17080583/2ad05364-512d-11e6-88b7-33540bb37d10.png)
![stb_fail3](https://cloud.githubusercontent.com/assets/5270662/17080584/2ad314c8-512d-11e6-94ee-d3bce53cc454.jpg)

**Comment by theodore-h-smith** [comment]
These 3 images look the same, but they are different sizes or formats. They all look fine to me in the browser, but stb_image can't load them properly.

**Comment by nothings** [comment]
What do you mean by doesn't load them properly? Does it fail to load them with an error message? Does it load them and they look incorrect?

I tried to load the first one and it looks the same to me in the browser as in stb_image.

**Comment by theodore-h-smith** [comment]
> On 24 Jul 2016, at 00:00, Sean Barrett <notifications@github.com> wrote:
> 
> What do you mean by doesn't load them properly? Does it fail to load them with an error message? Does it load them and they look incorrect?
> 
> I tried to load the first one and it looks the same to me in the browser as in stb_image.

Hi Sean sorry for my unclear message. Your library is very nice... anyhow... the top image is what I see with stb_image.

The second image is what I see with lodepng.

The last image is just what it would look like with all the crazy-post processing I'm doing... erm just ignore that one sorry.

**Comment by nothings** [comment]
This is what my browser shows:

![what](https://cloud.githubusercontent.com/assets/7525026/17080948/89375860-50f8-11e6-832f-fb20d59ccc6b.png)

**Comment by theodore-h-smith** [comment]
I see the same too... that's the correct image.

But if you look at the first two images I sent in the last email, on the bottom right is a cube. The cube has the wrong texture on the first image I sent you.

It's grey instead of colored, and distorted like sloped at an angle (parallelogram?).

**Comment by nothings** [comment]
Can you highlight the area in question? It's not obvious at all.

**Comment by theodore-h-smith** [comment]
Sorry... the last two images I sent you for comparison, that's within my game prototype.

I'm drawing the texture onto a cube. I don't have full-screen drawing of textures in my game-engine, all textures are loaded onto in-game objects. So I drew the "bad texture with stb_image" onto a cube.

**Comment by nothings** [comment]
There is nothing different in the bottom right corner of the top two images.

**Comment by nothings** [comment]
Let's start over. Here's how you report a bug in an image loader:

"This image loader doesn't load this image correctly." Attach the image that doesn't load correctly. Without it I'll never be able to reproduce or debug the error.

"It fails in the following way: (a) it doesn't load with the following error message; (b) it crashes; (c) some of the pixels are wrong; (d) all of the pixels are wrong."

If you want to attach a screenshot of it going wrong, you can, but I have stb_image myself, I can run it myself, I don't need you to prove that it goes wrong by attaching a screenshot of your game.

**Comment by theodore-h-smith** [comment]
The first image is grey and the colors are slanted. That's the problem.







I checked my code, I can make stbi_load work! I don't know if I'm calling it wrong though...

// this produces bad images, sometimes.
	unsigned char* Result = stbi_load(path, &w, &h, &n, 0);
	// produces n = 3, but loading this image results in that grey and slanted image.


// this version works
	unsigned char* Result = stbi_load(path, &w, &h, &n, 4);
    	n = 4; // manually set to 4, So the rest of my code knows it is 4.
	// the image loads OK now.


From what I read in your header docs... the first version of the code SHOULD work?

	"The number of components N is 'req_comp' if req_comp is non-zero, or *comp otherwise."

Well... it is zero, so the number should be in *comp, so n should be 4, but it's set to 3?

**Comment by nothings** [comment]
The image you're loading is an RGB image with no alpha channel, so it only has 3 channels, so if you don't tell stb_image to force it to have 4 channels, it will load it with only 3 channels. If your code then tries to treat it as having 4 channels, it will draw incorrectly.

**Comment by nothings** [comment]
And for future reference, the first two images you posted are literally identical (I checked in an image compare utility). You must be talking about images other than the ones you posted here (maybe you posted the same image twice accidentally).

It also contains literally nothing that looks like a cube (although there are squares of many different sizes).

**Comment by rygorous** [comment]
To expand a bit, this has to be the most frequently misunderstood thing
about stb_image (and the header file should probably be more explicit about
it).

The value returned in *comp describes the original image file, not the
returned pixel data. If you set req_comp to a nonzero value, the data you
get back *will* have that number of components.

In this case, *comp==3 means that all pixels have the same (synthetic)
alpha value. This can be useful to know when say trying to pick a texture
compression format, because it means e.g. DXT1 (which doesn't have a true
alpha channel) is a viable choice. But it doesn't mean the returned pixel
data has 3 bytes per pixel, not if you specified a nonzero value for
req_comp.

**Comment by theodore-h-smith** [comment]
Ryan. I sent images by email. github seems to strip image attachments instead of adding them to the thread. I've manually added the images now.

**Comment by nothings** [comment]
You want glPixelStorei(GL_UNPACK_ALIGNMENT, 1);

But this is not the place to explain why.

**Comment by theodore-h-smith** [comment]
It's OK I already understand why. As soon as I saw that line of code it's meaning is obvious.

**Comment by seyitcemyilmaz** [comment]
> You want glPixelStorei(GL_UNPACK_ALIGNMENT, 1);
> 
> But this is not the place to explain why.

It solved my problem thank you very much. This can be tried.

**Comment by YXHXianYu** [comment]
> You want glPixelStorei(GL_UNPACK_ALIGNMENT, 1);
> 
> But this is not the place to explain why.

Same problem, thanks a lot!
