### ISSUE TITLE
another entry for other_libs.md

### ISSUE THREAD

**Issue by hidefromkgb** [nothings/stb#342]
https://github.com/hidefromkgb/gif_load

**Comment by hidefromkgb** [comment]
…there is, apparently, a valid reason why no one answers, of which I`m unaware. What have I done wrong?

**Comment by zao** [comment]
Sean seems to do most of his work on the library in larger batches when free time magically appears.
I'm speculating wildly but the lack of description about what the library actually is might be a contributing factor as to why it may be deferred.

**Comment by hidefromkgb** [comment]
Understood.
Basically, the only thing this code does is loading animated GIFs. It`s not constrained to any predefined storage format or file reading method, or even memory manager. These are the things that the user has to define for himself.
Storage format is defined by providing a frame handling callback into which every decoded frame is passed, one frame == one call. The user is also fully responsible for reading GIFs from disk if needed, as `gif_load` can only work with GIF data stored in RAM.

**Comment by nothings** [comment]
I've added it to the list.

* I couldn't find any indication of what license the project is under.
* I'm guessing it works from C++, the code doesn't indicate, but I didn't test that.

**Comment by hidefromkgb** [comment]
Added a public domain statement (taken from [unlicense.org](http://unlicense.org/)), disabled name mangling for C++.

**Comment by nothings** [comment]
Updated.
