### ISSUE TITLE
[FEATURE] Add abort option to the progress callback for stb_image_resize

### ISSUE THREAD

**Issue by chetan-prime** [nothings/stb#348]
stb_image_resize already has a callback to report progress. I've uploaded a patch of my attempt.
The premise is simple. If the progress callback ever returns non-zero then we abort the resize and return a NULL output pointer to the program. This will help with multi-threaded programs where we're resizing a large image in the background that isn't needed anymore. Perhaps its possible to even add a context like the pointer to the source pixels so one function can handle multiple resize threads at a time? 

I had changed STBIR_PROGRESS_REPORT to from void to int return type. Also added another field abort_indicated to struct stbir_info. Also the function is now evaluvated and we set abort_indicated accordingly. My code crashes as I'm not familiar with the internals of the stbir functions.

[stb_image_resize.abortcallback_patch.txt](https://github.com/nothings/stb/files/422309/stb_image_resize.abortcallback_patch.txt)
Issue has been edited due an accidental "enter" pressed in subject field.

**Comment by nothings** [comment]
What is the purpose of the 'abort_indicated' field?

**Comment by chetan-prime** [comment]
Hi @nothings ,thanks for the great headers btw.
I wasn't really sure what the stbir internal functions return and the pattern of function execution. So I thought it simpler to add a field that indicates the state.
However if the same result can be achieved with function return codes there is no need for the field.
My code is crashing when I try to abort through the callback so please feel free to change it as you like to get the desired result. Also the code expects an int function now so it no longer works with the default callback, perhaps you can use ifdefs's to not call anything when a callback isn't defined.

**Comment by BSVino** [comment]
Perhaps you could break your image into smaller tiles, calling stbir on each tile and checking for abort between tile processing. Should be able to do so with only one output buffer using the advanced api.

**Comment by chetan-prime** [comment]
Thats an idea @BSVino , but isn't it much simpler to use the existing progress callback to ask for an abort? No need to write code thats much more complex and might cause resize quality degradation as we're splitting the image into tiles.

**Comment by nothings** [comment]
In the long run, influencing control flow from callbacks is a worse experience than driving it yourself. It makes the code harder to understand, e.g. when debugging. So doing it without callbacks is probably preferable. (Doing an "information-only" callback is different.)

stbir is designed so that you can do create  tiles with no quality loss. you pass in the *whole* image for reading, but ask it to only write a tile, and you get the exact same results you would have.

**Comment by chetan-prime** [comment]
I'll go the route suggested by using the advanced API. Am going through the examples for one that shows how to do an image in tiles , will read the headers comments if I am unable to find an example for that.
Thanks , am closing this issue
