### ISSUE TITLE
Add Apache2 license?

### ISSUE THREAD

**Issue by PaulRashidi** [nothings/stb#350]
Hello maintainers,
  Would you be open to tri-licensing the code by adding the Apache 2 license as an option? For various reasons (I'm not qualified to speak to) licensing under custom licenses causes difficulties in re-use for others.

Thanks,

Paul

**Comment by nothings** [comment]
Not at this time.

**Comment by PaulRashidi** [comment]
Thanks for addressing so quickly, although the decision is unfortunate.
