### ISSUE TITLE
stb_truetype: Ubuntu.ttf bitmap errors

### ISSUE THREAD

**Issue by Ch40zz** [nothings/stb#353]
Hey guys!
Using the standard "Ubuntu-R.ttf" font or "Arial.ttf" (hard to see but existent) from windows together with the new rasterizer version 2 results in artifacts:
![TTF Bug](http://i.imgur.com/9rpZeEp.png)
The 'C' on top left is drawn with the library, notice the horizonal line, click to enlarge.
Happens with 'D', 'B', 'O', ... too, looks like its a bug in the anti aliasing code

I tried fixing the error but could not find the direct issue, it works with the old rasterizer, but sadly the old one is pretty slow and does not look as good as the new one.

Just in case, here is my code:

```
int ascent;
stbtt_fontinfo font;
stbtt_InitFont(&font, font_buff, 0);

float scale = stbtt_ScaleForPixelHeight(&font, 150);
stbtt_GetFontVMetrics(&font, &ascent, 0, 0);

int baseline = ascent * scale;

wchar_t ch = 'C';

int advance, lsb, x0, y0, x1, y1;
stbtt_GetCodepointHMetrics(&font, ch, &advance, &lsb);
stbtt_GetCodepointBitmapBoxSubpixel(&font, ch, scale, scale, 0, 0, &x0, &y0, &x1, &y1);

int glyph_x = x1 - x0;
int glyph_y = y1 - y0;

uint8_t *scr_buffer = calloc(glyph_x*glyph_y);
uint8_t *four_buffer = calloc(glyph_x*glyph_y*width);

stbtt_MakeCodepointBitmapSubpixel(&font, scr_buffer, glyph_x, glyph_y, glyph_x, scale, scale, 0, 0, ch);

int i;
for(i = 0; i < glyph_x*glyph_y; i++)
    *(uint32_t*)(four_buffer + i*width) = (scr_buffer[i] << 24) | (color & 0x00FFFFFF);
```

Thanks alot for your great library :)

**Comment by nothings** [comment]
Sorry, I shouldn't have let this sit so long. I'll try to take a look at it soon.

**Comment by HueHue44** [comment]
@Ch40zz Has this been resolved? If you use custom "ceil" and "floor" functions make sure they  work exactly like the C functions. I got the same graphical errors as you because I had not accounted for the functions when it came to negative numbers. So make sure that floor(-6.4) becomes -7 and not -6 like with positive numbers.

**Comment by Ch40zz** [comment]
Im an idiot.
Thanks alot you just fixed a bug in my OS :+1: 
Sory for being dumb and wasting your time nothings =(
