### ISSUE TITLE
pixel access

### ISSUE THREAD

**Issue by bobombolo** [nothings/stb#358]
is it possible to use stbi to access individual pixel values? stbi_get_pixel(x,y)

**Comment by bobombolo** [comment]
preferably without loading the entire image into memory

**Comment by nothings** [comment]
No.

**Comment by technosaurus** [comment]
Since PNG uses zlib compression, the best you could do is say that the buffer size is x*y*4 + fudge factor so that you get the partially decompressed image data to that point, ... though I may be confusing this with the stb_vorbis API.

**Comment by nothings** [comment]
stb_image doesn't have any option for anything like that.

(stb_vorbis allows seeking to an arbitrary sample properly without decoding everything up to that point, even.)
