### ISSUE TITLE
Missing ; before enum and Missing type specifier.

### ISSUE THREAD

**Issue by SleepyAkubi** [nothings/stb#36]
Error   1   error C2143: syntax error: missing ';' before 'enum [tag]'  D:\Programming\WarpCore\WarpCore\include\stb_image.h    205 1   WarpCore
Error   2   error C4430: missing type specifier - int assumed. Note: C++ does not support default-int   D:\Programming\WarpCore\WarpCore\include\stb_image.h    205 1   WarpCore

http://puu.sh/ba7hQ/2be31bcc02.png

Am I doing something wrong or is this an issue?

**Comment by salvonos** [comment]
how you solved this? I have the same issue. Where should I put #define?
