### ISSUE TITLE
stb_image: probably bug in PSD loader

### ISSUE THREAD

**Issue by iskolbin** [nothings/stb#383]
When compiling stb_image with Clang i've got next warning:
```
./../stb/stb_image.h:5722:45: warning: implicit conversion from 'int' to 'stbi_uc' (aka 'unsigned char') changes
      value from 65535 to 255 [-Wconstant-conversion]
               stbi_uc val = channel == 3 ? 65535 : 0;
                       ~~~                  ^~~~~
1 warning generated.
```

https://github.com/nothings/stb/blob/master/stb_image.h#L5722

I guess the correct type of `val` should be `stbi__uint16`.

**Comment by nothings** [comment]
Yep, this is part of the new untested 16-bit-per-channel PSD code, thanks.

**Comment by nothings** [comment]
dupe, fixed in next version
