### ISSUE TITLE
Split subprojects into subdirectories and then submodules

### ISSUE THREAD

**Issue by technosaurus** [nothings/stb#384]
Many individual stb header files are being used in other projects; however, since individual projects are part of a repository that contains other projects they don't use, most developers just copy the current file(s) into their repository.  This is bad for both projects: the downstream project ends up missing updates/fixes and it's more difficult for them to submit fixes upstream (can't just do a pull request)

As a fix, I propose moving them to submodules.  I tried something similar about a year or so ago with [stb_image](https://github.com/technosaurus/stb_image) but lost track of it.

From my recollection though, I think I moved the individual files into subdirectories saving history (As described in this stackoverflow question)
[Is it possible to move/rename files in git and maintain their history?](http://stackoverflow.com/questions/2314652/) ... modified as necessary for subprojects with multiple files - are there any?  Perhaps old stb_xxx.c files that were moved to the header?  If so this [stackoverflow question](http://stackoverflow.com/questions/18667308/), may be more helpful.

```bash
   git filter-branch --tree-filter 'if [ -f old ]; then mkdir dir && mv old dir/new; fi' HEAD
```

Then convert the folders into submodules according to [this stackoverflow question](http://stackoverflow.com/questions/359424/) or [the github tutorial](https://help.github.com/articles/splitting-a-subfolder-out-into-a-new-repository/)

**Comment by nothings** [comment]
I didn't put the stb libraries on github so people could have clean automatic git access, just to enable issues & PRs on github. So I don't really care about that use case that much.

IMO if people want to do clean git pulling, they can just put the entire stb tree into a subfolder (which they can set up as a submodule if they want), and then pull that whole tree down to update. Enabling them to do so selectively doesn't seem like that much value. It would also limit the effectiveness of the github front page.

**Comment by nothings** [comment]
There's also a separate proposal for having separate repositories for each library, further discussion of this should go there. https://github.com/nothings/stb/issues/359
