### ISSUE TITLE
GCC warnings stb_vorbis.h

### ISSUE THREAD

**Issue by akw0088** [nothings/stb#396]
First off thanks for the awesome header files, specifically stb_vorbis and stb_image, I *hate* dependencies, but here are some warnings I get from gcc:

In file included from src/audio.cpp:7:0:
./include/stb_vorbis.h: In function ‘void decode_residue(vorb*, float**, int, int, int, uint8*)’:
./include/stb_vorbis.h:2258:31: warning: statement has no effect [-Wunused-value]
    temp_free(f,part_classdata);
                               ^
./include/stb_vorbis.h: In function ‘void inverse_mdct(float*, int, vorb*, int)’:
./include/stb_vorbis.h:2907:21: warning: statement has no effect [-Wunused-value]
    temp_free(f,buf2);
                     ^
./include/stb_vorbis.h: In function ‘int _ZL13start_decoderP10stb_vorbis.part.20(vorb*)’:
./include/stb_vorbis.h:3920:36: warning: ‘hi’ may be used uninitialized in this function [-Wmaybe-uninitialized]
             g->neighbors[j][1] = hi;
                                    ^
./include/stb_vorbis.h:3919:37: warning: ‘low’ may be used uninitialized in this function [-Wmaybe-uninitialized]
             g->neighbors[j][0] = low;
                                     ^
./include/stb_vorbis.h: In function ‘int stb_vorbis_seek_frame(stb_vorbis*, unsigned int)’:
./include/stb_vorbis.h:4641:35: warning: ‘offset’ may be used uninitialized in this function [-Wmaybe-uninitialized]
                offset += error * 2;
                                   ^
./include/stb_vorbis.h:4589:11: note: ‘offset’ was declared here
    double offset, bytes_per_sample;
           ^
./include/stb_vorbis.h:4638:84: warning: ‘bytes_per_sample’ may be used uninitialized in this function [-Wmaybe-uninitialized]
                double error = ((double) sample_number - mid.last_decoded_sample) * bytes_per_sample;
                                                                                    ^
./include/stb_vorbis.h:4589:19: note: ‘bytes_per_sample’ was declared here
    double offset, bytes_per_sample;
                   ^
./include/stb_vorbis.h: In function ‘int stb_vorbis_get_frame_short(stb_vorbis*, int, short int**, int)’:
./include/stb_vorbis.h:5129:75: warning: ‘output’ may be used uninitialized in this function [-Wmaybe-uninitialized]
       convert_samples_short(num_c, buffer, 0, f->channels, output, 0, len);

There is also one regarding 65535 going to an unsigned char 'val' in stb_image, but it is otherwise clean (around line 5798 or so) I just changed the temp val to an unsigned short

**Comment by mockthebear** [comment]
Add these lines at the begin of the file:
`#ifdef __MINGW32__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmaybe-uninitialized"
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wunused-value"
#endif`

And in the end of the file
`#ifdef __MINGW32__
#pragma GCC diagnostic pop
#pragma GCC diagnostic pop
#endif`

That sould stop these annoying error messages in gcc (mingw)

**Comment by nothings** [comment]
This doesn't invalidate your bug report, but do be cautious: there is no stb_vorbis.h in the official release, just stb_vorbis.c

**Comment by rygorous** [comment]
I'm not getting the maybe-uninitialized warnings in the current code and with a more recent GCC, but the unused-value warnings are now fixed in the dev branch; will be in the next release.
