### ISSUE TITLE
stb_sdict_for unusable outside STB_DEFINE translation unit

### ISSUE THREAD

**Issue by kalineh** [nothings/stb#397]
stb_sdict_for() uses (d)->limit but outside the STB_DEFINE translation unit there is only a forward declaration of stb__st_stb_dict, it is defined lower in stb_define_hash_base()

not sure if there is really a good solution

**Comment by nothings** [comment]
I need to add accessor functions I guess.

**Comment by nothings** [comment]
fixed in next release
