### ISSUE TITLE
Likely erroneous pointer arithmetic in stb_c_lexer

### ISSUE THREAD

**Issue by H2CO3** [nothings/stb#400]
[Exhibit A](https://github.com/nothings/stb/blob/master/stb_c_lexer.h#L462):

    if (lexer->eof && lexer+n > lexer->eof)

should probably be

    if (lexer->eof && lexer->parse_point + n > lexer->eof)

instead.

Better yet, because performing pointer arithmetic that results in a pointer pointing more than one past the end of the array results in undefined behavior, I would actually rewrite the condition as

    if (lexer->eof && lexer->eof - lexer->parse_point < n)

**Comment by rygorous** [comment]
Fixed by commit 0bd0a9abc44957d79cbc6cfdf49565b7e95a463d.

**Comment by H2CO3** [comment]
Yay! 👍
