### ISSUE TITLE
stbi_is_hdr_from_file() modifies the file position

### ISSUE THREAD

**Issue by Shimmen** [nothings/stb#403]
While refactoring some image loading code I went from using the stbi functions that take a filename to the ones using a file. What I thought was a structure-only change turned out to introduce a new bug.

If the the HDR check is performed before the load, using the same file, the load will be unable to successfully load the image. Here is a small example showcasing the issue:

```c
#include <assert.h>
#include <stdio.h>

#define STB_IMAGE_IMPLEMENTATION
#include "stb_image.h"

int main() {
    FILE *file = fopen("test.jpg", "rb");
    assert(file);

    int is_hdr = stbi_is_hdr_from_file(file);
    //fseek(file, 0, SEEK_SET);

    int width, height, numComponents;
    void *pixels;

    if (is_hdr) {
        pixels = stbi_loadf_from_file(file, &width, &height, &numComponents, 0);
    } else {
        pixels = stbi_load_from_file(file, &width, &height, &numComponents, 0);
    }

    if (!pixels) {
        printf("Error loading image: %s.\n", stbi_failure_reason());
    }

    fclose(file);
    return 0;
}
```

The program will print "Error loading image: unknown image type.". Fixing the issue for me is as simple as uncommenting the `fseek` call, but I wonder if the current behaviour of the function is really the best or most intuitive. I was at least very surprised about it when I realised what was going on.

If you think it would make sense to make it so that `stbi_is_hdr_from_file` rewinds the file to the beginning (alternatively back to where it was before it performed the check) I can create a pull request.

**Comment by nothings** [comment]
Yeah, I agree this doesn't seem right. I guess I should look at all the 'is_hdr' functions and think about it first.

**Comment by nothings** [comment]
This was already handled correctly in other API functions, just not this one. Fixed in next version.
