### ISSUE TITLE
stbtt__GetGlyphBox changed its behaviour for non-TrueType font

### ISSUE THREAD

**Issue by kompilor** [nothings/stb#404]
Previously, when passing some valid pointers and some `NULL` to `stbtt__GetGlyphBox`, for example
`stbtt__GetGlyphBox(my_x0, my_y0, NULL, NULL);`
my_x0 and my_y0 was filled properly, and all went fine.
Since the integration of new font type, `stbtt__GetGlyphBox` forwards its call to `stbtt__GetGlyphInfoT2` for non-TrueType font, but this function only check the `x0` pointer for nullity, so that the previous example will crash, `stbtt__GetGlyphBox(NULL, NULL, my_x1, my_y1);` will left the passed parameters unchanged.

**Comment by nothings** [comment]
Fixed in next release.
