### ISSUE TITLE
stb_image_resize: Ring buffer assertion error with certain height combinations

### ISSUE THREAD

**Issue by danpla** [nothings/stb#406]
stb_image_resize gives the following error with some image heights:
```
stb_image_resize.h:1422: float* stbir__add_empty_ring_buffer_entry(stbir__info*, int):
Assertion `ring_buffer_index != stbir_info->ring_buffer_begin_index' failed.
```
It seems like width doesn't matter.
For example:
```c++
    int bpp = 3;
    int width = 1;

    int in_height = 95;
    uint8_t* in = (uint8_t*)malloc(in_height * bpp);

    int out_height = 97;
    uint8_t* out = (uint8_t*)malloc(out_height * bpp);

    stbir_resize_uint8(
        in, width, in_height, 0,
        out, width, out_height, 0,
        bpp);
```
Some other combinations that fail:

in_height|out_height
-|-
96| 352
97|135
98|138
99|101
100|108

stb_image_resize v0.92

**Comment by BSVino** [comment]
I'll see if I can investigate this later today.

**Comment by BSVino** [comment]
Looks like floating point inaccuracy causes one extra scanline to be necessary for the ring buffer sometimes. I have a fix for it, going to send stb a patch after I do more testing. I'll post it here as well for you.

**Comment by BSVino** [comment]
https://github.com/nothings/stb/pull/407

**Comment by nothings** [comment]
fixed in next release
