### ISSUE TITLE
Crash when padding is non-zero but glyph size is zero.

### ISSUE THREAD

**Issue by qimmer** [nothings/stb#409]
I am experiencing a bug where a glyph height is 0, but when padding is added, it jumps back to USHRT_MAX and represents an invalid glyph size.

Look at line 2920 in stb_truetype.h:

`
r->w -= pad;
`

r->w and r->h is unsigned shorts. If r->w is 0 and pad is non-zero, which is the case for one of my fonts, this causes r->w and r->h to become 65535 instead of -1.

**Comment by nothings** [comment]
BTW, that's nothing like line 2920 in current version, you may want to update.

**Comment by nothings** [comment]
(Corresponding line appears to be line 3634.)

**Comment by nothings** [comment]
It looks like line 3593 adds spc->spacing to w, and then line 3634 is supposed to be subtracting it back out, so it's not supposed to ever be 0 at line 3634. Can you supply font and sample code that triggers this bug?

**Comment by nothings** [comment]
Closing this for lack of information, though it's probably a real bug. Reopen if you have info.
