### ISSUE TITLE
stb_image: usage in commercial applications

### ISSUE THREAD

**Issue by Flix01** [nothings/stb#413]
Hi,
I know that stb_image (and all the other stb files in this repository) are in the public domain.

However stb_image contains algorithms to decode proprietary image formats, and some parts of them might be patented.

I'm not a lawyer, nor I'm currently using stb_image in a commercial application: but since it's easy to use, portable and compact, I guess many people are already doing it!

My main concern derives from the LZW algorithm used in the .gif format, after having read [this](http://www.fileformat.info/format/gif/egff.htm):
```
 LZW Is Not Free

If you are creating or modifying software that implements the LZW algorithm, be aware that under certain circumstances, you will need to pay a licensing fee for the use of LZW.

Unisys Corporation owns the patent for the LZW codec (encoding/decoding algorithm) and requires that a licensing fee be paid for each software program that implements the LZW algorithm.

Many people have concluded that the Unisys licensing claim applies only to LZW encoders (software that creates LZW data) and not to LZW decoders (software that only reads LZW data). 
However, Unisys believes that its patent covers the full LZW codec and requires a licensing fee even for software that reads, but does not write, LZW data.

For more information about the entire issue of LZW licensing, refer to the section called "LZW Legal Issues" in Chapter 9. For a popular alternative to graphics file formats that use LZW, consider using the Portable Network Graphics (PNG) file format. 
```

Maybe we could disable the .gif decoder by default, and add an optional definition to re-enable it...

**Comment by gcatlin** [comment]
> The United States LZW patent expired on 20 June 2003. The counterpart patents in the United Kingdom, France, Germany and Italy expired on 18 June 2004, the Japanese patents expired on 20 June 2004, and the Canadian patent expired on 7 July 2004. Consequently, while Unisys has further patents and patent applications relating to improvements to the LZW technique, the GIF format may now be used freely.

Source: https://en.wikipedia.org/wiki/GIF#Unisys_and_LZW_patent_enforcement

**Comment by Flix01** [comment]
@gcatlin: Good news! Thanks for the clarification :smiley:
