### ISSUE TITLE
stbi_load only returns first pixel

### ISSUE THREAD

**Issue by itsharmsdawg** [nothings/stb#433]
Hi
I am  trying to read pixels to create a maze solving program.  I tried loading image using your library.
Calling the stbi_load only returns first pixel of the image back. 
Image height and width comes back correct. Here is the sinipit of my code that i am using

 unsigned char* image = stbi_load("tiny.png", &x, &y, &n, 1); 

I tried debugging it and there is no error..

Thanks
Harman

PS-
I am writing it in C.

**Comment by nothings** [comment]
What do you mean only returns the first image? What is contained in the other pixels? Are you sure tiny.png isn't 1x1?

**Comment by itsharmsdawg** [comment]
I tried loading different images as well, but it always returns "0" or any number between "0" to "255". Depending on the first pixel(top left) color of the image. I have attached an image of debugging and return.
![image](https://cloud.githubusercontent.com/assets/11324425/23828892/46a49186-0695-11e7-8768-79f13286e704.PNG)

**Comment by nothings** [comment]
You are only looking at the first byte of the array.

**Comment by itsharmsdawg** [comment]
I am sorry, but can you please give me an example how to read the whole array. I think i search every where and I couldn't find any thing.

**Comment by itsharmsdawg** [comment]
I am really sorry. But all seems to be working now. I really like your work.
Thank you very much for your help. I was just assigning the value wrong.
Cheers
Harman

**Comment by nothings** [comment]
This is a issue with learning C, not something to do with this library, you will have to look elsewhere. Good luck!

**Comment by nothings** [comment]
Glad you got it working, good luck!
