### ISSUE TITLE
stb_image.h: JPG not loaded properly when req_comp is 0 or 3.

### ISSUE THREAD

**Issue by dariomanesku** [nothings/stb#434]
Input image:
![screenshot](https://cloud.githubusercontent.com/assets/1139260/23879975/df377302-0850-11e7-845e-7e12152676f2.jpg)
It loads fine when req_comp is 4.
When req_comp is 0 or 3: three channels are used, it loads successfully, but output looks like this:
![stb](https://cloud.githubusercontent.com/assets/1139260/23880006/1bc13ae2-0851-11e7-82cb-a8be3353d813.jpg)
_(note: disregard the difference in contrast and brightness)_

**Comment by rygorous** [comment]
This is almost certainly not a problem with stb_image, but with your image upload/writing code. Please verify that the actual image data in memory is wrong.

https://www.khronos.org/registry/OpenGL-Refpages/gl4/html/glPixelStore.xhtml

The default GL_UNPACK_ALIGNMENT is 4 bytes. If you're trying to upload a 3-component image with odd width as GL_RGB, GL will round up the row stride (distance in bytes between rows) to the next multiple of 4, and you get this kind of result. stb_image returns pixels in a dense layout with no padding between rows. If you're using GL, try setting GL_UNPACK_ALIGNMENT to 1.

**Comment by dariomanesku** [comment]
You're right, setting GL_UNPACK_ALIGNMENT to 1 did fix the problem.

In conclusion: this was not a problem with stb_image.
