### ISSUE TITLE
stbbtt__hheap_free fails if heap has more than one chunk

### ISSUE THREAD

**Issue by briancostabile** [nothings/stb#446]
I believe the issue is that the next pointer is not accounted for when allocating blocks from the chunk.

return (char *) (hh->head) + size * hh->num_remaining_in_head_chunk;

should be:

return (char *) (hh->head) + sizeof(stbtt__hheap_chunk) + size * hh->num_remaining_in_head_chunk;

or else the next pointer of the chunk will be overwritten by the last block allocated from that chunk.

**Comment by kompilor** [comment]
Had the same issue. The described fix solved the problem for me.

**Comment by nothings** [comment]
fixed in next version, thanks!
