### ISSUE TITLE
stb_sprintf.h GCC warnings: dereferencing type-punned pointer will break strict-aliasing rules

### ISSUE THREAD

**Issue by wojdyr** [nothings/stb#448]
I get warnings about type punning when compiling stb_sprintf.h with GCC 6 and `-Wall`.
The output below has also `-Wmisleading-indentation` warnings, but I'm worried only about `-Wstrict-aliasing`. (I'd rather keep strict aliasing on.)

```
$ g++-6 -c test.cc -O2 -Wall
In file included from test.cc:2:0:
stb_sprintf.h: In function ‘int stbsp_vsprintfcb(char* (*)(char*, void*, int), void*, char*, const char*, __va_list_tag*)’:
stb_sprintf.h:507:9: warning: this ‘if’ clause does not guard... [-Wmisleading-indentation]
         if ( l > (stbsp__uint32)pr ) l = pr; while ((l>1)&&(pr)&&(sn[l-1]=='0')) { --pr; --l; }
         ^~
stb_sprintf.h:507:46: note: ...this statement, but the latter is misleadingly indented as if it is guarded by the ‘if’
         if ( l > (stbsp__uint32)pr ) l = pr; while ((l>1)&&(pr)&&(sn[l-1]=='0')) { --pr; --l; }
                                              ^~~~~
stb_sprintf.h:588:11: warning: this ‘if’ clause does not guard... [-Wmisleading-indentation]
           if ((stbsp__int32)(l+n)>pr) l=pr-n; i=l; while(i) { *s++=*sn++; --i; }
           ^~
stb_sprintf.h:588:47: note: ...this statement, but the latter is misleadingly indented as if it is guarded by the ‘if’
           if ((stbsp__int32)(l+n)>pr) l=pr-n; i=l; while(i) { *s++=*sn++; --i; }
                                               ^
stb_sprintf.h:734:126: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
           if((fl&STBSP__TRIPLET_COMMA)==0) { while(n) { s-=2; *(stbsp__uint16*)s=*(stbsp__uint16*)&stbsp__digitpair[(n%100)*2]; n/=100; } }
                                                                                                                              ^
In file included from test.cc:2:0:
stb_sprintf.h: In function ‘int stbsp__real_to_str(const char**, unsigned int*, char*, int*, double, unsigned int)’:
stb_sprintf.h:1131:89: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
     while(n) { out-=2; *(stbsp__uint16*)out=*(stbsp__uint16*)&stbsp__digitpair[(n%100)*2]; n/=100; e+=2; }
                                                                                         ^
$ cat test.cc 
#define STB_SPRINTF_IMPLEMENTATION
#include "stb_sprintf.h"
```

**Comment by nothings** [comment]
The author prefers to leave strict aliasing optimizations off than working around those.. If somebody wants to do a pass to fix it I'll accept it, but I'm unlikely to fix it myself anytime soon.

**Comment by nothings** [comment]
Just to be clear, I'm fully in charge of this and the original author isn't involved, so it's not up to him it's up to me, I just mentioned him to explain why it was the way it was.

He had performance testing stuff but I didn't bother trying to bring it over.

The whole file needs to be reformatted. Somebody was working on it but I'm not sure he's gonna finish. Small reformatting is fine as well, although there's so much to be done I don't really want to merge 500 formatting PRs in the long run, but just to remove warnings, sure.

**Comment by Leandros** [comment]
I believe the warning is a false-positive. `char` and `unsigned char` are allowed to alias everything, which is why the reported statement: 

```
*(stbsp__uint16*)out=*(stbsp__uint16*)&stbsp__digitpair[(n%100)*2];
```

is well defined since both `out` and `stbsp__digitpair` are `char`.

**Comment by wojdyr** [comment]
yes, I think I should close it as the newer versions of GCC don't show this warning. There would be still a problem in this line if `out` or `stbsp__digitpair` was not aligned to 2, but this is discussed in #484
