### ISSUE TITLE
Baseline And Dimensions not clear

### ISSUE THREAD

**Issue by gitsomecrabs** [nothings/stb#450]
Not exacle clear how to determine the dimensions of each glyph:

In the stb_truetype.h:

scale = stbtt_ScaleForPixelHeight(&font, 76);
stbtt_GetFontVMetrics(&font, &ascent,0,0);
baseline = (int) (ascent*scale);

The scaled value of the baseline with relation to what?

stbtt_GetFontVMetrics returns values that apply the entire font set.

But as I retrieve each individual glyph:

stbtt_GetGlyphBox( *info, index, x0, y0, x1, y1)

In the source it says:
// Gets the bounding box of the visible part of the glyph, in unscaled coordinates

What is the bounding box of the visible part?
This implies there is some invisible part?

So maybe someone could shed some light.

Or better yet make a sketch of the values returned by the GetFontVMetrics, GlyphHMetrics, GlyphKernAdvance, and GlyphBox and how the dimensions should be interpreted.

Thanks anyone.

**Comment by rygorous** [comment]
The visible part of a glyph is the part that actually has "ink" (in TrueType terms, that's the bounding box for the outline vertices). If you're preparing say a bitmap font atlas, that's the part that you would actually store in the bitmap.

Some characters don't have any outlines, but still have an extent. Spaces are the most obvious example.

The ascender/descender size given by GetFontVMetrics gives you the ascender/descender size for the font as a whole. These values influence how text is laid out and are entirely independent from the bounding boxes of the glyph outlines. For example, frequently characters like "O" or "G" will poke slightly above the ascender height on the uppermost strokes of their outlines.

Similarly, GetFontHMetrics tells you where to place the character relative to the cursor position. Again, this is independent of the bounding box of the outline. Some glyphs are only whitespace. They have an advance width but aren't drawing anything. Some can have a negative "left side bearing", meaning they are actually placed to the left of the cursor. This can happen with italics for example.

The FreeType tutorial has a few diagrams: https://www.freetype.org/freetype2/docs/tutorial/step2.html#section-1
("leftSideBearing" corresponds to "horiBearingX" in their terminology)

**Comment by gitsomecrabs** [comment]
Rygorous:

It would be great if you would keep going linking the various parameters in the STB true type functions match up with the dimensions on the truetype link you provided. 

You started to do it with "leftSideBearing" -> "horizBearingX" in your response above, but I am still having to guesstimate matching parameters and return values for stbtt_GetGlyphbox(), stbtt_GetFontVMetrics(), stbtt_FontHMetrics(), stbtt_GetFontBoundingBox() (Font Wide) , stbtt_GetGlyphBitmap()

The FreeType tutorial has a few diagrams: https://www.freetype.org/freetype2/docs/tutorial/step2.html#section-1

"leftSideBearing" -> "horiBearingX" 

The other parameters relations to the freetype.org document.

**Comment by gitsomecrabs** [comment]
Ok:

Here is the dimensional description:

For a given call to stbtt_InitFont(), you get the following:

A) ScaleForPixelHeight() to obtain a scale factor (SF) useful in right-sizing your values to the general maximum vertical bound you want to use. 

B) use FontVMetrics( ) to create a baseline reference across the entire font face based on your target pixel heights.  The ascent + descent (x SF) is defined as above and below your baseline. Ggap is how much space between rendered rows of your font face.

C) GlyphBitmapBox( ) gets you bounding box X0,X1,Y0,Y1 at your given SF.  Bounding box is the actual visible area for your glyph.

X0 -> Left side of bounding box from origin (better to use Left below)
X1 -> Right side of bounding box from origin
Y0 -> (Neg value) Ascent of bounding box from origin (portion above baseline)
Y1 -> Descent of bounding box from origin (portion below baseline)

D) GlyphHMetrics( ) gets you advance and left.  Origin+Advance == Next Origin.  Origin+Left == Left side of bounding box (Close to same as X0 above except when left==negative, zero then)

So when you blend multiple digits together, you have to use advance to move from origin to origin, along with the original baseline value you got when you got FontVMetrics().

Finally, you can use the Kerning value to optimize the horizontal spacing of letters.  You may want ignore kerning when you draw a blinking cursor between digits.

Hope this helps anyone.

Here is a graphic drawing:

http://tinypic.com/r/2ekqes8/9

**Comment by nothings** [comment]
I added the following text to the file for next version, which should address this issue if people find it.

    // DETAILED USAGE:
    //
    //  Scale:
    //    Select how high you want the font to be, in points or pixels.
    //    Call ScaleForPixelHeight or ScaleForMappingEmToPixels to compute
    //    a scale factor SF that will be used by all other functions.
    //
    //  Baseline:
    //    You need to select a y-coordinate that is the baseline of where
    //    your text will appear. Call GetFontBoundingBox to get the baseline-relative
    //    bounding box for all characters. SF*-y0 will be the distance in pixels
    //    that the worst-case character could extend above the baseline, so if
    //    you want the top edge of characters to appear at the top of the
    //    screen where y=0, then you would set the baseline to SF*-y0.
    //
    //  Current point:
    //    Set the current point where the first character will appear. The
    //    first character could extend left of the current point; this is font
    //    dependent. You can either choose a current point that is the leftmost
    //    point and hope, or add some padding, or check the bounding box or
    //    left-side-bearing of the first character to be displayed and set
    //    the current point based on that.
    //
    //  Displaying a character:
    //    Compute the bounding box of the character. It will contain signed values
    //    relative to <current_point, baseline>. I.e. if it returns x0,y0,x1,y1,
    //    then the character should be displayed in the rectangle from
    //    <current_point+SF*x0, baseline+SF*y0> to <current_point+SF*x1,baseline+SF*y1).
    //
    //  Advancing for the next character:
    //    Call GlyphHMetrics, and compute 'current_point += SF * advance'.
    //
