### ISSUE TITLE
stb_image_write: Static import problem

### ISSUE THREAD

**Issue by hankarun** [nothings/stb#457]
When used with  #define STB_IMAGE_WRITE_STATIC definition, some functions cause linker errors because of multiple redefinition if you are using different solutions in project. To prevent this STBIWDEF or static keyword must be added to the missing functions.

**Comment by ema-pe** [comment]
Is it a pitfall of using single file libraries? Because I'm using a single file library (not in stb), and I have the same problem.

Should [this](https://github.com/nothings/stb/blob/master/docs/stb_howto.txt#L61) fix? If yes, should I open an issue it in the library's repository?

**Comment by nothings** [comment]
[PROJECT]_STATIC is only intended for the case where you're intentionally trying to use two different versions/variations of the same library. If you're not, it is probably an error on your part, or some other issue with the library.

**Comment by nothings** [comment]
fixed in next version
