### ISSUE TITLE
warnings compiling stb.h

### ISSUE THREAD

**Issue by nothings** [nothings/stb#46]
https://gist.github.com/emoon/c635437f33d2c8d43570

**Comment by nothings** [comment]
updated: https://gist.github.com/emoon/7a45d512633d5ef9ee15

**Comment by nothings** [comment]
can disable clang warnings like this: https://github.com/ocornut/imgui/blob/master/imgui.cpp#L280

**Comment by nothings** [comment]
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wmultichar"

char b = 'df'; // no warning.

#pragma clang diagnostic pop

**Comment by nyotis** [comment]
"-Weverything: This is an insane group that literally enables every warning in Clang. *Don't use this* on your code. It is intended strictly for Clang developers or for exploring what warnings exist."
[carruth on clang warning flags](https://programmers.stackexchange.com/questions/122608/clang-warning-flags-for-objective-c-development)

**Comment by nothings** [comment]
Thanks!

**Comment by nothings** [comment]
closing this as the report is too out of date now
