### ISSUE TITLE
stb_vorbis.c: compiler error on gcc + mingw32

### ISSUE THREAD

**Issue by waldnercharles** [nothings/stb#461]
When using gcc and mingw32 to compile, the compiler fails complaining that alloca is not defined.

To fix this, [line 554](https://github.com/nothings/stb/blob/master/stb_vorbis.c#L554) needs to change to `#if defined(_MSC_VER) || defined(__MINGW32__)`

**Comment by rygorous** [comment]
Fixed in stb_vorbis 1.11.
