### ISSUE TITLE
Set the same size, use different ttf file, the text size of the display difference

### ISSUE THREAD

**Issue by tailangjun** [nothings/stb#465]
In order to show Simplified Chinese, I tried several different ttf files. I found that set the same size, use different ttf file, the text size of the display difference. Should we need to read out some parameters from ttf file and set to fontstash?
华文黑体.ttf is bigger than UILabel, use the same fontsize.
PingFang Regular.ttf is smaller than UILabel, use the same fontsize.

1.use PingFang Regular.ttf
![usepingfang](https://user-images.githubusercontent.com/12316965/27180156-8b0ff10c-5204-11e7-8c4f-3383991aaac0.jpeg)

2.华文黑体.ttf
![usehuawen](https://user-images.githubusercontent.com/12316965/27180181-b239e512-5204-11e7-93d8-8849bbbc9397.jpeg)

**Comment by nothings** [comment]
What interface are you using to choose the size? What are UILable and nanovg in this context?

**Comment by nothings** [comment]
Closing from lack of response.
