### ISSUE TITLE
stb-image.h documentation references 'req_comp', which is called 'desired_channels' above

### ISSUE THREAD

**Issue by tomjakubowski** [nothings/stb#466]
https://github.com/nothings/stb/blob/master/stb_image.h#L125-L141

First it's `desired_channels`, but is later referred to as `req_comp`. Same applies to `channels_in_file` and `comp`.

I suspect there was a renaming of that variable for clarity, and someone missed a spot in the documentation. :-)

**Comment by rygorous** [comment]
Fixed in stb_image 2.16.
