### ISSUE TITLE
Compilation of stb_vorbis.c fails on Mac

### ISSUE THREAD

**Issue by ndevireddy** [nothings/stb#468]
cc stb_vorbis.c 
Undefined symbols for architecture x86_64:
  "_main", referenced from:
     implicit entry/start for main executable
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by nothings** [comment]
stb_vorbis is not a standalone program. main() is the main entry point for your program.
