### ISSUE TITLE
PVS Studio Analyst Error

### ISSUE THREAD

**Issue by drillsar** [nothings/stb#479]
V522 There might be dereferencing of a potential null pointer 'hash_table'. stb_image_write.h 758

**Comment by rygorous** [comment]
Yeah, that code isn't safe if the image data passed in is in the first 32k of the address space among other things. (Can't happen on Windows which always reserves the bottom 64k, but definitely can happen on OS X.)

**Comment by nothings** [comment]
I think the original report is just that if malloc of hash_table fails, it would try to write to it. I've fixed this.

I don't think there's any issue with pointers being in the bottom 32K; the hash is on uncompressed data bytes, and the pointer subtraction with 'data' are from pointers derived from 'data'.
