### ISSUE TITLE
stb_vorbis overly generic macro defs

### ISSUE THREAD

**Issue by Emartronics** [nothings/stb#480]
at line 5002(was causing whole project to fold in on itself):
#define L  (PLAYBACK_LEFT  | PLAYBACK_MONO)
#define C  (PLAYBACK_LEFT  | PLAYBACK_RIGHT | PLAYBACK_MONO)
#define R  (PLAYBACK_RIGHT | PLAYBACK_MONO)

static int8 channel_position[7][6] =
{
   { 0 },
   { C },
   { L, R },
   { L, C, R },
   { L, R, L, R },
   { L, C, R, L, R },
   { L, C, R, L, R, C },
};

needed to add undefs below:
#undef L 
#undef C
#undef R

**Comment by rygorous** [comment]
stb_vorbis.c is *not* meant to be used as a single-header library, and has several problems like this.

Issue #25 is for converting stb_vorbis to a single-header lib; until that's resolved (it's on my TODO!), the only "supported" way to use stb_vorbis is by compiling it separately.
