### ISSUE TITLE
SDF recommendations

### ISSUE THREAD

**Issue by gitsomecrabs** [nothings/stb#482]
Sean:

Does your your new SDF (signed distance field) output try to included aliasing information or is the shader smoothstep( ) going to handle that?

Based on my initial reading, it looks like smaller size glyphs are better rendered using raw alpha texture but at a certain size, its better to use SDF for flexible sizing and orientation.

What sort of guidance would you offer to decide at given glyph sizes which method to use, raw alpha textures and SDF textures.

The code has a disclaimer about not being optimized, so it could be slow, but the real question is whether you liked the outcome of your effort?

There are various opinions on this subject:

wr00m seems to think signed distance fields can handle text at any size and look crisp. The video has his concept of this and his reference uses libcinder for implementation.

https://www.youtube.com/watch?v=rL8zDgTlXso
http://forum.libcinder.org/#Topic/23286000001127007  (shader code)

How would you alter your shader to properly handle the SDF values that STB outputs?

#FRAGMENT SHADER SNIPPET

#Color set to red for example snippet
gl_FragColor = vec4(1.0,0.0,0.0,0.0) ;

float gmask = texture2D( tex0, gl_TexCoord.xy).a;

// perform simple thresholding
if ( gmask < 0.5 )  gl_FragColor.a = 0.0;
else gl_FragColor.a = 1.0;

//Anti-aliasing
gl_FragColor.a *= smoothstep(0.25, 0.75, gmask);

}

**Comment by nothings** [comment]
Paragraph 1: SDF is meant to be antialiased and the software-rendered sample shows one way to compute that (approximate) anti-aliasing.

Paragraph 2-3: I don't have any guidance for switching between bitmaps and SDF.

Paragraph 4: We are planning on shipping this SDF system in our next UI system at my job.

"How would you alter your shader to properly handle the SDF values that STB outputs" -- see the (software-rendered) sample code in tests/sdf/sdf_test.c

**Comment by gitsomecrabs** [comment]
Sean:  The sdf_test image sample has the statement, "This is goofy text, size 8! Really needs in-shader supersampling to look good"

Any general guide or clues on how you would do in-shader supersample to make Open GL ES.2.0 shader supersample the texture values?    (multiple texture2D retrievals?)

**Comment by nothings** [comment]
Yes, multiple texture2D retrievals, just repeat basically the same AA calculation at e.g. 4 points in the pixel.
