### ISSUE TITLE
SDF computation seems to cause memory corruption w/ padding == 0

### ISSUE THREAD

**Issue by luddyharrison** [nothings/stb#487]
The recently added sdf functionality is working quite well for me, with just one exception.  When I use a large pixel height (via ScaleForPixelHeight) and either a low or a zero padding value, I sometimes get what seems to be memory corruption.  The specific symptom is that FindGlyphIndex crashes (it falls through to the final assert(0) which means the format was unrecognized) -- and for a codepoint for which FindGlyphIndex succeeded previously for the same font.  That is, I call FindGlyphIndex once for every codepoint I'm interested in; then for those present in the font I call GetSDF for each such codepoint.  But as this is an offline tool, I didn't bother to record the glyph indices, and I call GetCodepointSDF (which of course triggers another glyph index lookup).  It is in one of these second-round calls to FindGlyphIndex that the assertion goes off, as if the font structures have been corrupted (by an out-of-bounds access?)

I tried everything I could think of to discover the offender, but couldn't find it.  The data[] and precomputed[] references are fine -- I think it's easy to verify that they can't wander out of bounds.

When this error does not occur, the results seem to be exactly right, and text displays quite well.

BTW, I did an experiment generating a _float_ distance field (i.e., returning +/-min_dist instead of projecting it into unsigned char), and shading using a float texture of those values.  I didn't observe any dropout even at 32 pixels height.  FWIW.  I saw that you had mentioned dropout elsewhere and was curious whether it was a precision / quantization problem with the field data itself, or rather something more complex like having too much font detail around individual pixels when rendering at a smaller size.  The little bit of experimentation I did suggested that it might be the former thing.

(Lato-Light.ttf, pixel height = 64, a palette of codepoints that corresponds to a US keyboard, and a low padding value triggers the failure for me.)

**Comment by nothings** [comment]
Can you get a simple repeatable process that crashes, i.e. 'use font X, do GetSDF on char y, then FindGlyphIndex on z crashes' with specific details, so I can see if I can easily reproduce it?

**Comment by luddyharrison** [comment]
I will try to put together an isolated test case.  (I would simply pass you the very code that triggers it, but it's sitting in a bunch of infrastructure that makes it ungainly to pass along & build.)

**Comment by luddyharrison** [comment]
````
#define STB_TRUETYPE_IMPLEMENTATION
#include "stb_truetype.h"

#include <stdio.h>
#include <stdlib.h>

unsigned char buf[100000];

int main(int argc, const char *argv[])
{
  fread(buf, 1, 1<<20, fopen(argv[1], "rb"));

  stbtt_fontinfo font;
  stbtt_InitFont(&font, buf, 0);
  float scale = stbtt_ScaleForPixelHeight(&font, 64.0);

  for (int p=0; p<256; ++p)
    {
      int i = stbtt_FindGlyphIndex(&font, p);
      if (i)
        {
          printf("forming sdf for codepoint %d\n", p);
          int width, height, xoff, yoff;
          unsigned char *sdf = stbtt_GetCodepointSDF(&font, scale, p, 0, 127, 1.0, &width, &height, &xoff, &yoff);
        }
    }

  return 0;
}
````

running this program as ``a.out Ubuntu-Light.ttf`` causes a segmentation violation.

**Comment by luddyharrison** [comment]
I can't come up with an isolated test case that reproduces this.  :-\  In an isolated test case, the only .ttf I can find that crashes on FindGlyphIndex is NotoColorEmoji.ttf.  But that's hardly an ordinary font file.  (FWIW, just initializing that font and doing a FindGlyphIndex(&info, 0) causes a crash.)

So: I'm going to close this until/unless I can extract a proper test case from my code.  Sorry for the distraction...
