### ISSUE TITLE
stb_textedit: Build failure on MacOS

### ISSUE THREAD

**Issue by codecat** [nothings/stb#493]
I get the following error when building on MacOS:

```
/Users/nimble/dev/nimble-app/ext/stb/stb_textedit.h:1053:12: error: case value evaluates to 3221225741, which cannot be narrowed to type
      'int' [-Wc++11-narrowing]
      case STB_TEXTEDIT_K_LINEEND | STB_TEXTEDIT_K_SHIFT: {
           ^
/Users/nimble/dev/nimble-app/src/nimble/widgets/text.cpp:74:35: note: expanded from macro 'STB_TEXTEDIT_K_LINEEND'
#define STB_TEXTEDIT_K_LINEEND    STB_TEXTEDIT_K_KEYDOWN | GLFW_KEY_END
                                  ^
/Users/nimble/dev/nimble-app/src/nimble/widgets/text.cpp:10:35: note: expanded from macro 'STB_TEXTEDIT_K_KEYDOWN'
#define STB_TEXTEDIT_K_KEYDOWN    0x80000000
                                  ^
```

Which makes sense, `3221225741` is `0xC000010D`. Should I just use `-Wno-c++11-narrowing`, or is there a better solution? (Using `uint32_t` instead of `int` for keys?)

**Comment by nothings** [comment]
I believe it should all be changed to be "unsigned int", yeah. (not uint32_t for old-compiler reasons)

**Comment by nothings** [comment]
So, technically, the API says it takes an 'int', so it's just on you to make sure your values are in range. So e.g. don't mape anything like STB_TEXTEDIT_K_KEYDOWN to 0x8000000, just use 0x4000000 or lower.

But I've added a define in the next version that you can change the definition of 'int key' to any other type.

**Comment by codecat** [comment]
Thank you!
