### ISSUE TITLE
Inconsistent comments regarding 16-bits-per-pixel PNG

### ISSUE THREAD

**Issue by jameswilddev** [nothings/stb#494]
Just a minor one!

It's mentioned in https://github.com/nothings/stb/blob/master/stb_image.h#L56 and https://github.com/nothings/stb/blob/master/stb_image.h#L24 that there is support for 16-bit PNGs, but https://github.com/nothings/stb/blob/master/stb_image.h#L108 specifies that there is not support for 16-bit PNGs.

**Comment by ni9elf** [comment]
Are 16-bit PNGs supported or not?

**Comment by nothings** [comment]
They are supported.

**Comment by ni9elf** [comment]
To make this thread a complete reference on 16-bit PNG image files, what are the commands to load and save these files?

**Comment by nothings** [comment]
That's not really the purpose of the tread; and (a) there's no writing in stb_image, and no 16-bit support in stb_image_write; and (b) I think the existing documentation should be sufficient for the reading side.

**Comment by nothings** [comment]
Whoops, ignore the accidental close, pressed the wrong button.

**Comment by nothings** [comment]
fixed in next version
