### ISSUE TITLE
stb_truetype: bug on FIXED16 to float conversion, CFF table size

### ISSUE THREAD

**Issue by ECorvi** [nothings/stb#504]
```
// push immediate
if (b0 == 255) {
    f = (float)stbtt__buf_get32(&b) / 0x10000;
```

should really be:
`    f = ((float)(stbtt_int32)stbtt__buf_get32(&b)) / 0x10000;`

stbtt__buf_get32 returns an uint32, but FLOAT16 is signed on the top 16 bits, so it needs casting to int32_t before dividing by 65536

this caused some OTF fonts using push immediate not to return the box properly or render properly.

---

This function returns the table size:
```
static stbtt_uint32 stbtt__table_size(stbtt_uint8 *data, stbtt_uint32 fontstart, const char *tag)
{
	stbtt_int32 num_tables = ttUSHORT(data + fontstart + 4);
	stbtt_uint32 tabledir = fontstart + 12;
	stbtt_int32 i;
	for (i = 0; i < num_tables; ++i) {
		stbtt_uint32 loc = tabledir + 16 * i;
		if (stbtt_tag(data + loc + 0, tag))
			return ttULONG(data + loc + 12);
	}
	return 0;
}
```
So now, in stbtt_InitFont_internal() you can replace the 512MB allocation with:

```
      stbtt_uint32 cfflen = stbtt__table_size(data, fontstart, "CFF ");

      // @TODO this should use size from table (not 512MB)
      info->cff = stbtt__new_buf(data+cff, cfflen);

```

**Comment by nothings** [comment]
These have been fixed (differently) in the next release.
