### ISSUE TITLE
stb_truetype.h implicit fallthrough warning

### ISSUE THREAD

**Issue by mgerhardy** [nothings/stb#507]
```
/home/travis/build/mgerhardy/engine/src/modules/voxel/font/stb_truetype.h: In function ‘int stbtt__run_charstring(const stbtt_fontinfo*, int, stbtt__csctx*)’:
/home/travis/build/mgerhardy/engine/src/modules/voxel/font/stb_truetype.h:2060:10: warning: this statement may fall through [-Wimplicit-fallthrough=]
          if (!has_subrs) {
          ^~
/home/travis/build/mgerhardy/engine/src/modules/voxel/font/stb_truetype.h:2066:7: note: here
       case 0x1D: // callgsubr
       ^~~~
```

**Comment by nothings** [comment]
what compiler? there's a "// fallthrough" before it which some compilers recognize

**Comment by mgerhardy** [comment]
g++ (Ubuntu 7.2.0-1ubuntu1~14.04) 7.2.0
I checked a few other situations, it looks like they must not be in the same line in some situations. Weird warning flag.

**Comment by nothings** [comment]
If you can figure out what it takes for it not to warn about it I'll change it.

**Comment by dougallj** [comment]
I'm guessing it'd be `__attribute__ ((fallthrough));` with a bunch of ifdefs to match compilers that works on. This makes for fascinating reading (but not really in a good way): https://developers.redhat.com/blog/2017/03/10/wimplicit-fallthrough-in-gcc-7/

Given the mess of different annotations, a more solid fix might be to remove the fallthrough altogether:
```
case 0x0A: // callsubr
case 0x1D: // callgsubr
    if (b0 == 0x0A && !has_subrs) {
```

**Comment by nothings** [comment]
Unfortunately there are a other fallthroughs in stb that aren't fixed so easily.

**Comment by nothings** [comment]
According to https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html

    // fallthrough

is supposed to be sufficient for gcc up to -Wimplicit-fallthrough=4, and default of -Wimplicit-fallthrough is 3.

**Comment by nothings** [comment]
Oh no, wait, I guess it's supposed to have a - at the front for -Wimplicit-fallthrough=3-4. Sigh.

**Comment by nothings** [comment]
I'd appreciate if someone who gets this warning can check that changing the comment to "// -fallthrough" fixes it.

**Comment by rygorous** [comment]
Fix for this is (at long last) merged into dev branch and will be in the next release.
