### ISSUE TITLE
stb_image treat 8-bit png as 24-bit

### ISSUE THREAD

**Issue by andreyugolnik** [nothings/stb#510]
Hello, 

Stb_image report that attached PNG has 3 channels, instead 1 channel.
That's wrong. Gimp and any other viewer based on libpng treats it as 8-bit per pixel image.
 
![shutters](https://user-images.githubusercontent.com/1927370/31570691-2d3caf04-b08f-11e7-9b51-a516a4fdfd1f.png)

Image size 128x256 at 8 bit.

**Comment by nothings** [comment]
This is behaving as expected. The image is paletted. stb_image does not provide any means to access the palettized version of the image; it is automatically "depalettized". PNG has no way to specify that a palette is monochrome; it is always 3 or 4 channels, thus after depalettization, paletted PNG images are alwayy 3 or 4 channels.

PNG also supports monochrome, 8-bit-per-channel images that would also be 8-bit and would behave as you expect in stb_image; it's just a question of how to get the program that created the image to product it, which is outside the scope of this repository.
