### ISSUE TITLE
stb_truetype.h: Add Font outline rendering

### ISSUE THREAD

**Issue by kphillisjr** [nothings/stb#519]
This is mostly an improvement on the bitmap rasterization system to allow for generating font outlines in a fashion similar to how the HTML Canvas ```strokeText``` function works.  An example of Font outline rendering is available on  [Mozilla Developers Network - Drawing text - Web APIs](https://developer.mozilla.org/en-US/docs/Web/API/Canvas_API/Tutorial/Drawing_text). 

Font outlines are mostly used to ensure text is readable in cases where the Background color matches the general fill color of the text. is when the background color matches the text to be rendered. Using HTML Canvas as an example, the following code shows this well.

```JavaScript
ctx.fillStyle = '#0000FF';
ctx.strokeStyle = '#000000';
ctx.font = '40px serif';
ctx.lineWidth = 1.5;

/*
 * Draw Solid Color background 
 */
ctx.fillRect(0, 0, 300, 175);

/*
 * This text can be seen.
 */
ctx.fillText('Hello world', 25, 55);
ctx.strokeText('Hello world', 25, 55);

/* 
 * This text cannot be seen.
 */
ctx.fillText('Hello world', 25, 125);

```

**Comment by nothings** [comment]
This can be done by post-processing the bitmaps or by using the SDF output, but I'm not sure it makes sense to add to the library itself, it seems a bit out of scope.
