### ISSUE TITLE
stb_dxt.h: A detection of constant color in stb__CompressColorBlock also checks for a constant alpha

### ISSUE THREAD

**Issue by andrewe-playrix** [nothings/stb#523]
stb__CompressColorBlock
>    // check if block is constant
>    for (i=1;i<16;i++)
>       if (((unsigned int *) block)[i] != ((unsigned int *) block)[0])
>          break;
> 
>    if(i == 16) { // constant color

Works as
>    if(i == 16) { // constant color and constant alpha

So, stb__CompressColorBlock is dependent on alpha in an unsuspected way

**Comment by nothings** [comment]
Thanks! Fixed in next version.
