### ISSUE TITLE
stb_image_write.h monochrome BMP

### ISSUE THREAD

**Issue by Chribba** [nothings/stb#53]
Hello!

The addition of monochrome TGA writing broke monochrome BMP writing. This is because BMP expects the single Y component to be expanded to RGB, while TGA writes the Y as is.

In write_pixels():
where it used to say "case 2: write3(f, d[0],d[0],d[0]);" (needed for BMP)
you now have "case 2: fwrite(d, 1, 1, f);" (needed for TGA)

**Comment by nothings** [comment]
Fixed in 0.96
