### ISSUE TITLE
Secure CRT Errors with Visual Studio

### ISSUE THREAD

**Issue by xeekworx** [nothings/stb#533]
https://github.com/nothings/stb/blob/9d9f75eb682dd98b34de08bb5c489c6c561c9fa6/stb_image_write.h#L233

If I compile stb_image_write.h in Visual Studio 2017 (likely previous versions as well) I get the following sort of errors, "This function or variable may be unsafe", for functions such as fopen, sprintf, etc. Is there any anticipation for fixing these? I understand they used to be warnings (they're errors now), but it would be nice to avoid having to turn off CRT deprecation errors just for this header.

I can probably whip up a solution if need-be. I can't believe I haven't see anything here about this yet.

**Comment by xeekworx** [comment]
For example, at least something for this call; there are other lines than this one.
_Not relevant: Why does this file use 3 space tabs?_

```cpp
static int stbi__start_write_file(stbi__write_context *s, const char *filename)
{
   FILE *f;
#ifdef _MSC_VER
   fopen_s(&f, filename, "wb");
#else
    f = fopen(filename, "wb");
#endif
   stbi__start_write_callbacks(s, stbi__stdio_write, (void *) f);
   return f != NULL;
}
```

**Comment by nothings** [comment]
FWIW: "Why does this file use 3 space tabs?"

Because I use 3-space indentation when I program, and I wrote this file.

**Comment by nothings** [comment]
Please paste a list of all the lines with warnings/errors so they can be fixed.

**Comment by xeekworx** [comment]
I just cloned the repo .. I can submit a PR

**Comment by nothings** [comment]
Sure. Just create a new #define that invokes the secure calls, rather than conditional on MSVC directly. That will allow reusing it if there are other compilers w/ same ones, and lets us avoid breaking older versions of MSVC where the secure functions were named differently or didn't exist.

**Comment by xeekworx** [comment]
Are you sure? I mean we are really talking really really old versions of MSVC. Are you suggesting there be something like #ifdef STB_MSC_SECURE_CRT ?

**Comment by xeekworx** [comment]
This would suggest STB leans more towards very old compiler support by default.

**Comment by nothings** [comment]
Yes, something like STBI_MSC_SECURE_CRT. (Note "STBI" so it doesn't conflict with other STB libraries.)

stb libs try to support both new and old compilers. personally I dev primarily in msvc6 (1997). But we do want to fully support newer ones, we just don't have automated tests for them for msvc like we do on linux.

**Comment by xeekworx** [comment]
I would have though a vast majority would be using a post 1997 MSVC compiler so that the definition should be the opposite as to prefer a majority over the minority. It is modern times so I suppose not. You're the owner so I shall respect that -- updating my branch...

**Comment by nothings** [comment]
I don't care if old or new gets priority--I don't care if the name is STBI_MSC_SECURE_CRT or STBI_MSC_INSECURE_CRT, my only point was to not #ifdef on _MSC_VER directly.

**Comment by xeekworx** [comment]
I totally understood that. I didn't mean in any way at all for things to get confrontational. I was already making the changes...

**Comment by nothings** [comment]
No worries, no confrontation intended.
