### ISSUE TITLE
Photoshop can't open jpg or png files created by stbi_write_*_to_func

### ISSUE THREAD

**Issue by jceipek** [nothings/stb#535]
Here's an example jpg created using `stbi_write_jpg_to_func`:
![teststbimage](https://user-images.githubusercontent.com/438112/34550092-ea4ad512-f0c2-11e7-9a02-031f110f5b6d.jpg)

For some reason, Adobe Photoshop CC 2015 complains: "Could not complete your request because an unexpected end-of-file was encountered." but other apps on my computer (such as MacOS Preview and Affinity Photo) open the image with no issue.

I need to use `stbi_write_jpg_to_func` because I would like to use the library for a Google API that accepts base-64 encoded images, so I'm streaming the image data to a base 64 string.

**Comment by nothings** [comment]
If stbi_write_jpg works but stbi_write_jpg_to_func works, why do you think it is a bug in stb_image_write rather than a bug in your output function?

**Comment by jceipek** [comment]
Because I was too close to the problem. Thank you for asking the right question 👍
