### ISSUE TITLE
stbi doesn't report color profile

### ISSUE THREAD

**Issue by ryanastout** [nothings/stb#537]
image files contain information about the color profile used when saving the image. https://www.w3.org/TR/2003/REC-PNG-20031110/#11addnlcolinfo for example describes how PNG stores the color profile. It would be nice if stbi had a way to query this information

**Comment by ryanastout** [comment]
closing because after some more searching it seems that not all supported image formats contain color profile information, so it wouldn't be possible to add this for all the formats

**Comment by sanjay-nambiar** [comment]
It would be an extremely useful feature if this is supported. For formats that don't contain a color profile, the method can return some sort of empty object / null. This can be very useful for real-time rendering applications to understand what color profile the textures are in and convert to linear if needed.

**Comment by nothings** [comment]
Yeah, I agree, there's no reason not to support it even if it's only for some formats. E.g. users who want this can restrict themselves to the formats that work.

Reopened, but I don't have any plans to work on this anytime soon.

**Comment by Tom94** [comment]
If exposing color profiles is too much work, would it be possible for stbi to indicate the _existence_ of a custom color profile?

This would allow an application to fail gracefully (or emit a warning) rather than displaying wrong data.
