### ISSUE TITLE
stb_image.h: use of undeclared identifier 'stbi__malloc_mad4' with STBI_ONLY_PNG defined

### ISSUE THREAD

**Issue by ssjdrn** [nothings/stb#539]
I got an error

`stb_image.h:1615:23: error: use of undeclared identifier 'stbi__malloc_mad4'`

when compiling with STBI_ONLY_PNG defined. Fixed after also defining STBI_NO_LINEAR, but then I get warnings about unused functions 'stbi__sse2_available' and 'stbi__vertical_flip_slices'.

**Comment by nothings** [comment]
Fixed for next version, I think. Reopen if not.
