### ISSUE TITLE
SDF for stb_truetype

### ISSUE THREAD

**Issue by nothings** [nothings/stb#54]
Try building three signed-distance fields (see Valve paper, etc.).

For each one, differently perturb vertices away from sharp corners along different edges.

Use intersection of first two to get sharp convex corners

Get union with third to get sharp concave corners.

Write detector that tells if vertices get displaced too close to other edges; if so, try running the character at a higher resolution.

Store AA pixel coverage in fourth channel; shader dynamically chooses between SDF or manually subsampling coverage (use heavily biased mipmapping).

**Comment by nothings** [comment]
Added in stb_truetype version 1.16.

**Comment by godratio** [comment]
@nothings  
I know you dont like to be notified for nothing but just wanted to say thanks for putting in the effort for this its a really good effort and helpful and useful.
