### ISSUE TITLE
stb_dxt error in v1.08

### ISSUE THREAD

**Issue by DMartinek** [nothings/stb#542]
In version 1.08 of stb_dxt there seems to be an error in line 653:
`unsigned char *data[16][4];`
should be 
`unsigned char data[16][4];`
as far as I know. Or am I wrong?

Greetings,
Daniel

**Comment by nothings** [comment]
Yes, it won't compile at all as it is. Whoops.

I just discovered is that my testbed wasn't actually compiling stb_dxt's implementation section because I misspelled STB_DXT_IMPLEMENTATION.

Fixed in 1.08b, released now.
