### ISSUE TITLE
stb_image.h: implicit conversion warning in stbi_is_hdr_from_file

### ISSUE THREAD

**Issue by jcredmond** [nothings/stb#543]
In v2.17b, compiling a 64-bit iOS build, clang generates an "implicit conversion loses integer precision" ('long' to 'int') warning. The function should return an int, but res is a long.

**Comment by nothings** [comment]
line number?

**Comment by jcredmond** [comment]
Line 1341.

**Comment by nothings** [comment]
fixed in next version
