### ISSUE TITLE
Typo in `stb_vrobis.h`

### ISSUE THREAD

**Issue by v1993** [nothings/stb#548]
Just found this:

    #define temp_free(f,p)                  (f->alloc.alloc_buffer ? 0 : dealloca(size))
Did you meant

    #define temp_free(f,p)                  (f->alloc.alloc_buffer ? 0 : dealloca(p))
?

**Comment by nothings** [comment]
Unclear. I don't know where that code came from. Reference for alloca() for linux indicates there is no dealloca() function at all, so I don't know if I wrote it or if somebody else submitted it at some point.

Since alloca() allocates space on the stack, it would not be unreasonable for dealloca to be defined to takey the corresponding size which simply moves the stack pointer back the same amount. Whereas it is unclear how it would be implemented if it took a pointer argument (at least for stacks which grow downwards).

**Comment by v1993** [comment]
After all, it isn't valid, so should be fixed or removed, right?

**Comment by nothings** [comment]
Yes I see the line of code you're talking about. I don't think you understand my reply.

Prove to me the code is wrong. Give me a link to the definition of dealloca.

**Comment by v1993** [comment]
Code is wrong by one simple reason: there is no argument named `size`. I tried to replace it with malloc/free for my needs and found that.

**Comment by v1993** [comment]
Well, I didn't found any references to this function in google. Is it even exist anywhere?

**Comment by nothings** [comment]
That is my point. Maybe it exists on some platform. Maybe somebody submitted it as a change in the past and I added it. Without knowing the definition of dealloca, we don't know that 'size' is wrong.  alloca *does not* work like malloc. In fact, the way alloca works (by allocating on the stack), it makes more sense that dealloca would take size than that it would take the pointer. But I don't actually know.

**Comment by v1993** [comment]
I discovered that it was there starting from `commit e2caccb811d70af0dc359be5522e6b0d3b503e46`, it is `inital checkin`, so it isn't patch from someone.

After all, it is GCC's opinion: still no `size`.

**Comment by nothings** [comment]
> so it isn't patch from someone

stb_vorbis was in development for some time before it was moved to github. there is no commit history for the time before it was on github, but I did take patches by email during that time.

I have no idea what you mean by this:

> After all, it is GCC's opinion: still no size.

Are you getting a warning from gcc about this?

**Comment by v1993** [comment]
No, but if someone will even have `dealloca`, it will fail, because there isn't `size`. Ok, in this case we will know what is `dealloca`'s argument.

As I said before, I found this when I tried to use `malloc`/`free` instead of `alloca`/`dealloca`

**Comment by nothings** [comment]
Oh, I see what you mean now, temp_free doesn't specify `size`, you're right.

**Comment by nothings** [comment]
Anyway, I've deleted the dealloca thing for the next version, but you should know that you can't replace the temp_alloc with malloc/free. You have to pass in memory in the stb_vorbis_alloc parameter.
