### ISSUE TITLE
Small typo in stb_image_write.h

### ISSUE THREAD

**Issue by ignotion** [nothings/stb#552]
In documentation comments, i've found (line 40)
     int stbi_write_jpg(char const *filename, int w, int h, int comp, const **float** *data, int quality);
as documentation for writing jpg.
Obviously it should be, as it is in the code
     int stbi_write_jpg(char const *filename, int w, int h, int comp, const **void** *data, int quality);

Seems a due to c&p from previous line (the hdr writing which indeed needs float*)

**Comment by adamschackart** [comment]
There is also a missing underscore on what is currently line 237
"static int stbi_write_png_**compression level** = 8;"

**Comment by nothings** [comment]
Fixed in next version.
