### ISSUE TITLE
stb_image unicode support

### ISSUE THREAD

**Issue by nothings** [nothings/stb#557]
It would be nice to support Unicode filenames on windows. We can do this by making the char* be interpreted as UTF-8, converting to UTF-16, and using Windows UTF-16-base file operations. For back compatibility, the existing code-page behavior should be available on a define (or vice versa, old behavior is default, can ask for unicode explicitly--or even check for Windows UNICODE define). Also add a helper for windows that converts wchar_t to UTF-8 so if user has a wchar_t filename, they can use the utf-8 mode successfully. See discussion in #529

**Comment by jrsmith17** [comment]
I provided a pull request for this issue [here](https://github.com/nothings/stb/pull/559). Unicode needs to be explicitly defined or it defaults to the old behavior. I also provided a helper function for converting wchar_t to UTF-8. Let me know if this meets your needs. Thanks!

**Comment by nothings** [comment]
Fixed and released a couple weeks ago.
