### ISSUE TITLE
stb_rect_pack.h -  warning: comparison is always true due to limited range of data type [-Wtype-limits]

### ISSUE THREAD

**Issue by codeyash** [nothings/stb#558]
If possible please fix these warnings.

warning: In file included from c_src/stb_rect_pack.h:203:0,
warning:                  from c_src/stb_truetype.c:4:
warning: c_src/stb_rect_pack.h: In function ‘stbrp_pack_rects’:
warning: c_src/stb_rect_pack.h:559:31: warning: comparison is always true due to limited range of data type [-Wtype-limits]
warning:        STBRP_ASSERT(rects[i].w <= 0xffff && rects[i].h <= 0xffff);
warning:                                ^
warning: c_src/stb_rect_pack.h:559:7: note: in expansion of macro ‘STBRP_ASSERT’
warning:        STBRP_ASSERT(rects[i].w <= 0xffff && rects[i].h <= 0xffff);
warning:        ^
warning: c_src/stb_rect_pack.h:559:55: warning: comparison is always true due to limited range of data type [-Wtype-limits]
warning:        STBRP_ASSERT(rects[i].w <= 0xffff && rects[i].h <= 0xffff);
warning:                                                        ^
warning: c_src/stb_rect_pack.h:559:7: note: in expansion of macro ‘STBRP_ASSERT’
warning:        STBRP_ASSERT(rects[i].w <= 0xffff && rects[i].h <= 0xffff);

**Comment by rygorous** [comment]
Fix for this was merged in 2019.
