### ISSUE TITLE
Stb_Image RGBA -> BGRA etc conversions

### ISSUE THREAD

**Issue by Tom-III** [nothings/stb#565]
Is it possible to add conversions such as between color ordering?
Maybe if the desired channels are -4 or -3 they get swapped respectively?
Would be a really awesome feature! (Considering software like Direct3D/OpenGL prefer their pixels in certain orders...)

**Comment by rygorous** [comment]
If you want BGRA (or BGR), you can just swap the channels yourself in a few lines of code!

While adding this functionality would be convenient for the people who need it, it would also further complicate the semantics of `desired_channels` and `channels_in_file`, which are already the most frequent source of user questions about stb_image.

One thing we are considering is adding a new API entry point for "complex" usage that has better support for things like 16-bit or floating-point images and stops using globals for things like the "PNG de-iPhone" flag or the vertical flip flag. If we end up implementing this, that's probably also a good point to add BGRA output support (if desired). But making the `desired_channels` parameter "magic" is definitely not something we want to do.

**Comment by pbozikis** [comment]
@rygorous 

What lines do i need to edit in the .h file? I've tried switching the byte order in one function but that didn't work. I'm sure there's other points where the bytes are assigned but I can't find it

**Comment by nothings** [comment]
You shouldn't change the h file. In the file where you call stbi_load, you write a few lines of code after calling stbi_load that swap the channels.

**Comment by pbozikis** [comment]
Thank you for the quick reply, I have been actually working on switching them just now, i'm using window.h to render and their RGB macro shifts blue << 16 bits but does it displays as red when you give the blue parameter 255, so i'm really confused what format it is, or maybe if some endianness is messing it up. When I used to declare my own colours i did so like 0xffff0000 which would be red and so I assumed their format is ARGB but now im not sure

**Comment by nothings** [comment]
First figure out how to correctly set colors in the windows API without worrying about stb_image. Then, once you're sure how that works, it should be easy to connect up stb.
