### ISSUE TITLE
conan package

### ISSUE THREAD

**Issue by p-groarke** [nothings/stb#566]
Providing a conan package would be appreciated. Even though stb is header only, managing it as a traditional library helps when using multiple dependencies that include the headers.

Cheers

**Comment by OvermindDL1** [comment]
For note, [stb is available via hunter](https://docs.hunter.sh/en/latest/packages/pkg/stb.html), so if you add the huntergate cmake file to your project then just add these to your CMakeLists.txt file:

```cmake
# Use the huntergate file:
include("cmake/HunterGate.cmake")

# Use the standard repository, or use a custom one, or make your own, just using the 'standard' one here:
HunterGate(
    URL "https://github.com/ruslo/hunter/archive/v0.20.9.tar.gz"
    SHA1 "8f7cf6d719d05c49224a4ebeba90c6bb90b90f4a"
)

# Add dependencies from hunter
hunter_add_package(stb)
# And whatever other dependencies you want to pull from the hunter repo's you defined
```

Then just use it like any other cmake library:

```cmake
find_package(stb CONFIG REQUIRED)
target_link_libraries(my_project PUBLIC stb::stb) # I'm not actually sure it has a link step actually, it probably doesn't...
```

No secondary programs needed (unlike conan), nothing but the cmake itself needed, etc...

**Comment by p-groarke** [comment]
Seems like the conan team likes STB as well :)

https://bintray.com/conan-community/conan/stb%3Aconan
