### ISSUE TITLE
stbi_image_write_hdr has incorrect stride calculation

### ISSUE THREAD

**Issue by vchizhov** [nothings/stb#567]
Hi,

I recently swapped v. 1.07 with v.2.19 and I get an "access violation reading..." error in stbi_image_write_hdr. I tested it with a simple piece of code, and it still breaks:
```
        int w = 100;
	int h = 100;
	int n = 1;
	float* data = new float[w*h*n];
	for(int y=0;y<h;++y)
		for (int x = 0; x < w; ++x)
		{
			for (int i = 0; i < n; ++i)
				data[n*(x + y*w) + i] = float(y) / float(h);
		}
	stbi_write_hdr("test.hdr", w, h, n, data);
```
This and my other code works perfectly fine with v 1.07.

**Comment by nothings** [comment]
I will take a look.
