### ISSUE TITLE
warning: unused variable ‘pairSetCount’ in stb_truetype.h

### ISSUE THREAD

**Issue by pjessesco** [nothings/stb#569]
I have this warning in `stb_truetype.h` 1.19. I'm using gcc 4.8.5, 64bit ubuntu 16.04

path/stb_truetype.h: In function ‘stbtt_int32 stbtt__GetGlyphGPOSInfoAdvance(const stbtt_fontinfo*, int, int)’:
path/stb_truetype.h:2454:42: error: unused variable ‘pairSetCount’ [-Werror=unused-variable]
                             stbtt_uint16 pairSetCount = ttUSHORT(table + 8);

**Comment by rygorous** [comment]
This is now fixed in the dev branch, will be in the next release.
