### ISSUE TITLE
Memory pool for STB Image

### ISSUE THREAD

**Issue by sasmaster** [nothings/stb#573]
Hi. I have been using STB Image for a while. I like it very much,but I wonder if it's possible to fetch memory from some pool/arena so that STB wouldn't allocate it during image loading.

**Comment by sasmaster** [comment]
Hi. I have implemented a simple 'memory arena'. I also see that stb_image performs several alloc/realloc calls during a single image load session. Can anybody take a look at this impl and tell me if it is ok with how the internals of the lib are working? I mean,my main concern is "free". I currently imply that I can reset the pointer advance as the "free" call is the last call in the current loading session and it de-allocates all the previously allocated memory for this session (I also believe this thread can be useful for more people to use stb with memory pools:

        #define POOL_SIZE 4096 * 4096 * 4
        unsigned char* pool = nullptr;
        size_t pool_pos = 0;
        void* __alloc(size_t size)
        {
	     void* newAlloc = pool; 
	     pool_pos += size;
	     assert(pool_pos < POOL_SIZE);
	     pool += size;
	    return newAlloc;
        }

       void* __realloc(void*p, size_t newsize)
       {
	    void* newAlloc = nullptr;
	   if (p)
	   {
		  newAlloc = p; 
	   }
	   else
	   {
		newAlloc = pool;
	   }
	   pool_pos += newsize;
	   assert(pool_pos <  POOL_SIZE);
	   pool += newsize;
	   return newAlloc;
       }
       //we assume that the user frees the chunk of memory,which
       //used all the previous alloc/realloc
       void __free(void* p)
      {
	pool_pos = 0;
       }

       #define STBI_MALLOC(sz) __alloc(sz)
       #define STBI_REALLOC(p,newsz)__realloc(p,newsz)
       #define STBI_FREE(p) __free(p)         

       #ifndef STB_IMAGE_IMPLEMENTATION
       #define STB_IMAGE_IMPLEMENTATION
       #endif // !STB_IMAGE_IMPLEMENTATION
       #include <stb_image.h>

       int main(int argc, char* argv[])
      {
	     pool = (unsigned char*)malloc(4096 * 4096 * 4);
	     int w, h, d;
	     unsigned char* data = stbi_load("test.png", &w, &h, &d, 0);
	     assert(data);
       }

Thanks!

**Comment by nothings** [comment]
your code is assuming the FIRST free call is safe to free all of the memory. this is probably not true, or if it is true now, it may not be in the future.

(also, you don't copy the memory in realloc).

This isn't really the appropriate place for this discussion though.
