### ISSUE TITLE
stb_image_write.h : Allocator sizeof operand mismatch

### ISSUE THREAD

**Issue by Martinfx** [nothings/stb#576]
Hi , scan-build reported on line 825, 
Result of 'malloc' is converted to a pointer of type 'unsigned char **', which is incompatible with sizeof operand type 'char **'

`unsigned char ***hash_table = (unsigned char***) STBIW_MALLOC(stbiw__ZHASH * sizeof(char**));`

**Comment by nothings** [comment]
It's harmless but I will fix it.

**Comment by Martinfx** [comment]
Ok thanks you.

**Comment by rygorous** [comment]
This was fixed in stb_image_write v1.13.
