### ISSUE TITLE
assert triggered..

### ISSUE THREAD

**Issue by Sur3** [nothings/stb#579]
Hi I had this assert triggered, what does it mean, is it a bug in the library or the usage or in the sound file?
https://github.com/nothings/stb/blob/e6afb9cbae4064da8c3e69af3ff5c4629579c1d2/stb_vorbis.c#L3127

**Comment by ongamex** [comment]
without me being able to help you, I think you should add a way to reproduce the issue

**Comment by nothings** [comment]
It's probably a bug in the code. It means it didn't correctly track some temporary memory.

(I assume you're passing a temporary memory buffer? I don't normally test this path. If most files work but this file is failing, it probably means there's an error in the file and the stb_vorbis code path that recovers from that error isn't freeing the memory, in which case the answer to your question is 'both the first and last'.)

**Comment by rygorous** [comment]
No answer in over 2 years, closing.

**Comment by Sur3** [comment]
Oh sorry for not answering. I dont exactly remember where i used the library though. So having this closed is fine by me for now. ^^

**Comment by rygorous** [comment]
All right, no worries, if it comes up again we can fix it then!
