### ISSUE TITLE
stb_vorbis.c: Logic error Dereference of undefined pointer value

### ISSUE THREAD

**Issue by Martinfx** [nothings/stb#581]
Hi , scan-build reported on line 2224 reported :  Dereference of undefined pointer value
`part_classdata[j][class_set] = r->classdata[temp];`

**Comment by rygorous** [comment]
I know this is a really late response (both Sean and me have been busy with other things), but could you give us a bit more detail?

**Comment by Martinfx** [comment]
Hello rygorous, this it was only report from static analyze

**Comment by rygorous** [comment]
There's nothing wrong with this that I can see. Looks like a false positive because whatever static analyzer you're using doesn't expand the DECODE macro to see that it's what's initializing `temp`.
