### ISSUE TITLE
[BUG]8-bit bitmap image is read as 24-bit 

### ISSUE THREAD

**Issue by DaneSpiritGOD** [nothings/stb#584]
```
int x, y, n;
uint8_t *data = stbi_load(pre->fullPath, &x, &y, &n, 0);
```
after run,`n` is 3,but actually `n` is 1!

**Comment by zao** [comment]
As per https://github.com/nothings/stb/blob/master/stb_image.h#L160 all BMPs are depalletized into RGB.
The number of output channels depends on the number of channels you ask for.
If you ask for 3 or 4 channels, you get that many channels. If you ask for fewer, it will post-convert. If you ask for 0 you get either 3 or 4 based on if the image has alpha.
