### ISSUE TITLE
stb_image: Length of data

### ISSUE THREAD

**Issue by codekrafter** [nothings/stb#587]
I am trying to integrate stb_image into my project, but I need to serialize the data. I have looked and I have not been able to find a way to get the length of the data. Any help would be appreciated!

**Comment by nothings** [comment]
You are trying to serialize the compressed data or the decoded data?

The stb_image docs at the top are very explicit about the size of the decoded data--it is w*h*n bytes.

**Comment by codekrafter** [comment]
Thank you, I was doing sizeof(data)*w*h*n. I am serializing the data that stbi_load generates. I am still working out he kinks of the system, but I can post on the forums for the serialization library. Thanks for the quick reply

**Comment by zao** [comment]
Please note that `sizeof` a pointer is a compile-time quantity indicating how many bytes of storage a pointer takes, it has nothing to do with what it points.

I would like to elaborate on that stb's comment refers to the size if you use the 8-bit interface where each component is a byte each. If you use the HDR interface that gets you floating point values, you have `w*h` pixels, each with `n` channels of `float` type, which unsurprisingly are `sizeof(float)` big.
