### ISSUE TITLE
stb_truetype: Glyph placement weird for certain characters

### ISSUE THREAD

**Issue by dvadura1** [nothings/stb#589]
Hi, I am using this library to layout and render text with OpenGL. From a simple string, we iterate over the characters, and using `stbtt_GetGlyphBox` generate quad meshes next to each other. The problem I have (I tried few different fonts and it is the same for each), is with narrow characters like "i", "j".

Here is what the string looks like with SDF textures generated using stb as well (without using sdf shader):
![screen shot 2018-04-03 at 11 18 24](https://user-images.githubusercontent.com/3251922/38240774-d3f8f640-3730-11e8-8724-c48bc8243c5a.png)
You can see how the "i" and "j" are stretched. Here is the code I am using to generate the quads:

    int x0, x1, y0, y1;
    stbtt_GetGlyphBox(font_->getFontInfo(), glyphIndex, &x0, &y0, &x1, &y1);

    float left = x0 * scaleFactor_;
    float right = x1 * scaleFactor_;
    float top = y1 * scaleFactor_;
    float bottom = y0 * scaleFactor_;

    glyphBounds_.emplace_back(Rectangle<float>(cursor.x + left, cursor.y - top, right - left, top - bottom));

The cursor is advanced by the advance from `stbtt_GetGlyphHMetrics` after every character.

**Comment by nothings** [comment]
Don't use stbtt_GetGlyphBox to generate the quads. The function you're calling to generate the SDF returns an xoff, yoff, width, height (effectively x0,y0, x1-x0, y1-y0); you must use those.

**Comment by dvadura1** [comment]
@nothings thanks, you are right, that immediately fixed the sizing problem. I also had to scale the bounds returned by `stbtt_GetGlyphBox`, because I generate the SDF textures with constant scale, but use them for labels of different sizes.

**Comment by nothings** [comment]
Just to be clear why this happens: the SDF computation (and the regular rendering) returns a bitmap, which is a grid of pixels. This grid of pixels has an *integer* dimensions. Therefore, it's not the same size as scaled GetGlyphBox, which is not snapped to integers. Instead, it's slightly larger. (Also, the SDF bitmap has extra padding if you request it, which is not included in GetGlyphBox.)
