### ISSUE TITLE
spelling error

### ISSUE THREAD

**Issue by martingronlund** [nothings/stb#590]
https://github.com/nothings/stb/blob/master/stb_voxel_render.h#L1867

`float`?

**Comment by zao** [comment]
`flat` is an [interpolation qualifier](https://www.khronos.org/opengl/wiki/Type_Qualifier_(GLSL)#Interpolation_qualifiers) to indicate that the value should not be interpolated between the vertices of the primitive, but instead taken verbatim from the provoking vertex.
