### ISSUE TITLE
Image Resize Speed

### ISSUE THREAD

**Issue by zjxeditor** [nothings/stb#595]
Hi, I am use the image resize module. It works fine, bu the speed is pretty slow (compared with OpenCV). I know that there is no any SSE and multi thread optimization. If I want to speed it up, what can I do except lots of source code modification ?

**Comment by nothings** [comment]
You can use multiple threads on your side and have each thread do part of the resize. Beyond that is lots of source code modification.

**Comment by zjxeditor** [comment]
Fine, I will dive into it.

**Comment by rygorous** [comment]
Closing this since it seems to be resolved for the original poster and "stb_image_resize could be way faster if it was written completely differently", while true, is not exactly immediately actionable.

(We could reopen this later and look into optimizing the resizing kernels, akin to the stb_image JPEG/PNG decoder optimizations a few years ago, if there's demand at some point in the future.)

**Comment by ozkanonur** [comment]
I also have not good performance on resizing images @nothings 

Function:
``` C
void JpgResizer(int out_w, int out_h)
{
    unsigned char *input_pixels, *output_pixels;
    int w, h, n;

    input_pixels = stbi_load("img.jpg", &w, &h, &n, 0);
    output_pixels = (unsigned char *)malloc(out_w * out_h * n);

    stbir_resize_uint8(input_pixels, w, h, 0, output_pixels, out_w, out_h, 0, n);
    stbi_write_jpg("output.jpg", out_w, out_h, n, output_pixels, 0);
}
```

Benchmark results on resizing 2048x1235 jpg to 6000x6000 on 3700x CPU
```
index % time    self  children    called     name
                0.00    2.94       1/1           main [2]
[1]     99.7    0.00    2.94       1         JpgResizer [1]
                0.00    1.40       1/1           stbi_write_jpg [3]
                0.00    1.39       1/1           stbir_resize_uint8 [8]
                0.00    0.15       1/1           stbi_load [21]
```

Looks like stbi_write_jpg and stbir_resize_uint8 take a lot of time. Is there anything I need to add/change to improve the performance of this function?

**Comment by nothings** [comment]
no. there is a full rewrite in progress, but with no known release date.

**Comment by jinfagang** [comment]
@nothings hello, does it released yet?

**Comment by nothings** [comment]
No, it is very nearly done but we have to get the finishing touches right.

**Comment by jinfagang** [comment]
thank u, any eta approximately?

**Comment by mr-sihc** [comment]
@nothings how far is it now? eta?

**Comment by rygorous** [comment]
No ETA. It'll release when it releases.

**Comment by nothings** [comment]
It is ready for release, I just have to release it!
