### ISSUE TITLE
stb_truetype ascent problem

### ISSUE THREAD

**Issue by lh123** [nothings/stb#601]
The **ascent** value obtained in `stbtt_GetFontVMetrics ` seems to be wrong

here is my code
```c++
struct FrontGlyph {
    float scale;
    
    int ascent;
    int descent;
    int lineGap;
};
.....

.....
stbtt_InitFont(frontInfo, frontBuffer, stbtt_GetFontOffsetForIndex(frontBuffer, 0));

stbtt_GetFontVMetrics(frontInfo, &glyph.ascent, &glyph.descent, &glyph.lineGap);
glyph.scale = stbtt_ScaleForPixelHeight(frontInfo, DEFAULT_FONT_SIZE);

glyph.ascent *= glyph.scale;
glyph.descent *= glyph.scale;
glyph.lineGap *= glyph.scale;
.....

.....
drawLine(x, y, x + 300, y, color); //baseLine
drawLine(x, y - glyph.ascent, x + 300, y - glyph.ascent, color);//ascent
drawLine(x, y - glyph.descent, x + 300, y - glyph.descent, color);//descent
.....
```
result:
![image](https://user-images.githubusercontent.com/10697249/39424266-5b5464f8-4ca8-11e8-8694-844a3a43992a.png)
![image](https://user-images.githubusercontent.com/10697249/39424536-c58ca24e-4ca9-11e8-8be0-baa5c127e24f.png)

**Comment by nothings** [comment]
There may be some other character, for example try the | character.

Technically, the ascent value is defined by the font file. It's just whatever the font file has in there. If the value isn't useful to you, don't use it!

stb_truetype just returns the value defined in this table: https://developer.apple.com/fonts/TrueType-Reference-Manual/RM06/Chap6hhea.html

**Comment by nothings** [comment]
I have two answers for you. Read both of them. Do not reply unless you have read both of them. They follow after this message.

**Comment by nothings** [comment]
1. Reconsider what I was trying to communicate by saying "for example".

2. Read everything else I wrote in my original response to you after "Technically".

**Comment by lh123** [comment]
@nothings 
Thank you for your reminder.

the definition of ascent.
> The values for ascent, descent and lineGap represent the design intentions of the font's creator rather than any computed value.

When I finished reading it, I knew I should use `stbtt_GetGlyphBitmapBox` to get accurate font height.

**Comment by nothings** [comment]
You can try [```stbtt_GetFontBoundingBox```](https://github.com/nothings/stb/blob/master/stb_truetype.h#L770) but again these are vaues straight out of the font, so it's possible (but I think less likely) that there are fonts for which this is incorrect.
