### ISSUE TITLE
write_hdr row calculation causing crash

### ISSUE THREAD

**Issue by oconnorkg** [nothings/stb#602]
Line 697 of std_image_write.h has a typo:-
`stbiw__write_hdr_scanline(s, x, comp, scratch, data + comp*x*(stbi__flip_vertically_on_write ? y-1-i : i)*x);`

Removing the *x at the end of the line fixes it.

**Comment by tviksand** [comment]
Should be fixed in pullreq #604

**Comment by rygorous** [comment]
Duplicate of #567.
