### ISSUE TITLE
stb_load_from_memory does not load images correctly on GCC trunk with -O3

### ISSUE THREAD

**Issue by rHermes** [nothings/stb#603]
I have had some problems with stb_image.h when compiling with -O3 with the latest version of GCC.

Here is trunk with -O3: https://wandbox.org/permlink/2IlawjpgS4alPsVv

The output is:
```
WxHxN: 120 90 3
Hash for string was: 9417833158581383639
```

Here is trunk with -O2: https://wandbox.org/permlink/1Bfh7Fl32hn6qEsL

The output is:
```
WxHxN: 120 90 3
Hash for string was: 10820677751734165473
```

This is the output that you will get from every other recent version of GCC regardless of optimization level.

I am not good enough to reduce this further, but I have found a couple of things:

+ This does not happen for PNG files, only for jpeg.
+ Adding `-fno-tree-vectorize`  will result in the correct hash: https://wandbox.org/permlink/9CxZJG7fkCRZYPce

I am not sure if this is a compiler error or not, I was hoping to get some help clarifying this point.

**Comment by nothings** [comment]
To clarify, JPEG does not define a bit-exact correct decoding, thus there is no "correct decoding" in the sense that a hash can verify. So it would be nice to know whether there is a visual difference between the two, or whether the difference is subtle and within tolerance.

That being said, I do believe the jpeg decoder is 100% integer and so *should* produce bit-exact results across all compilers and platforms, so this is probably a real issue. However, I have no way to test it, so somebody else will have to look into it.

**Comment by rHermes** [comment]
Hey!

There is indeed a visual difference, which is how I discovered this in the first place, the hash was just to "quantify" it.

Here is a sample of the visual difference: https://imgur.com/a/gJuNhsy

This kind of redshift happens to every image I try it on, but sometimes it appears in kind of different ways, but it's always a red distortion.

**Comment by nothings** [comment]
From the looks of that, I'd guess that the YCbCr-to-RGB conversion is being unrolled (for vectorization), and is broken except for the final, non-unrolled cleanup pixels.

What version of GCC are you using? 

I've put the above function into godbolt for GCC 7.3, and [I don't see any unrolling](https://godbolt.org/g/N7wx1U) there, so either that guess is wrong, or you're using a newer (unreleased?) version of GCC, presumably 8.x.

**Comment by rHermes** [comment]
I'm using a local build of GCC from the head of the SVN repository. The wandbox versions are using: `gcc HEAD 9.0.0 20180429 (experimental)` which you can see on the top left.

I updated the link you shared, to use the trunk build that I am using, and there is a difference there now: https://godbolt.org/g/LAUx38

If this unrolling is breaking the code is it a compiler error or something that hasn't been accounted for in the stb_image.h code?

**Comment by rygorous** [comment]
He said it was GCC trunk, i.e. some current unlabeled, unreleased dev
version.

This sounds like it should get reported to the GCC devs, not us!

**Comment by nothings** [comment]
Whoops, I don't speak open source release jargon, I just saw "latest version of GCC".

Anyway, @rHermes, while it could be our bug, if you're testing an unreleased compiler I would definitely tend to assume it's the compiler's bug and send it to them before sending it to us.
