### ISSUE TITLE
16 bit depth support for stbi_write_png

### ISSUE THREAD

**Issue by zrenegade** [nothings/stb#605]
Currently, stbi_write_png only supports 8 bit depths.

I didn't come across any open issues with regards to writing out to file. I saw the other issues on 16 bit depth for png image processing, but the issues or merge requests don't address adding support to writing out to file.

Let me know if I have missed something. I may try to add support for writing 16 bit depth.

**Comment by rygorous** [comment]
stb_image_write is only intended to be a quick way to get an image to disk in a format that is accepted by most image viewers.

If you want support for anything but 8-bit/channel formats, you're better off using something else.

**Comment by zrenegade** [comment]
Why would stb_image support 16 bit load but not write? I can understand it not being supported, but I am not sure why you would oppose support for it. This library is quickly becoming a standard for image processing.

**Comment by nothings** [comment]
`stb_image.h` and `stb_image_write.h` are two totally separate libraries, and are meant to serve different purposes. 

`stb_image.h` has evolved over time to be a serious image loading library (albeit one with somewhat limited image format support).

`stb_image_write.h` is meant to be a quick-and-dirty image writing library, nothing more. It is very limited in the formats it supports, and it doesn't necessarily do a very good job e.g. in terms of compression.

**Comment by kg** [comment]
Does this issue being closed mean that if I submitted a PR to add 16-bit png write support, it would be rejected? Just wondering

**Comment by nothings** [comment]
Correct. "If you want support for anything but 8-bit/channel formats, you're better off using something else" is our official stance.
