### ISSUE TITLE
[stb_image] Possible use of uninitialized memory

### ISSUE THREAD

**Issue by aheysse** [nothings/stb#608]
Within 
`load_jpeg_image`:

   // resample and color-convert
   {
      int k;
      unsigned int i,j;
      stbi_uc *output;
     ** stbi_uc *coutput[4]; **// <-- coutput is not defualt initialized

... starting line 3715 ...

            } else {
               stbi_uc *y = coutput[0]; // <-- coutput was never initialized here and is about to be derefed
               if (n == 1)
                  for (i=0; i < z->s->img_x; ++i) out[i] = y[i];
               else
                  for (i=0; i < z->s->img_x; ++i) *out++ = y[i], *out++ = 255;
            }

**Comment by nothings** [comment]
It's initialized on line 3635.

**Comment by aheysse** [comment]
@nothings Should have posted more info - oops. MSVC (15.6.4) warns: 
src-external\stbi\stb_image.h(3716): error C6001: Using uninitialized memory 'coutput'.

I've attached a min repro with the required MSVC build settings. I'd attempt to run on a version of MSVC >= 15.6.4. While making the min repro, I noticed there are other static code analysis warnings. 
[STBI.zip](https://github.com/nothings/stb/files/1985983/STBI.zip). In theory it could be a compiler bug, but I sort of doubt it.

**Comment by nothings** [comment]
Check if initializing coutput to { 0 } fixes it.

**Comment by nothings** [comment]
(PS: What do you mean by min repro? A minimal example that produces the error message, or a minimal example that crashes? The previous comment assumes you meant the errror message.)

**Comment by rsachetto** [comment]
> Check if initializing coutput to { 0 } fixes it.

I've downloaded the solution and, with VS 15.4.4, I can reproduce the Warning. Initializing with {0} creates another warning:

Warning	C6011	Dereferencing NULL pointer 'y'. 	STBI	d:\sache\downloads\stbi\stbi\stb_image.h	

> (PS: What do you mean by min repro? A minimal example that produces the error message, or a minimal example that crashes? The previous comment assumes you meant the errror message.)

I think it is a  A minimal example that produces the error message, as it is only a main with exit(0)

**Comment by nothings** [comment]
> Warning C6011 Dereferencing NULL pointer 'y'. STBI d:\sache\downloads\stbi\stbi\stb_image.h Line: 3718

I'll look through the code more carefully. Maybe it's a case that's broken but never been run in the wild. Or maybe it's just a bad false positive.

**Comment by nothings** [comment]
Not relevant as I don't have VS 2017 installed.

**Comment by rygorous** [comment]
Will fix in next release to initialize coutput first; this is trivial enough to not be worth doing any further fact-finding for. :)
