### ISSUE TITLE
Unused functions warning when STBI_ONLY_PNG

### ISSUE THREAD

**Issue by dp304** [nothings/stb#609]
Hi! When I #define STBI_ONLY_PNG, g++ 6.3.0 gives me warnings:

warning: ‘void stbi__float_postprocess(float*, int*, int*, int*, int)’ defined but not used [-Wunused-function]
warning: ‘void stbi__vertical_flip_slices(void*, int, int, int, int)’ defined but not used [-Wunused-function]
warning: ‘int stbi__sse2_available()’ defined but not used [-Wunused-function]

**Comment by nothings** [comment]
fixed in next release
