### ISSUE TITLE
stb_sprintf.h: return value not according to spec

### ISSUE THREAD

**Issue by Leandros** [nothings/stb#612]
While the standard `snprintf` returns the theoretical maximum length (without zero-terminator), even when not calling it with a `NULL`  buffer and `0` length, the stb implementation returns the actual length written into the buffer (without zero-terminator).

```
char buf[8];
int len = snprintf(buf, 8, "this string is too long");
assert(len == 23); /* length of the string, without zero-terminator */
len = stbsp_snprintf(buf, 8, "this string is too long");
assert(len == 23); /* will fail, len is 7 */
```

I'll look into submitting a fix later today. Should be relatively easy by tweaking the clamp callback.
Although, I'd like to have your input, since this is a breaking change, and if somebody is depending on this behavior, a change might break code.

**Comment by uucidl** [comment]
It seems stb_snprintf follows the linux kernel's scnprintf:
https://www.kernel.org/doc/htmldocs/kernel-api/API-scnprintf.html

**Comment by nothings** [comment]
That's not the same, as it doesn't have the NULL output case that returns the full length.

**Comment by ocornut** [comment]
(1) It is always possible to wrap the function into a helper that will do the clamping. Maybe a `stb_scnprintf()` could be provided that does exactly this?
(2) Standard behavior allows to implement a two-pass with alloc in-between. Which is common pattern BUT it completely defeats the benefit of using `stbsp_vsprintfcb()` which is arguably a better solution...
(3) I assume that the current behavior allowed for early out? (Haven't checked the code). However it feels particularly silly to rely on buffer-is-full early-out as an optimization.

My gut feeling would be to go for it for the sake of being standard + add comments and maybe extra entry point that does the clamping. Personally I always wrapped my snprintf into a wrapper that already did the clamping, to the point where I had completely forgot this wasn't the default.

**Comment by nothings** [comment]
Ok, @pervognsen points out that the C99 specified behavior is useful for the idiom: snprintf to stack buffer, if it doesn't fit snprintf to malloc(), as the common case only needs one call to snprintf, two for the fallback; whereas the current behavior requires 1/3 or 2/2. So probably going to merge the PR.

**Comment by namandixit** [comment]
Any idea if/when this PR will be merged? This behaviour is pretty crucial if one is trying to create a dynamically resizing `sprintf` using `stbsp_vsnprintf`.

**Comment by wojdyr** [comment]
FTR: it was merged and the return value is good as of today
