### ISSUE TITLE
[stb_image] -- ignoring failed malloc in stbi__gif_load_next

### ISSUE THREAD

**Issue by roboman2444** [nothings/stb#614]
Starting around line 6350 in stbi__gif_load_next

      g->out = (stbi_uc *) stbi__malloc(4 * g->w * g->h);
      g->background = (stbi_uc *) stbi__malloc(4 * g->w * g->h); 
      g->history = (stbi_uc *) stbi__malloc(g->w * g->h); 
      if (g->out == 0)                      return stbi__errpuc("outofmem", "Out of memory");

A maliciously crafted file can set a g->w and g->h such that the malloc for g->out is successful, but the mallocs for g->background and g->history are not. This results in the memsets a few lines down to segfault when they try to write to 0x00.

I've attached a file that does this on my test machine, generated by a fuzzer. In this example, g->w = 60555 and g->h = 38003, which results in the first malloc (to g->out) being around 8 GB, which works on my 16GB of ram, but the subsequent mallocs (8GB and 2GB) to fail.

![segfault](https://user-images.githubusercontent.com/3598431/40519192-44337312-5f8c-11e8-9068-6026768027ab.gif)

**Comment by rygorous** [comment]
PR #725 should address this, although now that I mention this, I don't see any checks on the image sizes either, and that's also wrong. Investigating.
