### ISSUE TITLE
Can I use stbi_load and stbi_loadf in multiple threads? 

### ISSUE THREAD

**Issue by NukeBird** [nothings/stb#616]
Need to load 6 .hdr images (6 faces of cubemap), 4 mb each
Can I do this asynchronously in multiple threads? Will this give me a speed gain?

What else can I do to speed up texture loading process?

P.S. I'm using Pixel Buffer Objects

**Comment by NukeBird** [comment]
And what if I'll read files in main thread, but in other threads images will be loaded from memory?

**Comment by nothings** [comment]
You should be able to load/decode the HDR images from/to memory asynchronously with stb_image without issue.

Whether this is the best performance possible I don't know; stb isn't generally focused on speed.

Issues with how to upload them to GL w/ multiple threads is outside of the scope of stb_image.
