### ISSUE TITLE
Wrong access to HDR images in stb_image_write

### ISSUE THREAD

**Issue by honzasp** [nothings/stb#619]
In `stbi_write_hdr_core`, when computing the offset for the current scanline in the call to `stbiw__write_hdr_scanline()`, the offset is incorrectly multiplied by `x` (the image width) twice, so the function will access invalid memory:

      stbiw__write_hdr_scanline(s, x, comp, scratch, data + comp*x*(stbi__flip_vertically_on_write ? y-1-i : i)*x);

should probably be

    stbiw__write_hdr_scanline(s, x, comp, scratch, data + comp*(stbi__flip_vertically_on_write ? y-1-i : i)*x);

**Comment by installgentoo** [comment]
Yes this is a bug that crashes the project, i just saw this very bug while debugging crash in this very header.

**Comment by zhabkab** [comment]
I also encountered this bug, but I found an older version of the lib had the correct code.  It seems like there was an extra multiplication which makes the offset far too large.

**Comment by rygorous** [comment]
Duplicate of #567.
