### ISSUE TITLE
stb_textedit.h: undo/redo after a 32 KB+ paste fail because undo record store sizes as 'short'

### ISSUE THREAD

**Issue by ocornut** [nothings/stb#620]
Hello,

**Problem**

Undo/redo tends to break severely when pasting 32 KB+, because the `insert_length`, `delete_length`  fields of StbUndoRecord are typed `short` (values becomes negative, general havoc occurs).

This is regardless of the value stored in `STB_TEXTEDIT_UNDOCHARCOUNT` (default=999). Also note that even with a small value, the code should in theory allow to do a large paste followed by an undo, since undo-ing an insertion doesn't consume characters in the undo_char buffer.

This is the current structure:
```
typedef struct
{
   // private data
   STB_TEXTEDIT_POSITIONTYPE  where;
   short           insert_length;
   short           delete_length;
   short           char_storage;
} StbUndoRecord;
```

- Both `insert_length` and `delete_length` could probably use `STB_TEXTEDIT_POSITIONTYPE`.

- `char_storage` in theory should be derived from the value of `STB_TEXTEDIT_UNDOCHARCOUNT`, which is probably doable with a `#if STB_TEXTEDIT_UNDOCHARCOUNT < 0x10000` block. Or it could be another define parameters e.g. `STB_TEXTEDIT_UNDOCHARPOSITIONTYPE` or just `int`.
Using `STB_TEXTEDIT_POSITIONTYPE` for `char_storage` would be misleading and wrong if `STB_TEXTEDIT_UNDOCHARCOUNT > 32KB` and `STB_TEXTEDIT_POSITIONTYPE == short` _however_ (a) this is going to be rare and (B) this wouldn't be a regression from the current version, so for simplicity maybe this would be the best solution.

- In StbUndoState, `undo_char_point`, `redo_char_point` should use the same type choosen for `char_storage`.

**Suggestion**

(Easy mode)
Use `STB_TEXTEDIT_POSITIONTYPE` for all four fields.

With default STB_TEXTEDIT_UNDOSTATECOUNT==99 we are taking saving ~594 bytes per instance, I think this is the sort of memory people can afford if they are going to be interactively editing text. If people care about that sort of memory they can still tweak values and/or limits active instances.

**Patch**

- Replace 3 types in `StbUndoRecord`: insert_length, delete_length, char_storage
- Replace 2 types in `StbUndoState`: undo_char_point, redo_char_point
- Search for cast to short (`(short)`) and replace with proper type, There are 8 of them in the code.

I'm not pushing for a PR because by the time a decision is taken on the type to use it should be faster for you to just apply the three steps above, but let me know if you would prefer a PR.

Thank you.

**Comment by nothings** [comment]
Hmm, I feel like if stb_textedit is being used for very large texts it might be worth reconsidering how all of this works. But in the short term I'd be fine with STB_TEXTEDIT_UNDOCHARPOSITIONTYPE being inferred from UNDOCHARCOUNT, or just using int.

I'm pretty slow at fixing stb libs these days, sorry.

**Comment by ocornut** [comment]
Thanks. I'll make a PR using STB_TEXTEDIT_POSITIONTYPE for insert_length, delete_length, and inferring STB_TEXTEDIT_UNDOCHARPOSITIONTYPE if not defined.

> might be worth reconsidering how all of this works

I agree. But to reduce pressure: the numbers I'm getting aren't too horrible. I'm testing on a 88 Kilobytes, 900 lines file right now, even with a pretty spiky profiler, all the cost involved are always <0.5 ms. This include my rendering code which needs to scan for selection begin/end to find their position, scan for text height, etc.. there's LOTS of waste. So even with all those sub-par searches running on when interaction happens (both on stb_textedit side and my side), the application is still usable enough. 
I'm mostly in there to get the undo/redo fixed because this is more problematic than the perf hit which the user can understand.

![image](https://user-images.githubusercontent.com/8225057/40996814-1787d044-6903-11e8-9538-cbc38bc1d99e.png)

(No worry at all, I really appreciate your support. Take it easy and thanks again!)
