### ISSUE TITLE
HDR image is too large

### ISSUE THREAD

**Issue by Ardook** [nothings/stb#627]
Hi,
stb doesn't support 16k or larger images (16384x8192) due to int operation overflow?  Am I correct?  Is there a plan to support such large images?

Thanks,
Ardavan

**Comment by nothings** [comment]
We could possibly support them on 64-bit platforms, but there's simply not enough memory on 32-bit platforms for such a large image.

**Comment by Ardook** [comment]
Ah, I see.  Thank you very much for your quick response.
