### ISSUE TITLE
stb_sprintf: Wrong output for size_t types on 32bit Linux

### ISSUE THREAD

**Issue by jspohr** [nothings/stb#632]
- GCC 5.4.0 on Linux (Ubuntu 64bit)
- building with -m32 to i386 target
- formatting the content of a size_t variable using "%jd" prints the correct value.
- printing two size_t variables in one call prints incorrect values.

Repro case:
```
#include <stddef.h>
#include <stdio.h>
#define STB_SPRINTF_IMPLEMENTATION
#include "stb_sprintf.h"

int main() {
  size_t s, t;
  char buf[64];

  stbsp_snprintf(buf, sizeof(buf), "sizeof(size_t) == %jd", sizeof(s));
  puts(buf);

  s = 1;
  t = 1;
  stbsp_snprintf(buf, sizeof(buf), "%jd == 1", s);
  puts(buf);
  stbsp_snprintf(buf, sizeof(buf), "%jd == %jd == 1", s, t);
  puts(buf);
  return 0;
}
```

Built with `gcc -m64 -o test test.c`, it yields the expected output:
```
sizeof(size_t) == 8
1 == 1
1 == 1 == 1
```

However, when building for 32bit with `gcc -m32 -o test test.c`, the pair of size_t values are not printed correctly:
```
sizeof(size_t) == 4
1 == 1
4294967297 == 577826199716233280 == 1
```
It gets the value right when printing `sizeof(s)` or just a single size_t, but not when passing two local variables.

EDIT: Just verified that the bug exists on Win32, too. Using MSC 18.0 (180040629) which comes with Visual Studio 2013.

**Comment by stefano-zanotti-88** [comment]
I've submitted a pull request with a fix for this (https://github.com/nothings/stb/pull/633)

Note that you should use the 'z' modifier for size_t; 'j' is for intmax_t/uintmax_t

**Comment by rygorous** [comment]
This was fixed in 2019.
