### ISSUE TITLE
Dead link to stua documentation

### ISSUE THREAD

**Issue by jameswilddev** [nothings/stb#634]
There's a link to documentation for stua, but it seems that the corresponding page (http://nothings.org/stb/stb_stua.html) no longer exists:

https://github.com/nothings/stb/blob/e6afb9cbae4064da8c3e69af3ff5c4629579c1d2/stb.h#L13021

**Comment by nothings** [comment]
It's in the "abandoned" subdirectory of that link, because Stua is dead, long dead. It will be deleted from stb.h soonish.

**Comment by nothings** [comment]
Leaving this open so I remember to clean it up.

**Comment by rygorous** [comment]
stb.h is itself deprecated at this point, but I also followed through and removed the Stua portion entirely, since it's been orphaned and unsupported for a good time longer than stb.h itself.
