### ISSUE TITLE
Can this image library read and write jpg and jpeg formats?

### ISSUE THREAD

**Issue by ArionTT** [nothings/stb#636]
I want to load and write a jpg or jpeg format image on my project.
I found the line:

stb_image_write.h | 1.09 | graphics | 1568 | image writing to disk: PNG, TGA, BMP
-- | -- | -- | -- | --

You didn't write the jpg format upon that. 
Does stb_image not support to write a jpeg file?

**Comment by zao** [comment]
That list is incomplete, the source claims it supports PNG, TGA, BMP, JPG and HDR.
https://github.com/nothings/stb/blob/master/stb_image_write.h#L43-L49

```c
/*
   There are five functions, one for each image file format:
     int stbi_write_png(char const *filename, int w, int h, int comp, const void *data, int stride_in_bytes);
     int stbi_write_bmp(char const *filename, int w, int h, int comp, const void *data);
     int stbi_write_tga(char const *filename, int w, int h, int comp, const void *data);
     int stbi_write_jpg(char const *filename, int w, int h, int comp, const void *data, int quality);
     int stbi_write_hdr(char const *filename, int w, int h, int comp, const float *data);
*/
```

**Comment by ArionTT** [comment]
Thank you!
