### ISSUE TITLE
stb_image_write.h C89 warning

### ISSUE THREAD

**Issue by ghost** [nothings/stb#641]
trying to conform to C89, I get
`initializer element is not computable at load time`
for
`const unsigned short EOB[2] = { HTAC[0x00][0], HTAC[0x00][1] };`
and similar.

Assigning EOB[0] EOB[1] later is forbidden, because of EOB[] being const.
So... just remove const?
I don't understand the code enough to know whether that is safe to do or not.

**Comment by jarikomppa** [comment]
Not knowing the actual context, I believe removing "const" is always safe,
from compiling point of view.
