### ISSUE TITLE
Uninitialized pointer may lead to compiler error

### ISSUE THREAD

**Issue by XZiar** [nothings/stb#643]
https://github.com/nothings/stb/blob/e6afb9cbae4064da8c3e69af3ff5c4629579c1d2/stb_dxt.h#L315

These pointers should be initialized with NULL.
Although they will definitely be assigned later, but some compiler are not clever enough (MSVC(VS2017.8) complains about that in W4 mode)

**Comment by mackron** [comment]
Yep, this is also affecting me. Compiler errors (not warnings) when compiling with latest MSVC. Just initializing these to NULL will clean this up.

**Comment by rygorous** [comment]
Will get fixed in next release.

**Comment by rygorous** [comment]
Fixed as part of the fix for #1117, is in the dev branch, will be in the next release.
