### ISSUE TITLE
Move token's enum of stb_c_lexer.h to the headers

### ISSUE THREAD

**Issue by Breush** [nothings/stb#647]
Currently the enum defining all tokens (like CLEX_id) is only visible if STB_C_LEXER_IMPLEMENTATION is defined. Thus requiring the implementation to use the result of `stb_c_lexer_get_token`.

**Comment by nothings** [comment]
Looks like you are correct. I wonder what I was thinking.

**Comment by Breush** [comment]
@nothings Do you want a small PR?

**Comment by rygorous** [comment]
Fix for this is now pushed to the dev branch, although FWIW you still need every place that includes stb_c_lexer.h to agree on what the values for the config flags are, so any reasonable use case I can think of for this still requires you to wrap stb_c_lexer.h in your own project in some way.

Anyway, will be in the next release.
