### ISSUE TITLE
stbi__de_iphone_flag   default value is opposite with comment

### ISSUE THREAD

**Issue by stanley0614** [nothings/stb#651]
I found a bug in the file stb_image.h
line:255~262, the comment said: "By default we convert iphone-formatted PNGs back to RGB ...You can disable this conversion by by calling stbi_convert_iphone_png_to_rgb(0)".  the means the default value for  stbi__de_iphone_flag   is  1;
but in the line 4674, the default value is 0.  in iphone for pngs, if you want convert pngs from BGR to RGB you must do: stbi_convert_iphone_png_to_rgb(1)

so which is right. the comment or the source code?

**Comment by nothings** [comment]
I would guess the source code is correct. I probably change it at some point do to it causing problems, and forgot to change the comment.

**Comment by stanley0614** [comment]
@nothings I see ,thank you for replying!  maybe you can add comments for the reason of changing!

**Comment by rygorous** [comment]
This if fixed in the dev branch and will be in the next release.
