### ISSUE TITLE
Calculus of scanline is multiplying X twice

### ISSUE THREAD

**Issue by ignotion** [nothings/stb#655]
https://github.com/nothings/stb/blob/e6afb9cbae4064da8c3e69af3ff5c4629579c1d2/stb_image_write.h#L697

If what's pretended is going to the scanline i, that sentence is mutiplying twice by X so it goes rapidly out of rance, if I'm correct it should be:

comp*x*(stbi__flip_vertically_on_write ? y-1-i : i)
size of pixel * pixels on X * i [or y-1-i]

**Comment by LysanderGG** [comment]
See PR #585

**Comment by rygorous** [comment]
Duplicate of #567.
