### ISSUE TITLE
stb_image_write: support for RGB 565 in stbi_write_png 

### ISSUE THREAD

**Issue by Cpasjuste** [nothings/stb#658]
Hi,

It seems "stbi_write_png" does not support RGB 565 (component=3, bpp=2), or maybe i'm doing something wrong. It would be great to get support for that, as it work nice for my other needs.

**Comment by rygorous** [comment]
The PNG format itself does not support RGB 565 pixels directly. You would end up having to convert the values to 8 bits/channel truecolor anyway.

stb_image and stb_image_write very intentionally stick with a very small number of pixel formats (primarily 8-bit channel RGB and RGBA) to keep the API and implementation simple. If you want a different format, you'll have to write some (simple) conversion code yourself.
