### ISSUE TITLE
stb_image_write - Additional PNG chunks?

### ISSUE THREAD

**Issue by raysan5** [nothings/stb#671]
I noticed that saved PNGs just include the basic header chunks: `IHDR`, `IDAT`, `IEND`. 

For most of the cases, that should be enough but just found a situation where I needed an additional `pHYs` chunk to be able to print (on paper) the generated PNG; printing didn't work without that chunk.

Would it be possible to add some mechanism to define (or add manually) additional chunks?

**Comment by rygorous** [comment]
That's really out of scope for stb_image_write.

Support for "special" features of the various file formats adds complications to the API; in stb_image_write, we only do so where it really is necessary to provide a sane implementation (like the `quality` setting for JPEG), and several of the stb libraries (stb_image and stb_image_write most of all) are currently suffering from having too many random bolted-on pieces of functionality that were submitted by well-meaning contributors over the last 10 years.

Individually, each such feature is not a big deal, but collectively, the scope creep and profusion of special cases and compile-time features makes the code harder to use and maintain, which is defeating the purpose of these libraries.

It sounds like your use case might be better served by post-processing the generated PNGs using a tool like ImageMagick `convert`' using the `-density` option: https://imagemagick.org/script/command-line-options.php#density

**Comment by raysan5** [comment]
Agree. I understand is a specific use case and it's out of scope. Thanks for the answer! :)
