### ISSUE TITLE
stb_image_write: Documentation incomplete

### ISSUE THREAD

**Issue by WurmD** [nothings/stb#681]
Comments in stb_image_write.h, namely about stbi_write_png, do not specify the pixel order (if it's row major or collumn major) nor the color order of a pixel (ARGB, or ABGR)

This is useful for developers taking image data not loaded with stb_image, that would like to use stb_image_write.

**Comment by rygorous** [comment]
They do: https://github.com/nothings/stb/blob/314d0a6f9af5af27e585336eecea333e95c5a2d8/stb_image_write.h#L79-L86

I don't see how much more explicit this could be.
