### ISSUE TITLE
iPhone load png (not compressed) won't convert BGRA to RGBA 

### ISSUE THREAD

**Issue by LinBinghe** [nothings/stb#684]
Load a png without compress, then won't go the STBI__PNG_TYPE('C','g','B','I') in stbi__parse_png_file，put the result pixels to OpenGL Texture，will found it is not RGBA

**Comment by technosaurus** [comment]
I'm not clear what this means.  Can you clarify?

**Comment by nothings** [comment]
I think the report is saying that there are some iphone images with the CgBI tag in them that are still ARGB not RGBA, so they don't get converted properly.

But without any info on how to detect those files, or without an example file, there's nothing we can do with this bug report.

I'm also not super-thrilled with the iPhone support in hindsight and wonder if we should just remove it from stb_image entirely.

**Comment by rygorous** [comment]
I think the original bug description is saying that the file does _not_ have the CgBI in it ("won't go the CgBI") but is somehow still not RGBA, but anyway, we asked for more information and got nothing in 2 years, so I'm closing this. If someone runs into this issues with a better description of what's going on or, preferably, an example file, we can have a look.
