### ISSUE TITLE
error in assigneing rgb ==> when you assign red to 255 ...it actually assign it to 254 ... and same as to green and blue

### ISSUE THREAD

**Issue by hhhh1566446574567654564** [nothings/stb#685]
//just assigning red channel to 255

#include <stdint.h>
#include<iostream>

#define STB_IMAGE_WRITE_IMPLEMENTATION
#include "stb/stb_image_write.h"

#define CHANNEL_NUM 3
#define rgb_image(i,j,k) *(rgb_image+i*(width*CHANNEL_NUM)+j*CHANNEL_NUM+k)

using namespace std;
int main() {
    int width = 300; 
    int height = 500;

    //uint8_t* rgb_image;
    //rgb_image = (uint8_t*)malloc(width*height*CHANNEL_NUM);
    //rgb_image = new uint8_t[width*height*CHANNEL_NUM];
    unsigned char* rgb_image;
    rgb_image = new unsigned char[width*height*CHANNEL_NUM]; 

    //initialize image with zeros
    for(int i=0;i<height;i++)
    	for(int j=0;j<width;j++)
    		//for(int k=0;k<3;k++)
    			rgb_image(i,j,0)=255;

    // Write your code to populate rgb_image here
	/*for(int i=0;i<height;i++)
    	for(int j=0;j<width;j++)
    		for(int k=0;k<3;k++)
    			rgb_image(i,j,k)=255;
    			//rgb_image(i,j,2)=255;*/

   

    stbi_write_jpg("image.jpg", width, height, CHANNEL_NUM, rgb_image, width*CHANNEL_NUM);
    delete [] rgb_image;
    return 0;
}

**Comment by nothings** [comment]
JPEG is a lossy image format. You do not get back the exact pixel values you put in, only an approximation that looks approximately the same. Save as PNG if you want the exact pixel values to be stored.
