### ISSUE TITLE
SSE2 Compilation errors 

### ISSUE THREAD

**Issue by BryceMehring** [nothings/stb#69]
I get the following error when I try to build stb_image from the current master(a7c8694d69da57b6d427efddd15992e257f0c179) with MinGW-w64:
```
/usr/lib/gcc/i686-w64-mingw32/4.8/include/emmintrin.h:31:3: error: #error "SSE2 instruction set not enabled" 
```

**Comment by nothings** [comment]
Fixed in 2.01
