### ISSUE TITLE
Precalculate Atlas Size

### ISSUE THREAD

**Issue by rebirth123** [nothings/stb#693]
I'm using the good packing features of stb_truetype and stb_rect_pack to build a texture atlas and have cached all the metric data and kerning into my own structures to save to binary (it all works nice and fast).  The problem I am having is that you have to pass the atlas size and create the bitmap before packing, which results in the final image either being too small or too big.  I was thinking multiple packing passes will be required to try and find the optimal dimensions, but I don't know how to go about that without scanning each row/column in the final image.  Is there no built in method to help me achieve an optimally sized packed atlas file?  I don't mind a speed penalty because I only plan on importing the TTF files once and then use my own rolled up binary format.

P.S. Sorry if this isn't so much as an issue (it isn't a bug), but I can't find any information on this.

**Comment by rebirth123** [comment]
Thanks.  The following works reasonably OK for a tight fitting atlas image.
```
int result = 0;
while (result != 1) {
	bitmap.resize(width * height);
	if (stbtt_PackBegin(&PC, &bitmap[0], width, height, 0, 1, NULL)) {
		stbtt_PackSetOversampling(&PC, 1, 1);
		result = stbtt_PackFontRange(&PC, ttf.data(), 0, fontSize, charStart, charCount, &chardata[0]);
		stbtt_PackEnd(&PC);
		if (result != 1) {
			width += 16;
			height += 16;
		}
	}
	else {
		return false;
	}
}
```

**Comment by nothings** [comment]
If you really want to minimize it, you might try to find a better rectangle packer.
