### ISSUE TITLE
3d image resize

### ISSUE THREAD

**Issue by malytomas** [nothings/stb#694]
The general version stbir_resize has separate filters for each axis. Could you clarify which filters are separable? Would using the function for 3D images (in two passes) produce correct results? Or would you consider adding such functionality?
Thanks

**Comment by nothings** [comment]
All filters are applied to axes separately, so they're all seperable in that sense. If you mean which ones create an isotropic final sampling, I would assume none of them, but I'm not an expert.

I think handling 3D images is outside the scope of what we want it to be.

**Comment by malytomas** [comment]
I understand. Thanks.
