### ISSUE TITLE
stb_image Load from memory issue

### ISSUE THREAD

**Issue by TheRealSmolt** [nothings/stb#696]
I know there are plenty of other issues about this, but the ones I've looked at are about color or something else. My issue is that the stbi_load_from_memory method is returning null.

Basically, I wrote a C++ program to convert files into char arrays to "embed" them into my executable. This is what I did for my images. I'm pretty sure that it converted/loaded it properly because the generated header file has a char array some 25,000 characters in length.

When I call stbi_load_from_memory (like I would stbi_load since the parameters in the header file are the same) it just returns NULL.

This is my first time trying to work with stb_image and I'm really confused. Thanks in advance.

**Comment by nothings** [comment]
If the image loads as a file with stbi_load but doesn't load with stbi_load_from_memory, you probably converted them to char arrays incorrectly.

You can check the string stbi__g_failure_reason to see what the error message is, but it probably won't be helpful.

**Comment by TheRealSmolt** [comment]
I tried it with stbi_load (which I didn't do because I've had trouble with it too in the past) and the image loaded fine. This means that my char array is incorrect, however, I use it for my shaders which work fine. I printed out the failure reason and it said: "expected marker." Thus my reading is incorrect. Thanks.
