### ISSUE TITLE
Problems with stbi_load

### ISSUE THREAD

**Issue by aleck099** [nothings/stb#700]
I am writing a c++ wrapper class for stb_image, and I met a problem.

```
class Image  {
	public:
	// constructor
	// will load an image using stbi_load and save the data in img_data
	Image(string path);
	Image(const Image &);
	Image(Image &&);
	// here, stbi_image_free will be called
	~Image();
	const unsigned char *getRawData() const;
	//...
	private:
	int iwidth;
	int iheight;
	int nChannels;
	unsigned char *img_data;
};
```

Yes, the class has a copy constructor.
I want to memcpy the data in img_data to a new object in the copy constructor, but I don't know the size of img_data because it is allocated by stbi_load.
Is there a way to know the size of the memory block?

**Comment by nothings** [comment]
width * height * channels bytes
