### ISSUE TITLE
Bugs in stb_rect_pack

### ISSUE THREAD

**Issue by vamalo** [nothings/stb#701]
I found a couple of bugs in stb_rect_pack:

399      // find first node that's admissible
400      while (tail->x < width) //FIXME: test whether tail is NULL
401         tail = tail->next;

412         y = stbrp__skyline_find_min_y(c, node, xpos, width, &waste);
413         if (y + height < c->height) { //FIXME: < should be <=
414            if (y <= best_y) {

**Comment by nothings** [comment]
What makes you think that first one is a bug? Have you seen it go wrong?

**Comment by vamalo** [comment]
Yes.  It causes an access violation when the rectangle width is too large to fit in the provided space.  In other words, the final value of tail->x in the linked list is still less than width.

**Comment by nothings** [comment]
Okay, I think the correct fix for the case you mention is to validate the rectangle vs maximum size outside that function, rather than insert an extra test in that loop.

**Comment by vamalo** [comment]
Alright.  By the way, I did a thorough stress test of stb_rect_pack using random rectangles.  I compared the result from stbrp_pack_rects() against a trivial solution that maintains the height at every integer and attempts to place each rectangle at every possible value of x.  Would you be interested in adding this stress test to your repository?  I can show you my code if you'd like.

**Comment by raysan5** [comment]
what a coincidence! just found the same issue yesterday! I was about to report it right now! :)

**Comment by rygorous** [comment]
Fixed in #722.
