### ISSUE TITLE
Confused about usage of stb_truetype

### ISSUE THREAD

**Issue by TooManyDots** [nothings/stb#702]
I am trying to understand how to use stb_truetype to render fonts.

I get the images just fine, but the horizontal advancement are always wrong ( I am guessing I use the api wrong).

This here is a, shortened, version of my creation of bitmap + metainformations

```
FILE* File = fopen("C:\\windows\\Fonts\\arial.ttf", "rb");
[...]
stbtt_fontinfo stbFont;
stbtt_InitFont(&stbFont, (u8*)FileContent, 0);
r32 stbScale = stbtt_ScaleForPixelHeight(&stbFont, 128);

const u32 StartCodePoint = '!';
const u32 EndCodePoint = 'z';
const u32 CodePointCount = 1 + EndCodePoint - StartCodePoint;
r32* HorizontalAdvance = malloc(sizeof(r32) * Font->CodePointCount * Font->CodePointCount));

//Get the image for every code-point we need
for(u32 CodePoint = StartCodePoint; CodePoint <= EndCodePoint; ++CodePoint) {
  s32 AdvanceWidth;
  stbtt_GetCodepointHMetrics(&stbFont, CodePoint, &AdvanceWidth, 0);
  
  s32 Width, Height;
  s32 xOffset, yOffset;
  u8* MonoBitmap = stbtt_GetCodepointBitmap(&stbFont, stbScale, stbScale, CodePoint, &Width, &Height, &xOffset, &yOffset);
  loaded_bitmap Bitmap = MakeEmptyBitmap(&TransientState->Arena, Width, Height);
  Bitmap->Memory = MonoBitmap;
  //Bitmap->AlignPercentage = {0.5f - ((r32)xOffset/(r32)Width), 0.5};
  //Bitmap->AlignPercentage = {(r32)xOffset /(r32)Width , 0.5f};

  //Kerning
  for(u32 PrevCodePoint = StartCodePoint; PrevCodePoint <= EndCodePoint; ++PrevCodePoint) {
    s32 Kerning = stbtt_GetCodepointKernAdvance(&stbFont, PrevCodePoint, CodePoint);
    HorizontalAdvance[PrevCodePoint*CodePointCount + CodePoint] = (stbScale * AdvanceWidth) + (stbScale * Kerning);
  }
}
```

If my understanding is correct all I have to do is `use stbtt_GetCodepointHMetrics` to get how far to advance horizontally + the kerning from `stbtt_GetCodepointKernAdvance` both scaled with `stbtt_ScaleForPixelHeight` ?

The problem is when, I go to render it loosk lke this

![fr](https://user-images.githubusercontent.com/35289254/52004862-82eadd00-24c8-11e9-8b03-00a0a2a748a0.png)

The vertical alignment is obviously wrong, because i have no code for it, but the space between the two letters is also way to big ( the kerning is 0 for those btw. ).

I wonder if I do my extraction using stb wrong, or if just my rendering is wrong ( or both ).

**Comment by nothings** [comment]
It's impossible for me to be 100% certain, but the extraction code looks reasonable.
