### ISSUE TITLE
stb_truetype 1.20 has new warnings

### ISSUE THREAD

**Issue by jamesdolan** [nothings/stb#707]
The comment block describing lines of code has some unintentional escape sequences that causes both Clang and GCC to throw different warnings. Both complain (with different warnings, the GCC one seems cant be disabled with a pragma for some reason) about the "Software rasterization" line where there are spaces after the backslash.

I suggest either replacing the escape characters with something else or putting non-whitespace after them to make the intentions clear.

```
// SOURCE STATISTICS (based on v0.6c, 2050 LOC)
//
//   Documentation & header file        520 LOC  \___ 660 LOC documentation
//   Sample code                        140 LOC  /
//   Truetype parsing                   620 LOC  ---- 620 LOC TrueType
//   Software rasterization             240 LOC  \                           
//   Curve tessellation                 120 LOC   \__ 550 LOC Bitmap creation
//   Bitmap management                  100 LOC   /
//   Baked bitmap interface              70 LOC  /
//   Font name matching & access        150 LOC  ---- 150 
//   C runtime library abstraction       60 LOC  ----  60
```

**Comment by rygorous** [comment]
Fixed in #721.
