### ISSUE TITLE
Fails to load JPEG

### ISSUE THREAD

**Issue by RainVector** [nothings/stb#709]
The image lib fails to load the following image:
![arm](https://user-images.githubusercontent.com/6712304/52712499-bef56600-2fcf-11e9-8a04-fad305618f0e.jpg)

**Comment by nothings** [comment]
Works for me.

Do other images work in your code? What version are you using?

**Comment by RainVector** [comment]
I use 2.20 `stb_imag.h`.
The source code of mine on Windows 10 Visual Studio 2015 is 
```
#define STB_IMAGE_IMPLEMENTATION
#include "stb_image.h"
#include <stdio.h>
#include <string>
int main()
{
	std::string filename = "../../picture/skin.jpg";
	int x, y, n;
	unsigned char* data = stbi_load(filename.c_str(), &x, &y, &n, 0);  // set breakpoint here
	printf("x: %d, y: %d, n: %d\n", x, y,n);
	stbi_image_free(data);
	return 0;
}
```
The data shows "invalid characters in string".
![wechat image_20190213211325](https://user-images.githubusercontent.com/6712304/52714192-37f6bc80-2fd4-11e9-975a-fbd7bf7297e3.png)

**Comment by zao** [comment]
@RainVector What you see is that the debugger is cautiously attempting to interpret the data as a text string for your convenience.

Actual success from `stbi_load` is determined by the return value. A null pointer indicates failure, a non-null pointer indicates success. The pointer points to densely packed pixels with the number of components you asked for, or in your case of passing 0, `n` components per pixel.

You can inspect your `x` and `y` variables for information about the dimensions of the loaded image.

Your screenshot shows the first two pixels of your image with RGB of (255, 255, 255) and (255, 255, 255).

**Comment by RainVector** [comment]
But when I try to use data as texture in my program:
```
glTexImage2D(GL_TEXTURE_2D, 0, GL_RGB, width, height, 0, GL_RGB, GL_UNSIGNED_BYTE, data);
```
I get an `access violation` error

![e](https://user-images.githubusercontent.com/6712304/52718767-24048800-2fdf-11e9-95d4-cefd556e2654.png)

**Comment by nothings** [comment]
You are probably using OpenGL incorrectly with images that aren't a multiple of 4 pixels wide. See #695.

**Comment by RainVector** [comment]
Thank you. I figure out where goes wrong.
```
unsigned char* data = stbi_load(filename.c_str(), &x, &y, &n, 4); // 0 -> 4
```
and 
```
glTexImage2D(GL_TEXTURE_2D, 0, GL_RGBA, width, height, 0, GL_RGBA, GL_UNSIGNED_BYTE, data); // GL_RGB-> GL_RGBA
```
