### ISSUE TITLE
Tonemapping

### ISSUE THREAD

**Issue by parasange** [nothings/stb#711]
Does stb_image.h already include any tonemapping method, after an image was loaded via stbi_loadf() (which returns 12 Bytes as RGB)?

**Comment by nothings** [comment]
No, it leaves the data untouched from the HDR format, presumably in the linear-light space it was stored as.

(If you load a low-dynamic range image like a JPG or 8-bit PNG, then it will attempt to linearize it using the documented gamma system, but if you want proper sRGB decoding you should load as 8-bit and convert yourself.)
