### ISSUE TITLE
stb_ds.h warning: ignoring return value of ‘realloc’, declared with attribute warn_unused_result

### ISSUE THREAD

**Issue by rsachetto** [nothings/stb#733]
When compiling stb_ds with gcc the compiler issues a warning: warning: ignoring return value of ‘realloc’, declared with attribute warn_unused_result [-Wunused-result]

One way to suppress this is to change the macro 

#define STBDS_FREE(x)  realloc(x,0) to 
#define STBDS_FREE(x)  if((void*)1==((void*)realloc(x,0))){;}

and change line 1450 in the function stbds_strreset to

STBDS_FREE(x) instead of using realloc(x,0);

I can make a pull request with this changes, but I am open an issue first to discuss if this code change 
is worth to include only to suppress some compiler warnings;

**Comment by nothings** [comment]
what about just
  #define STBDS_FREE(x) (void) realloc(x,0)
?

**Comment by rsachetto** [comment]
> what about just
> 
> ```
> #define STBDS_FREE(x) (void) realloc(x,0)
> ```
> ?

That was my first try. But it does not silence the warnings in the newer versions of gcc.

**Comment by nothings** [comment]
What warning does it give?

**Comment by rsachetto** [comment]
The same when using realloc(x,0)

**Comment by rsachetto** [comment]
I simpler way is to change the macro to:

#define STBDS_FREE(x)  if(realloc((x),0));

It works on gcc

**Comment by nothings** [comment]
using an if() like that in a macro breaks a following 'else'. embedding an else in the macro causes warnings in clang.

It looks like gcc has screwed the pooch on this, sigh. The best fix for now is to change STBDS_FREE to call stbds_free(p), and defined stbds_free to a function that calls realloc(p,0) and wraps it with whatever logic is necessary to prevent the warning. That way it's not macroified and avoids the macro issues.

**Comment by rsachetto** [comment]
I´ve tested this and seems to work

```
#define STBDS_FREE(x)  stbds_free((x))

static void stbds_free(void *a)
{
  //ignore realloc return value and avoid compiler warnings
  if(realloc(a,0));
}
```

**Comment by Manuzor** [comment]
Another way would be to define something like this:

```c
inline void stbds__ignore(...) { /* don't do anything here */ }
```

It can be used like this to quench that warning and is not subject to the same pitfalls as the `if(...);` solution:

```c
#define STBDS_FREE(x) stbds__ignore(realloc(x, 0))
```

This works for me at least for gcc 8.3.0. You could also use this in other situations than a void* return value.

BTW, on line 1444 realloc is used directly. This should probably use `STBDS_FREE(x)` instead of `realloc(x, 0)`.

**Comment by nothings** [comment]
`inline` isn't valid in pre-C99 C

**Comment by rsachetto** [comment]
This are my two suggestions to solve the problem:


```
#define STBDS_FREE(x)  stbds_free((x));

void stbds_free(void *a) {
    //ignore realloc return and silence compiler warnings
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wunused-result"
  (void) realloc(a,0);
  #pragma GCC diagnostic pop
}
```

or

```
#define STBDS_FREE(x)  stbds_free((x));
void stbds_free(void *a) {
  //ignore realloc return and silence compiler warnings
  if(realloc(a,0));
}

```

**Comment by nothings** [comment]
The latter is fine, as I tried to indicate with the thumbs-up.

The former is unacceptable, as it doesn't scale across large numbers of compilers.

**Comment by rsachetto** [comment]
I did not see the thumbs-up :). 

I´ve opened a Pull request to this issue. ( #735  )

**Comment by nothings** [comment]
This issue has been made irrelevant by the fact that using realloc() to free isn't cross-platform, so we got rid of that behavior entirely.
