### ISSUE TITLE
stb_textedit: Undo weirdness after failed paste

### ISSUE THREAD

**Issue by Unit2Ed** [nothings/stb#734]
We've noticed some weirdness caused by the undo_point being erroneously adjusted after a failed paste.

We believe this is happening because `stb_textedit_paste_internal` decrements `state->undostate.undo_point` if the paste fails, but the undo hadn't been created yet (contrary to the comment above the decrement). It looks like the undo it's trying to remove is the one created by `stb_text_makeundo_insert`, which won't have happened if the insertion failed.

This is the current version of `stb_textedit_paste_internal`:
```
// API paste: replace existing selection with passed-in text
static int stb_textedit_paste_internal(STB_TEXTEDIT_STRING *str, STB_TexteditState *state, STB_TEXTEDIT_CHARTYPE *text, int len)
{
   // if there's a selection, the paste should delete it
   stb_textedit_clamp(str, state);
   stb_textedit_delete_selection(str,state);
   // try to insert the characters
   if (STB_TEXTEDIT_INSERTCHARS(str, state->cursor, text, len)) {
      stb_text_makeundo_insert(state, state->cursor, len);
      state->cursor += len;
      state->has_preferred_x = 0;
      return 1;
   }
   // remove the undo since we didn't actually insert the characters
   if (state->undostate.undo_point)
      --state->undostate.undo_point;
   return 0;
}
```

We've fixed this locally by removing the decrement, but I wanted to check your thoughts on this.

EDIT:
Forgot to mention that we've seen a soft-lock caused by this too in the case where the undo_char buffer has been filled up followed by a failed paste. `stb_text_create_undo_record` will lock-up in this while loop because `stb_textedit_discard_undo` does nothing if `undo_point==0`, which can happen due to the erroneous decrement.

```
   // if we don't have enough free characters in the buffer, we have to make room
   while (state->undo_char_point + numchars > STB_TEXTEDIT_UNDOCHARCOUNT)
      stb_textedit_discard_undo(state);
```

**Comment by rygorous** [comment]
Fix for this is merged into dev branch, will be in the next release.
