### ISSUE TITLE
Don't lookup colour in palette

### ISSUE THREAD

**Issue by Danjb1** [nothings/stb#739]
I'd like to start by thanking you for your excellent project! Your _stb_image_ library is so easy to use, and you have done the game development community a great service.

---

Now, onto my slightly unconventional use-case. I am recreating an old game that relies on palette swapping, so I thought I'd follow the approach suggested [here](https://gamedev.stackexchange.com/a/43313/55129). Namely, I would like to supply a texture to OpenGL where each pixel is an 8-bit palette index, _not_ the actual colour.

I have a bunch of textures in indexed TGA format, and a 256-colour palette. However, when I load one of these textures, _stb_image_ does a palette lookup when loading each pixel, so the resulting pixel data contains the actual colours, and not the palette indices, as required.

Perhaps this is outside the scope of this library, in which case I will happily write my own solution. But what do you think of an option to disable palette lookups when loading a TGA image? Or is there, perhaps, a better way to do this?

**Example:**

    #define STBI_DISABLE_TGA_PALETTE_LOOKUP
    unsigned char *data = stbi_load("image.tga", &width, &height, &n, 0);
    // `data` contains a single 8-bit value per pixel, which is the palette index
    // `n` is 1

**Comment by nothings** [comment]
It's definitely outside the scope of this library.

Obviously for your own purposes you could make this change rather than rolling it from scratch, but maybe rolling it from scratch is easier, I don't know.

**Comment by bullno1** [comment]
I think you can write a shader for that to lookup color at render time instead.

**Comment by Danjb1** [comment]
@bullno1 That's my plan, but first I need to load the image data in such a way that it contains the palette indexes.
