### ISSUE TITLE
compile warnings in stb_image.h

### ISSUE THREAD

**Issue by baldurk** [nothings/stb#74]
In stb_image.h at the moment there's [a call directly to assert](https://github.com/nothings/stb/blob/master/stb_image.h#L4020) where the function isn't available if STBI_ASSERT is defined to something else before including.

There's also a warning generated by MSVC 2010 saying [this cast truncates a constant value](https://github.com/nothings/stb/blob/master/stb_image.h#L3014).

**Comment by nothings** [comment]
I fixed the former and made a guess at a portable fix for the latter (since signedness of char is implementation-defined).
