### ISSUE TITLE
Wrong usage of __STDC_WANT_SECURE_LIB__

### ISSUE THREAD

**Issue by XZiar** [nothings/stb#744]
https://github.com/nothings/stb/blob/2c2908f50515dcd939f24be261c3ccbcd277bb49/stb_image_write.h#L740-L743

According to [cppreference](https://en.cppreference.com/w/c/io/fprintf), it says:

> As with all bounds-checked functions, printf_s , fprintf_s, sprintf_s, and snprintf_s are only guaranteed to be available if \_\_STDC_LIB_EXT1\_\_ is defined by the implementation and if the user defines \_\_STDC_WANT_LIB_EXT1\_\_ to the integer constant 1 before including stdio.h.

So the existence of `__STDC_WANT_SECURE_LIB__` does not mean the existence of `sprintf_s`. For example, [GCC does not ship with `_s` functions](https://stackoverflow.com/questions/50724726/why-didnt-gcc-implement-s-functions/50724865#50724865)
It may be better replaced by `__STDC_LIB_EXT1__`.

The usage of `__STDC_WANT_SECURE_LIB__` also appeared in other files, but in another form:

https://github.com/nothings/stb/blob/2c2908f50515dcd939f24be261c3ccbcd277bb49/stb_ds.h#L1471-L1474

https://github.com/nothings/stb/blob/2c2908f50515dcd939f24be261c3ccbcd277bb49/stb_vorbis.c#L4995-L4998

https://github.com/nothings/stb/blob/2c2908f50515dcd939f24be261c3ccbcd277bb49/stb_tilemap_editor.h#L1960-L1966

But IMO, it's the `defined(_WIN32)` who plays the role.

**Comment by nothings** [comment]
Is there a specific bug? The use of "if defined(_WIN32) && defined(__STDC_WANT_SECURE_LIB__)" is specfically to deal with multiple versions of Visual Studio, some of which have _s functions and some don't. Those Visual Studio headers define the functions based on "__STDC_WANT_SECURE_LIB__" not "__STDC_LIB_EXT1__".

**Comment by XZiar** [comment]
I see.
But the `stb_image_write.h` is still buggy since it lacks `defined(_WIN32)`

**Comment by nothings** [comment]
Sure. Can you cut-and-paste the actual full list of warnings?

**Comment by XZiar** [comment]
Well, I defined `__STDC_WANT_SECURE_LIB__` in favor of `_s functions`, but GCC doesn't implement them.

> stb_image_write.h:741:13: error: ‘sprintf_s’ was not declared in this scope
>       len = sprintf_s(buffer, sizeof(buffer), "EXPOSURE=          1.0000000000000\n\n-Y %d +X %d\n", y, x);
>             ^~~~~~~~~
>stb_image_write.h:741:13: note: suggested alternative: ‘sprintf’
>       len = sprintf_s(buffer, sizeof(buffer), "EXPOSURE=          1.0000000000000\n\n-Y %d +X %d\n", y, x);
>             ^~~~~~~~~
>             sprintf

**Comment by XZiar** [comment]
It works well on my VS2017 and VS2019, but it does not work on GCC8 and Clang6.

Also, since usage of `STBI_MSC_SECURE_CRT` has been removed, these lines are better removed.
https://github.com/nothings/stb/blob/2c2908f50515dcd939f24be261c3ccbcd277bb49/stb_image_write.h#L13-L17

**Comment by nothings** [comment]
Yep, thanks.

**Comment by rygorous** [comment]
The fix for the issue in stb_image_write.h is now pushed in the dev branch, the rest requires no action. Will be in the next release.
