### ISSUE TITLE
stb_image.h: warning about unused parameter 'bpc'

### ISSUE THREAD

**Issue by BlackMATov** [nothings/stb#745]
https://github.com/nothings/stb/blob/2c2908f50515dcd939f24be261c3ccbcd277bb49/stb_image.h#L1004

it happens only with STBI_NO_PSD define of course

**Comment by BlackMATov** [comment]
> nothings reopened this 20 minutes ago

But... It's already fixed after merge. Why not close the task? :-)

**Comment by nothings** [comment]
oh, if it's fixed, absolutely! sometimes I get people deleting their old things that haven't been fixed for a long time and I assumed this was one of those. thanks for clarifying!
