### ISSUE TITLE
stb_image only loading 2 pixels

### ISSUE THREAD

**Issue by SoraKatadzuma** [nothings/stb#747]
*System:*

- Window 64 bit
- AMD Ryzen 5 2600x

*Problem:*
Attempting to load a png file of 32x32 pixels and only two pixels get loaded.

*Usage:*
```cpp
// Implementation file
#define STB_IMAGE_IMPLEMENTATION
#include <stb/stb_image.h>

// Usage file
int32_t width, height, channels;
uint8_t* data = stbi_load("res/images/test.png", &width, &height, &channels, STBI_rgb_alpha);
if (!data)
  std::cerr << "Failed to load texture, make sure you have the right path.\n";
else {
  const size_t length = sizeof(data);
  std::cout << "Length: " << length << std::endl;
  for (size_t index = 0; index < length; index += 4) {
    // prints out the pixels 4 at a time.
  }
}
```
*Outputs:*
```
Length: 8
58, 87, 39, 255
49, 85, 35, 255
```

Any logical reasons for why this may be happening?

**Comment by nothings** [comment]
sizeof(data) is not correct. please read the documentation.

**Comment by rygorous** [comment]
To elaborate a bit, `sizeof(data)` gives you the size of a `uint8_t *` (i.e. the size of a pointer to a `uint8_t`), which has absolutely nothing to do with the size of the image.

stb_image will return a pointer to an array of `width * height` pixels with the requested channel count, which in your case is 4, for a total of `width * height * 4` elements in the returned array.
