### ISSUE TITLE
stb_truetype: SVG support

### ISSUE THREAD

**Issue by chris-y** [nothings/stb#748]
Please can you add support for extracting SVG data from OpenType-SVG files.
I had a go at adding this myself but when I
```
t = stbtt__find_table(data, fontstart, "SVG ");
if (t) printf("off: %lx\n", ttULONG(data + t + 2));
```

The offset is always 0x0 (an illegal value), except in one font I found where it was 0xa.
For example, the Twitter Emoji font https://github.com/eosrei/twemoji-color-font/releases which definitely contains SVG font data gives me an illegal offset in the SVG table (edited; inserted wrong link originally).  otfcc https://github.com/caryll/otfcc shows the SVG data correctly.

**Comment by nothings** [comment]
Fixed by #750
