### ISSUE TITLE
Several memory leaks in "stb_vorbis.c"

### ISSUE THREAD

**Issue by BigJim** [nothings/stb#75]
First of all thanks for this great module and your other fine works.

My configuration: MS VS2013 w/STB_VORBIS_NO_STDIO & STB_VORBIS_NO_PUSHDATA_API
defined as I load my Oggs from a resource w/no streaming.

As I usually like to do with such algorithmic setups I tweaked stb_vorbis to use it's own private local heap with a HeapCreate() then I put macros to replace all malloc, realloc, and free() calls with HeapAlloc, HeapReAlloc, and HeapFree's respectively;
Added two methods, a "stb_vorbis_free_buffer(short *buffer);" to free up the buffer returned by "stb_vorbis_decode_memory", then after the Ogg has played a "stb_vorbis_heap_destroy()" calls "HeapDestroy" to remove this private heap.

Just to check, I run a two second Ogg and setup a mini-memory test setup looping HeapWalk() to count any unfreed blocks and sum up the bytes.
To my surprise my trace text: "Total 1094016 bytes leak from 101 unfreed blocks." The total is ∑(cbData + cbOverhead).

Now not really a problem for me since I destroy this heap after each play it mitigates any leaks, but not good if you are still using the default/main heap (loosing ~1mb each play).

I expanded my "poorman's" memory tracker by putting stubs around the HeapAlloc and HeapReAlloc to trace out the pointers, sizes, and source line #'s. Tried to trace it down for a few hours but the control flow in the inner decoding loops are not trivial.  
I see a few large blocks leaked and then a bunch of 128byte sized, then a large one (126992), then a string of 8 sized blocks..
Could be it's allocating a something twice, or just not freeing them in the end (almost the same but different). 

If you want I'll send you a text paste of the setup I'm using, and, or recommend you use some sort of memory tracer package.

Thanks,

**Comment by nothings** [comment]
which API function(s) are you going through? stb_vorbis_decode_memory?

**Comment by nothings** [comment]
Just to make sure, are you using 1.04, not some ancient version (version 1.00 fixed some memory leaks)?

**Comment by nothings** [comment]
Perhaps you didn't properly instrument setup_free or something related.

Anyway, this worked fine for me, using a lightly modified version to support the new functions at the end:

```
int main(int argc, char **argv)
{
   size_t memlen;
   unsigned char *mem = stb_fileu("c:/x/01.ogg", &memlen);
   int chan, samplerate;
   short *output;
   int samples = stb_vorbis_decode_memory(mem, memlen, &chan, &samplerate, &output);
   stb_vorbis_free(output);
   stb_vorbis_dumpmem();
   return 0;
}
```
so I'm closing it until there's some evidence this isn't an error on your side.

**Comment by BigJim** [comment]
Been meaning to get back to this for a small comment. Yea silly me didn't use the PROCESS_HEAP_ENTRY_BUSY flag.

Thanks again for all that you do.
Gave you a little donation.
