### ISSUE TITLE
can't load the png file

### ISSUE THREAD

**Issue by Jeff1996** [nothings/stb#752]
when i try to load a png file with the function "stbi_load" in a opengl project, it returns nothing. And i can make sure that the path of the image is right. what's more, the platform is win10, vs2017.

**Comment by nothings** [comment]
printf("%s\n", stbi_failure_reason());

**Comment by aribot-hrv** [comment]
I have same error with a big image of 17068x17068 with format 32 bits.
The error message is "too large". 
![tail_diffuse](https://user-images.githubusercontent.com/50961400/58269968-f3c04880-7d88-11e9-9a54-82ed4578d0c8.png)

**Comment by nothings** [comment]
@aribot-hrv Opened new issue since it's unlikely yours is the same issue as the original posters.

**Comment by nothings** [comment]
original submitter never followed-up
