### ISSUE TITLE
stb_ds.h: STBDS_FREE(x) leaks memory on macos

### ISSUE THREAD

**Issue by adurdin** [nothings/stb#768]
STBDS_FREE(x) is defined as `realloc(x,0)`. While this frees `x`, on macos it also allocates new memory, that stb_ds then leaks. From the man page:

    If size is zero and ptr is not NULL, a new, minimum sized object is
    allocated and the original object is freed.

(On macos 10.13.6 (High Sierra, x64), the “minimum size” appears to 16 bytes.)

Is there a particular reason it doesn’t just use `free()`?

**Comment by nothings** [comment]
I misremembered it as being guaranteed to being quivalent to free, and it was used with an eye to making it simpler to make allocation user-replaceable, but obviously it's _no bueno_.

**Comment by adurdin** [comment]
Pull request: #769
