### ISSUE TITLE
Memory leak in stbtt_PackFontRanges

### ISSUE THREAD

**Issue by aloucks** [nothings/stb#77]
https://github.com/nothings/stb/blob/master/stb_truetype.h#L2327

```c
rects = (stbrp_rect *) STBTT_malloc(sizeof(*rects) * n, spc->user_allocator_context);
```
rects is never freed.

**Comment by nothings** [comment]
Whoops, good catch!

**Comment by ddengster** [comment]
is this fixed yet?

**Comment by nothings** [comment]
Nope, it's not fixed. I have a new stb library I'm trying to finish before I make time to catch up on all the outstanding bugs.

**Comment by nothings** [comment]
Fixed in version I'm about to release.
