### ISSUE TITLE
stb_ds.h: hmlen and hmlenu crashes on NULL pointer

### ISSUE THREAD

**Issue by phoekz** [nothings/stb#770]
`hmlen` subtracts `t` by 1 before calling `arrlen`. If `t` is NULL (an empty hash map) then `arrlen` crashes, because `t` has underflowed to something non-NULL. For minimizing API surprises, I would make this return 0, just like `arrlen` would if `t` was NULL.

**Comment by nakst** [comment]
Also occurs with shlen and shlenu

**Comment by nothings** [comment]
fixed in 2019
