### ISSUE TITLE
stb_image.h Possible buffer overrun due to incorrect usage of MultiByteToWideChar

### ISSUE THREAD

**Issue by bplu4t2f** [nothings/stb#772]
The last argument of `MultiByteToWideChar` expects the number of wchar_t array elements. Not size of the array in bytes.

These lines in stb_image:

```
wchar_t wMode[64];
wchar_t wFilename[1024];
if (0 == MultiByteToWideChar(65001 /* UTF8 */, 0, filename, -1, wFilename, sizeof(wFilename)))
    return 0;
if (0 == MultiByteToWideChar(65001 /* UTF8 */, 0, mode, -1, wMode, sizeof(wMode)))
    return 0;
```

... use it incorrectly, it should be `sizeof(wFilename) / sizeof(wFilename[0])` (or wMode respectively)

Naysayer quote:

But why are you using sizeof here at all, why not
const int NUM_CHARACTERS = 10; wchar_t buf[NUM_CHARACTERS]; MultiByteToWideChar(..., NUM_CHARACTERS).

**Comment by tombsar** [comment]
Same issue in stb_image_write: https://github.com/nothings/stb/blob/c72a95d766b8cbf5514e68d3ddbf6437ac9425b1/stb_image_write.h#L307

Should be an easy fix!

**Comment by nothings** [comment]
>Naysayer quote:
>
>But why are you using sizeof here at all, why not
>const int NUM_CHARACTERS = 10; wchar_t buf[NUM_CHARACTERS]; MultiByteToWideChar(..., >NUM_CHARACTERS).

I prefer to avoid introducing unneeded buffer size names like this, if the only thing they're used for is defining the size of a buffer that nobody ever sees, because it pollutes the namespace of header file libraries (i.e. it has to be STBI__NUM_CHARACTERS). OTOH making them PUBLIC macros would allow people to make them larger.

**Comment by bplu4t2f** [comment]
@nothings I think Jon meant to define a constant in the *local scope*, which is unfortunately not possible in C (he didn't know the context when he commented).

**Comment by rygorous** [comment]
This bug is fixed in the dev branch, fix will be in the next version.
