### ISSUE TITLE
stb_image 2.22 skipping incorrect number of header bytes for 16-bit BI_BITFIELDS bitmap

### ISSUE THREAD

**Issue by thurstond** [nothings/stb#773]
In the attached 16-bit bitmap file [flirMod.zip](https://github.com/nothings/stb/files/3318585/flirMod.zip) (zipped because github doesn't support bitmap files), the pixel data is supposed to start at byte 0x42 (as specified by byte 10 of the header), which means the first two bytes read should be 0xDEAD. With the latest version of stb_image (2.22), it actually starts reading 12 bytes later, which shows up as 0xBEEF.

I believe the reason it reads 12 bytes later is because the header specifies that `compress == 3` (BI_BITFIELDS), which means that `stbi__bmp_parse_header` executes:

```
               info->mr = stbi__get32le(s);
               info->mg = stbi__get32le(s);
               info->mb = stbi__get32le(s);
```
to obtain the bitmasks, which is not accounted for in `stbi__bmp_load` when it calls:
```
    stbi__skip(s, info.offset - 14 - info.hsz);
```
(N.B. offset == 0x42 as expected, header size = 0x28, so it skips (66 - 14 - 40) == 12 bytes.)

An easy kludge to see that it's skipped to the wrong part of the file is to replace the previous skip command with:
```
      stbi__rewind(s); // ONLY WORKS FOR THIS EXAMPLE - STBI'S BUFFERING MAKES THIS INCORRECT IN MOST CASES
      stbi__skip(s, info.offset);
```
and then it will correctly load pixel data starting from location 0x42.

Here is a hexdump of the start of the bitmap file, annotated with the variable names for convenience (CAPITALIZED variables are important):

```
00000000   42 4D 52 2B  01 00 00 00  00 00 42 00  00 00 28 00  BMR+......B...(.
                                           ^----------- ^----
                                           OFFSET       HEADER SIZE

00000010   00 00 AE 00  00 00 24 FF  FF FF 01 00  10 00 03 00  ......$.........
           -----              ^----------- ^----  ^---- ^----
                              y            planes bpp   COMPRESSION

00000020   00 00 10 2B  01 00 00 00  00 00 00 00  00 00 00 00  ...+............
           ----- ^----------- ^----------- ^----------- ^----
                 sizeof       hres         vres         coloursused

00000030   00 00 00 00  00 00 00 F8  00 00 E0 07  00 00 1F 00  ................
           ----- ^----------- ^----------- ------------ -----
                 maximportant RED MASK     GREEN MASK   BLUE MASK

00000040   00 00 AD DE  00 00 00 00  00 00 00 00  00 00 EF BE  ................
           ----- ^----                                  ^----
                 PIXELS START HERE                      WRONG START
```

Thank you!

P.S.
- The original image (without the 0xDEAD and 0xBEEF modifications) was obtained from [https://www.ghostlyactivities.com/wp-content/uploads/2018/10/FLIR00079.bmp](https://www.ghostlyactivities.com/wp-content/uploads/2018/10/FLIR00079.bmp)
- It loads correctly in Adobe Photoshop CS6 (13.0.1 x64) and Microsoft Paint (Windows 10; OS Build 17134.829)
- It appears to be a BMP Version 3 (Microsoft Windows NT), which _"adds three additional fields that follow the bitmap header in place of a color palette. The bitmap header is 40 bytes in length ... If the bitmap contains 16 or 32 bits per pixel, then only a Compression value of 3 is supported and the RedMask, GreenMask, and BlueMask fields will be present following the header in place of a color palette."_ -- [https://www.fileformat.info/format/bmp/egff.htm](https://www.fileformat.info/format/bmp/egff.htm).
Notably, this implies that the color masks are not counted as part of the header size. Moreover, if I hexedit the header size to be 52 bytes, Microsoft Paint rejects it as an invalid image.

**Comment by nothings** [comment]
fixed in next release
