### ISSUE TITLE
stb_image.g warning: assuming signed overflow does not occur when changing X +- C1 cmp C2 to X cmp C2 -+ C1

### ISSUE THREAD

**Issue by GarethH96** [nothings/stb#774]
On GNU/Linux, I get a bunch of warnings with GCC using `-Wstrict-overflow=4`. The only way to shut it up is to enable `-fwrapv`.

The code that uses stb_image.h:
```
...
    int tex_width, tex_height, tex_channels;
    stbi_uc *pixels = stbi_load (TEXTUREDIR "gnu-logo.png",
				 &tex_width,
				 &tex_height,
				 &tex_channels,
				 STBI_rgb_alpha);
...

```

The warnings I get:
```
../src/main.cpp: In function ‘void stbi__grow_buffer_unsafe(stbi__jpeg*)’:
../src/main.cpp:1770:1: warning: assuming signed overflow does not occur when changing X +- C1 cmp C2 to X cmp C2 -+ C1 [-Wstrict-overflow]
 1770 | }
      | ^
../src/main.cpp: In function ‘void stbi__fill_bits(stbi__zbuf*)’:
../src/main.cpp:1770:1: warning: assuming signed overflow does not occur when changing X +- C1 cmp C2 to X cmp C2 -+ C1 [-Wstrict-overflow]
../src/main.cpp: In function ‘int stbi__parse_entropy_coded_data(stbi__jpeg*)’:
../src/main.cpp:1770:1: warning: assuming signed overflow does not occur when changing X +- C1 cmp C2 to X cmp C2 -+ C1 [-Wstrict-overflow]
../src/main.cpp:1770:1: warning: assuming signed overflow does not occur when changing X +- C1 cmp C2 to X cmp C2 -+ C1 [-Wstrict-overflow]
../src/main.cpp:1770:1: warning: assuming signed overflow does not occur when changing X +- C1 cmp C2 to X cmp C2 -+ C1 [-Wstrict-overflow]
../src/main.cpp:1770:1: warning: assuming signed overflow does not occur when changing X +- C1 cmp C2 to X cmp C2 -+ C1 [-Wstrict-overflow]
../src/main.cpp: In function ‘int stbi__compute_huffman_codes(stbi__zbuf*)’:
../src/main.cpp:1770:1: warning: assuming signed overflow does not occur when changing X +- C1 cmp C2 to X cmp C2 -+ C1 [-Wstrict-overflow]
../src/main.cpp:1770:1: warning: assuming signed overflow does not occur when changing X +- C1 cmp C2 to X cmp C2 -+ C1 [-Wstrict-overflow]
../src/main.cpp: In function ‘int stbi__parse_zlib(stbi__zbuf*, int)’:
../src/main.cpp:1770:1: warning: assuming signed overflow does not occur when changing X +- C1 cmp C2 to X cmp C2 -+ C1 [-Wstrict-overflow]
```

**Comment by lieff** [comment]
I think this is normal situation. This warnings only tells that compiler applies potentially dangerous optimization such as (x * 10) / 5 => x * 2. But "5" can come from table for example and compiler generates specialized function for hot path. This can happen in unexpected places in clean code, you simply cannot avoid that in general case for all compilers. Only way is to disable such optimizations.

**Comment by rygorous** [comment]
These are not even a warning about the code; they are literally just the compiler telling you that it's applying an optimization that might change the result if the original code had signed overflows; it's not warning that the expression itself is likely overlfowing. See documentation at https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html.

These is literally nothing here for us to fix, nor a sane way to avoid these warnings. If you don't want a ton of warnings of the compiler telling you when it's applying optimizations to the program, don't turn that warning on (or at least not at the higher levels).
