### ISSUE TITLE
stb image not working with precompiled headers

### ISSUE THREAD

**Issue by nicovanbentum** [nothings/stb#776]
I am trying to add stb_image to a visual studio precompiled header but I can't get it to work. 
I tried adding the `STB_IMAGE_IMPLEMENTATION` to the pch cpp file which didn't work, also tried adding it to the preprocessor definitions, didn't work. Is it not possible to use stb with precompiled headers?

**Comment by nothings** [comment]
One thing that might work would be something like:

```
#include "thing_that_does_pch.h" // this will #include stb_image.h

#define STB_IMAGE_IMPLEMENTATION
#include "stb_image.h"
```

However, the above may not be work if precompiled headers presume "#pragam once". In that case, you should just make a totally separate C++ file whose only job is to be the stb implementation:

```
[begin stb_implementation.c]
// do not include the PCH system in this file
#define STB_IMAGE_IMPLEMENTATION
#include "stb_image.h"
[end of stb_implementation.c]
```

**Comment by nicovanbentum** [comment]
That last one worked, also had to disable using the pch for that specific C++ file in the Visual Studio properties. thanks!
