### ISSUE TITLE
stb_easy_font: multiple definitions error when use from several source files

### ISSUE THREAD

**Issue by podsvirov** [nothings/stb#777]
Looks like we need split declaration and definitions and check `STB_EASY_FONT_IMPLEMENTATION` macro before define implementation.

**Comment by nothings** [comment]
I believe this was intentional as it was only intended to be used from one place, but I'll have to review my notes to see why.

**Comment by podsvirov** [comment]
What if check `STB_EASY_FONT_STATIC` and define `STB_EASY_FONT_DEF` before public symbols like in other headers?

**Comment by nothings** [comment]
From just reading the code, it looks like the data tables just need "static"?

Adding a requirement for STB_EASY_FONT_IMPLEMENTATION will break existing code that doesn't have it. The idea was that it's a function people are always going to need to wrap anyway, so there shouldn't be any need to include it from multiple files.

**Comment by podsvirov** [comment]
> From just reading the code, it looks like the data tables just need "static"?

and the internal variable `stb_easy_font_spacing_val` too.

Please review solution in #779.

**Comment by nothings** [comment]
fixed by #779
