### ISSUE TITLE
stb_image 2.22 doesn't ignore color masks when compress == 0 for BMPV4HEADER/BMPV5HEADER images

### ISSUE THREAD

**Issue by thurstond** [nothings/stb#783]
The attached image [bjm7nnow.zip](https://github.com/nothings/stb/files/3428353/bjm7nnow.zip) (zipped because github doesn't support BMPs) is:
- a Windows 98 bitmap (`header size == 124`)
- 32-bit with `compress == 0`
- but, notwithstanding `compress == 0`, specifies some funky bitmasks (RGBA instead of the usual BGRA)

stb_image 2.22 uses the bitmasks instead of ignoring them, resulting in a strange-looking image.

Why it uses the bitmasks:
- In the `stbi__bmp_parse_header` function, when the header size is 40 or 56, it only reads the bitmasks when compress == 3.
However, when the header size is 108 or 124, it always uses the bitmasks.

Why I think it's incorrect:
- According to Microsoft: "bV4RedMask: Color mask that specifies the red component of each pixel, valid only if bV4Compression is set to BI_BITFIELDS." (similarly for Green/Blue/Alpha)
(https://docs.microsoft.com/en-us/windows/win32/api/wingdi/ns-wingdi-bitmapv4header
https://docs.microsoft.com/en-us/windows/win32/api/wingdi/ns-wingdi-bitmapv5header)
- stb_image's output for the attached bitmap looks strange (blueish; blue and red channels are swapped)
- Microsoft Paint, Adobe Photoshop CS6 and Google Chrome (all on Windows 10) ignore the bitmasks, resulting in a natural-looking image of a box

The attached image was obtained from http://www.freshersopenings.in/wp-content/uploads/2013/10/bjm7nnow.bmp

hexdump of bitmap header with relevant fields noted:

```
00000000   42 4D 0A 14  03 00 00 00  00 00 8A 00  00 00 7C 00  BM............|.
                                                        ^----
                                                        HEADER SIZE = 124

00000010   00 00 2C 01  00 00 A8 00  00 00 01 00  20 00 00 00  ..,......... ...
                                                        ^----
                                                        COMPRESSION = 0

00000020   00 00 80 13  03 00 00 00  00 00 00 00  00 00 00 00  ................
           -----

00000030   00 00 00 00  00 00 FF 00  00 00 00 FF  00 00 00 00  ................
                              ^----------- ^----------- ^----
                              RED MASK     GREEN MASK   BLUE MASK
                                                        
00000040   FF 00 00 00  00 FF 42 47  52 73 00 00  00 00 00 00  ......BGRs......
           ----- ^-----------
                 ALPHA MASK
```

**Comment by thurstond** [comment]
This issue has some overlap with https://github.com/nothings/stb/issues/749 (with 24-bit BMPV4HEADER/BMPV5HEADER images for which the alpha mask is non-zero, stb_image outputs a 32-bit image with the alpha channel set to 255), so the fix for that _might_ also have solved this.

(This issue would still be present if that fix was specific to 24-bit images or the alpha channel e.g., "for 24-bit images, set s->img = 3;" or "for 24-bit images, zero out or don't read the alpha mask")

**Comment by rygorous** [comment]
A fix for this was pushed on the dev branch and should be in the next release.
