### ISSUE TITLE
"no SOI" error when loading some PNGs

### ISSUE THREAD

**Issue by kg** [nothings/stb#787]
Some PNGs look enough like a JPEG that the JPEG file format test will break with the "no SOI" error instead of rejecting the image as a JPEG. The error is in ```stbi__decode_jpeg_header``` here:
```C
   if (!stbi__SOI(m)) return stbi__err("no SOI","Corrupt JPEG");
```

```return 0``` instead of ```return stbi__err(...)``` fixes it.

**Comment by rygorous** [comment]
Can you give an example file? I'd like to handle this more systematically.

-Fabian

**Comment by nothings** [comment]
See also this very short twitter thread for a little discussion. https://twitter.com/nothings/status/1158523980589891584

**Comment by kg** [comment]
I'm not able to reproduce this now for some reason. I don't remember modifying the image, but I did update to a newer version of stb_image (in the process of creating my PR), so I guess something unrelated could have tweaked the file parsing?

It was reproducing consistently all day yesterday (always failing on the no SOI error) and not crashing so I'm not sure what else it could be. Given that I'm OK with not fixing it if we don't have an example. I might be able to come up with one if I look at the parser long enough (is this a task for a fuzzer?)

**Comment by kg** [comment]
More testing: It does actually hit no SOI, which is normal I think? That's rejecting part of the PNG header. I think what was happening is that because the error flag from that is never cleared, the 'last failure message' was no SOI even though I was hitting a different failure (a crash, probably) somewhere else in the code. That failure appears to be fixed so my codepath that was picking up the no SOI message is no longer running. If I manually run that path I get 'no SOI' again.

**Comment by nothings** [comment]
final conclusion is we should just test for JPEG later in the sequence

**Comment by AnterCreeper** [comment]
Hello!
During my test, I found that while I switch on the -O2 option, it will return "no SOI" and return a wrong data;
![image](https://user-images.githubusercontent.com/30188772/102620616-34f12800-4179-11eb-95dc-847a24436973.png)
![image](https://user-images.githubusercontent.com/30188772/102620723-6d910180-4179-11eb-8588-eba79c52edc2.png)
However, it will work correctly if i turn off -O2.

**Comment by rygorous** [comment]
The test sequence was reordered in a fix that's now on the dev branch and will be in the next version.

**Comment by pedrobagatin** [comment]
I am getting this error 

> turn off -O2

What is -O2? I am getting similar error and would like to fix it without changing library version if possible.

**Comment by nothings** [comment]
The previous user was able to work around the problem by disabling optimizations (which is done on some platforms with "-O2" on the commandline). This may or may not work for you.

**Comment by pedrobagatin** [comment]
> The previous user was able to work around the problem by disabling the highest level of optimizations (which are requested on some platforms with "-O2" on the commandline). Turning off optimizations, or some optimizations, may or may not work for you. We have no understanding or knowledge of what that user's experience was, and we will not support attempts to deal with this issue that don't include updating to the latest version.

Thanks, I figured out how to use a newer version in my project by compiling with -fPIC instead of -fPIE. But images are still not okay, using GIMP to export original PNG file as PNG again works. However some of my application image comes from a third-party which still uses poorly formatted PNG, do you have any idea what the problem is and how to solve it?

**Comment by nothings** [comment]
we can't do anything without more information. open a new issue and post/link-to a problematic PNG and we can look at it. (this is almost certainly unrelated to the original bug in this thread so should be its own issue, not piggy-backed here)
