### ISSUE TITLE
Compilation fail in stb_image_write if STBI_WRITE_NO_STDIO is defined

### ISSUE THREAD

**Issue by siliace** [nothings/stb#793]
Hello,

I have a compilation error in stb_image_write.h when STBI_WRITE_NO_STDIO is defined. The compiler complain about lack of sprintf_s (with visual studio) or sprintf (with GCC) in the function stbi_write_hdr_core with the following code:

```
#define STBI_WRITE_NO_STDIO
#define STB_IMAGE_WRITE_IMPLEMENTATION
#include "stb_image_write.h"

int main()
{
	return 0;
}
```
Thanks !

**Comment by zao** [comment]
The offending lines are in `stbi_write_hdr_core` at https://github.com/nothings/stb/blob/master/stb_image_write.h#L735-L739

The top-level comment mentions that HDR writing is disabled if stdio is, but the actual implementation only disables the top-level HDR writing function, not the inner `stbi_write_hdr_core` function that actually uses stdio.

While being just a warning in C, it's an error in C++ as they don't do implicit declarations.

**Comment by rygorous** [comment]
Fix for this is in the current dev branch and will ship in the next release.
