### ISSUE TITLE
Why not the Unlicense?

### ISSUE THREAD

**Issue by Hexstream** [nothings/stb#797]
It seems to me that [the Unlicense](https://unlicense.org) would be a perfect fit for you.

I've been using the Unlicense for all my projects (except one, which wraps a proprietary component) for 8+ years without problems.

This is a fairly popular license that is even suggested by GitHub in the "Add a license" dropdown box when creating a new project, so this is definitely legitimate and safe to use.

This is probably much safer to use than some ad-hoc public domain dedication, and should result in less head-scratching for your users.

**Comment by Hexstream** [comment]
Sorry I guess. ¯\_(ツ)_/¯

**Comment by zao** [comment]
@Hexstream The headers are dual-licensed under both MIT and PD, the wording for PD is verbatim the Unlicense (even linking to unlicense.org).

The previous discussion on licensing that ended with this conclusion can be found in #240.

The presence of an "actual" license enables use for companies that have whitelists (like the commenter in that issue that may only use OSI-approved licenses).

My impression is that the licensing problem has been sufficiently solved for these libraries and any theoretical improvement seems to just be detrimental.
