### ISSUE TITLE
stb_truetype: can't understand how vertical alignment to a base line should be computed

### ISSUE THREAD

**Issue by bnoazx005** [nothings/stb#813]
So, the question looks simple, but after reading inlined documentation I still can't understand how properly compute a vertical alignment of glyphs when we use SDF generated bitmaps using stb_truetype library.

In nutshell I have own texture packer system that generates a texture atlas with all needed SDF represented glyphs. Also there is a data type that contains the following parameters per code point including width, height, xoff and yoff, which I get from stbtt_GetCodepointSDF function.

**Comment by nothings** [comment]
Draw the top-left of the character bitmap at cursor+xoff, baseline+yoff.

**Comment by bnoazx005** [comment]
Thank you! I've doubted that use offsets in correct way. But in the end due to your help I've found out that text's mesh was drawn with inverted texture coordinates.
