### ISSUE TITLE
Add a bit-array manipulation header?

### ISSUE THREAD

**Issue by HalosGhost** [nothings/stb#814]
I have been working on a small header to make it as seamless as possible to work with bit arrays (stack-allocated) and bit buffers (heap-allocated) as possible.

I have been thoroughly enjoying using this header, but I am sure it could use some improvements and perhaps it might be of interest to others? If people are interested in having it included, I would happily dedicate it to the public domain and add it to this project, and perhaps it can get even better!

If this is out-of-scope for stb, let me know, and no hard feelings. Otherwise, I would love to make this more available for people to leverage.

**Comment by nothings** [comment]
Maybe https://github.com/nothings/single_file_libs is more appropriate?

**Comment by HalosGhost** [comment]
Fair enough! I will consider spinning it off to its own repo and make a PR to that list if I do. Thanks for the input!
