### ISSUE TITLE
stb_vorbis: value is assigned but immediately overwritten; needs review

### ISSUE THREAD

**Issue by kcgen** [nothings/stb#816]
In the codebook calculation, `val` is set but then immediately re-assigned without the first value being used.
```
   float val = mults[off];
   val = mults[off]*c->delta_value + c->minimum_value + last;
```

Here's a link to the full code for context:
https://github.com/nothings/stb/blob/052dce117ed989848a950308bd99eef55525dfb1/stb_vorbis.c#L3837

However, maybe the first value was meant to be used in some way?
``` c++
val =
val +=

or ...
val =
val *=
```
?

**Comment by rygorous** [comment]
No, there's definitely nothing special that should happen there (at least nothing that I can find in the Vorbis spec, and also nothing in the alternative code paths in stb_vorbis. This appears to just be a leftover of code editing.

The pointless assignment was removed in the dev branch but the old version was also fine so I'm closing this issue.
