### ISSUE TITLE
stb_vorbis: dead code cleanup

### ISSUE THREAD

**Issue by kcgen** [nothings/stb#817]
The following variables aren't used:

https://github.com/nothings/stb/blob/052dce117ed989848a950308bd99eef55525dfb1/stb_vorbis.c#L4910

The next two variables also follow with if statements that are also unnecessary (unused), and can also be removed.

https://github.com/nothings/stb/blob/052dce117ed989848a950308bd99eef55525dfb1/stb_vorbis.c#L5228

https://github.com/nothings/stb/blob/052dce117ed989848a950308bd99eef55525dfb1/stb_vorbis.c#L5248

**Comment by rygorous** [comment]
This is now fixed in the dev branch, will be in the next release.

**Comment by kcgen** [comment]
Thank you, @rygorous.  
The dev branch is shaping up have quite a few fixups!

**Comment by rygorous** [comment]
The goal was to clean up our big backlog of issues as much as possible over
the long weekend!

-Fabian
