### ISSUE TITLE
Merge the checklist when opening a PR into CONTRIBUTING.md

### ISSUE THREAD

**Issue by haferburg** [nothings/stb#820]
I just opened a PR, and I got the following item in a checklist:

> Make sure you're using a special branch just for this pull request. (Sometimes people unknowingly use a default branch, then later update that branch, which updates the pull request with the other changes if it hasn't been merged yet.)

Would you mind adding that to https://github.com/nothings/stb/blob/master/.github/CONTRIBUTING.md? It's not going to be an issue for me, but maybe it helps others.

Also I didn't know what branch to merge the PR into. `master` is ok, right? Maybe you could clarify that in CONTRIBUTING.md as well.

**Comment by nothings** [comment]
I fixed the first thing. I addressed the second by deleting all branches except master.
