### ISSUE TITLE
Run-Time Check Failure #2 - Stack around the variable 'buffer' was corrupted.

### ISSUE THREAD

**Issue by DAMON-BIN** [nothings/stb#827]
static char **readdir_raw(char *dir, int return_subdirs, char *mask)

Run-Time Check Failure #2 - Stack around the variable 'buffer' was corrupted.

windows

change line 1928
stb_p_strcpy_s(d,n+1,s);
to
stb_p_strcpy_s(d,n,s);

**Comment by nothings** [comment]
fixed by a PR, I forget which one
