### ISSUE TITLE
Minor: underline ==== comments clash with git's merge-conflict identifier

### ISSUE THREAD

**Issue by krcroft** [nothings/stb#830]
When merging code, git by-default will flag merge conflicts using BEFORE and AFTER code blocks separated with a `=======` string:
``` diff
Changes made on the branch that is being merged into. In most cases,
this is the branch that I have currently checked out (i.e. HEAD).
=======
Changes made on the branch that is being merged in. This is often a 
feature/topic branch.
```
If the code itself contains `=======` strings, then this becomes error-prone to edit and search for.  

The recommendation here is (so long as this repo is managed in git) to use ASCII strings that don't overlap with git's identifier lines (perhaps `-------`'s)?

**Comment by nothings** [comment]
which file?

**Comment by krcroft** [comment]
stb.h (I'm using vorbis, but that's been converted to ---'s already)

**Comment by nothings** [comment]
![image](https://user-images.githubusercontent.com/7525026/68077992-17051000-fd8b-11e9-945e-ef4f13009f2d.png)

**Comment by krcroft** [comment]
lol

**Comment by nothings** [comment]
I think this isn't a big enough deal to be worth changing; it doesn't interfere with the automated merge detection, it just means you have to skip past it when searching.

**Comment by krcroft** [comment]
Yes; it's only a change to help the person doing the merging. I thought you might be interested, given many stb headers are already 'clean' and use a different ascii line character besides =.
