### ISSUE TITLE
[question] set data structure

### ISSUE THREAD

**Issue by jabbalaci** [nothings/stb#851]
I find the dynamic array and the hashmap very useful. Do you happen to have a set data structure too? I didn't find it. Or as a workaround, should I use a hashmap with a dummy value? What do you do when you need a set? Thanks.

**Comment by nothings** [comment]
You can make a struct with just the key, and then use the 'struct' functions that end with s.

**Comment by jabbalaci** [comment]
Excuse me, what do you mean by "'struct' functions that end with s"? Could you give an example? Thanks.

**Comment by nothings** [comment]
hmgets / hmputs

they accept any struct as long as it has a 'key' field
