### ISSUE TITLE
stb_image: stbi_set_flip_vertically_on_load is thread-unfriendly

### ISSUE THREAD

**Issue by mcclure** [nothings/stb#856]
stb_image uses a shared global flag to determine whether to flip images upside down when loading them. I am currently working on a program that loads PNGs in two separate threads at the same time and the threads have different preferences for the `stbi__vertically_flip_on_load` value. Hilarious problems result.

I would be happy to implement a patch addressing this. However I can see two different ways to do it

1. Eliminate stbi_set_flip_vertically_on_load and use arguments to determine flippiness.
2. (Might require taking on dependencies stb libraries usually don't, I'm not sure?) Make stbi__vertically_flip_on_load thread-local storage.

Would you be interested in a patch for this, and which solution would you prefer the patch use?

(I encountered the problem in v2.12 but by code inspection it is still present in v2.23)

**Comment by nothings** [comment]
Some discussion of this is in the following Twitter thread:

https://twitter.com/mcclure111/status/1207432774660939776

**Comment by nothings** [comment]
I think on reflection I'm willing to live with the broken DLL nonsense if we just have an optional #define to disable the threadlocal variable. I'll ask for feedback on twitter for the design of this.

**Comment by nothings** [comment]
Fixed in next release.
