### ISSUE TITLE
Does not support Unicode file paths on Windows using MinGW/gcc

### ISSUE THREAD

**Issue by EasiestSoft** [nothings/stb#857]
`Can't fopen` exception when loading or saving an image

**Comment by nothings** [comment]
How is this different from #729?

**Comment by EasiestSoft** [comment]
It's the same thing. This issue makes it clear that ` stb does not support Unicode file paths on Windows using MinGW / gcc`, and #729 locates the relevant source code

**Comment by EasiestSoft** [comment]
> 
> 
> How is this different from #729?



> 
> 
> How is this different from #729?

It's the same thing. This issue makes it clear that ` stb does not support Unicode file paths on Windows using MinGW / gcc`, and #729 locates the relevant source code

**Comment by nothings** [comment]
Closed duplicate of #729.

**Comment by Photosounder** [comment]
It's still not fixed if I'm not mistaken and it's also annoying that it doesn't default to UTF-8. Maybe consider just using something like this to spare everyone headaches: https://github.com/Photosounder/fopen_utf8/
