### ISSUE TITLE
Assertion inconsistency in stb_truetype

### ISSUE THREAD

**Issue by codecat** [nothings/stb#859]
This code causes issues if the macro expands to something more complex:

https://github.com/nothings/stb/blob/f67165c2bb2af3060ecae7d20d6f731173485ad0/stb_truetype.h#L2934-L2943

For example:

```c++
#define STBTT_assert(cond) { if (!(cond)) { /* do stuff */ } }
```

So there should probably be `{ }` brackets around the if statements.

**Comment by nothings** [comment]
You need to wrap your assertion properly to avoid this. E.g.

#define STBTT_assert(cond) do { if (!(cond)) { /* do stuff */ } } while (0)

**Comment by codecat** [comment]
Ah, I have seen that syntax before. Couldn't think of it myself! Thanks :)
