### ISSUE TITLE
STBI_INCLUDE_STB_IMAGE_H issue

### ISSUE THREAD

**Issue by oldoldman** [nothings/stb#861]
STBI_INCLUDE_STB_IMAGE_H does not protect the entire header file , the following file(test.c) will fail (C2084) to compile
#include <stb_image.h>
#include <stb_image.h>
int main()
{}
cl /nologo /DSTB_IMAGE_IMPLEMENTATION test.c
many thanks!

**Comment by nothings** [comment]
That is not a bug. You cannot define STB_IMAGE_IMPLEMENTATION on the commandline.
