### ISSUE TITLE
Unresolved External Symbols, but I did the #define in a cpp file.

### ISSUE THREAD

**Issue by thom-bahm** [nothings/stb#875]
Basically what the title says, This is the .cpp file where I define STB_IMAGE_IMPLEMENTATION (and I have tried it in the Texture.cpp file as well but that gives same errors)
![Unresolved External symbols](https://user-images.githubusercontent.com/56136360/72401125-cb6acd00-3710-11ea-8b3d-116e0640ad07.PNG)
Here is the build output:
![Unresolved External symbols1](https://user-images.githubusercontent.com/56136360/72401126-cb6acd00-3710-11ea-96dc-2099bb7fb500.PNG)
Heres where I call the code thats throwing errors:
![Unresolved External symbols2](https://user-images.githubusercontent.com/56136360/72401127-cb6acd00-3710-11ea-8ced-bffdedcf24e1.PNG)

**Comment by nothings** [comment]
You misspelled STB_IMAGE_IMPLEMENTATION.

**Comment by thom-bahm** [comment]
@nothings Wow I copy-and-pasted the #define from the .h file, idk how I screwed that up, sorry for that waste of time; Also thanks for letting me know.
