### ISSUE TITLE
stb_vorbis: The 'f->error' variable was assigned the same value.

### ISSUE THREAD

**Issue by kcgen** [nothings/stb#883]
![image](https://user-images.githubusercontent.com/1557255/72758698-6982eb00-3b88-11ea-82db-9fece2453ce6.png)

https://www.viva64.com/en/w/v1048/

**Comment by rygorous** [comment]
It says right on the line that this line exists to be a breakpoint for debugging. Yes, it's setting an error to the same value it already was, and yes, your analyzer might complain about it, but it's legal, intentional and definitely harmless.
