### ISSUE TITLE
stb_vorbis: Expression 'f->valid_bits < 0' is always false.

### ISSUE THREAD

**Issue by kcgen** [nothings/stb#884]
![image](https://user-images.githubusercontent.com/1557255/72758739-86b7b980-3b88-11ea-875c-d18de9a95e8b.png)

https://www.viva64.com/en/w/v547/

**Comment by vickit144** [comment]
I created a pull request to fix this issue by removing that line.

**Comment by krcroft** [comment]
Thank you @vickit144 !

**Comment by vickit144** [comment]
I committed the change you suggested to my pull request.

**Comment by nothings** [comment]
No big deal, but just for future reference, you don't need to document it in both places, it just means I get two email notifications instead of one.

**Comment by rygorous** [comment]
This fix was merged last year, closing issue.
