### ISSUE TITLE
stb_easy_font should check also against '\r'

### ISSUE THREAD

**Issue by elect86** [nothings/stb#887]
As titled, I think [this](https://github.com/nothings/stb/blob/e6afb9cbae4064da8c3e69af3ff5c4629579c1d2/stb_easy_font.h#L207) should be instead:

`if (*text == '\n' || *text == '\r')`

**Comment by nothings** [comment]
why should this support \r? it's meant to accept C strings, which normally don't have \r in them.

**Comment by rygorous** [comment]
And more to the point, if \r was to be supported it would _definitely_ be wrong to treat it as a newline; that's not how CR works. (If anything, it should reset x to start_x without incrementing y for the conventional meaning of CR, but I still don't see why you would want CR support here in the first place.)
