### ISSUE TITLE
Inconsistent info behavior

### ISSUE THREAD

**Issue by rds1983** [nothings/stb#892]
Hi,
I've noticed  following inconsistency in info methods: stbi__bmp_info always rewinds stream to the start, while other info methods seems to do it only on failure.

stbi__bmp_info(always rewinds stream):
```c
static int stbi__bmp_info(stbi__context *s, int *x, int *y, int *comp)
{
   void *p;
   stbi__bmp_data info;

   info.all_a = 255;
   p = stbi__bmp_parse_header(s, &info);
   stbi__rewind( s );
  ...
}
```

stbi__png_info(rewinds stream only on fail):
```c
static int stbi__png_info_raw(stbi__png *p, int *x, int *y, int *comp)
{
   if (!stbi__parse_png_file(p, STBI__SCAN_header, 0)) {
      stbi__rewind( p->s );
      return 0;
   }
   if (x) *x = p->s->img_x;
   if (y) *y = p->s->img_y;
   if (comp) *comp = p->s->img_n;
   return 1;
}

static int stbi__png_info(stbi__context *s, int *x, int *y, int *comp)
{
   stbi__png p;
   p.s = s;
   return stbi__png_info_raw(&p, x, y, comp);
}
```

**Comment by rygorous** [comment]
Fixed in dev branch, now BMP reader also only rewinds on failure, same as everyone else. It's somewhat arbitrary but now it's at least consistent. Will be in the next version.
