### ISSUE TITLE
stb_vorbis: assert on variable after use

### ISSUE THREAD

**Issue by jarikomppa** [nothings/stb#901]
```
      while (z > 0 && !available[z]) --z;
      if (z == 0) { return FALSE; }
      res = available[z];
      assert(z >= 0 && z < 32);
      available[z] = 0;
      add_entry(c, bit_reverse(res), i, m++, len[i], values);
```
Asserting z range should probably happen before accessing available[z]; on the previous line.

**Comment by rygorous** [comment]
It's cosmetic, z (or rather len[k]) is range-checked earlier when that array is populated, but I pushed a change in the dev branch that makes the asserts a bit clearer, hopefully.
