### ISSUE TITLE
Should info about #define STB_IMAGE_IMPLEMENTATION be in the readme?

### ISSUE THREAD

**Issue by akami-channel** [nothings/stb#903]
I tend to think that this information about 
#define STB_IMAGE_IMPLEMENTATION
should be included in the readme? When things weren't working I spent a lot of time trying random things to make it work instead of actually looking in the header file for instructions. Usually instructions for how to use are in the readme in my experience.

**Comment by akami-channel** [comment]
If it's too specific to a specific header file, then maybe saying "check each header file for instructions" etc?

**Comment by rygorous** [comment]
A new version of the README that explains this as part of the FAQ section is now in the dev branch and will migrate to master when we next do a release.
