### ISSUE TITLE
stb_image 2.25 load bmp

### ISSUE THREAD

**Issue by sdragonx** [nothings/stb#905]
First chance exception at $7480A832. Exception class const char * with message 'Exception Object Address: 0x337E0BE'

**Comment by sdragonx** [comment]
static void *stbi__bmp_load(stbi__context *s, int *x, int *y, int *comp, int req_comp, stbi__result_info *ri)
...
//line 5327
   if (info.hsz == 12) {
      if (info.bpp < 24)
         psize = (info.offset - info.extra_read - 24) / 3;
   } else {
      if (info.bpp < 16)
         psize = (info.offset - info.extra_read - info.hsz) >> 2;
   }
   if (psize == 0) {
      STBI_ASSERT(info.offset == (s->img_buffer - s->buffer_start));//EXCEPTION!!
   }

**Comment by nothings** [comment]
what image?

**Comment by sdragonx** [comment]
24bit windows bmp。

//STBI_ASSERT(info.offset == (s->img_buffer - s->buffer_start));//EXCEPTION!!

**Comment by nothings** [comment]
Ok, so you, as a person looking to report a bug to an open source project, need to imagine yourself in the shoes of the person working on the open source project. How is that person going to fix the bug given your bug report?

**Comment by nothings** [comment]
Are you using stbi_load or stbi_load_from_memory?

**Comment by sdragonx** [comment]
comment out that line, that's ok.
i using stbi_load_from_memory();

**Comment by nothings** [comment]
Duplicate of #909, who actually provided a sample file that crashes.

**Comment by sdragonx** [comment]
Yes, I see. I need an example.
