### ISSUE TITLE
I am getting these errors when trying to include stb_image.h on linux

### ISSUE THREAD

**Issue by akami-channel** [nothings/stb#910]
/usr/bin/ld: /tmp/ccTCc9h1.o: undefined reference to symbol 'pow@@GLIBC_2.29'
/usr/bin/ld: /usr/lib/libm.so.6: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status

**Comment by zao** [comment]
If building with a C compiler, you need to link the math library (`-lm`) for `pow`.

**Comment by akami-channel** [comment]
Ah ok, great. Thank you. Might it not be good to put this information either in the readme or at the top of the relevant header file?

**Comment by rygorous** [comment]
We can add a note in the docs, but honestly we normally just assume that you know how to compile and link C programs on your target.
