### ISSUE TITLE
Add .avif (AV1 Image File Format) support

### ISSUE THREAD

**Issue by EwoutH** [nothings/stb#912]
The AV1 Image File Format (AVIF) is a new image format based on the AV1 video codec. It would be great if support for this format could be added.

- The AVIF spec: https://aomediacodec.github.io/av1-avif/. 
- The AVIF reference library, libavif: https://github.com/AOMediaCodec/libavif

Multiple large companies are committed to pushing AVIF, including [Netflix](https://netflixtechblog.com/avif-for-next-generation-image-coding-b1d75675fe4) and [Facebook](https://bugs.chromium.org/p/chromium/issues/detail?id=960620#c112).

Netflix published some test images here: http://download.opencontent.netflix.com/?prefix=AV1/Chimera/AVIF/

**Comment by nothings** [comment]
No; the FAQ on the front page is relevant.
