### ISSUE TITLE
stb_image.h with STB_IMAGE_IMPLEMENTATION produce errors: * already defined in *

### ISSUE THREAD

**Issue by lufog** [nothings/stb#917]
When I using a stb_image.h with a #define STB_IMAGE_IMPLEMENTATION, I get 42 errors LNK2005. For example: stbi_zlib_decode_noheader_malloc already defined in Application.obj	TestProject.

Tested on an almost empty project:
main.cpp
```c++
#include <cstdlib>
#include <exception>
#include <iostream>
#include "Application.h"

int main()
{
	Application app;

	try {
		app.run();
	}
	catch (const std::exception & e) {
		std::cerr << e.what() << std::endl;
		return EXIT_FAILURE;
	}

	return EXIT_SUCCESS;
}
```
Application.h
```c++
#pragma once
#define STB_IMAGE_IMPLEMENTATION
#include <stb_image.h>


class Application
{
public:
	void run();
};
```

Application.cpp
```c++
#include "Application.h"

void Application::run()
{
}
```

**Comment by nothings** [comment]
You can't put #define STB_IMAGE_IMPLEMENTATION in a header file. Only one source file can see the #define. If you put it in a header, many do.
