### ISSUE TITLE
stb_dxt sometimes produces weird output on Windows

### ISSUE THREAD

**Issue by daigennki** [nothings/stb#919]
I am writing a utility program in C to convert various image formats to DDS with block compression, and running into this very bizarre issue where some blocks produced by stb_dxt functions appear corrupted. It's really weird, as I cannot recognize a pattern as to where and when it happens. I've tested it on Windows with MinGW64 clang 9.0.1-1, MinGW64 gcc 9.2.0-2, and MSVC v142, all of which produce the same output. Meanwhile, compiling and testing it on Windows Subsystem for Linux Debian using clang 7.0-47 amd64 produces perfect results that appear exactly as it should. I also asked a friend to test it on their Linux machine, on which we confirmed it works correctly as well.

Here's an example. The input:
![irasutoya_shibainu](https://user-images.githubusercontent.com/18689525/75955710-c1d43900-5ef9-11ea-97f0-64b260e45a78.png)
and the output, converted back to PNG from DDS using RenderDoc:
![test_output](https://user-images.githubusercontent.com/18689525/75955826-fa741280-5ef9-11ea-8150-58e1ad65f39f.png)

which was produced by this code:
```c
static void writeData(FILE* outputFile, const int w, const int h, const int channels, const int mipCount, const stbi_uc* inRow)
{
    writeHeader(outputFile, w, h, channels, mipCount);

    unsigned char inDataBuf[64];
    unsigned char outDataBuf[16];
    printf("Writing data...\n");
    const int blockSize = (channels == 2 || channels == 4 ? 16 : 8);
    printf("Block size: %i\n", blockSize);
    int mw = w, mh = h;
    for (unsigned int m = 0; m < mipCount; ++m, mw /= 2, mh /= 2)
    {
        //uint8_t* sampleOutput = NULL;
        //uint8_t* sampleOutputPos;
        /* change the number in this if statement to set which mipmap you want to get a sample from */
        /*if (m == 0)
        {
            sampleOutput = malloc(mw * mh * 4);
            sampleOutputPos = sampleOutput;
        }*/

        for (int l = 0; l < mh; l += 4, inRow += mw * 4 * 3)    /* every 4 rows */
        {
            for (int j = 0; j < mw; j += 4, inRow += 4 * 4)     /* every 4 columns */
            {
                for (int i = 0; i < 4; ++i)     /* every row in the 4x4 RGBA pixel block */
                {
                    for (int k = 0; k < 4; ++k)
                    {
                        memcpy(inDataBuf + (i * 4 + k) * channels, inRow + (i * mw + k) * 4, channels);
                        //if (sampleOutput) memcpy(sampleOutputPos + (i * mw + k) * 4, inDataBuf + (i * 4 + k) * channels, 16);
                    }
                }
                switch (channels)
                {
                case 3:
                case 4:
                    stb_compress_dxt_block(outDataBuf, inDataBuf, (channels == 4 ? 1 : 0), STB_DXT_DITHER | STB_DXT_HIGHQUAL);
                    break;
                case 1:
                    stb_compress_bc4_block(outDataBuf, inDataBuf);
                    break;
                case 2:
                    stb_compress_bc5_block(outDataBuf, inDataBuf);
                    break;
                }
                fwrite(outDataBuf, blockSize, 1, outputFile);
                //if (sampleOutput) sampleOutputPos += 4 * 4; 
            }
            //if (sampleOutput) sampleOutputPos += mw * 4 * 3;
        }
        /*if (sampleOutput)
        {
            stbi_write_png("sample_output.png", mw, mh, 4, sampleOutput, 0);
            free(sampleOutput);
        }*/
    }
}
```
I have confirmed that it is not the input data which is broken, by writing the input data to PNG, as shown in the lines of code that are commented out. 
Disabling optimization (-O0) did not help either.

Please let me know if additional information is needed, or I overlooked something.

**Comment by rygorous** [comment]
You didn't show the code that does the `fopen`.

Looking at your result, I'm fairly sure you're not opening the output file
in "binary" mode (you need to fopen(filename, "wb") not "w").
When compiling for a native Windows target, that means the file is
interpreted as a text file, which means any '\n' (ASCII 0x0a) byte gets
written as "\r\n" (CRLF, ASCII 0x0d 0x0a).
WSL and Linux use straight LF line endings and don't do any conversion on
files no matter what mode they're in.

Separately, I'm reasonably certain the code you posted won't work for right
for channels==3, because stb_compress_dxt_block always expects four bytes
per pixel input.

-Fabian

**Comment by daigennki** [comment]
Oh dear, well this is embarassing. You're right. I forgot to specify "wb". It works now. I'm sorry.
