### ISSUE TITLE
Multichannel Signed Distance Field (SDF) in stb_truetype.h

### ISSUE THREAD

**Issue by dumblob** [nothings/stb#920]
I just stumbled among this really awesome technology:

https://github.com/Chlumsky/msdfgen

and had to read the associated paper because of these cool features it offers:

1. it's easy to implement
2. it's easy to accelerate
3. it's faster (usually significantly) than all other SDF methods and not just those
4. offers superior rendering quality (quite close to vector rendering)
5. offers some useful visual effects "for free" (e.g. outline, blur, thickness adjustment) - see part 5.1.3 in the [thesis](https://github.com/Chlumsky/msdfgen/files/3050967/thesis.pdf )

Feel free to take a look and maybe copy some ideas to `stb_truetype.h` :wink:.

**Comment by nothings** [comment]
I looked at it back in the day and it didn't seem particularly robust. Sharp features near each other cause IMO worse artifacts than regular SDF does. The *idea* is great but engineering a working solution seems pretty hard.

**Comment by dumblob** [comment]
Interesting - there was another implementation and that had issues you describe. But this implementation is simpler and doesn't seem to have these issues. Did you look exactly at this implementation?

**Comment by nothings** [comment]
I have looked at this implementation in the past, but it was long enough ago that I don't remember the details, only that I decided to just go with straight SDF. So it was around the time analytic SDF was added to stb_truetype.

**Comment by dumblob** [comment]
Ok. It seems there were some issues solved according to commit messages (didn't try any older versions for comparison). Feel free to take a look again if those edge cases of yours got solved or not.

**Comment by nothings** [comment]
There's nothing stopping anyone from using MSDF. I don't think there's any point in adding it to stb_truetype regardless.
