### ISSUE TITLE
stb_image_write global config vars in C++

### ISSUE THREAD

**Issue by baldurk** [nothings/stb#921]
Currently in stb_image_write.h the global config vars are declared as directly extern:

```
#ifndef STB_IMAGE_WRITE_STATIC  // C++ forbids static forward declarations
extern int stbi_write_tga_with_rle;
extern int stbi_write_png_compression_level;
extern int stbi_write_force_png_filter;
#endif
```

But if the header is included from C++ and the implementation is defined in C then name mangling kicks in inconsistently and the linker can't resolve the mangled names.

It works for me if I change the extern to `extern "C"`. I think possibly it should be using the `STBIWDEF` above but that might break on some config. I'm also not sure if this C++/C mix is intended to work - if not then just close this issue as it's not a big deal to me.

**Comment by nothings** [comment]
I thought C++ variables didn't get name-mangled in the link, that's why I always put them outside extern "C" blocks.

**Comment by nothings** [comment]
From googling, I guess the specification doesn't say, and compilers have switched from no mangling to yes mangling at some point in time. Sigh.

**Comment by baldurk** [comment]
Ah sorry I didn't realise that, I thought C++ symbols were all mangled. Indeed from testing it looks like gcc and clang work fine but MSVC (where I was testing) breaks. At least for VS2015 and VS2019.

**Comment by nothings** [comment]
No worries, thanks for pointing this out. A bug is a bug.

**Comment by rygorous** [comment]
This is now fixed in the dev branch, will be in the next release.
