### ISSUE TITLE
stb_ds: according to docs arraddn should return pointer but it returns an offset

### ISSUE THREAD

**Issue by michal-z** [nothings/stb#923]
To work as documented it should look like:
  (stbds_arrmaybegrow(a, n), stbds_header(a)->length += (n), **&(a)[stbds_header(a)->length - (n)]**)

instead of:
  (stbds_arrmaybegrow(a, n), stbds_header(a)->length += (n), **stbds_header(a)->length - (n)**)

**Comment by rygorous** [comment]
This is fixed in the dev branch; also there are two versions, "addnptr" and "addnindex", that return a pointer and index respectively. The old (ambiguous) arraddn name is deprecated and should not be used.
