### ISSUE TITLE
stb_image.h jpeg decoding error 

### ISSUE THREAD

**Issue by 2020karaulov2020** [nothings/stb#927]
stb_image.h not works

**Comment by 2020karaulov2020** [comment]
https://github.com/nothings/stb/blob/f54acd4e13430c5122cab4ca657705c84aa61b08/stb_image.h#L3741

Original file:
![test66](https://user-images.githubusercontent.com/62130676/77227962-0e27a600-6b95-11ea-835b-dacf52af498b.jpg)
[test66.zip](https://github.com/nothings/stb/files/4363044/test66.zip)

before code modified:

![test3](https://user-images.githubusercontent.com/62130676/77227988-3d3e1780-6b95-11ea-87e8-7a9c846b30da.png)


after adding 

```
 if (z->app14_color_transform == -1)
       z->app14_color_transform = 0;
```
![test3](https://user-images.githubusercontent.com/62130676/77227979-27c8ed80-6b95-11ea-931a-9048d0dd8211.png)

**Comment by nothings** [comment]
The change you suggest would break most normal JPEGs, since it would force them to incorrectly try to convert from CMYK to RGB. Presumably there is something else in the file that indicates it's CMYK.

**Comment by 2020karaulov2020** [comment]
@nothings thanks for answer ! This is Blizzard jpeg format, normal processed with INTEL JPEG LIBRARY.
Example

```

void * ReadImage( int &width,
	int &height,
	int &nchannels,
	const void *buffer,
	int sizebytes )
{
	JPEG_CORE_PROPERTIES jcprops = JPEG_CORE_PROPERTIES( );

	if ( ijlInit( &jcprops ) != IJL_OK )
	{
		ijlFree( &jcprops );
		return NULL;
	}

	nchannels = 4;

	unsigned char * pixbuff;
#ifdef STORMMEM
	pixbuff = ( unsigned char * )Storm::MemAlloc( width*height*nchannels );
#else 
	pixbuff = new unsigned char[ width*height*nchannels ];
#endif

	if ( !pixbuff )
	{
		ijlFree( &jcprops );
		return NULL;
	}

	jcprops.UseJPEGPROPERTIES = 0;

	jcprops.DIBBytes = ( unsigned char * )pixbuff;
	jcprops.DIBWidth = width;
	jcprops.DIBHeight = height;
	jcprops.DIBPadBytes = 0;
	jcprops.DIBChannels = nchannels;
	jcprops.DIBColor = IJL_OTHER;
	jcprops.DIBSubsampling = IJL_NONE;

	jcprops.JPGFile = NULL;
	jcprops.JPGBytes = ( unsigned char * )buffer;
	jcprops.JPGSizeBytes = sizebytes;
	jcprops.JPGWidth = width;
	jcprops.JPGHeight = height;
	jcprops.JPGChannels = nchannels;
	jcprops.JPGColor = IJL_OTHER;
	jcprops.JPGSubsampling = IJL_NONE;
	jcprops.JPGThumbWidth = 0;
	jcprops.JPGThumbHeight = 0;
	jcprops.cconversion_reqd = 1;
	jcprops.upsampling_reqd = 1;
	jcprops.jquality = 75;

	if ( ijlRead( &jcprops, IJL_JBUFF_READWHOLEIMAGE ) != IJL_OK )
	{
		ijlFree( &jcprops );
		return NULL;
	}

	if ( ijlFree( &jcprops ) != IJL_OK )
	{
		return 0;
	}

	return ( void * )pixbuff;
}
```

**Comment by 2020karaulov2020** [comment]
Possible to support this JPEG format with stb_image.h without code modified?

**Comment by nothings** [comment]
No, it'll require some kind of code change. I just don't know what.

**Comment by 2020karaulov2020** [comment]
@nothings  But i see in browser normal image, just swapped R and B channel. 
You can't get detect colorspace as in Google Chrome ?)))

See 
![TVJlit 1](https://user-images.githubusercontent.com/62130676/77228371-e1c15900-6b97-11ea-87d7-20f01a43bffc.jpg)

**Comment by 2020karaulov2020** [comment]
@nothings thanks for working at this issue!

You don't know, maybe this code can work for unknown image color space, using RGBA?


```
   if (!is_rgb && z->app14_color_transform == -1)
       z->app14_color_transform = 0;
```
(If color space not RGB and not detected, set color space to 0)


It works in this images without problem.

**Comment by rygorous** [comment]
OK this is clearly a nonstandard JPEG file/extension, and outside the scope of what stb_image supports, given that it doesn't correctly decode in the browser either. ("Just R and B channels swapped" definitely counts as "not decoding correctly".)
