### ISSUE TITLE
stb_image_write.h jpeg encoding error

### ISSUE THREAD

**Issue by 2020karaulov2020** [nothings/stb#928]
```
void WriteMegaPNG(void* context, void* data, int size)
{
	StormBuffer* output = (StormBuffer*)context;
	output->buf = (char*)malloc(size);
	memcpy(output->buf, data, size);
	output->length = size;
}

bool RAW2Jpg(StormBuffer input, StormBuffer& output, int width, int height, int bpp, const char* filename)
{
	stbi_write_jpg_to_func(WriteMegaPNG, &output, width, height, bpp, input.buf, 100);
	return true;
}
```

I got zero file... 

But with 
```

bool RAW2Png(StormBuffer input, StormBuffer& output, int width, int height, int bpp, const char* filename)
{
	stbi_write_png_to_func(WriteMegaPNG, &output, width, height, bpp, input.buf, width * bpp);
	return true;
}
```

got normal result!

Why stbi_write_jpg_to_func not works ? (Input 4bpp RGBA pixels)

**Comment by 2020karaulov2020** [comment]
@nothings you can fix this error https://github.com/nothings/stb/issues/927 ? 🌝

**Comment by nothings** [comment]
Dude, you do not need to post about #927 3 times. Once is plenty.

**Comment by 2020karaulov2020** [comment]
Yes, sorry, problem and in these issue. I can't write jpeg file using std_image_write.h but easy write png image. Why ?

Input data RGBA pixels (4bpp)

**Comment by nothings** [comment]
Dude, you do not need to re-ask the same question multiple times. This is a bug tracker, not a chat. You may not get answers for days, months, or weeks.

**Comment by 2020karaulov2020** [comment]
Yes, I did not know about it! :)

**Comment by rygorous** [comment]
Your callback is wrong. It assumes it only gets called once, which happens to be true for the current stb_image_write PNG writer, but is not true in general.

In general, it will be called multiple times, sometimes a few bytes at a time and sometimes with larger chunks, and you need to concatenate all the individual byte sequences you get to produce the output. Normally that means you'll want to be writing to a resizable array, std::vector or similar if you want the results in memory.
