### ISSUE TITLE
Stack around variable corrupted: stb_readdir_recursive

### ISSUE THREAD

**Issue by Vawx** [nothings/stb#930]
Run-Time Check Failure #2 - Stack around the variable 'with_slash' was corrupted.
Run-Time Check Failure #2 - Stack around the variable 'buffer' was corrupted.

Simple use case:

```
char SourceDirectory[Directory::MAX_FILE_NAME_LENGTH] = {};
char Wildcard[3] = ".h";
Directory::GetSourceDirectory(&SourceDirectory[0]);

if (char** Files = stb_readdir_recursive(&SourceDirectory[0], &Wildcard[3]))
{
	while (*Files++)
	{
		 // Files....
	}
}
```

Visual Studio 2019. Turning off run-time exceptions gets rid of the error but Files comes back nullptr.

**Comment by nothings** [comment]
&Wildcard[3] is invalid

**Comment by Vawx** [comment]
Should "*.h" or nullptr work?

**Comment by nothings** [comment]
"*.h" should work, just &Wildcard[0] when you pass it in

**Comment by Vawx** [comment]
```
size_t stb_strscpy(char *d, const char *s, size_t n)
{
   size_t len = strlen(s);
   if (len >= n) {
      if (n) d[0] = 0;
      return 0;
   }
   stb_p_strcpy_s(d,n+1,s);
   return len + 1;
}
```

Mostly a guess but does stop the error:

n+1 on stb_p_strcpy_s() brings buffer size up to 4097.

**Comment by Vawx** [comment]
```
   n = stb_strscpy(buffer,dir,sizeof(buffer));
   if (!n || n >= sizeof(buffer))
      return NULL;
   stb_fixpath(buffer);
   /** n--; [need to remove this if stb_strscpy() no longer has + 1]
```

**Comment by nothings** [comment]
I believe this is fixed in the forthcoming versoin.
