### ISSUE TITLE
assert in stb_image.h v2.25 function stbi__extend_receive()

### ISSUE THREAD

**Issue by richgel999** [nothings/stb#933]
I've attached a jpeg file that, when loaded with stbi_load(), triggers this assert on line 2055 in function stbi__extend_receive():

STBI_ASSERT(n >= 0 && n < (int) (sizeof(stbi__bmask)/sizeof(*stbi__bmask)));

n is 21. Compiled with latest VS 2019, debug x64 build.

Zipped JPEG file:
http://www.subquantumtech.com/stb_assert.zip

Callstack:

>	basisuD.exe!stbi__extend_receive(stbi__jpeg * j, int n) Line 2055	C++
 	basisuD.exe!stbi__jpeg_decode_block(stbi__jpeg * j, short * data, stbi__huffman * hdc, stbi__huffman * hac, short * fac, int b, unsigned short * dequant) Line 2114	C++
 	basisuD.exe!stbi__parse_entropy_coded_data(stbi__jpeg * z) Line 2879	C++
 	basisuD.exe!stbi__decode_jpeg_image(stbi__jpeg * j) Line 3278	C++
 	basisuD.exe!load_jpeg_image(stbi__jpeg * z, int * out_x, int * out_y, int * comp, int req_comp) Line 3730	C++
 	basisuD.exe!stbi__jpeg_load(stbi__context * s, int * x, int * y, int * comp, int req_comp, stbi__result_info * ri) Line 3887	C++
 	basisuD.exe!stbi__load_main(stbi__context * s, int * x, int * y, int * comp, int req_comp, stbi__result_info * ri, int bpc) Line 1057	C++
 	basisuD.exe!stbi__load_and_postprocess_8bit(stbi__context * s, int * x, int * y, int * comp, int req_comp) Line 1169	C++
 	basisuD.exe!stbi_load_from_file(_iobuf * f, int * x, int * y, int * comp, int req_comp) Line 1283	C++
 	basisuD.exe!stbi_load(const char * filename, int * x, int * y, int * comp, int req_comp) Line 1273	C++
 	basisuD.exe!test(int argc, const char * * argv) Line 2763	C++
 	basisuD.exe!main_internal(int argc, const char * * argv) Line 2802	C++
 	basisuD.exe!main(int argc, const char * * argv) Line 2892	C++
 	[External Code]	

![stb_assert](https://user-images.githubusercontent.com/6934809/77479717-b7210b80-6df6-11ea-98d7-759eb07fbb7a.jpg)

**Comment by nothings** [comment]
Photoshop reports it as corrupt. Do you have any expectation of it loading correctly, or you just want the assert to go away?

**Comment by rygorous** [comment]
We definitely shouldn't assert on bad data, it should just report an error if the file is malformed.

**Comment by nothings** [comment]
Yeah, I just wanted to gather data if it was something we should successfully open.

**Comment by rygorous** [comment]
Fixed by commit a3f2897b85760d1e98fedbe31fcf2ddf089c169e in the dev branch, this fix will be in the next release.
