### ISSUE TITLE
stbir_resize_float not working properly

### ISSUE THREAD

**Issue by petrovicu** [nothings/stb#936]
Hi,

I have a problem using **stbir_resize_float** method. The exception is thrown from stb_image_resize.h file, line 1840:
`((float*)output_buffer)[index] = encode_buffer[index];`
Access violation writing location 0x00000257BC034000.

from:

```
case STBIR__DECODE(STBIR_TYPE_FLOAT, STBIR_COLORSPACE_LINEAR):
            for (x=0; x < num_pixels; ++x)
            {
                int pixel_index = x*channels;

                for (n = 0; n < channels; n++)
                {
                    int index = pixel_index + n;
                    ((float*)output_buffer)[index] = encode_buffer[index];
                }
            }
            break;
```

My usage (code snippet):
float * img_data = stbi_loadf("image.jpg", &x, &y, &n, 3);
float* resized_image = (float*)std::malloc(800 * 800 * 3);
stbir_resize_float(img_data, x, y, 0, resized_image, 800, 800, 0, 3);

Can you please help or maybe correct me if I am doing something wrong?

Thanks in advance!

**Comment by nothings** [comment]
You're not mallocing enough memory.
