### ISSUE TITLE
stbiw__fopen, stbi__fopen

### ISSUE THREAD

**Issue by 0xc0de** [nothings/stb#939]
> wchar_t wMode[64];
> wchar_t wFilename[1024];
> if (0 == MultiByteToWideChar(65001 /* UTF8 */, 0, filename, -1, wFilename, sizeof(wFilename)))
>       return 0;
> if (0 == MultiByteToWideChar(65001 /* UTF8 */, 0, mode, -1, wMode, sizeof(wMode)))
>       return 0;

Last parameter (cchWideChar) is size, in characters, of the buffer indicated by lpWideCharStr.
Therefore, it will be correct to write:
sizeof(wFilename)/sizeof(wFilename[0])
sizeof(wMode)/sizeof(wMode[0])

**Comment by Akuli** [comment]
If someone writes a pull request to fix this, note that the same code (copy/pasta?) is also in `stb_image_write.h`. Those are all I found by grepping for `MultiByteToWideChar`.

**Comment by Akuli** [comment]
Seems like the same code has another issue: on MinGW, there's no way to specify that you want to use an utf-8 filename, even though it's possible with msvc. Some of the `defined(_MSC_VER)` checks could be changed to something like `defined(_WIN32)` to fix this.

**Comment by rygorous** [comment]
Duplicate of #772.
