### ISSUE TITLE
assertion "total_filter > 0.9" failed: file "/Users/takabatomoki/Desktop/esp-cam-test/main/stb_image_resize.h", line 1066, function: stbir__calculate_coefficients_upsample

### ISSUE THREAD

**Issue by acsses** [nothings/stb#942]
I use this library on ESP-IDF.
But Wen I run my proguram include stb_image_resize.h,I catch this error.
`assertion "total_filter > 0.9" failed: file "/Users/takabatomoki/Desktop/esp-cam-test/main/stb_image_resize.h", line 1066, function: stbir__calculate_coefficients_upsample`
this error may be result of  assertioned
but I don't know What I should do for resolve this error.
Please teach me how to solve this error

**Comment by nothings** [comment]
What values are you passing in to the function when it hits this? What size image, what filter mode, etc.? (The contents of the bitmap don't matter.)
