### ISSUE TITLE
'pow' was not declared in this scope

### ISSUE THREAD

**Issue by WinteryFox** [nothings/stb#957]
Building under MSYS2 c++20 results in the following error;
```
C:/Users/[redacted]/Desktop/VixenEngineVulkan/engine/contrib/stb/stb_image.h: In function 'float* stbi__ldr_to_hdr(stbi_uc*, int, int, int)':
C:/Users/[redacted]/Desktop/VixenEngineVulkan/engine/contrib/stb/stb_image.h:1768:40: error: 'pow' was not declared in this scope
 1768 |          output[i*comp + k] = (float) (pow(data[i*comp+k]/255.0f, stbi__l2h_gamma) * stbi__l2h_scale);
      |                                        ^~~
C:/Users/[redacted]/Desktop/VixenEngineVulkan/engine/contrib/stb/stb_image.h: In function 'stbi_uc* stbi__hdr_to_ldr(float*, int, int, int)':
C:/Users/[redacted]/Desktop/VixenEngineVulkan/engine/contrib/stb/stb_image.h:1794:28: error: 'pow' was not declared in this scope
 1794 |          float z = (float) pow(data[i*comp+k]*stbi__h2l_scale_i, stbi__h2l_gamma_i) * 255 + 0.5f;
      |                            ^~~
C:/Users/[redacted]/Desktop/VixenEngineVulkan/engine/contrib/stb/stb_image.h: In function 'void stbi__hdr_convert(float*, stbi_uc*, int)':
C:/Users/[redacted]/Desktop/VixenEngineVulkan/engine/contrib/stb/stb_image.h:6835:20: error: 'ldexp' was not declared in this scope
 6835 |       f1 = (float) ldexp(1.0f, input[3] - (int)(128 + 8));
      |                    ^~~~~
```
I am not using the `STBI_NO_LINEAR` or `STBI_NO_HDR` options.

**Comment by zvezdochiot** [comment]
:information_source: Added in head:
```sh
#include <math.h>
```
and added `LDFLAGS += -lm` in `Makefile`.

**Comment by WinteryFox** [comment]
While including cmath does solve it, shouldn't STBI include this instead?

**Comment by zvezdochiot** [comment]
:information_source: No. Should not. It should only have a link in the documentation.

**Comment by nothings** [comment]
I'm not sure what @zvezdochiot is thinking, but it is incorrect; stb_image should #include anything it needs.

However, I'm confused, since there is `#include <math.h>` on line 545.

https://github.com/nothings/stb/blob/master/stb_image.h#L545

It is guarded by STBI_NO_LINEAR and STBI_NO_HDR, but the report says those flags aren't defined. Can you put a "#error test" or some such above line 545, inside the #if?

**Comment by nothings** [comment]
Or is the problem that when compiling as C++, including math.h isn't getting the right stuff, and you need something called cmath.h? (I don't use C++.)

**Comment by WinteryFox** [comment]
That error is triggered, so yes those flags are not defined.

**Comment by WinteryFox** [comment]
That might be the case, math.h is not a thing in C++ as far as I'm aware, we include cmath instead.

**Comment by zvezdochiot** [comment]
@nothings say:
>but it is incorrect; stb_image should #include anything it needs.

I did not say that this is impossible. I said: not necessary.

**Comment by WinteryFox** [comment]
ah wait I am stupid, I have an include `Math.h` inside of my own project, which might be causing a conflict. Renaming it fixes the issue, however there is still a deprecation warning since math.h is actually deprecated and you should include cmath instead in C++

**Comment by nothings** [comment]
Ok, presumably the correct fix for this is to test what version of cplusplus you're in and choose between math.h and cmath.h appropriately. Does anyone know what version deprecates it?

(Why did they do this? Sigh.)

**Comment by zvezdochiot** [comment]
@nothings say;
>I don't use C++

You will not be able to track performance. Maybe you should add this moment to the documentation.

**Comment by WinteryFox** [comment]
I believe that `math.h` is deprecated in *all* versions of C++, don't quote me though.

**Comment by nothings** [comment]
You're doing a great job of getting yourself banned. Keep it up.

> 
> 
> @nothings say;
> 
> > I don't use C++
> 
> question You will not be able to track performance. Maybe you should add this moment to the documentation?

**Comment by nothings** [comment]
Ok, stackoverflow isn't the most trustworthy, but the claim seems to be that math.h guarantees it puts its symbols in the global namespace, and cmath does not. Therefore, use of cmath would require use of `std::` prefix. (And according to that discussion, cmath does not offer the practical value of NOT polluting the global namespace; it may or may not, depending on implementation, thus is no better from a portable-code POV.)

While this could be #define'd away with a `#define pow std::pow`, I think it's better to just live with the fact you're going to get these deprecation warnings, given that it doesn't seem to be something mainstream C++ compilers warn about. Generally my policy is to try to suppress warnings for the convenience of users, but given the value of having code that compiles as both C and C++, I have to look askance at any compiler that intentionally breaks that compatibility. And when that compiler is mingw (or at least the msys2 version of it), AGAIN... Yeah.

I'll reconsider if anybody can advance a good argument or a really convenient way of dealing with it.
