### ISSUE TITLE
stb_truetype.h: Quads all black

### ISSUE THREAD

**Issue by tinspin** [nothings/stb#963]
![truetype](https://user-images.githubusercontent.com/4329234/81829834-9eea8480-953b-11ea-81b1-aed1a405392d.png)

**Comment by nothings** [comment]
you have a bug

**Comment by tinspin** [comment]
Sure, but it would be good to find out what the bug is for you too, since I'm probably not the first or last to have this bug?

I'm trying to figure it out and looking for help. What could it be?

**Comment by nothings** [comment]
You misunderstand me. *You* have a bug. In your code. It's not my problem. Finding out what your bug doesn't any good for me.
