### ISSUE TITLE
%.*s will read up to three bytes past end given by precission

### ISSUE THREAD

**Issue by seventh-chord** [nothings/stb#966]
In stb_sprintf.h

Specifically, code like the following would fail, because `case 's'` doesn't respect the given precision when reading from the given string.
```
char *big = (char *) VirtualAlloc(0, 4096, MEM_RESERVE | MEM_COMMIT, PAGE_READWRITE);
memcpy(big + 4096 - 5, "hello", 5);
char buffer[64];
stbsp_sprintf(buffer, "%.*s", 5, big + 4096 - 5);
assert(strcmp(buffer, "hello") == 0);
```
This is because `sn - s >= pr` is not checked before calling `goto lchk` on line 561, leading to an access violation on line 543.

Similarly, code where an invalid, unaligned pointer is passed with precision 0 will fail, because no check for `sn - s == 0 >= pr` is made at the start of the loop.

As far as I can tell, printf in the msvc crt handles these cases properly, nor does the C11 spec forbid them.

The simplest fix, as far as I can tell, would be to change line 543 to `if (((stbsp__uint32)(sn - s) >= (stbsp__uint32)pr) || sn[0] == 0)` (which works because `pr` defaults to -1 and becomes `UINT32_MAX` when cast to an unsigned in). I guess this isn't all that desirable because it complicates the inner loop though, not sure.

**Comment by rygorous** [comment]
This is now fixed in the dev branch and will be in the next release.
