### ISSUE TITLE
Regarding the public domain problem, is CC0 or BSD0 okay?

### ISSUE THREAD

**Issue by RetroZvoc** [nothings/stb#968]
Hello!
I am so amazed with how there is still some public domain software for common-sense operations like image formats, string processing, etc..
You have inspired me to pursue writing my own game engine and many great things without the existential dread of copyright.

However, when I saw that the public domain license might be a problem as stated in your "Why Public Domain" document, I thought to myself could it be possible to use the CC0 or the BSD0 license instead. Is it possible to use such a license?

The purpose of this is that any person using my software built upon yours can safely use a simple notice such as "No copyright infringement intended." since there either is no copyright or the copyright license cannot be breached as it doesn't require any legalese that the kind of my users would be baffled with.

Some unfortunately cannot even comply with the MIT license, whether it's that they are kids, dyslexic, disabled or have grown up on using "Fair Use" as the magic bullet for all their problems in the memes/fandom/hacking/modding communities. Obviously due to these problems, they don't want to deal with catch22s of money/job/experience/resources/etc. and I'd like to make their lives easier with tools that are just "free as in childhood" so they don't make horrible games with broken tools, but so that they make amazing things with their talents while avoiding all sociopolitical drama as far as possible. As a kid, I believed that computers are tools against politics and for uniting best buddies.

Thank you very much for understanding!
I hope you deem this as honesty and not as cringe.
I'm looking forward to your reply.

P.S. I hope one day your software is used in post-scarcity 3D printers ;)

**Comment by nothings** [comment]
This is an issue tracker, not a discussion forum.
