### ISSUE TITLE
`setup_temp_free` leaks temp memory causing an assert in `start_decoder`

### ISSUE THREAD

**Issue by k6l2** [nothings/stb#972]
This was caused by commit 2f18c96cfb914ed30503b1554a7875a847f99293 for issue #799 as far as I can tell.  Peter fixed alignment in `setup_temp_malloc`, but forgot to fix the alignment calculation in `setup_temp_free`.  This causes `setup_temp_free` to increment `f->temp_offset` by the wrong byte amount, ultimately causing a temp buffer memory leak assertion check to fail inside `start_decoder` on my end.

**Comment by k6l2** [comment]
Looks like https://github.com/nothings/stb/pull/961 fixes this issue.

**Comment by rygorous** [comment]
Fix was merged last year, closing this issue.
