### ISSUE TITLE
How to get around anti-aliasing for intentionally pixelated fonts?

### ISSUE THREAD

**Issue by tristanschneider** [nothings/stb#982]
I have an intentionally pixelated font for which I am using `stbtt_PackFontRanges` to rasterize the glyphs to an image that is later sampled in a shader to render the text. However, the anti-aliasing done as part of the rasterization always leaves the font looking blurry. I read the article on how the V2 rasterization works (http://nothings.org/gamedev/rasterize/) and believe that if I were to pick a size such that a pixel in the font is a pixel in the bitmap to rasterize to, then no pixels should end up being partially filled with glyphs, meaning all pixels are completely on or off. However, I have tried all sizes (`stbtt_pack_range::font_size`) between 8 and 108 both in pixels and using `STBTT_POINT_SIZE`, but none of them seem to align properly. **Is there a way to find a size or otherwise pixel-align values so that anti-aliasing doesn't blur the pixelated font?**

This is what the call looks like:
```
		for (int i = 0; i < 100; ++i) {
			cg::ImageDescription imageDetails;
			imageDetails.mWidth = imageDetails.mHeight = 2048;
			imageDetails.mTextureFormat = mce::TextureFormat::R8_UNORM;
			imageDetails.mColorSpace = cg::ColorSpace::Linear;
			atlasTexture = std::make_shared<cg::ImageBuffer>(imageDetails);

			stbtt_pack_context packContext;
			stbBakeResult = stbtt_PackBegin(&packContext, atlasTexture->get(), imageDetails.mWidth, imageDetails.mHeight, 0, 1, nullptr);

			if (stbBakeResult != 0) {
				stbtt_PackSetOversampling(&packContext, 2, 2);
				int fontIndex = (mCollectionIndex < 0) ? 0 : mCollectionIndex;
				stbtt_pack_range packRange;
				packRange.first_unicode_codepoint_in_range = 0;
				packRange.array_of_unicode_codepoints = atlasGlyphInfo.codepoints.data();
				packRange.num_chars = atlasGlyphInfo.codepoints.size();
				atlasGlyphInfo.packedCharacters.assign(packRange.num_chars, stbtt_packedchar());
				packRange.chardata_for_range = atlasGlyphInfo.packedCharacters.data();
				// Both pixels and points end up blurry.
				packRange.font_size = STBTT_POINT_SIZE(pixel_height + static_cast<float>(i)); //STBTT_POINT_SIZE(pixel_height + static_cast<float>(i));
				stbBakeResult = stbtt_PackFontRanges(&packContext, dataFromFile, fontIndex, &packRange, 1);
			}
			stbtt_PackEnd(&packContext);

			_cacheAtlasImage(Core::StackPathBuffer::joinParts({ _getTestPath() }, Core::StackPathBuffer(std::to_string(pixel_height + i)), ".png"), atlasTexture);
		}
```

Here is what the font looks like in Font Forge
![image](https://user-images.githubusercontent.com/19154637/85972749-a8ae3700-b985-11ea-97ea-bd8732a0f7e0.png)
Here is what it looks like after rasterizing using stb at 24pt:
![image](https://user-images.githubusercontent.com/19154637/85973597-1bb8ad00-b988-11ea-8f9e-a93156f13451.png)
And here is what 'T' should look like. Not that each "pixel" is 100 units and the entire character is 600, 800, with 50 units (half a pixel) of space on the left and right.

![image](https://user-images.githubusercontent.com/19154637/85973691-718d5500-b988-11ea-890d-0abbb3d007cd.png)

**Comment by nothings** [comment]
i do not know of any way to to do this directly. you could draw it much larger, quantize it, and then scale it down nearest-neighbor.

also that doesn't seem like the correct output from stb_truetype in the first place. the anti-aliased edges where the color is neither black nor white should be 1-pixel wide, not two. maybe there's a bug, but i don't trust whatever you've used to scale it up for display.

**Comment by nothings** [comment]
btw, if you zoom in on the font-forge screenshot, you'll see one-pixel-wide antialiasing.

![image](https://user-images.githubusercontent.com/7525026/85975205-499ff080-b98c-11ea-8220-41b2d5a4e800.png)

**Comment by nothings** [comment]
anyway, the short answer is: if you want a pixellated font, don't use truetype, use bitmaps

**Comment by tristanschneider** [comment]
Alright, thanks for the feedback!
