### ISSUE TITLE
STB Idea

### ISSUE THREAD

**Issue by adamsch1** [nothings/stb#990]
Hi Sean,

Thank you for sharing your libraries, they are great.  I have an idea that might be useful for header only single file type repositories.  A single file that can cut/paste into other offerings that handle all the system define checks and portability issues on linux/win/mac/freebsd etc.

So instead of everyone rolling their own  #if def hell at the top checking for MAX_INT size or if the compiler provides __attribute__ offerings we have one version that does all of that, perhaps with the ability to locally define it to a namespace.  

I would use it in a heart beat.  I think you could pull it off with the success of STB.

**Comment by nothings** [comment]
Brian Hook wrote something like this at one point. I assume it hasn't been updated in a long time, but regardless it seemed like a nightmare to do properly, which is why I've stayed away from it.

https://en.wikipedia.org/wiki/Poshlib

**Comment by adamsch1** [comment]
ah good to know I'll check it out.

**Comment by turol** [comment]
https://github.com/nemequ/hedley
