### ISSUE TITLE
Strange statement in stb_sprintf.h

### ISSUE THREAD

**Issue by ldelenger** [nothings/stb#997]
stb_sprintf.h:1002
``` 
if (pr == 0) {
     l = 0;
    cs = (((l >> 4) & 15)) << 24;
   goto scopy;
}
```
We're setting value to 0 and then using it in a formula that will obviously produce a 0.
Doesn't look like it was intended.

**Comment by rygorous** [comment]
It's intended and written that way to match the way cs is initialized in other paths of the code (see e.g. "get the tens and the comma pos" below), but I'll just change it to set cs to 0 directly.

**Comment by rygorous** [comment]
This is now fixed in the dev branch, will be in the next release.
